package com.gregtech.gregtech.loaders;

import com.gregtech.gregtech.GregTech;
import com.gregtech.gregtech.api.material.GTMaterial;
import com.gregtech.gregtech.api.material.GTMaterialRegistry;
import com.gregtech.gregtech.api.tool.GTToolType;
import com.gregtech.gregtech.block.wood.WoodSpecies;
import com.gregtech.gregtech.content.recipe.GTWoodRecipes;
import com.gregtech.gregtech.data.MaterialPrefix;
import com.gregtech.gregtech.recipe.ToolShapedRecipe;
import com.gregtech.gregtech.registry.GTItems;
import com.gregtech.gregtech.registry.GTToolItems;
import com.gregtech.gregtech.registry.GTWoods;
import net.minecraft.core.NonNullList;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.CraftingBookCategory;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.Recipe;
import net.minecraft.world.item.crafting.RecipeManager;
import net.minecraft.world.item.crafting.ShapedRecipe;
import net.minecraft.world.item.crafting.ShapelessRecipe;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Registers {@link GTWoodRecipes} - the crafting rows GT6's wood dictionary produces for the port's
 * own nine tree species.
 *
 * <p>GT6's original ({@code gregtech/loaders/c/Loader_Recipes_Woods.java:183-185}, {@code :203-205} and
 * {@code :243-244}) walks {@code WoodDictionary.LIST_WOODS}/{@code LIST_BEAMS}/{@code LIST_PLANKS} and
 * registers one set of rows per table entry, so a port row is only possible for an entry the port has
 * blocks for. {@link GTWoodRecipes} carries exactly that subset (generated by
 * {@code tools/generate_wood_recipes.py}) plus the manifest of the GT6 statements that stay
 * untranslated with their line numbers; this class resolves the table's item specs at runtime and
 * installs the recipes the same way {@link Loader_StoneCraftingRecipes} does.</p>
 *
 * <p>Two GT6 details are carried over:</p>
 * <ul>
 *   <li>The rows do <em>not</em> mirror. GT6's {@code CR.DEF_NCC} has no {@code MIR} bit
 *       ({@code gregapi/util/CR.java:161-163}) while 1.20.1 mirrors shaped recipes by default, so every
 *       row is wrapped in {@link ToolShapedRecipe} with {@code allowMirror = false}.</li>
 *   <li>The tool keys are GT tools ({@code 's'} saw, {@code 'f'} file; {@code CR.java:344-360}), i.e.
 *       the port's {@code gregtech:tool_saw}/{@code tool_file} items that wear on use.</li>
 * </ul>
 *
 * <p>A spec that does not resolve (a missing material form, a missing tool type) skips that single row
 * and is reported through {@link #skipped()}; {@code gametest/WoodRecipeTests.java} asserts the list is
 * empty, so a gap shows up as a failing test instead of a silently missing recipe.</p>
 */
public final class Loader_WoodCraftingRecipes {

    private static final List<String> REGISTERED = new ArrayList<>();
    private static final List<String> SKIPPED = new ArrayList<>();
    private static final List<String> TREATED_REGISTERED = new ArrayList<>();

    private Loader_WoodCraftingRecipes() {}

    /** Recipe ids the last server start added, for tests and reports. */
    public static List<String> registeredIds() { return List.copyOf(REGISTERED); }
    public static List<String> treatedRegisteredIds() { return List.copyOf(TREATED_REGISTERED); }

    /** Rows whose specs did not resolve in this port, with the reason. */
    public static List<String> skipped() { return List.copyOf(SKIPPED); }

    /** Species ids of the generated table, in the order the tool wrote them. */
    public static List<String> speciesIds() {
        List<String> ids = new ArrayList<>();
        for (String row : GTWoodRecipes.SPECIES) ids.add(row.split("\\|", -1)[0]);
        return List.copyOf(ids);
    }

    /** The port's wood block for one of the table's species specs, or {@link ItemStack#EMPTY}. */
    public static ItemStack block(String kind, String species) {
        WoodSpecies resolved = species(species);
        if (resolved == null) return ItemStack.EMPTY;
        return switch (kind) {
            case "log" -> new ItemStack(GTWoods.log(resolved));
            case "planks" -> new ItemStack(GTWoods.planks(resolved));
            case "beam" -> new ItemStack(GTWoods.beam(resolved));
            default -> ItemStack.EMPTY;
        };
    }

    private static WoodSpecies species(String id) {
        for (WoodSpecies candidate : WoodSpecies.values()) {
            if (candidate.id().equals(id)) return candidate;
        }
        return null;
    }

    public static void apply(RecipeManager manager, net.minecraft.core.RegistryAccess access) {
        List<Recipe<?>> recipes = new ArrayList<>(manager.getRecipes());
        REGISTERED.clear();
        SKIPPED.clear();
        TREATED_REGISTERED.clear();
        int added = 0;
        for (String row : GTWoodRecipes.CRAFT_ROWS) added += row(recipes, row);
        added += treatedWoodRows(recipes);
        if (added > 0) com.gregtech.gregtech.recipe.RuntimeRecipeLifecycle.replaceGenerated(manager, recipes);
        GregTech.LOGGER.info("Registered {} GT6 wood dictionary crafting rows for {} species ({} skipped)",
                added, speciesIds().size(), SKIPPED.size());
        for (String reason : SKIPPED) GregTech.LOGGER.debug("[gregtech] wood row skipped: {}", reason);
    }

    /**
     * GT6 {@code Loader_OreProcessing.java:194} and {@code Loader_Recipes_Woods.java:217-218}.
     * The gear rows there use ONLY_IF_HAS_RESULT; their WoodTreated gear forms are now
     * registered explicitly, so that original condition succeeds in this port.
     */
    private static int treatedWoodRows(List<Recipe<?>> recipes) {
        ItemStack saw = requiredTreated(resolve("tool:saw"), "saw");
        ItemStack plank = requiredTreated(GTItems.getStack(MaterialPrefix.plate,
                GTMaterialRegistry.get("WoodTreated"), 1), "treated plank");
        ItemStack woodBolt = requiredTreated(GTItems.getStack(MaterialPrefix.bolt,
                GTMaterialRegistry.get("Wood"), 2), "wood bolt");
        ItemStack treatedBolt = requiredTreated(GTItems.getStack(MaterialPrefix.bolt,
                GTMaterialRegistry.get("WoodTreated"), 1), "treated wood bolt");
        ItemStack smallGear = requiredTreated(GTItems.getStack(MaterialPrefix.gearGtSmall,
                GTMaterialRegistry.get("WoodTreated"), 1), "treated small gear");
        ItemStack gear = requiredTreated(GTItems.getStack(MaterialPrefix.gearGt,
                GTMaterialRegistry.get("WoodTreated"), 1), "treated gear");

        addTreated(recipes, "wood_bolt", new String[]{"s ", " S"},
                Map.of('s', Ingredient.of(saw), 'S', Ingredient.of(net.minecraft.world.item.Items.STICK)), woodBolt);
        addTreated(recipes, "small_gear", new String[]{"P ", " s"},
                Map.of('P', Ingredient.of(plank), 's', Ingredient.of(saw)), smallGear);
        addTreated(recipes, "gear", new String[]{"BPB", "PsP", "BPB"},
                Map.of('B', Ingredient.of(treatedBolt), 'P', Ingredient.of(plank), 's', Ingredient.of(saw)), gear);
        return 3;
    }

    private static ItemStack requiredTreated(ItemStack stack, String description) {
        if (stack == null || stack.isEmpty())
            throw new IllegalStateException("GT6 treated wood recipe missing " + description);
        return stack;
    }

    private static void addTreated(List<Recipe<?>> recipes, String path, String[] pattern,
                                   Map<Character, Ingredient> keys, ItemStack result) {
        int width = pattern[0].length();
        NonNullList<Ingredient> ingredients = NonNullList.withSize(width * pattern.length, Ingredient.EMPTY);
        for (int y = 0; y < pattern.length; y++) {
            if (pattern[y].length() != width) throw new IllegalArgumentException("Uneven treated wood pattern " + path);
            for (int x = 0; x < width; x++) {
                char symbol = pattern[y].charAt(x);
                if (symbol == ' ') continue;
                Ingredient ingredient = keys.get(symbol);
                if (ingredient == null) throw new IllegalArgumentException("Missing treated wood key " + symbol);
                ingredients.set(x + y * width, ingredient);
            }
        }
        ResourceLocation id = ResourceLocation.fromNamespaceAndPath(GregTech.MODID, "wood/treated/" + path);
        ShapedRecipe base = new ShapedRecipe(id, "gt.wood", CraftingBookCategory.MISC,
                width, pattern.length, ingredients, result);
        recipes.add(new ToolShapedRecipe(base, false));
        TREATED_REGISTERED.add(id.toString());
    }

    /**
     * The key map of one generated row, or {@code null} when a key is malformed or does not resolve.
     *
     * <p>A key is one character plus {@code =} plus a spec - GT6's own keys are single letters
     * ({@code 's'} saw, {@code 'f'} file, {@code 'L'} log, {@code 'B'} beam, {@code 'P'} plank), so the
     * {@code =} sits at index 1; anything else is a malformed row. Public so
     * {@code gametest/WoodRecipeTests.java} can run the loader's real parser over every generated row -
     * an earlier revision of this guarded on a longer symbol and silently skipped all 68 rows.</p>
     */
    @Nullable
    public static Map<Character, Ingredient> keys(String path, String encoded) {
        Map<Character, Ingredient> keys = new LinkedHashMap<>();
        for (String entry : encoded.split(";")) {
            if (entry.isEmpty()) continue;
            if (entry.length() < 3 || entry.charAt(1) != '=') {
                SKIPPED.add(path + ": malformed key '" + entry + "' (expected <symbol>=<spec>)");
                return null;
            }
            char symbol = entry.charAt(0);
            String spec = entry.substring(2);
            ItemStack stack = resolve(spec);
            if (stack.isEmpty()) {
                SKIPPED.add(path + ": key '" + symbol + "' does not resolve (" + spec + ")");
                return null;
            }
            keys.put(symbol, Ingredient.of(stack));
        }
        return keys;
    }

    /** One {@code path|shape|mirror|pattern|keys|result|gt6} row of the generated table. */
    private static int row(List<Recipe<?>> recipes, String row) {
        String[] parts = row.split("\\|", -1);
        if (parts.length != 7) {
            SKIPPED.add(row + ": malformed generated row");
            return 0;
        }
        String path = parts[0];
        String shape = parts[1];
        boolean mirror = parts[2].equals("mirror");
        String[] pattern = parts[3].isEmpty() ? new String[0] : parts[3].split("/");
        Map<Character, Ingredient> keys = keys(path, parts[4]);
        if (keys == null) return 0;
        int count = 1;
        String resultSpec = parts[5];
        int star = resultSpec.lastIndexOf('*');
        if (star > 0) {
            count = Integer.parseInt(resultSpec.substring(star + 1));
            resultSpec = resultSpec.substring(0, star);
        }
        ItemStack output = resolve(resultSpec);
        if (output.isEmpty()) {
            SKIPPED.add(path + ": result '" + resultSpec + "' does not resolve");
            return 0;
        }
        output.setCount(count);

        ResourceLocation id = ResourceLocation.fromNamespaceAndPath(GregTech.MODID, "wood/" + path);
        if (shape.equals("shapeless")) {
            NonNullList<Ingredient> ingredients = NonNullList.create();
            for (Ingredient ingredient : keys.values()) ingredients.add(ingredient);
            if (ingredients.isEmpty()) {
                SKIPPED.add(path + ": shapeless row without ingredients");
                return 0;
            }
            recipes.add(new ShapelessRecipe(id, "gt.wood", CraftingBookCategory.BUILDING, output, ingredients));
            REGISTERED.add(id.toString());
            return 1;
        }
        int width = pattern.length == 0 ? 0 : pattern[0].length();
        int height = pattern.length;
        NonNullList<Ingredient> ingredients = NonNullList.withSize(width * height, Ingredient.EMPTY);
        for (int y = 0; y < height; y++) {
            if (pattern[y].length() != width) {
                SKIPPED.add(path + ": pattern row " + y + " has the wrong width");
                return 0;
            }
            for (int x = 0; x < width; x++) {
                char symbol = pattern[y].charAt(x);
                if (symbol == ' ') continue;
                Ingredient ingredient = keys.get(symbol);
                if (ingredient == null) {
                    SKIPPED.add(path + ": pattern uses key '" + symbol + "' the row does not define");
                    return 0;
                }
                ingredients.set(x + y * width, ingredient);
            }
        }
        ShapedRecipe base = new ShapedRecipe(id, "gt.wood", CraftingBookCategory.BUILDING,
                width, height, ingredients, output);
        recipes.add(new ToolShapedRecipe(base, mirror));
        REGISTERED.add(id.toString());
        return 1;
    }

    /**
     * Resolves one generated spec: {@code log|planks|beam:<species>} (the port's own wood blocks),
     * {@code rod:<material>}/{@code rodlong:<material>} (GT6's {@code OP.stick}/{@code OP.stickLong} of
     * a wood material) and {@code tool:<id>} (a {@link GTToolType}).
     */
    public static ItemStack resolve(String spec) {
        int colon = spec.indexOf(':');
        if (colon < 0) return ItemStack.EMPTY;
        String kind = spec.substring(0, colon);
        String argument = spec.substring(colon + 1);
        switch (kind) {
            case "log", "planks", "beam":
                return block(kind, argument);
            case "rod":
            case "rodlong": {
                GTMaterial material = GTMaterialRegistry.get(argument);
                if (material == null || !material.isValid()) return ItemStack.EMPTY;
                return GTItems.getStack(kind.equals("rod") ? MaterialPrefix.stick : MaterialPrefix.stickLong,
                        material, 1);
            }
            case "tool": {
                for (GTToolType type : GTToolType.values()) {
                    if (type.id().equals(argument)) {
                        var item = GTToolItems.get(type);
                        return item == null ? ItemStack.EMPTY : new ItemStack(item);
                    }
                }
                return ItemStack.EMPTY;
            }
            default:
                return ItemStack.EMPTY;
        }
    }
}
