package com.gregtech.gregtech.content.food;

import com.gregtech.gregtech.content.nuclear.PlayerRadiation;
import com.gregtech.gregtech.data.RegisteredFluids;
import com.gregtech.gregtech.data.generated.GTDrinksGen;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.material.Fluid;
import net.minecraftforge.fluids.FluidStack;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;

/**
 * GT6 {@code CS.DrinksGT}: what a drink does to you.
 *
 * <p>GT6 registers every drinkable fluid in {@code Loader_Fluids} as a {@code FoodStatDrink}, which puts the
 * entry into {@code DrinksGT.REGISTER} keyed by the fluid's name ({@code FoodStatDrink.java:46-52}); a
 * GT6 bottle (250&nbsp;mB of that fluid, {@code MultiItemBottles}) reads it through {@code FoodStatFluid}.
 * The port keys the same table by {@link Fluid}, generated by {@code tools/extract_gt6_drinks.py} into
 * {@link GTDrinksGen} (272 rows; the fluid is resolved through {@link RegisteredFluids#get(String)}, which
 * carries GT6's own {@code FL} field names).
 *
 * <p>Drinking applies GT6's {@code FoodStat.onEaten}: the food level and saturation go through vanilla's food
 * data, the six statistics into {@link PlayerFoodStats} (and {@link PlayerRadiation} for the radiation one).
 */
public final class GTDrinks {
    /** One {@code FoodStatDrink} row: the food values and the six statistics GT6 tracks. */
    public record Row(String field, int foodLevel, float saturation, int alcohol, int caffeine,
                      int dehydration, int sugar, int fat, int radiation) {}

    private static final Map<Fluid, Row> BY_FLUID = new IdentityHashMap<>();
    private static final List<String> UNRESOLVED = new java.util.ArrayList<>();
    private static boolean built;

    private GTDrinks() {}

    private static void ensureBuilt() {
        if (built) {
            return;
        }
        built = true;
        for (DrinkNutritionRows.Row source : GTDrinksGen.ROWS) {
            Row row=new Row(source.field(),source.foodLevel(),source.saturation(),source.alcohol(),source.caffeine(),source.dehydration(),source.sugar(),source.fat(),source.radiation());
            // GT6 keys drinks by FL field name for most fluids and by the FL.create("...") name for the
            // brews; the port keys its own table by field, so try both and finally match on the registry
            // path with sanitizePath applied to both sides (which is what the port itself registers).
            Fluid fluid = stillFluid(row.field());
            if (fluid == null) {
                fluid = fluidOf(RegisteredFluids.get(row.field()));
            }
            if (fluid == null) {
                fluid = byRegistryPath(row.field());
            }
            if (fluid != null) {
                BY_FLUID.put(fluid, row);
            } else {
                // Never dropped silently: the port has no fluid for this GT6 drink (another mod's fluid or
                // a row the extractor could not key), and the count is asserted in DrinkTests.
                UNRESOLVED.add(row.field());
            }
        }
    }

    /** GT6 drink rows whose fluid is not in the port (never silently dropped). */
    public static List<String> unresolved() {
        ensureBuilt();
        return List.copyOf(UNRESOLVED);
    }

    private static Fluid byRegistryPath(String key) {
        String wanted = RegisteredFluids.sanitizePath(key);
        for (RegisteredFluids.FluidEntry entry : RegisteredFluids.all().values()) {
            if (RegisteredFluids.sanitizePath(entry.registryName()).equals(wanted)) {
                Fluid fluid = fluidOf(entry);
                if (fluid != null) {
                    return fluid;
                }
            }
        }
        return null;
    }

    private static Fluid stillFluid(String field) {
        net.minecraftforge.registries.RegistryObject<Fluid> ro = com.gregtech.gregtech.registry.GTFluids.still(field);
        return ro != null && ro.isPresent() ? ro.get() : null;
    }

    /**
     * The registered still fluid of a GT6 fluid entry. Resolved through {@code GTFluids.entryForFluid} rather
     * than by name, so the three world waters and every other renamed fluid resolve correctly.
     */
    public static Fluid fluidOf(RegisteredFluids.FluidEntry entry) {
        if (entry == null) {
            return null;
        }
        for (net.minecraftforge.registries.RegistryObject<Fluid> ro
                : com.gregtech.gregtech.registry.GTFluids.FLUIDS.getEntries()) {
            if (ro.isPresent() && com.gregtech.gregtech.registry.GTFluids.entryForFluid(ro.get()) == entry) {
                return ro.get();
            }
        }
        return null;
    }

    /** GT6 {@code DrinksGT.REGISTER.get(fluidName)}, keyed by the fluid instead of its name. */
    public static Row rowFor(Fluid fluid) {
        ensureBuilt();
        return fluid == null ? null : BY_FLUID.get(fluid);
    }

    /** Convenience for a stack. */
    public static Row rowFor(FluidStack stack) {
        return stack == null || stack.isEmpty() ? null : rowFor(stack.getFluid());
    }

    /** How many of GT6's drink fluids exist in the port (the rest are other mods' / potion brews). */
    public static int registered() {
        ensureBuilt();
        return BY_FLUID.size();
    }

    /** The port fluid a GT6 drink row resolved to, by GT6 field name (case-insensitive); for tests/tooling. */
    public static Fluid fluidForField(String field) {
        ensureBuilt();
        for (Map.Entry<Fluid, Row> entry : BY_FLUID.entrySet()) {
            if (entry.getValue().field().equalsIgnoreCase(field)) {
                return entry.getKey();
            }
        }
        Fluid direct = stillFluid(field);
        return direct != null ? direct : byRegistryPath(field);
    }

    /** GT6 drink rows whose fluid is not in the port (other mods' fluids, vanilla potion brews). */
    public static List<String> skipped() {
        return GTDrinksGen.SKIPPED;
    }

    /**
     * GT6 {@code FoodStat.onEaten} for a drink: food level, saturation, the six statistics and the drink
     * sound. Returns false when the fluid is not a drink, so callers can pass.
     */
    public static boolean drink(Player player, FluidStack stack) {
        Row row = rowFor(stack);
        if (row == null || player.level().isClientSide) {
            return false;
        }
        player.getFoodData().eat(row.foodLevel(), row.saturation());
        if (row.alcohol() != 0) {
            PlayerFoodStats.change(player, row.alcohol(), GTFoodStats.ALCOHOL);
        }
        if (row.caffeine() != 0) {
            PlayerFoodStats.change(player, row.caffeine(), GTFoodStats.CAFFEINE);
        }
        if (row.dehydration() != 0) {
            PlayerFoodStats.change(player, row.dehydration(), GTFoodStats.DEHYDRATION);
        }
        if (row.sugar() != 0) {
            PlayerFoodStats.change(player, row.sugar(), GTFoodStats.SUGAR);
        }
        if (row.fat() != 0) {
            PlayerFoodStats.change(player, row.fat(), GTFoodStats.FAT);
        }
        if (row.radiation() != 0) {
            PlayerRadiation.change(player, row.radiation());
        }
        player.level().playSound(null, player.blockPosition(), SoundEvents.GENERIC_DRINK, SoundSource.PLAYERS,
                0.5F, 0.4F / (player.level().random.nextFloat() * 0.4F + 0.8F));
        return true;
    }
}
