package com.gregtech.gregtech.content.food;

import com.gregtech.gregtech.data.generated.GTFoodStatsGen;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;

import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;

/**
 * GT6 {@code CS.FoodsGT}: which food feeds which of the six tracked statistics.
 *
 * <p>GT6 keys the table by {@code ItemStack} (NBT-sensitive first, then a stack-size-1 fallback) and fills
 * it from {@code MultiItemFood} plus the ore-dictionary listeners of {@code Loader_Recipes_Food} /
 * {@code Loader_Recipes_Crops}. The port has no ore dictionary and no NBT-carrying meta items, so the table
 * is an identity map from {@link Item} to the six numbers, generated by
 * {@code tools/extract_gt6_food_stats.py} into {@link GTFoodStatsGen}.
 *
 * <p>The order is GT6's: <b>alcohol, caffeine, dehydration, sugar, fat, radiation</b>
 * ({@code CS.FoodsGT.put}'s javadoc). Radiation shares its own tracker with
 * {@link com.gregtech.gregtech.content.nuclear.PlayerRadiation}, exactly as GT6's {@code mRadiation}
 * shares {@code EntityFoodTracker} with its radiation branch.
 */
public final class GTFoodStats {
    public static final int ALCOHOL = 0;
    public static final int CAFFEINE = 1;
    public static final int DEHYDRATION = 2;
    public static final int SUGAR = 3;
    public static final int FAT = 4;
    public static final int RADIATION = 5;
    /** The five statistics {@link PlayerFoodStats} tracks; radiation lives in {@code PlayerRadiation}. */
    public static final int TRACKED = 5;

    private static final Map<Item, int[]> BY_ITEM = new IdentityHashMap<>();

    /** One {@code FoodsGT.put} row: the item and its six statistics in GT6's order. */
    public record Row(Item item, int alcohol, int caffeine, int dehydration, int sugar, int fat, int radiation) {}

    static {
        for (Row row : GTFoodStatsGen.ROWS) {
            BY_ITEM.put(row.item(), new int[] {
                    row.alcohol(), row.caffeine(), row.dehydration(),
                    row.sugar(), row.fat(), row.radiation()});
        }
    }

    private GTFoodStats() {}

    /** GT6 {@code FoodsGT.get}: the six statistics of a food, or null when it is not in the table. */
    public static int[] stats(ItemStack stack) {
        return stack.isEmpty() ? null : BY_ITEM.get(stack.getItem());
    }

    /** How many food items carry statistics (GT6's table has the same entries plus other mods' food). */
    public static int registered() {
        return BY_ITEM.size();
    }

    /** GT6 food whose 1.20.1 counterpart does not exist, with the reason (never silently dropped). */
    public static List<String> skipped() {
        return GTFoodStatsGen.SKIPPED;
    }
}
