package com.gregtech.gregtech.api.material;

import com.gregtech.gregtech.data.MaterialPrefix;
import java.util.List;

/** Complete original VanillaUnificationLoader identity/weight table without Minecraft types. */
public final class VanillaUnificationDefinitions {
    private VanillaUnificationDefinitions() {}
    public record Entry(String itemPath, MaterialPrefix prefix, String materialName, long amount) {}
    public static List<Entry> entries() {
        return List.of(
                new Entry("ender_pearl", MaterialPrefix.gem, "EnderPearl", MaterialPrefix.gem.getMaterialWeight()),
                new Entry("ender_eye", MaterialPrefix.gem, "EnderEye", MaterialPrefix.gem.getMaterialWeight()),
                new Entry("diamond", MaterialPrefix.gem, "Diamond", MaterialPrefix.gem.getMaterialWeight()),
                new Entry("emerald", MaterialPrefix.gem, "Emerald", MaterialPrefix.gem.getMaterialWeight()),
                new Entry("coal", MaterialPrefix.gem, "Coal", MaterialPrefix.gem.getMaterialWeight()),
                new Entry("charcoal", MaterialPrefix.gem, "Charcoal", MaterialPrefix.gem.getMaterialWeight()),
                new Entry("quartz", MaterialPrefix.gem, "NetherQuartz", MaterialPrefix.gem.getMaterialWeight()),
                new Entry("nether_star", MaterialPrefix.gem, "NetherStar", MaterialPrefix.gem.getMaterialWeight()),
                new Entry("lapis_lazuli", MaterialPrefix.gem, "Lapis", MaterialPrefix.gem.getMaterialWeight()),
                new Entry("iron_ingot", MaterialPrefix.ingot, "Fe", MaterialPrefix.ingot.getMaterialWeight()),
                new Entry("gold_ingot", MaterialPrefix.ingot, "Au", MaterialPrefix.ingot.getMaterialWeight()),
                new Entry("copper_ingot", MaterialPrefix.ingot, "Cu", MaterialPrefix.ingot.getMaterialWeight()),
                new Entry("brick", MaterialPrefix.ingot, "Brick", MaterialPrefix.ingot.getMaterialWeight()),
                new Entry("nether_brick", MaterialPrefix.ingot, "NetherBrick", MaterialPrefix.ingot.getMaterialWeight()),
                new Entry("gold_nugget", MaterialPrefix.nugget, "Au", MaterialPrefix.nugget.getMaterialWeight()),
                new Entry("redstone", MaterialPrefix.dust, "Redstone", MaterialPrefix.dust.getMaterialWeight()),
                new Entry("glowstone_dust", MaterialPrefix.dust, "Glowstone", MaterialPrefix.dust.getMaterialWeight()),
                new Entry("gunpowder", MaterialPrefix.dust, "Gunpowder", MaterialPrefix.dust.getMaterialWeight()),
                new Entry("sugar", MaterialPrefix.dust, "Sugar", MaterialPrefix.dust.getMaterialWeight()),
                new Entry("bone_meal", MaterialPrefix.dust, "Bone", MaterialPrefix.dust.getMaterialWeight()),
                new Entry("blaze_powder", MaterialPrefix.dustTiny, "Blaze", MaterialPrefix.dustTiny.getMaterialWeight()),
                new Entry("blaze_rod", MaterialPrefix.stick, "Blaze", MaterialPrefix.stick.getMaterialWeight()),
                new Entry("stick", MaterialPrefix.stick, "Wood", MaterialPrefix.stick.getMaterialWeight()),
                new Entry("paper", MaterialPrefix.plate, "Paper", MaterialPrefix.plate.getMaterialWeight()),
                new Entry("glass_pane", MaterialPrefix.plate, "Glass", MaterialPrefix.plate.getMaterialWeight()),
                new Entry("flint", null, "Flint", GTValues.U),
                new Entry("sand", null, "Sand", 9L * GTValues.U),
                new Entry("red_sand", null, "RedSand", 9L * GTValues.U),
                new Entry("glass", null, "Glass", 9L * GTValues.U),
                new Entry("netherrack", null, "Netherrack", 9L * GTValues.U),
                new Entry("end_stone", null, "Endstone", 9L * GTValues.U),
                new Entry("obsidian", null, "Obsidian", 9L * GTValues.U),
                new Entry("soul_sand", null, "SoulSand", 9L * GTValues.U),
                new Entry("gravel", null, "Stone", 9L * GTValues.U),
                new Entry("sandstone", null, "Sand", 9L * GTValues.U),
                new Entry("iron_block", null, "Fe", 9L * GTValues.U),
                new Entry("gold_block", null, "Au", 9L * GTValues.U),
                new Entry("copper_block", null, "Cu", 9L * GTValues.U),
                new Entry("diamond_block", null, "Diamond", 9L * GTValues.U),
                new Entry("emerald_block", null, "Emerald", 9L * GTValues.U),
                new Entry("lapis_block", null, "Lapis", 9L * GTValues.U),
                new Entry("coal_block", null, "Coal", 9L * GTValues.U),
                new Entry("redstone_block", null, "Redstone", 9L * GTValues.U),
                new Entry("coal_ore", null, "Coal", 2L * GTValues.U),
                new Entry("iron_ore", null, "Fe", 2L * GTValues.U),
                new Entry("gold_ore", null, "Au", 2L * GTValues.U),
                new Entry("copper_ore", null, "Cu", 2L * GTValues.U),
                new Entry("lapis_ore", null, "Lapis", 2L * GTValues.U),
                new Entry("redstone_ore", null, "Redstone", 2L * GTValues.U),
                new Entry("diamond_ore", null, "Diamond", 2L * GTValues.U),
                new Entry("emerald_ore", null, "Emerald", 2L * GTValues.U),
                new Entry("nether_quartz_ore", null, "NetherQuartz", 2L * GTValues.U),
                new Entry("deepslate_coal_ore", null, "Coal", 2L * GTValues.U),
                new Entry("deepslate_iron_ore", null, "Fe", 2L * GTValues.U),
                new Entry("deepslate_gold_ore", null, "Au", 2L * GTValues.U),
                new Entry("deepslate_copper_ore", null, "Cu", 2L * GTValues.U),
                new Entry("deepslate_lapis_ore", null, "Lapis", 2L * GTValues.U),
                new Entry("deepslate_redstone_ore", null, "Redstone", 2L * GTValues.U),
                new Entry("deepslate_diamond_ore", null, "Diamond", 2L * GTValues.U),
                new Entry("deepslate_emerald_ore", null, "Emerald", 2L * GTValues.U),
                new Entry("raw_copper", MaterialPrefix.oreRaw, "Cu", MaterialPrefix.oreRaw.getMaterialWeight()),
                new Entry("raw_copper_block", MaterialPrefix.oreRaw, "Cu", MaterialPrefix.oreRaw.getMaterialWeight()),
                new Entry("raw_iron", MaterialPrefix.oreRaw, "Fe", MaterialPrefix.oreRaw.getMaterialWeight()),
                new Entry("raw_iron_block", MaterialPrefix.oreRaw, "Fe", MaterialPrefix.oreRaw.getMaterialWeight()),
                new Entry("raw_gold", MaterialPrefix.oreRaw, "Au", MaterialPrefix.oreRaw.getMaterialWeight()),
                new Entry("raw_gold_block", MaterialPrefix.oreRaw, "Au", MaterialPrefix.oreRaw.getMaterialWeight()),
                new Entry("iron_nugget", MaterialPrefix.nugget, "Fe", MaterialPrefix.nugget.getMaterialWeight()),
                new Entry("amethyst_shard", MaterialPrefix.gem, "Amethyst", MaterialPrefix.gem.getMaterialWeight()),
                new Entry("amethyst_block", null, "Amethyst", 9L * GTValues.U),
                new Entry("netherite_ingot", MaterialPrefix.ingot, "Netherite", MaterialPrefix.ingot.getMaterialWeight()),
                new Entry("netherite_block", null, "Netherite", 9L * GTValues.U),
                new Entry("netherite_scrap", null, "AncientDebris", GTValues.U),
                new Entry("ancient_debris", null, "AncientDebris", 2L * GTValues.U),
                new Entry("clay_ball", null, "Clay", GTValues.U),
                new Entry("clay", null, "Clay", 9L * GTValues.U),
                new Entry("glowstone", null, "Glowstone", GTValues.U * 4),
                new Entry("quartz_block", null, "NetherQuartz", GTValues.U * 4),
                new Entry("bone", null, "Bone", GTValues.U * 2),
                new Entry("bone_block", null, "Bone", GTValues.U * 6),
                new Entry("stone", null, "Stone", GTValues.U),
                new Entry("cobblestone", null, "Stone", GTValues.U),
                new Entry("mossy_cobblestone", null, "Stone", GTValues.U),
                new Entry("granite", null, "Granite", GTValues.U),
                new Entry("diorite", null, "Diorite", GTValues.U),
                new Entry("andesite", null, "Andesite", GTValues.U),
                new Entry("deepslate", null, "Deepslate", GTValues.U),
                new Entry("cobbled_deepslate", null, "Deepslate", GTValues.U),
                new Entry("basalt", null, "Basalt", GTValues.U),
                new Entry("blackstone", null, "Blackstone", GTValues.U),
                new Entry("calcite", null, "Calcite", GTValues.U),
                new Entry("tuff", null, "Tuff", GTValues.U),
                new Entry("dripstone_block", null, "Dripstone", GTValues.U),
                new Entry("glass_bottle", null, "Empty", GTValues.U));
    }
}
