package com.gregtech.gregtech.worldgen.center;
/** Original CS.BIOMES_INFINITE_WATER names. Modern native biome tags are checked separately. */
public final class OriginBiomeNames {
    private OriginBiomeNames() {}
    private static final java.util.Set<String> WATER = java.util.Set.of(
            "beach",
            "coldbeach",
            "coldocean",
            "coldriver",
            "coralreef",
            "creekbed",
            "deepocean",
            "estuary",
            "frozenocean",
            "frozenriver",
            "hotocean",
            "hotriver",
            "iceocean",
            "iceriver",
            "improvedoceans",
            "kelpforest",
            "lake",
            "lushriver",
            "mangrove",
            "mushroomislandshore",
            "oasis",
            "ocean",
            "oceanoasis",
            "oceanoilfield",
            "riparianzone",
            "river",
            "riveroasis",
            "rwgoceancold",
            "rwgoceanhot",
            "rwgoceanice",
            "rwgoceanoasis",
            "rwgoceantemperate",
            "rwgoceanwet",
            "rwgrivercold",
            "rwgriverhot",
            "rwgriverice",
            "rwgriveroasis",
            "rwgrivertemperate",
            "rwgriverwet",
            "sandstonecanyon",
            "sandstonecanyon2",
            "stonebeach",
            "temperateocean",
            "temperateriver",
            "tropicalbeach",
            "tropicallake",
            "tropicalocean",
            "tropicalriver",
            "twilightlake",
            "twilightstream",
            "wetocean",
            "wetriver",
            "woodlandlake",
            "woodlandlakeedge");
    public static boolean water(String path) {
        return WATER.contains(path.toLowerCase(java.util.Locale.ROOT).replaceAll("[^a-z0-9]", ""));
    }
}
