/**
 * Copyright (c) 2022 GregTech-6 Team
 *
 * This file is part of GregTech.
 *
 * GregTech is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GregTech is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with GregTech. If not, see <http://www.gnu.org/licenses/>.
 */

package com.gregtech.gregtech.worldgen.center;
/** Original WorldgenTesting inventory slots, resolved by the native item adapter. */
public final class OriginTestInventory { private OriginTestInventory() {}
public static final java.util.List<String> ROWS=java.util.List.of(
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.SWORD                 , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.PICKAXE               , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.SHOVEL                , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.AXE                   , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.HOE                   , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.SAW                   , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.HARDHAMMER            , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.SOFTHAMMER            , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.WRENCH                , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.MONKEY_WRENCH         , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.FILE                  , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.CROWBAR               , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.SCREWDRIVER           , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.CLUB                  , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.WIRECUTTER            , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.SCOOP                 , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.BRANCHCUTTER          , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.UNIVERSALSPADE        , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.KNIFE                 , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.BUTCHERYKNIFE         , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.PLOW                  , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.ROLLING_PIN           , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.CHISEL                , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.FLINT_AND_TINDER      , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.BENDING_CYLINDER      , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.BENDING_CYLINDER_SMALL, MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.DOUBLE_AXE            , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.CONSTRUCTION_PICK     , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.SCISSORS              , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.PINCERS               , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.SPADE                 , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.HAND_DRILL            , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.SENSE                 , MT.NetherizedDiamond, MT.LightBlue)",
"NI",
"NI",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.BUILDERWAND           , MT.Vibramantium, MT.WOODS.Scorched)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.POCKET_MULTITOOL      , MT.Vibramantium, MT.Vibramantium)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.PLUNGER               , MT.Greatwood, MT.Greatwood)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.MAGNIFYING_GLASS      , MT.DiamondPink, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.GEM_PICK              , MT.DiamondPink, MT.LightBlue)",
"ST.make(Items.wooden_pickaxe , 1, 0)",
"ST.make(Items.stone_pickaxe  , 1, 0)",
"ST.make(Items.golden_pickaxe , 1, 0)",
"ST.make(Items.iron_pickaxe   , 1, 0)",
"ST.make(Items.diamond_pickaxe, 1, 0)",
"IL.Tool_Chunk_Remover.get(1)",
"IL.Tool_Worldgen_Debugger.get(1)",
"IL.Tool_Cheat.get(1)",
"IL.IC2_Debug.get(1)",
"IL.Pill_Cure_All.get(64)",
"IL.Thermometer_Quicksilver.get(1)",
"IL.Circuit_Selector.getWithDamage(1, 0)",
"IL.Circuit_Selector.getWithDamage(1, 1)",
"IL.Circuit_Selector.getWithDamage(1, 2)",
"IL.TC_Thaumometer.get(1)",
"IL.TC_Crimson_Rites.get(1)",
"IL.TC_Thaumonomicon.get(1)",
"ST.make(MD.TC, \"ItemThaumonomicon\", 1, 42)",
"ST.make(Items.item_frame, 1, 0)",
"ST.make(Items.bucket, 1, 0)",
"ST.make(Items.water_bucket, 1, 0)",
"ST.make(Items.lava_bucket, 1, 0)",
"ST.make(Items.milk_bucket, 1, 0)",
"ST.make(Blocks.stone_button, 1, 0)",
"ST.make(Blocks.lever, 1, 0)",
"ST.make(Items.redstone, 1, 0)",
"ST.make(Blocks.redstone_torch, 1, 0)",
"ST.make(Items.repeater, 1, 0)",
"ST.make(Items.comparator, 1, 0)",
"ST.make(Blocks.redstone_lamp, 1, 0)",
"OP.cableGt01.mat(MT.Signalum, 1)",
"OP.wireGt01.mat(MT.Lumium, 1)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.WRENCH_LV     , 1, MT.NetherizedDiamond, MT.Magenta, V[1] * 1000, V[1], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.MININGDRILL_LV, 1, MT.NetherizedDiamond, MT.Magenta, V[1] * 1000, V[1], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.CHAINSAW_LV   , 1, MT.NetherizedDiamond, MT.Magenta, V[1] * 1000, V[1], Long.MAX_VALUE)",
"NI",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.MIXER_LV      , 1, MT.NetherizedDiamond, MT.Magenta, V[1] * 1000, V[1], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.SCREWDRIVER_LV, 1, MT.NetherizedDiamond, MT.Magenta, V[1] * 1000, V[1], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.BUZZSAW_LV    , 1, MT.NetherizedDiamond, MT.Magenta, V[1] * 1000, V[1], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.TRIMMER_LV    , 1, MT.NetherizedDiamond, MT.Magenta, V[1] * 1000, V[1], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.DRILL_LV      , 1, MT.NetherizedDiamond, MT.Magenta, V[1] * 1000, V[1], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.WRENCH_MV     , 1, MT.NetherizedDiamond, MT.Magenta, V[2] * 1000, V[2], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.MININGDRILL_MV, 1, MT.NetherizedDiamond, MT.Magenta, V[2] * 1000, V[2], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.CHAINSAW_MV   , 1, MT.NetherizedDiamond, MT.Magenta, V[2] * 1000, V[2], Long.MAX_VALUE)",
"NI",
"NI",
"NI",
"NI",
"IL.Brain_Tape.get(64)",
"IL.Dynamite_Strong.get(64)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.WRENCH_HV     , 1, MT.NetherizedDiamond, MT.Magenta, V[3] * 1000, V[3], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.MININGDRILL_HV, 1, MT.NetherizedDiamond, MT.Magenta, V[3] * 1000, V[3], Long.MAX_VALUE)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.CHAINSAW_HV   , 1, MT.NetherizedDiamond, MT.Magenta, V[3] * 1000, V[3], Long.MAX_VALUE)",
"NI",
"NI",
"NI",
"NI",
"NI",
"IL.Tool_Remote_Activator.get(1)",
"IL.Battery_Lead_Acid_LV.getWithCharge(1, Long.MAX_VALUE)",
"IL.Battery_Lead_Acid_MV.getWithCharge(1, Long.MAX_VALUE)",
"IL.Battery_Lead_Acid_HV.getWithCharge(1, Long.MAX_VALUE)",
"OP.plateCurved.mat(MT.SteelGalvanized, 64)",
"OP.plateCurved.mat(MT.Al, 64)",
"OP.plateCurved.mat(MT.StainlessSteel, 64)",
"IL.MOTORS[1].get(64)",
"IL.MOTORS[2].get(64)",
"IL.MOTORS[3].get(64)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.PISTOL                , MT.Steel            , MT.WOODS.Spruce)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.PISTOL                , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.PISTOL                , MT.Thaumium         , MT.Magenta)",
"OP.bulletGtSmall.mat(MT.Steel, 64)",
"OP.bulletGtSmall.mat(MT.Netherite, 64)",
"OP.bulletGtSmall.mat(MT.Thaumium, 64)",
"OP.bulletGtSmall.mat(MT.SterlingSilver, 64)",
"OP.bulletGtSmall.mat(MT.RoseGold, 64)",
"OP.bulletGtSmall.mat(MT.Rubber, 64)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.CARBINE               , MT.Steel            , MT.WOODS.Spruce)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.CARBINE               , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.CARBINE               , MT.Thaumium         , MT.Magenta)",
"OP.bulletGtMedium.mat(MT.Steel, 64)",
"OP.bulletGtMedium.mat(MT.Netherite, 64)",
"OP.bulletGtMedium.mat(MT.Thaumium, 64)",
"OP.bulletGtMedium.mat(MT.SterlingSilver, 64)",
"OP.bulletGtMedium.mat(MT.RoseGold, 64)",
"OP.bulletGtMedium.mat(MT.Rubber, 64)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.RIFLE                 , MT.Steel            , MT.WOODS.Spruce)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.RIFLE                 , MT.NetherizedDiamond, MT.LightBlue)",
"ToolsGT.sMetaTool.getToolWithStats(ToolsGT.RIFLE                 , MT.Thaumium         , MT.Magenta)",
"OP.bulletGtLarge.mat(MT.Steel, 64)",
"OP.bulletGtLarge.mat(MT.Netherite, 64)",
"OP.bulletGtLarge.mat(MT.Thaumium, 64)",
"OP.bulletGtLarge.mat(MT.SterlingSilver, 64)",
"OP.bulletGtLarge.mat(MT.RoseGold, 64)",
"OP.bulletGtLarge.mat(MT.Rubber, 64)",
"NI",
"NI",
"NI",
"NI",
"NI",
"NI",
"NI",
"NI",
"NI"
);
}
