package com.gregtech.gregtech.api.fluid;
import net.minecraft.core.HolderLookup;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.resources.ResourceLocation;import net.minecraft.world.item.ItemStack;import net.neoforged.neoforge.fluids.FluidStack;import com.gregtech.gregtech.platform.neoforge.fluid.FluidDisplayItem;import com.gregtech.gregtech.data.RegisteredFluids;
/** Full source display payload, preserving external fluid identity and native components via provider serialization. */
public final class FluidDisplayBinding {private FluidDisplayBinding(){}public static final String TAG="gt.display_fluid";
 private static volatile java.util.function.Supplier<HolderLookup.Provider> clientLookup=()->null;
 public static void setClientLookup(java.util.function.Supplier<HolderLookup.Provider> lookup){clientLookup=java.util.Objects.requireNonNull(lookup);}
 public static HolderLookup.Provider currentLookup(){var server=net.neoforged.neoforge.server.ServerLifecycleHooks.getCurrentServer();return server==null?clientLookup.get():server.registryAccess();}
 public static FluidStack resolveCurrent(ItemStack stack){var lookup=currentLookup();return hasPayload(stack)&&lookup==null?FluidStack.EMPTY:resolve(lookup,stack);}

 public static boolean hasPayload(ItemStack stack){var tag=com.gregtech.gregtech.content.data.UsbDataMedia.tag(stack);return tag!=null&&tag.contains(TAG,10);}
 public static ItemStack display(HolderLookup.Provider lookup,FluidStack fluid){if(fluid.isEmpty())return ItemStack.EMPTY;var id=BuiltInRegistries.FLUID.getKey(fluid.getFluid());net.minecraft.world.item.Item item=id.getNamespace().equals("gregtech")?BuiltInRegistries.ITEM.get(ResourceLocation.fromNamespaceAndPath("gregtech","fluid_item_"+id.getPath())):null;if(!(item instanceof FluidDisplayItem))for(var handle:com.gregtech.gregtech.platform.neoforge.fluid.FluidRegistries.ITEMS.getEntries()){item=handle.get();break;}if(!(item instanceof FluidDisplayItem))return ItemStack.EMPTY;var out=new ItemStack(item);var tag=com.gregtech.gregtech.content.data.UsbDataMedia.tagOrEmpty(out);tag.put(TAG,fluid.save(lookup));com.gregtech.gregtech.content.data.UsbDataMedia.store(out,tag);return out;}
 public static FluidStack resolve(HolderLookup.Provider lookup,ItemStack stack){if(!(stack.getItem() instanceof FluidDisplayItem item))return FluidStack.EMPTY;if(hasPayload(stack))return FluidStack.parseOptional(lookup,com.gregtech.gregtech.content.data.UsbDataMedia.tag(stack).getCompound(TAG));var id=ResourceLocation.fromNamespaceAndPath("gregtech",RegisteredFluids.sanitizePath(item.fluidEntry().registryName()));var fluid=BuiltInRegistries.FLUID.get(id);return fluid==net.minecraft.world.level.material.Fluids.EMPTY?FluidStack.EMPTY:new FluidStack(fluid,1000);}
 public static String subtype(HolderLookup.Provider lookup,ItemStack stack){var fluid=resolve(lookup,stack);return fluid.isEmpty()?"empty":BuiltInRegistries.FLUID.getKey(fluid.getFluid())+"/"+fluid.getComponentsPatch();}
}
