package com.gregtech.gregtech.gametest;

import com.gregtech.gregtech.block.stone.StoneType;
import com.gregtech.gregtech.blockentity.misc.CoinPileBlockEntity;
import com.gregtech.gregtech.worldgen.GTDungeonFeature;
import com.gregtech.gregtech.worldgen.dungeon.GTDungeonChunk;
import com.gregtech.gregtech.worldgen.dungeon.GTDungeonChunkRoomLibraryNormal;
import com.gregtech.gregtech.worldgen.dungeon.GTDungeonChunkRoomMiningBedrock;
import com.gregtech.gregtech.worldgen.dungeon.GTDungeonChunkRoomWorkshop;
import com.gregtech.gregtech.worldgen.dungeon.GTDungeonData;
import com.gregtech.gregtech.worldgen.dungeon.GTDungeonLayout;
import com.gregtech.gregtech.worldgen.dungeon.GTDungeonSharedState;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.util.RandomSource;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.gametest.GameTestHolder;
import net.minecraftforge.gametest.PrefixGameTestTemplate;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;

/** Guards the dungeon-wide decisions that must survive arbitrary chunk generation order. */
@GameTestHolder("gregtech_repair")
@PrefixGameTestTemplate(false)
public final class DungeonSharedStateTests {
    private DungeonSharedStateTests() {}

    private static byte[][] layout() {
        byte[][] cells = new byte[8][8];
        for (int i = 1; i < 7; i++) for (int j = 1; j < 7; j++) cells[i][j] = 1;
        cells[1][1] = GTDungeonLayout.BARRACKS;
        cells[1][2] = GTDungeonLayout.CORRIDOR;
        return cells;
    }

    @GameTest(template = "test_empty", timeoutTicks = 200)
    public static void roomAndKeyPlanIsDungeonWideAndOrderIndependent(GameTestHelper helper) {
        byte[][] layout = layout();
        for (long seed = 1; seed <= 96; seed++) {
            GTDungeonSharedState first = GTDungeonSharedState.create(layout, seed);
            GTDungeonSharedState rebuilt = GTDungeonSharedState.create(layout, seed);
            Map<String, Integer> roomCounts = new HashMap<>();
            boolean[] expectedKeys = new boolean[GTDungeonFeature.KEY_COUNT];
            String metal = first.cell(1, 1).coinMetal();
            for (int i = 1; i < 7; i++) {
                for (int j = 1; j < 7; j++) {
                    GTDungeonSharedState.CellState cell = first.cell(i, j);
                    GTDungeonSharedState.CellState again = rebuilt.cell(i, j);
                    helper.assertTrue(cell.coinMetal().equals(metal) && again.coinMetal().equals(metal),
                            "one coin metal for every cell of seed " + seed);
                    helper.assertTrue(cell.chosenRoom() == again.chosenRoom()
                                    && cell.tagsBefore().equals(again.tagsBefore())
                                    && Arrays.equals(cell.keysBefore(), again.keysBefore()),
                            "the cell plan is reproducible without chunk-order state: " + seed + "/" + i + "/" + j);
                    if (layout[i][j] <= 0) continue;
                    GTDungeonChunk room = cell.chosenRoom();
                    String tag = GTDungeonSharedState.tagFor(room);
                    if (tag != null) roomCounts.merge(tag, 1, Integer::sum);
                    helper.assertTrue(Arrays.equals(cell.keysBefore(), expectedKeys),
                            "normal rooms see keys generated by earlier normal rooms");
                    if (room instanceof GTDungeonChunkRoomWorkshop && cell.workshopKey() < expectedKeys.length) {
                        expectedKeys[cell.workshopKey()] = true;
                    } else if (room instanceof GTDungeonChunkRoomLibraryNormal) {
                        for (int row : new int[]{1, 2, 4, 5}) expectedKeys[cell.libraryKey(row)] = true;
                    }
                }
            }
            helper.assertTrue(roomCounts.values().stream().allMatch(count -> count == 1),
                    "each GT6 tagged room appears at most once per dungeon, got " + roomCounts);
            helper.assertTrue(Arrays.equals(first.cell(1, 1).keysBefore(), expectedKeys),
                    "the barracks sees the complete earlier-room key record");
            for (int key : new int[]{0, 1, 3, 4}) expectedKeys[key] = true;
            helper.assertTrue(Arrays.equals(first.cell(1, 2).keysBefore(), expectedKeys),
                    "a corridor after the barracks sees its four guaranteed keys");

            // Production calls create(...) afresh for each chunk. Visit the first few sampled
            // dungeons in the opposite order and require exactly the same cell-local decisions.
            if (seed <= 6) {
                for (int i = 6; i >= 1; i--) {
                    for (int j = 6; j >= 1; j--) {
                        GTDungeonSharedState.CellState inReverse = GTDungeonSharedState.create(layout, seed).cell(i, j);
                        GTDungeonSharedState.CellState canonical = first.cell(i, j);
                        helper.assertTrue(inReverse.chosenRoom() == canonical.chosenRoom()
                                        && inReverse.tagsBefore().equals(canonical.tagsBefore())
                                        && Arrays.equals(inReverse.keysBefore(), canonical.keysBefore())
                                        && inReverse.coinMetal().equals(canonical.coinMetal()),
                                "reverse chunk visitation cannot change dungeon state");
                    }
                }
            }
        }
        helper.succeed();
    }

    @GameTest(template = "coin_pile_space", timeoutTicks = 200)
    public static void separatePilesReceiveTheSameDungeonMetal(GameTestHelper helper) {
        byte[][] layout = layout();
        GTDungeonSharedState plan = GTDungeonSharedState.create(layout, 80714L);
        BlockPos a = helper.absolutePos(new BlockPos(2, 1, 2));
        BlockPos b = helper.absolutePos(new BlockPos(5, 1, 5));
        GTDungeonData first = data(helper, a, layout, 2, 2, plan.cell(2, 2));
        GTDungeonData second = data(helper, b, layout, 3, 3, plan.cell(3, 3));
        helper.assertTrue(first.coins(0, 0, 0) && second.coins(0, 0, 0), "both coin piles are placed");
        CoinPileBlockEntity pileA = (CoinPileBlockEntity) helper.getLevel().getBlockEntity(a);
        CoinPileBlockEntity pileB = (CoinPileBlockEntity) helper.getLevel().getBlockEntity(b);
        helper.assertTrue(pileA != null && pileB != null
                        && ItemStack.isSameItemSameTags(pileA.coinItem(), pileB.coinItem()),
                "different dungeon cells use the same chosen coin material");
        helper.succeed();
    }

    /** GT6 marks the mining tag before testing the world's bedrock; that reservation is not a key. */
    @GameTest(template = "test_empty", timeoutTicks = 200)
    public static void bedrockRefusalCanReserveOnlyTheMiningTag(GameTestHelper helper) {
        byte[][] layout = layout();
        boolean found = false;
        for (long seed = 1; seed <= 96 && !found; seed++) {
            GTDungeonSharedState plan = GTDungeonSharedState.create(layout, seed);
            GTDungeonSharedState.CellState precedingMining = null;
            for (int i = 1; i < 7; i++) {
                for (int j = 1; j < 7; j++) {
                    if (layout[i][j] <= 0) continue;
                    GTDungeonSharedState.CellState current = plan.cell(i, j);
                    if (precedingMining != null) {
                        helper.assertTrue(current.tagsBefore().contains(GTDungeonChunkRoomMiningBedrock.TAG_MINING_BEDROCK),
                                "a failed bedrock check still consumes its GT6 room tag");
                        helper.assertTrue(Arrays.equals(current.keysBefore(), precedingMining.keysBefore()),
                                "the mining room cannot fabricate a key when the terrain check rejects it");
                        found = true;
                        break;
                    }
                    precedingMining = current.chosenRoom() instanceof GTDungeonChunkRoomMiningBedrock
                            ? current : null;
                }
                if (found) break;
            }
        }
        helper.assertTrue(found, "a sampled dungeon assigned a mining room before another normal room");
        helper.succeed();
    }

    @GameTest(template = "test_empty", timeoutTicks = 200)
    public static void plannedWorkshopKeyPreservesLaterRoomRolls(GameTestHelper helper) {
        byte[][] layout = layout();
        for (long seed = 1; seed <= 96; seed++) {
            GTDungeonSharedState plan = GTDungeonSharedState.create(layout, seed);
            for (int i = 1; i < 7; i++) {
                for (int j = 1; j < 7; j++) {
                    GTDungeonSharedState.CellState state = plan.cell(i, j);
                    if (!(state.chosenRoom() instanceof GTDungeonChunkRoomWorkshop)) continue;
                    RandomSource original = RandomSource.create(173L);
                    int originalIndex = original.nextInt(GTDungeonFeature.KEY_COUNT * 2);
                    if (originalIndex < GTDungeonFeature.KEY_COUNT) original.nextInt(18);
                    int nextOriginalRoll = original.nextInt(32);
                    GTDungeonData data = data(helper, helper.absolutePos(new BlockPos(1, 1, 1)),
                            layout, i, j, state);
                    GTDungeonData.WorkshopKeyDecision decision = data.workshopKeyDecision();
                    helper.assertTrue(decision.index() == state.workshopKey()
                                    && data.next(32) == nextOriginalRoll,
                            "the shared key choice keeps GT6's later workshop room stream aligned");
                    helper.succeed();
                    return;
                }
            }
        }
        helper.fail("sampled dungeons never assigned a workshop");
    }

    private static GTDungeonData data(GameTestHelper helper, BlockPos at, byte[][] layout, int i, int j,
                                      GTDungeonSharedState.CellState state) {
        long[] ids = new long[GTDungeonFeature.KEY_COUNT];
        ItemStack[] stacks = new ItemStack[GTDungeonFeature.KEY_COUNT];
        return new GTDungeonData(helper.getLevel(), at.getX(), at.getY(), at.getZ(),
                StoneType.LIMESTONE, StoneType.SLATE, 3, layout, i, j, 4,
                ids, stacks, state.keysBefore(), new HashSet<>(), new HashSet<>(state.tagsBefore()),
                RandomSource.create(173L), state);
    }
}
