package com.gregtech.gregtech.gametest;

import com.gregtech.gregtech.api.tool.GTToolHelper;
import com.gregtech.gregtech.item.GTToolItem;
import com.gregtech.gregtech.item.TechItem;
import com.gregtech.gregtech.registry.GTTechnological;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.inventory.AbstractContainerMenu;
import net.minecraft.world.inventory.TransientCraftingContainer;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Recipe;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.gametest.GameTestHolder;
import net.minecraftforge.gametest.PrefixGameTestTemplate;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * The hand-crafting batch that closed GT6's cover, USB, logistics and selector-circuit gaps.
 *
 * <p>Rows are generated by {@code tools/generate_covers_usb_logistics_recipes.py} from GT6's own
 * registrations — covers {@code MultiItemTechnological:139-178} plus the pump/conveyor/robot-arm
 * covers at {@code :419-422}, USB parts {@code :796-822}, logistics buses {@code :773-787} with the
 * shapeless variant cycle at {@code :117-131}, and the selector circuits at
 * {@code ItemIntegratedCircuit:58-85}.</p>
 *
 * <p>What these tests protect: every item of the batch is craftable, no recipe of the batch has an
 * ingredient that resolves to nothing (an empty tag silently produces an uncraftable recipe), and no
 * two rows of the batch match the same grid — GT6's own {@code CR.DEF} does not mirror patterns, so a
 * mirror-image pair such as the logistics export/storage buses would otherwise collapse.</p>
 */
@GameTestHolder("gregtech")
@PrefixGameTestTemplate(false)
public final class HandCraftingTests {

    /** Every item the batch had to make obtainable, in the order the generator writes them. */
    private static final String[] BATCH_OUTPUTS = {
            // covers (MultiItemTechnological:140,159,161,167,170,178). The pump/conveyor/robot-arm
            // covers, the redstone torch/repeater covers and the tag selector are not items of their
            // own: GT6 gives those roles to the compact components (MultiItemTechnological:50-53),
            // the vanilla blocks (GT_API:799-802) and the selector circuits (ItemIntegratedCircuit:87)
            // — see HandCraftingTests.vanillaBlocksAndComponentsDoubleAsCovers.
            "crafting_table_cover", "warning_cover", "item_retriever_cover", "drain", "air_vent",
            "pressure_value",
            // USB parts (MultiItemTechnological:796-799, :808-811, :819-822)
            "usb1_stick", "usb2_stick", "usb3_stick", "usb4_stick",
            "usb1_cable", "usb2_cable", "usb3_cable", "usb4_cable",
            "usb1_hdd", "usb2_hdd", "usb3_hdd", "usb4_hdd",
            // logistics (MultiItemTechnological:773-787)
            "logistics_display_cpu_logic", "logistics_display_cpu_control",
            "logistics_display_cpu_storage", "logistics_display_cpu_conversion",
            "filtered_logistics_export_bus_item", "filtered_logistics_import_bus_item",
            "filtered_logistics_storage_bus_item", "filtered_logistics_export_bus_fluid",
            "filtered_logistics_import_bus_fluid", "filtered_logistics_storage_bus_fluid",
            "generic_logistics_export_bus", "generic_logistics_import_bus",
            "generic_logistics_storage_bus", "logistics_dump_bus_item",
            // selector circuits (ItemIntegratedCircuit:58-85)
            "integrated_circuit_0", "integrated_circuit_1", "integrated_circuit_2",
            "integrated_circuit_3", "integrated_circuit_4", "integrated_circuit_5",
            "integrated_circuit_6", "integrated_circuit_7", "integrated_circuit_8",
            "integrated_circuit_9", "integrated_circuit_10", "integrated_circuit_11",
            "integrated_circuit_12", "integrated_circuit_13", "integrated_circuit_14",
            "integrated_circuit_15", "integrated_circuit_16", "integrated_circuit_17",
            "integrated_circuit_18", "integrated_circuit_19", "integrated_circuit_20",
            "integrated_circuit_21", "integrated_circuit_22", "integrated_circuit_23",
            "integrated_circuit_24"};

    /** Recipe directories/ids the generated batch owns. */
    private static boolean isBatchRecipe(ResourceLocation id) {
        if (!id.getNamespace().equals("gregtech")) return false;
        String path = id.getPath();
        if (path.startsWith("hand_covers/") || path.startsWith("hand_components/")) return true;
        if (!path.startsWith("logistics/")) return false;
        String name = path.substring("logistics/".length());
        return name.startsWith("logistics_display_cpu_") || name.startsWith("logistics_cycle_")
                || name.startsWith("filtered_logistics_") || name.startsWith("generic_logistics_")
                || name.equals("logistics_dump_bus_item");
    }

    private static List<Recipe<?>> batch(GameTestHelper helper) {
        List<Recipe<?>> batch = new ArrayList<>();
        for (Recipe<?> recipe : helper.getLevel().getRecipeManager().getRecipes()) {
            if (isBatchRecipe(recipe.getId())) batch.add(recipe);
        }
        return batch;
    }

    private static TransientCraftingContainer grid() {
        var menu = new AbstractContainerMenu(null, 0) {
            public ItemStack quickMoveStack(net.minecraft.world.entity.player.Player player, int slot) {
                return ItemStack.EMPTY;
            }

            public boolean stillValid(net.minecraft.world.entity.player.Player player) {
                return true;
            }
        };
        return new TransientCraftingContainer(menu, 3, 3);
    }

    /** GT tools have to be usable copies, exactly like a player would hold them. */
    private static ItemStack usable(ItemStack stack) {
        if (stack.getItem() instanceof GTToolItem) {
            return GTToolItem.create(GTToolHelper.getType(stack),
                    com.gregtech.gregtech.content.material.Materials.Steel,
                    com.gregtech.gregtech.api.material.GTMaterialRegistry.get("Wood"));
        }
        return stack.copy();
    }

    /** Every item the batch promised to make obtainable is produced by some recipe. */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 400)
    public static void batchItemsAreCraftable(GameTestHelper h) {
        Set<String> produced = new TreeSet<>();
        for (Recipe<?> recipe : h.getLevel().getRecipeManager().getRecipes()) {
            ItemStack result;
            try {
                result = recipe.getResultItem(h.getLevel().registryAccess());
            } catch (RuntimeException e) {
                continue;
            }
            if (result != null && !result.isEmpty()) {
                ResourceLocation key = ForgeRegistries.ITEMS.getKey(result.getItem());
                if (key != null) produced.add(key.getPath());
            }
        }
        List<String> missing = new ArrayList<>();
        for (String id : BATCH_OUTPUTS) if (!produced.contains(id)) missing.add(id);
        h.assertTrue(missing.isEmpty(), "GT6 hand recipes missing for: " + missing);

        // ... and no other cover/USB/logistics/selector item is left without a recipe either.
        List<String> leftovers = new ArrayList<>();
        for (var entry : GTTechnological.all()) {
            if (!entry.isPresent()) continue;
            ResourceLocation key = ForgeRegistries.ITEMS.getKey(entry.get());
            if (key == null) continue;
            String id = key.getPath();
            boolean inBatchFamily = id.startsWith("cover") || id.startsWith("usb")
                    || id.contains("logistics") || id.startsWith("integrated_circuit_")
                    || id.equals("drain") || id.equals("air_vent") || id.equals("pressure_value");
            if (inBatchFamily && !produced.contains(id)) leftovers.add(id);
        }
        h.assertTrue(leftovers.isEmpty(), "cover/USB/logistics items still without a recipe: " + leftovers);
        h.succeed();
    }

    /** No generated row may contain an ingredient that matches nothing (an empty tag / bad id). */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 400)
    public static void batchIngredientsResolve(GameTestHelper h) {
        List<Recipe<?>> batch = batch(h);
        h.assertTrue(batch.size() == 71, "71 generated hand recipes loaded; got " + batch.size());
        for (Recipe<?> recipe : batch) {
            for (var ingredient : recipe.getIngredients()) {
                if (ingredient.isEmpty()) continue;             // pattern space
                h.assertTrue(ingredient.getItems().length > 0,
                        "ingredient of " + recipe.getId() + " matches no item");
            }
        }
        h.succeed();
    }

    /**
     * Each row must craft exactly once: building the grid from a recipe's own ingredients may match
     * that recipe only. This is what catches the mirror-image collisions GT6 avoids by not setting
     * {@code CR.MIR}.
     */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 600)
    public static void batchPatternsAreUnambiguous(GameTestHelper h) {
        List<Recipe<?>> batch = batch(h);
        List<Recipe<?>> all = new ArrayList<>(h.getLevel().getRecipeManager().getRecipes());
        TreeMap<String, String> collisions = new TreeMap<>();
        int checked = 0;
        for (Recipe<?> recipe : batch) {
            if (!(recipe instanceof net.minecraft.world.item.crafting.ShapedRecipe shaped)) continue;
            TransientCraftingContainer grid = grid();
            for (int y = 0; y < shaped.getHeight(); y++) {
                for (int x = 0; x < shaped.getWidth(); x++) {
                    var ingredient = shaped.getIngredients().get(x + y * shaped.getWidth());
                    if (!ingredient.isEmpty()) {
                        ItemStack[] options = ingredient.getItems();
                        h.assertTrue(options.length > 0, "ingredient of " + shaped.getId() + " matches no item");
                        grid.setItem(x + y * 3, usable(options[0]));
                    }
                }
            }
            h.assertTrue(shaped.matches(grid, h.getLevel()), "generated pattern works: " + shaped.getId());
            List<String> also = new ArrayList<>();
            for (Recipe<?> other : all) {
                if (other == shaped || !(other instanceof net.minecraft.world.item.crafting.ShapedRecipe candidate)) {
                    continue;
                }
                if (candidate.matches(grid, h.getLevel())) also.add(other.getId().toString());
            }
            if (!also.isEmpty()) collisions.put(shaped.getId().toString(), also.toString());
            checked++;
        }
        h.assertTrue(collisions.isEmpty(), "generated patterns collide: " + collisions);
        // 57 of the 71 generated rows are shaped (6 covers, 12 USB parts, 14 logistics buses,
        // 25 selector circuits); the other 14 are the shapeless logistics variant cycle.
        h.assertTrue(checked == 57, "shaped rows checked for collisions: " + checked);
        h.succeed();
    }

    /**
     * GT6's rows do not mirror unless they say so ({@code CR.java:161-163}: {@code DEF = BUF|NO_REM},
     * {@code DEF_MIR = DEF|MIR}); 1.20.1 mirrors shaped recipes by default. Every
     * {@code gregtech:tool_shaped} recipe therefore has to carry the original's answer
     * ({@code tools/apply_recipe_mirror_flags.py} writes it from
     * {@code docs/gt6-crafting-mirror-flags.json}); the census found no port row that opts in
     * (93 of GT6's 1188 rows do; this port registers the Blue Spruce slab from
     * {@code Loader_Recipes_Woods.java:270}, which uses {@code CR.DEF_NCC_MIR}).
     *
     * <p>The pattern itself is reported per row ({@code docs/tool-shaped-mirror-report.json}, read
     * back by {@code tools/report_tool_shaped_mirror.py}) so the flag can be audited against the
     * shape; the collision check — what mirroring actually breaks in game — is
     * {@link #batchPatternsAreUnambiguous}.</p>
     */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 600)
    public static void toolShapedRecipesDoNotMirrorUnlessTheOriginalDid(GameTestHelper h) {
        int checked = 0;
        int asymmetric = 0;
        int unresolvedIngredients = 0;
        java.util.List<String> mirroring = new java.util.ArrayList<>();
        for (Recipe<?> recipe : h.getLevel().getRecipeManager().getRecipes()) {
            if (!recipe.getId().getNamespace().equals("gregtech")) continue;
            if (!(recipe instanceof com.gregtech.gregtech.recipe.ToolShapedRecipe tool)) continue;
            // Rows injected at runtime (hand recipes, the GT6 masonry patterns) state their own flag in
            // code and are audited by their own tests; this rule is about the data-pack rows the
            // mirror-flag tool writes.
            if (com.gregtech.gregtech.loaders.Loader_StoneCraftingRecipes.registeredIds()
                    .contains(tool.getId().toString())) continue;
            if (com.gregtech.gregtech.loaders.Loader_HandToolCraftingRecipes.registeredIds()
                    .contains(tool.getId().toString())) continue;
            if (com.gregtech.gregtech.loaders.Loader_ToolCraftingRecipes.registeredIds()
                    .contains(tool.getId().toString())) continue;
            checked++;
            if (tool.allowMirror()) mirroring.add(tool.getId().toString());
            int width = tool.getWidth();
            int height = tool.getHeight();
            boolean symmetric = true;
            for (int y = 0; y < height; y++) {
                for (int x = 0; x < width; x++) {
                    var ingredient = tool.getIngredients().get(x + y * width);
                    var mirrored = tool.getIngredients().get(width - 1 - x + y * width);
                    if (ingredient.isEmpty() != mirrored.isEmpty()) symmetric = false;
                    if (!ingredient.isEmpty() && ingredient.getItems().length == 0) unresolvedIngredients++;
                }
            }
            if (!symmetric) asymmetric++;
        }
        // 668 data-pack rows (the runtime hand/stone rows state their flag in code and are audited by
        // their own tests, so they are excluded above).
        h.assertTrue(checked >= 600, "tool_shaped recipes checked: " + checked);
        h.assertTrue(mirroring.equals(java.util.List.of("gregtech:wood/slab_bluespruce")),
                "only the GT6 CR.DEF_NCC_MIR Blue Spruce slab row mirrors: " + mirroring);
        // 113 of those 668 data-pack rows have a pattern that is not mirror-symmetric, i.e. exactly the
        // rows where the flag is observable at all (183 counting the runtime hand/stone rows, which
        // state their own flag in code).
        h.assertTrue(asymmetric >= 100, "asymmetric patterns present: " + asymmetric);
        h.assertTrue(unresolvedIngredients == 0,
                "ingredients that match no item: " + unresolvedIngredients);
        h.succeed();
    }

    /** Shape report for the mirror rule: written so the pattern of every row can be inspected. */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 400)
    public static void mirrorRuleReportIsWritten(GameTestHelper h) {
        var report = new java.util.TreeMap<String, com.google.gson.JsonObject>();
        int unbuildable = 0;
        int asymmetric = 0;
        for (Recipe<?> recipe : h.getLevel().getRecipeManager().getRecipes()) {
            if (!recipe.getId().getNamespace().equals("gregtech")) continue;
            if (!(recipe instanceof com.gregtech.gregtech.recipe.ToolShapedRecipe tool)) continue;
            int width = tool.getWidth();
            int height = tool.getHeight();
            StringBuilder shape = new StringBuilder();
            boolean buildable = true;
            boolean symmetric = true;
            int unresolved = 0;
            for (int y = 0; y < height; y++) {
                for (int x = 0; x < width; x++) {
                    var ingredient = tool.getIngredients().get(x + y * width);
                    var mirrored = tool.getIngredients().get(width - 1 - x + y * width);
                    boolean empty = ingredient.isEmpty();
                    boolean emptyMirror = mirrored.isEmpty();
                    if (empty != emptyMirror) symmetric = false;
                    if (empty) {
                        shape.append('.');
                        continue;
                    }
                    if (ingredient.getItems().length == 0) {
                        buildable = false;
                        unresolved++;
                        shape.append('?');
                        continue;
                    }
                    shape.append('X');
                }
                shape.append('/');
            }
            if (!buildable) unbuildable++;
            else if (!symmetric) asymmetric++;
            var entry = new com.google.gson.JsonObject();
            entry.addProperty("mirror", tool.allowMirror());
            entry.addProperty("size", width + "x" + height);
            entry.addProperty("shape", shape.toString());
            entry.addProperty("symmetric", symmetric);
            entry.addProperty("unresolvedIngredients", unresolved);
            report.put(tool.getId().toString(), entry);
        }
        try {
            java.nio.file.Files.writeString(
                    java.nio.file.Path.of("../../docs/tool-shaped-mirror-report.json"),
                    new com.google.gson.GsonBuilder().setPrettyPrinting().create().toJson(report));
        } catch (java.io.IOException e) {
            h.fail("cannot write docs/tool-shaped-mirror-report.json: " + e);
            return;
        }
        h.assertTrue(report.size() >= 1180, "rows reported: " + report.size()
                + " (asymmetric " + asymmetric + ", unbuildable " + unbuildable + ")");
        h.succeed();
    }
    /** The 25 selector circuits are what makes the programming grid meaningful: 0 plus 24 tags. */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 300)
    public static void selectorCircuitsAreProgrammable(GameTestHelper h) {
        for (int i = 0; i < 25; i++) {
            h.assertTrue(GTTechnological.selectorTag(i) != null, "selector circuit " + i + " is registered");
            h.assertTrue(GTTechnological.selectorTag(i) instanceof TechItem,
                    "selector circuit " + i + " is a recipe selector");
        }
        Set<String> ids = new TreeSet<>();
        for (Recipe<?> recipe : batch(h)) {
            if (recipe.getId().getPath().startsWith("hand_components/integrated_circuit_")) {
                ids.add(recipe.getId().getPath());
            }
        }
        h.assertTrue(ids.size() == 25, "25 selector circuit recipes loaded; got " + ids.size());
        h.succeed();
    }

    /**
     * GT6's shared-role covers: the vanilla redstone torch/repeater ({@code GT_API:799-802}) and the
     * compact electric pump/conveyor/robot arm ({@code MultiItemTechnological:50-53}) are covers
     * themselves, and the programmed circuit is the tag selector ({@code ItemIntegratedCircuit:87}).
     * The port must attach those items directly — no separate cover item, and no recipe for one.
     */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 400)
    public static void vanillaBlocksAndComponentsDoubleAsCovers(GameTestHelper h) {
        var pump = new ItemStack(GTTechnological.get("compact_electric_pump_lv"));
        var conveyor = new ItemStack(GTTechnological.get("compact_electric_conveyor_ulv"));
        var arm = new ItemStack(GTTechnological.get("compact_robot_arm_uv"));
        var circuit = new ItemStack(GTTechnological.selectorTag(7));
        var torch = new ItemStack(net.minecraft.world.item.Items.REDSTONE_TORCH);
        var repeater = new ItemStack(net.minecraft.world.item.Items.REPEATER);

        h.assertTrue(com.gregtech.gregtech.content.cover.CoverItems.behavior(torch)
                .equals(com.gregtech.gregtech.content.cover.CoverItems.REDSTONE_TORCH),
                "a vanilla redstone torch is a redstone torch cover");
        h.assertTrue(com.gregtech.gregtech.content.cover.CoverItems.behavior(repeater)
                .equals(com.gregtech.gregtech.content.cover.CoverItems.REDSTONE_REPEATER),
                "a vanilla repeater is a redstone repeater cover");
        h.assertTrue(com.gregtech.gregtech.content.cover.CoverItems.behavior(pump)
                .equals(com.gregtech.gregtech.content.cover.CoverItems.PUMP), "a compact pump is a pump cover");
        h.assertTrue(com.gregtech.gregtech.content.cover.CoverItems.behavior(circuit)
                .equals(com.gregtech.gregtech.content.cover.CoverItems.TAG_SELECTOR), "a circuit selects tags");
        h.assertTrue(com.gregtech.gregtech.content.cover.CoverItems.selectorTag(circuit) == 7,
                "the circuit's variant is the selected tag");
        h.assertTrue(!com.gregtech.gregtech.content.cover.CoverItems.isCover(new ItemStack(Items.IRON_INGOT)),
                "an ordinary item is not a cover");

        // GT6 tiers: CoverPump(250 << 2i) mB per 20 ticks, CoverConveyor/RobotArm(512 >> i) ticks.
        h.assertTrue(com.gregtech.gregtech.content.cover.CoverItems.pumpThroughput(pump) == 1000,
                "LV pump moves 1000 mB per operation");
        h.assertTrue(com.gregtech.gregtech.content.cover.CoverItems.itemInterval(conveyor) == 512,
                "ULV conveyor moves a stack every 512 ticks");
        h.assertTrue(com.gregtech.gregtech.content.cover.CoverItems.itemInterval(arm) == 2,
                "UV robot arm moves a stack every 2 ticks");

        // ... and the machine accepts them on a face, which is what makes them covers.
        var block = com.gregtech.gregtech.api.machine.MachineRegistry.basicMachines().get(0).get();
        BlockPos pos = new BlockPos(4, 3, 4);
        h.setBlock(pos, Blocks.AIR);
        h.setBlock(pos, block);
        var machine = (com.gregtech.gregtech.blockentity.machine.BasicMachineBlockEntity)
                h.getLevel().getBlockEntity(h.absolutePos(pos));
        h.assertTrue(machine.attachCover(Direction.NORTH, pump), "machine face accepts a compact pump");
        h.assertTrue(com.gregtech.gregtech.content.cover.CoverItems.behavior(machine.getCover(Direction.NORTH))
                        .equals(com.gregtech.gregtech.content.cover.CoverItems.PUMP),
                "the attached pump keeps its cover behaviour");
        h.assertTrue(machine.removeCover(Direction.NORTH).is(pump.getItem()), "crowbar returns the component");
        h.assertTrue(!machine.attachCover(Direction.SOUTH, torch), "machine rejects a wire-only redstone torch");
        h.assertTrue(!machine.hasRedstoneCover(), "rejected torch does not become a machine cover");
        h.succeed();
    }

    /**
     * The filled cells come from the Canning Machine (GT6 {@code MultiItemTechnological:462-482}
     * declares each filled cell as a fluid container), so each empty cell needs exactly one row and
     * that row must deliver the original's electrolyte amount.
     */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 300)
    public static void filledBatteryCellsComeFromTheCanner(GameTestHelper h) {
        String[][] expected = {
                {"lead_acid_cell_empty", "lead_acid_cell_filled", "2000"},
                {"alkaline_button_cell_empty", "alkaline_button_cell_filled", "1000"},
                {"nickel_cadmium_cell_empty", "nickel_cadmium_cell_filled", "1000"},
                {"lithium_cobalt_cell_empty", "lithium_cobalt_cell_filled", "2000"},
                {"lithium_manganese_cell_empty", "lithium_manganese_cell_filled", "2000"}};
        h.assertTrue(com.gregtech.gregtech.content.recipe.BatteryCellRecipes.skipped().isEmpty(),
                "no battery cell row was skipped: "
                        + com.gregtech.gregtech.content.recipe.BatteryCellRecipes.skipped());
        for (String[] row : expected) {
            ItemStack empty = stack(row[0]);
            h.assertTrue(!empty.isEmpty(), "empty cell is registered: " + row[0]);
            int found = 0;
            for (com.gregtech.gregtech.api.recipe.Recipe recipe
                    : com.gregtech.gregtech.data.MachineRecipeMaps.Canner.mRecipeList) {
                if (recipe.mInputs.length == 0 || !recipe.mInputs[0].is(empty.getItem())) continue;
                found++;
                h.assertTrue(recipe.mOutputs.length == 1 && recipe.mOutputs[0].is(stack(row[1]).getItem()),
                        row[0] + " cans into " + row[1]);
                h.assertTrue(recipe.mFluidInputs.length == 1
                                && recipe.mFluidInputs[0].getAmount() == Integer.parseInt(row[2]),
                        row[0] + " needs " + row[2] + " mB of electrolyte");
            }
            h.assertTrue(found == 1, row[0] + " has exactly one canning row; got " + found);
        }
        h.succeed();
    }

    private static ItemStack stack(String id) {
        Item item = ForgeRegistries.ITEMS.getValue(
                ResourceLocation.fromNamespaceAndPath("gregtech", id));
        return item == null ? ItemStack.EMPTY : new ItemStack(item);
    }
}
