package com.gregtech.gregtech.gametest;

import com.gregtech.gregtech.api.material.GTMaterial;
import com.gregtech.gregtech.api.material.GTMaterialRegistry;
import com.gregtech.gregtech.api.tool.GTToolHelper;
import com.gregtech.gregtech.api.tool.GTToolType;
import com.gregtech.gregtech.block.wood.WoodSpecies;
import com.gregtech.gregtech.content.recipe.GTWoodRecipes;
import com.gregtech.gregtech.data.MaterialPrefix;
import com.gregtech.gregtech.item.GTToolItem;
import com.gregtech.gregtech.loaders.Loader_WoodCraftingRecipes;
import com.gregtech.gregtech.registry.GTItems;
import com.gregtech.gregtech.registry.GTWoods;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.inventory.AbstractContainerMenu;
import net.minecraft.world.inventory.TransientCraftingContainer;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.Recipe;
import net.minecraft.world.item.crafting.ShapedRecipe;
import net.minecraftforge.gametest.GameTestHolder;
import net.minecraftforge.gametest.PrefixGameTestTemplate;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * The wood-dictionary crafting batch: GT6's {@code gregtech/loaders/c/Loader_Recipes_Woods.java} rows
 * for the port's own nine trees.
 *
 * <p>Rows are generated by {@code tools/generate_wood_recipes.py} into
 * {@link GTWoodRecipes} (GENERATED) and registered by {@link Loader_WoodCraftingRecipes} on server
 * start, the same way {@code Loader_StoneCraftingRecipes} does it. What these tests protect:</p>
 *
 * <ul>
 *   <li>the port really registers every generated row (a row whose item specs do not resolve is
 *       skipped, and {@link Loader_WoodCraftingRecipes#skipped()} has to stay empty),</li>
 *   <li>every row is a real crafting recipe whose result exists - the results are the port's own
 *       {@code gregtech:planks_*}/{@code beam_*}/{@code log_*} blocks and GT6's wood-material
 *       {@code OP.stick}/{@code OP.stickLong} forms (<code>MT.WOODS.Maple</code> and friends),</li>
 *   <li>the amounts are GT6's own table amounts with {@code CS.NERFED_WOOD = true}
 *       ({@code gregapi/data/CS.java:866}): a log gives 2 planks by hand and 4 with a saw, a beam 3 and
 *       5, and the beams are worth 3 long rods against the log's 2,</li>
 *   <li>no two rows share a recipe id, and no row's grid is matched by another recipe - GT6's
 *       {@code CR.DEF_NCC} does not mirror ({@code CR.java:161-168}), which is why
 *       {@code Loader_WoodCraftingRecipes} wraps the rows in {@code ToolShapedRecipe}.</li>
 * </ul>
 */
@GameTestHolder("gregtech")
@PrefixGameTestTemplate(false)
public final class WoodRecipeTests {

    private static final String PREFIX = "gregtech:wood/";

    /**
     * Row count of the generated table: nine GT6 tree species x the eight dictionary rows
     * ({@code Loader_Recipes_Woods.java:183-185}, {@code :203-205}, {@code :243-244}) minus the four
     * cinnamon rows, whose plank material {@code MT.WOODS.Cinnamon} (id 9317) the port does not
     * register.
     */
    private static final int ROWS = 68;

    /** The species the generator mapped, in {@code LoaderWoodDictionary.java} order. */
    private static final String[] SPECIES = {
            "rubber", "maple", "willow", "blue_mahoe", "hazel", "cinnamon", "coconut", "rainbowood",
            "bluespruce"};

    /** GT6's own table amounts for the port's species (WoodEntry/BeamEntry/PlankEntry defaults). */
    private static final Map<String, Integer> AMOUNTS = Map.of(
            "log_to_planks_hand", 2,
            "log_to_planks_saw", 4,
            "log_to_sticks", 2,
            "beam_to_planks_hand", 3,
            "beam_to_planks_saw", 5,
            "beam_to_sticks", 3,
            "planks_to_sticks_hand", 2,
            "planks_to_sticks_saw", 2);

    /**
     * The result family of every row, spelled out per row kind rather than inferred from the row's
     * name: GT6's plank rows produce planks, the log and beam rows produce {@code OP.stickLong} of the
     * species material, and the plank rows produce {@code OP.stick} of it
     * ({@code WoodEntry}/{@code BeamEntry} carry the long rod, a {@code PlankEntry} the short one).
     *
     * <p>An earlier revision classified with {@code kind.contains("planks")}, which also matched
     * {@code planks_to_sticks_hand} and therefore demanded a planks block from a rod row.</p>
     */
    private static final Map<String, String> RESULT_KIND = Map.of(
            "log_to_planks_hand", "planks",
            "log_to_planks_saw", "planks",
            "log_to_sticks", "rodlong",
            "beam_to_planks_hand", "planks",
            "beam_to_planks_saw", "planks",
            "beam_to_sticks", "rodlong",
            "planks_to_sticks_hand", "rod",
            "planks_to_sticks_saw", "rod");

    /**
     * GT6's statement line to the result it registers ({@code Loader_Recipes_Woods}): the {@code Lsf}
     * rows of the wood loop ({@code :183}) and the beam loop ({@code :203}) write
     * {@code aEntry.mStick} of a {@code WoodEntry}/{@code BeamEntry} (= {@code OP.stickLong}, one per
     * saw), the {@code "P"}/{@code "P"} and {@code "s"}/{@code "P"} rows of the plank loop
     * ({@code :243-244}) write the {@code PlankEntry}'s {@code OP.stick}, and the rest produce planks.
     */
    private static final Map<Integer, String> GT6_LINE_KIND = Map.of(
            183, "rodlong", 184, "planks", 185, "planks",
            203, "rodlong", 204, "planks", 205, "planks",
            243, "rod", 244, "rod");

    /** The rows GT6 gates on its saw key ({@code 's'} in :184, :204, :244 and in :183/:203). */
    private static final Set<String> SAW_ROWS = Set.of("log_to_planks_saw", "log_to_sticks",
            "beam_to_planks_saw", "beam_to_sticks", "planks_to_sticks_saw");

    /** ... and the two rows that also need its file key ({@code 'f'} in :183 and :203). */
    private static final Set<String> FILE_ROWS = Set.of("log_to_sticks", "beam_to_sticks");

    private static ItemStack tool(GTToolType type) {
        var item = com.gregtech.gregtech.registry.GTToolItems.get(type);
        return item == null ? ItemStack.EMPTY : new ItemStack(item);
    }

    private static WoodSpecies species(String id) {
        for (WoodSpecies candidate : WoodSpecies.values()) {
            if (candidate.id().equals(id)) return candidate;
        }
        return null;
    }

    /** The port material name the generated table carries for a species, or {@code null}. */
    private static String material(String species) {
        for (String row : GTWoodRecipes.SPECIES) {
            String[] parts = row.split("\\|", -1);
            if (parts[0].equals(species)) return parts[4].equals("-") ? null : parts[4];
        }
        return null;
    }

    private static List<String> rowPaths() {
        List<String> paths = new ArrayList<>();
        for (String id : Loader_WoodCraftingRecipes.registeredIds()) {
            if (!id.startsWith(PREFIX)) continue;
            paths.add(id.substring(PREFIX.length()));
        }
        return paths;
    }

    private static TransientCraftingContainer grid() {
        var menu = new AbstractContainerMenu(null, 0) {
            public ItemStack quickMoveStack(net.minecraft.world.entity.player.Player player, int slot) {
                return ItemStack.EMPTY;
            }

            public boolean stillValid(net.minecraft.world.entity.player.Player player) {
                return true;
            }
        };
        return new TransientCraftingContainer(menu, 3, 3);
    }

    /** GT tools have to be usable copies, exactly like a player would hold them. */
    private static ItemStack usable(ItemStack stack) {
        if (stack.getItem() instanceof GTToolItem) {
            return GTToolHelper.displayTool(GTToolHelper.getType(stack));
        }
        return stack.copy();
    }

    /** {@code Recipe#matches} needs the container's concrete type, so the port's two types are named. */
    private static boolean matches(Recipe<?> recipe, TransientCraftingContainer grid,
                                   net.minecraft.world.level.Level level) {
        if (recipe instanceof ShapedRecipe shaped) return shaped.matches(grid, level);
        if (recipe instanceof net.minecraft.world.item.crafting.ShapelessRecipe shapeless) {
            return shapeless.matches(grid, level);
        }
        return false;
    }

    /**
     * The table is the tool's output and the registration delivered all of it: 68 rows over nine
     * species with no runtime skip, the four rows the port cannot express listed in the table's own
     * {@code SKIPPED_CRAFT_ROWS}, and GT6's file split (128 statements = 71 {@code RM.*} machine rows +
     * 57 {@code CR.*} crafting rows) as the generator counted it.
     */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 300)
    public static void woodRowsAreRegistered(GameTestHelper h) {
        h.assertTrue(GTWoodRecipes.craftRowCount() == ROWS,
                "generated wood rows: " + GTWoodRecipes.craftRowCount() + " (expected " + ROWS + ")");
        h.assertTrue(GTWoodRecipes.gt6StatementCount() == 128
                        && GTWoodRecipes.gt6MachineRowCount() == 71
                        && GTWoodRecipes.gt6CraftingStatementCount() == 57,
                "GT6 Loader_Recipes_Woods statement split: "
                        + GTWoodRecipes.gt6StatementCount() + " = "
                        + GTWoodRecipes.gt6MachineRowCount() + " RM + "
                        + GTWoodRecipes.gt6CraftingStatementCount() + " CR");
        h.assertTrue(Loader_WoodCraftingRecipes.skipped().isEmpty(),
                "no wood row was skipped: " + Loader_WoodCraftingRecipes.skipped());
        h.assertTrue(Loader_WoodCraftingRecipes.registeredIds().size() == ROWS,
                "registered wood rows: " + Loader_WoodCraftingRecipes.registeredIds().size());
        h.assertTrue(Loader_WoodCraftingRecipes.speciesIds().equals(List.of(SPECIES)),
                "mapped species: " + Loader_WoodCraftingRecipes.speciesIds());
        // GT6's 128 statements minus the eight crafting statements (183-185, 203-205, 243-244) that are
        // the source of these rows: every other statement is recorded with its line number.
        h.assertTrue(GTWoodRecipes.SKIPPED_ROWS.length == GTWoodRecipes.gt6StatementCount() - 8,
                "GT6 statements recorded as not translated: " + GTWoodRecipes.SKIPPED_ROWS.length);
        for (String skipped : GTWoodRecipes.SKIPPED_ROWS) {
            h.assertTrue(skipped.startsWith("Loader_Recipes_Woods.java:")
                            && skipped.indexOf('|') > "Loader_Recipes_Woods.java:".length(),
                    "every skipped statement names its GT6 line: " + skipped);
        }
        // ... and the dictionary's own rows: 9 species x the 8 rows, of which the four cinnamon rod rows
        // cannot be expressed (the port has no MT.WOODS.Cinnamon, GT6 material 9317).
        int dictionaryRows = SPECIES.length * AMOUNTS.size();
        h.assertTrue(GTWoodRecipes.craftRowCount() + GTWoodRecipes.SKIPPED_CRAFT_ROWS.length
                        == dictionaryRows,
                "generated rows plus documented row skips are the dictionary's " + dictionaryRows
                        + " rows: " + GTWoodRecipes.craftRowCount() + " + "
                        + GTWoodRecipes.SKIPPED_CRAFT_ROWS.length);
        h.assertTrue(GTWoodRecipes.SKIPPED_CRAFT_ROWS.length == 4,
                "rows the port cannot express: " + GTWoodRecipes.SKIPPED_CRAFT_ROWS.length);
        for (String skipped : GTWoodRecipes.SKIPPED_CRAFT_ROWS) {
            h.assertTrue(skipped.startsWith("cinnamon/")
                            && skipped.contains("Loader_Recipes_Woods.java:"),
                    "a row skip names the cinnamon row and its GT6 line: " + skipped);
        }
        h.assertTrue(GTWoodRecipes.UNMAPPED_ENTRIES.length > 20,
                "dictionary entries without a port block are listed: "
                        + GTWoodRecipes.UNMAPPED_ENTRIES.length);
        h.succeed();
    }

    /**
     * Every generated row goes through the loader's own key reader
     * ({@link Loader_WoodCraftingRecipes#keys(String, String)}): one-character symbols, an {@code =}, a
     * spec the loader implements, and a key for every symbol the pattern uses.
     *
     * <p>This is the regression guard for the first revision of the loader, which required a key symbol
     * longer than one character and therefore skipped all 68 rows at server start while every other
     * assertion about the table still looked right.</p>
     */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 300)
    public static void woodTableRowsParseWithTheLoadersKeyReader(GameTestHelper h) {
        int checked = 0;
        for (String row : GTWoodRecipes.CRAFT_ROWS) {
            String[] parts = row.split("\\|", -1);
            h.assertTrue(parts.length == 7, "the row has 7 fields: " + row);
            String path = parts[0];
            Map<Character, net.minecraft.world.item.crafting.Ingredient> keys =
                    Loader_WoodCraftingRecipes.keys(path, parts[4]);
            h.assertTrue(keys != null, "the loader reads the keys of " + path + ": " + parts[4]);
            h.assertTrue(!keys.isEmpty(), "the row defines at least one key: " + path);
            for (Map.Entry<Character, net.minecraft.world.item.crafting.Ingredient> key
                    : keys.entrySet()) {
                h.assertTrue(!key.getValue().isEmpty(),
                        "key '" + key.getKey() + "' of " + path + " matches at least one item");
            }
            for (int i = 0; i < parts[3].length(); i++) {
                char symbol = parts[3].charAt(i);
                if (symbol == '/' || symbol == ' ') continue;
                h.assertTrue(keys.containsKey(symbol),
                        "pattern symbol '" + symbol + "' of " + path + " has a key");
            }
            // The result and its amount are cross-checked against the GT6 statement the row cites:
            // GT6's :183/:203 register long rods, :243/:244 rods and the rest planks, so a shifted
            // result table cannot pass here even if it looks plausible.
            String kind = path.substring(path.indexOf('/') + 1);
            String family = RESULT_KIND.get(kind);
            h.assertTrue(family != null, "known row kind: " + path);
            String resultSpec = parts[5];
            int star = resultSpec.lastIndexOf('*');
            h.assertTrue(star > 0, "the result carries GT6's amount: " + path + " -> " + resultSpec);
            String resultKind = resultSpec.substring(0, resultSpec.indexOf(':'));
            h.assertTrue(resultKind.equals(family),
                    path + " produces a " + family + " (GT6 " + parts[6] + "), table says " + resultKind);
            int amount = Integer.parseInt(resultSpec.substring(star + 1));
            h.assertTrue(amount == AMOUNTS.get(kind),
                    path + " produces GT6's amount " + AMOUNTS.get(kind) + ", table says " + amount);
            Integer gt6Line = Integer.valueOf(parts[6].substring(parts[6].indexOf(':') + 1));
            String lineFamily = GT6_LINE_KIND.get(gt6Line);
            h.assertTrue(lineFamily != null && lineFamily.equals(resultKind),
                    path + " cites " + parts[6] + ", which registers a " + lineFamily
                            + ", but produces a " + resultKind);
            checked++;
        }
        h.assertTrue(checked == ROWS, "rows parsed with the loader's key reader: " + checked);
        h.assertTrue(Loader_WoodCraftingRecipes.skipped().isEmpty(),
                "the key reader accepted every row: " + Loader_WoodCraftingRecipes.skipped());
        h.succeed();
    }

    /**
     * Every row is a loaded recipe: its id is in the recipe manager, its result item exists and its
     * ingredients resolve to at least one item (an empty tag silently produces an uncraftable row).
     */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 400)
    public static void woodRowsLoadEveryRecipe(GameTestHelper h) {
        int checked = 0;
        for (String id : Loader_WoodCraftingRecipes.registeredIds()) {
            ResourceLocation key = ResourceLocation.parse(id);
            Recipe<?> recipe = h.getLevel().getRecipeManager().byKey(key).orElse(null);
            h.assertTrue(recipe != null, "wood recipe loaded: " + id);
            ItemStack result = recipe.getResultItem(h.getLevel().registryAccess());
            h.assertTrue(!result.isEmpty(), "wood recipe has a result: " + id);
            h.assertTrue(ForgeRegistries.ITEMS.getKey(result.getItem()) != null,
                    "wood recipe result is registered: " + id);
            for (var ingredient : recipe.getIngredients()) {
                if (ingredient.isEmpty()) continue;                 // pattern space
                h.assertTrue(ingredient.getItems().length > 0,
                        "ingredient of " + id + " matches no item");
            }
            checked++;
        }
        h.assertTrue(checked == ROWS, "wood rows checked: " + checked);
        h.succeed();
    }

    /**
     * Every row works on the port's own wood blocks and produces them (or GT6's wood-material rod of
     * the species' material), with GT6's amounts from the dictionary table.
     */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 400)
    public static void woodRowsUseThePortsOwnSpecies(GameTestHelper h) {
        h.assertTrue(RESULT_KIND.keySet().equals(AMOUNTS.keySet()),
                "every row kind has a result family: " + RESULT_KIND.keySet() + " vs " + AMOUNTS.keySet());
        Map<String, Recipe<?>> byPath = new LinkedHashMap<>();
        for (String id : Loader_WoodCraftingRecipes.registeredIds()) {
            var recipe = h.getLevel().getRecipeManager().byKey(ResourceLocation.parse(id)).orElse(null);
            if (recipe == null) continue;
            byPath.put(id.substring(PREFIX.length()), recipe);
        }
        int checked = 0;
        int absent = 0;
        for (String species : SPECIES) {
            WoodSpecies resolved = species(species);
            h.assertTrue(resolved != null, "the port registers the species '" + species + "'");
            ItemStack log = new ItemStack(GTWoods.log(resolved));
            ItemStack planks = new ItemStack(GTWoods.planks(resolved));
            ItemStack beam = new ItemStack(GTWoods.beam(resolved));
            h.assertTrue(!log.isEmpty() && !planks.isEmpty() && !beam.isEmpty(),
                    "the species'" + " blocks are registered: " + species);
            h.assertTrue(ForgeRegistries.ITEMS.getKey(log.getItem()).getNamespace().equals("gregtech"),
                    "the species' log is a gregtech block: " + species);

            String material = material(species);
            ItemStack rod = material == null ? ItemStack.EMPTY
                    : GTItems.getStack(MaterialPrefix.stick, GTMaterialRegistry.get(material), 1);
            ItemStack longRod = material == null ? ItemStack.EMPTY
                    : GTItems.getStack(MaterialPrefix.stickLong, GTMaterialRegistry.get(material), 1);
            if (material != null) {
                h.assertTrue(!rod.isEmpty(), species + " has a rod form (" + material + ")");
                h.assertTrue(!longRod.isEmpty(), species + " has a long rod form (" + material + ")");
                // The three result families are three different items; a shifted result table would
                // hand out one of the others.
                h.assertTrue(!rod.is(planks.getItem()) && !longRod.is(planks.getItem())
                                && !rod.is(longRod.getItem()),
                        species + "'s rod, long rod and planks are distinct items");
            }

            for (Map.Entry<String, Integer> row : AMOUNTS.entrySet()) {
                String kind = row.getKey();
                String family = RESULT_KIND.get(kind);
                String path = species + "/" + kind;
                Recipe<?> recipe = byPath.get(path);
                if (recipe == null) {
                    // Only the cinnamon rod rows may be absent (the port has no MT.WOODS.Cinnamon, 9317);
                    // the generated table lists them in SKIPPED_CRAFT_ROWS.
                    h.assertTrue(species.equals("cinnamon") && !family.equals("planks"),
                            "row is registered: " + path);
                    absent++;
                    continue;
                }
                ItemStack result = recipe.getResultItem(h.getLevel().registryAccess());
                h.assertTrue(result.getCount() == row.getValue(),
                        path + " produces GT6's amount " + row.getValue() + "; got " + result.getCount());
                // The row's own result family decides the exact expected item, and the other two
                // families have to fail - this is what catches a shifted result table.
                switch (family) {
                    case "planks" -> {
                        h.assertTrue(result.is(planks.getItem()),
                                path + " produces the port's planks block, got " + result);
                        h.assertTrue(!result.is(rod.getItem()) && !result.is(longRod.getItem()),
                                path + " is not a rod row, got " + result);
                    }
                    case "rod" -> {
                        h.assertTrue(result.is(rod.getItem()),
                                path + " produces " + material + "'s rod, got " + result);
                        h.assertTrue(!result.is(planks.getItem()) && !result.is(longRod.getItem()),
                                path + " is not a plank or long rod row, got " + result);
                    }
                    case "rodlong" -> {
                        h.assertTrue(result.is(longRod.getItem()),
                                path + " produces " + material + "'s long rod, got " + result);
                        h.assertTrue(!result.is(planks.getItem()) && !result.is(rod.getItem()),
                                path + " is not a plank or rod row, got " + result);
                    }
                    default -> h.assertTrue(false, "unclassified row kind: " + kind);
                }
                ItemStack expectedInput = kind.startsWith("log") ? log
                        : kind.startsWith("beam") ? beam : planks;
                boolean matches = false;
                boolean saw = false;
                boolean file = false;
                ItemStack sawTool = tool(GTToolType.SAW);
                ItemStack fileTool = tool(GTToolType.FILE);
                for (var ingredient : recipe.getIngredients()) {
                    if (ingredient.isEmpty()) continue;
                    if (ingredient.test(expectedInput)) matches = true;
                    if (!sawTool.isEmpty() && ingredient.test(sawTool)) saw = true;
                    if (!fileTool.isEmpty() && ingredient.test(fileTool)) file = true;
                }
                h.assertTrue(matches, path + " is keyed on the port's own " + expectedInput
                        + " block of " + species);
                // GT6's tool keys: 's' = saw on :184/:204/:244 and in the "sLf"/"sBf" rows of
                // :183/:203, 'f' = file in those two rows only, the hand rows carry no tool at all.
                h.assertTrue(saw == SAW_ROWS.contains(kind),
                        path + (SAW_ROWS.contains(kind) ? " needs GT6's saw key" : " carries no saw key"));
                h.assertTrue(file == FILE_ROWS.contains(kind),
                        path + (FILE_ROWS.contains(kind) ? " needs GT6's file key" : " carries no file key"));
                checked++;
            }
        }
        h.assertTrue(checked == ROWS, "wood rows checked against their species: " + checked);
        h.assertTrue(absent == GTWoodRecipes.SKIPPED_CRAFT_ROWS.length,
                "rows absent from the registration: " + absent + ", documented in the table: "
                        + GTWoodRecipes.SKIPPED_CRAFT_ROWS.length);
        h.succeed();
    }

    /** Recipe ids are unique, and none of them collides with an id another recipe already uses. */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 300)
    public static void woodRowIdsAreUnique(GameTestHelper h) {
        List<String> ids = Loader_WoodCraftingRecipes.registeredIds();
        Set<String> unique = new LinkedHashSet<>(ids);
        h.assertTrue(unique.size() == ids.size(), "wood recipe ids are unique: " + ids.size()
                + " rows, " + unique.size() + " ids");
        Map<String, Integer> occurrences = new TreeMap<>();
        for (Recipe<?> recipe : h.getLevel().getRecipeManager().getRecipes()) {
            String id = recipe.getId().toString();
            if (unique.contains(id)) occurrences.merge(id, 1, Integer::sum);
        }
        List<String> missing = new ArrayList<>();
        List<String> duplicated = new ArrayList<>();
        for (String id : unique) {
            int count = occurrences.getOrDefault(id, 0);
            if (count == 0) missing.add(id);
            if (count > 1) duplicated.add(id + " x" + count);
        }
        h.assertTrue(missing.isEmpty(), "wood recipes the manager lost: " + missing);
        h.assertTrue(duplicated.isEmpty(), "wood recipe ids used twice: " + duplicated);
        h.succeed();
    }

    /**
     * Each row crafts exactly once: building the grid from a recipe's own ingredients may match that
     * recipe only, and the mirror flag has to match GT6's {@code CR.MIR} answer (false for all eight
     * rows, which use {@code CR.DEF_NCC}).
     */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 600)
    public static void woodRowGridsMatchExactlyTheirOwnRow(GameTestHelper h) {
        Set<String> batch = new LinkedHashSet<>(Loader_WoodCraftingRecipes.registeredIds());
        List<Recipe<?>> all = new ArrayList<>(h.getLevel().getRecipeManager().getRecipes());
        TreeMap<String, String> collisions = new TreeMap<>();
        TreeSet<String> mirroring = new TreeSet<>();
        int shaped = 0;
        int shapeless = 0;
        for (Recipe<?> recipe : all) {
            if (!batch.contains(recipe.getId().toString())) continue;
            TransientCraftingContainer grid = grid();
            if (recipe instanceof ShapedRecipe shapedRecipe) {
                if (recipe instanceof com.gregtech.gregtech.recipe.ToolShapedRecipe tool) {
                    if (tool.allowMirror()) mirroring.add(recipe.getId().toString());
                }
                for (int y = 0; y < shapedRecipe.getHeight(); y++) {
                    for (int x = 0; x < shapedRecipe.getWidth(); x++) {
                        var ingredient = shapedRecipe.getIngredients().get(x + y * shapedRecipe.getWidth());
                        if (ingredient.isEmpty()) continue;
                        ItemStack[] options = ingredient.getItems();
                        h.assertTrue(options.length > 0, "ingredient of " + recipe.getId()
                                + " matches no item");
                        grid.setItem(x + y * 3, usable(options[0]));
                    }
                }
                shaped++;
            } else {
                int slot = 0;
                for (var ingredient : recipe.getIngredients()) {
                    if (ingredient.isEmpty()) continue;
                    grid.setItem(slot++, usable(ingredient.getItems()[0]));
                }
                shapeless++;
            }
            h.assertTrue(matches(recipe, grid, h.getLevel()),
                    "generated row matches its own grid: " + recipe.getId());
            List<String> also = new ArrayList<>();
            for (Recipe<?> other : all) {
                if (other == recipe) continue;
                if (matches(other, grid, h.getLevel())) also.add(other.getId().toString());
            }
            if (!also.isEmpty()) collisions.put(recipe.getId().toString(), also.toString());
        }
        h.assertTrue(collisions.isEmpty(), "generated wood rows collide: " + collisions);
        h.assertTrue(mirroring.isEmpty(), "GT6's CR.DEF_NCC rows do not mirror: " + mirroring);
        // A full species has six shaped rows (3 log/beam saw rows, 2 beam/plank rows, 2 plank rows)
        // and two shapeless ones (log and beam by hand); cinnamon contributes only its two plank rows
        // shaped and its two by-hand rows shapeless: 8 x 6 + 2 = 50 and 8 x 2 + 2 = 18.
        h.assertTrue(shaped == 50, "shaped wood rows checked: " + shaped);
        h.assertTrue(shapeless == 18, "shapeless wood rows checked: " + shapeless);
        h.succeed();
    }

    /** The dictionary's own material binding: the table names the port material per species. */
    @GameTest(template = "test_blueprint_empty", timeoutTicks = 300)
    public static void woodSpeciesCarryTheirMaterial(GameTestHelper h) {
        Map<String, String> expected = Map.of(
                "rubber", "WoodRubber",
                "maple", "Maple",
                "willow", "Willow",
                "blue_mahoe", "BlueMahoe",
                "hazel", "Hazel",
                "coconut", "Coconutwood",
                "rainbowood", "Rainbowood",
                "bluespruce", "BlueSpruce");
        for (Map.Entry<String, String> entry : expected.entrySet()) {
            h.assertTrue(entry.getValue().equals(material(entry.getKey())),
                    entry.getKey() + " carries GT6's plank material " + entry.getValue());
            GTMaterial resolved = GTMaterialRegistry.get(entry.getValue());
            h.assertTrue(resolved != null && resolved.isValid(),
                    entry.getValue() + " is registered in the port");
        }
        // The one gap: MT.WOODS.Cinnamon is GT6 material 9317, which the port does not have (its only
        // Cinnamon is the spice, 9785), so the generator had to skip the four cinnamon rod rows.
        h.assertTrue(material("cinnamon") == null,
                "the port has no Cinnamonwood material, so no cinnamon rod row is generated");
        h.assertTrue(GTMaterialRegistry.get(9317) == null || !GTMaterialRegistry.get(9317).isValid(),
                "GT6 material 9317 stays unregistered");
        h.succeed();
    }
}
