package com.gregtech.gregtech.content.plant;
/** Original icon identities in original order; registered wood IDs remain owned by GTWoods. */
public final class IconPlantCatalog {private IconPlantCatalog(){}public static final String[] ICON_NAMES={
            "asphalt",
            "cfoam_fresh", "cfoam_fresh_owned", "cfoam_hardened", "cfoam_hardened_owned",
            "clay_blue", "clay_brown", "clay_red", "clay_white", "clay_yellow",
            "concrete", "concrete_reinforced", "crate",
            "crystal_ore_arsenopyrite", "crystal_ore_chalcopyrite", "crystal_ore_cinnabar",
            "crystal_ore_cobaltite", "crystal_ore_galena", "crystal_ore_kesterite",
            "crystal_ore_molybdenite", "crystal_ore_pyrite", "crystal_ore_sphalerite",
            "crystal_ore_stannite", "crystal_ore_stibnite", "crystal_ore_tetrahedrite",
            "flower_alpine_catchfly", "flower_altered_andesite_buckwheat", "flower_copper_plant",
            "flower_crosby_buckwheat", "flower_desert_trumpet", "flower_four_wing_saltbush",
            "flower_hexalily", "flower_narcissus_sheldonia", "flower_orechid",
            "flower_pandanus_candelabrum", "flower_prince_s_plume", "flower_sagebrush",
            "flower_thlaspi_lereschianum", "flower_thompsons_locoweed",
            "flower_tufted_evening_primrose", "flower_tungstus", "flower_viola_calaminaria",
            "fluid_spring",
            "gear", "gear_clockwise", "gear_counterclockwise",
            "gearbox", "gearbox_axle",
            "glass_clear",
            "glowtus_black", "glowtus_blue", "glowtus_brown", "glowtus_cyan",
            "glowtus_gray", "glowtus_green", "glowtus_light_blue", "glowtus_light_gray",
            "glowtus_lime", "glowtus_magenta", "glowtus_orange", "glowtus_pink",
            "glowtus_purple", "glowtus_red", "glowtus_white", "glowtus_yellow",
            "greg_o_lantern", "hatch",
            "leaves_bluemahoe", "leaves_bluespruce", "leaves_bluespruce_xmas",
            "leaves_cinnamon", "leaves_coconut", "leaves_hazel",
            "leaves_maple", "leaves_maple_brown", "leaves_maple_orange",
            "leaves_maple_red", "leaves_maple_yellow",
            "leaves_opaque_bluemahoe", "leaves_opaque_bluespruce", "leaves_opaque_bluespruce_xmas",
            "leaves_opaque_cinnamon", "leaves_opaque_coconut", "leaves_opaque_hazel",
            "leaves_opaque_maple", "leaves_opaque_maple_brown", "leaves_opaque_maple_orange",
            "leaves_opaque_maple_red", "leaves_opaque_maple_yellow",
            "leaves_opaque_rainbowood", "leaves_opaque_rubber", "leaves_opaque_willow",
            "leaves_rainbowood", "leaves_rubber", "leaves_willow",
            "logistics_wire",
            "long_dist_pipe_fluid", "long_dist_pipe_item",
            "long_dist_wire", "long_dist_wire_ev", "long_dist_wire_iv",
            "long_dist_wire_luv", "long_dist_wire_uv", "long_dist_wire_zpm",
            "machine", "mud",
            "ore_amber", "ore_amethyst", "ore_anthracite", "ore_apatite",
            "ore_bastnasite", "ore_bauxite", "ore_borax", "ore_cassiterite",
            "ore_galena", "ore_graphite", "ore_gypsum", "ore_lignite",
            "ore_milkyquartz", "ore_netherquartz", "ore_oil", "ore_pentlandite",
            "ore_pitchblende", "ore_rocksalt", "ore_ruby", "ore_rutile",
            "ore_salt", "ore_scheelite", "ore_sheldonite", "ore_sulfur",
            "ore_tetrahedrite",
            "piston_idle", "piston_moving",
            "planks_bluemahoe", "planks_bluespruce", "planks_cinnamon",
            "planks_coconut", "planks_compressed", "planks_dry", "planks_frozen",
            "planks_hazel", "planks_maple", "planks_mossy", "planks_rainbowood",
            "planks_rotten", "planks_rubber", "planks_treated", "planks_willow",
            "planks_wood",
            "rendering_error",
            "sand_basalt_magnetite", "sand_granite_magnetite", "sand_magnetite",
            "sapling_large_bluemahoe", "sapling_large_bluespruce", "sapling_large_cinnamon",
            "sapling_large_coconut", "sapling_large_hazel", "sapling_large_maple",
            "sapling_large_rainbowood", "sapling_large_rubber", "sapling_large_willow",
            "sapling_small_bluemahoe", "sapling_small_bluespruce", "sapling_small_cinnamon",
            "sapling_small_coconut", "sapling_small_hazel", "sapling_small_maple",
            "sapling_small_rainbowood", "sapling_small_rubber", "sapling_small_willow",
            "turf",
        };
    /** Renderer sprites from Textures.BlockIcons, never standalone GT6 block identities. */
    public static final java.util.Set<String> RENDERER_ONLY = java.util.Set.of(
            "gear", "gear_clockwise", "gear_counterclockwise", "gearbox", "gearbox_axle",
            "crate", "hatch", "machine", "piston_idle", "piston_moving",
            "rendering_error", "greg_o_lantern");
    public static final java.util.List<String> BLOCK_ICONS = java.util.Arrays.stream(ICON_NAMES)
            .filter(id -> !RENDERER_ONLY.contains(id)).toList();
    public static final java.util.List<String> IDS=java.util.Arrays.stream(ICON_NAMES).filter(id->id.startsWith("flower_")||id.startsWith("glowtus_")||id.startsWith("sapling_large_")||id.startsWith("sapling_small_")).toList();public static boolean lily(String id){return id.equals("flower_hexalily")||id.startsWith("glowtus_");}public static int light(String id){return id.startsWith("glowtus_")?15:0;}}
