/* Copyright GregTech-6 Team / Gregorius Techneticies; LGPL-3.0-or-later.
 * Loader_MultiTileEntities.metalset, CR.REV, OP, MT.DATA, technological items and
 * automatic craftingChest data. Unknown automatic inputs retain their source absence.
 * Generated by tools/integration/generate_storage_material_data.py. */
package com.gregtech.gregtech.content.machine;

import com.gregtech.gregtech.api.material.*;
import com.gregtech.gregtech.data.ImportedMaterialData;
import com.gregtech.gregtech.data.SourceBlockProperties;
import java.util.*;

/** Original storage recipes, source IDs and explicit block-group/metadata choices. */
public final class OriginalStorageMaterialData {
    private OriginalStorageMaterialData() {}
    private static final Map<String,ItemComposition> DATA = new LinkedHashMap<>();
    private static final Map<String,SourceBlockProperties.Params> HARVEST = new LinkedHashMap<>();
    static {
        metalset("lead",0,ImportedMaterialData.Pb,"bookshelf_metal_lead");
        metalset("bismuth",16,ImportedMaterialData.Bi,"bookshelf_metal_bismuth");
        metalset("antimony",47,ImportedMaterialData.Sb,"bookshelf_metal_antimony");
        metalset("nickel",22,ImportedMaterialData.Ni,"bookshelf_metal_nickel");
        metalset("constantan",37,ImportedMaterialData.Constantan,"bookshelf_metal_constantan");
        metalset("bronze",9,ImportedMaterialData.Bronze,"bookshelf_metal_bronze");
        metalset("arsenic_copper",57,ImportedMaterialData.ArsenicCopper,"bookshelf_metal_arsenic_copper");
        metalset("aluminium",1,ImportedMaterialData.Al,"bookshelf_metal_aluminium");
        metalset("brass",8,ImportedMaterialData.Brass,"bookshelf_metal_brass");
        metalset("tin_alloy",5,ImportedMaterialData.TinAlloy,"bookshelf_metal_tin_alloy");
        metalset("cobalt",21,ImportedMaterialData.Co,"bookshelf_metal_cobalt");
        metalset("ardite",38,ImportedMaterialData.Ardite,"bookshelf_metal_ardite");
        metalset("arsenic_bronze",58,ImportedMaterialData.ArsenicBronze,"bookshelf_metal_arsenic_bronze");
        metalset("bismuth_bronze",56,ImportedMaterialData.BismuthBronze,"bookshelf_metal_bismuth_bronze");
        metalset("germanium",23,ImportedMaterialData.Ge,"bookshelf_metal_germanium");
        metalset("invar",6,ImportedMaterialData.Invar,"bookshelf_metal_invar");
        metalset("steel",10,ImportedMaterialData.Steel,"bookshelf_metal_steel");
        metalset("hsla",18,ImportedMaterialData.HSLA,"bookshelf_metal_h_s_l_a_steel");
        metalset("gold",2,ImportedMaterialData.Au,"bookshelf_metal_gold");
        metalset("silver",3,ImportedMaterialData.Ag,"bookshelf_metal_silver");
        metalset("manganese",46,ImportedMaterialData.Mn,"bookshelf_metal_manganese");
        metalset("manyullyn",39,ImportedMaterialData.Manyullyn,"bookshelf_metal_manyullyn");
        metalset("lumium",54,ImportedMaterialData.Lumium,"bookshelf_metal_lumium");
        metalset("knightmetal",25,ImportedMaterialData.Knightmetal,"bookshelf_metal_knightmetal");
        metalset("steel_galvanized",19,ImportedMaterialData.SteelGalvanized,"bookshelf_metal_steel_galvanized");
        metalset("meteorite",43,ImportedMaterialData.Meteorite,"bookshelf_metal_meteorite");
        metalset("meteoric_steel",24,ImportedMaterialData.MeteoricSteel,"bookshelf_metal_meteoric_steel");
        metalset("gilded_iron",20,ImportedMaterialData.GildedIron,"bookshelf_metal_gilded_iron");
        metalset("molybdenum",49,ImportedMaterialData.Mo,"bookshelf_metal_molybdenum");
        metalset("syrmorite",44,ImportedMaterialData.Syrmorite,"bookshelf_metal_syrmorite");
        metalset("electrum",7,ImportedMaterialData.Electrum,"bookshelf_metal_electrum");
        metalset("stainless_steel",11,ImportedMaterialData.StainlessSteel,"bookshelf_metal_stainless_steel");
        metalset("thaumium",27,ImportedMaterialData.Thaumium,"bookshelf_metal_thaumium");
        metalset("manasteel",40,ImportedMaterialData.Manasteel,"bookshelf_metal_manasteel");
        metalset("efrine",53,ImportedMaterialData.Efrine,"bookshelf_metal_efrine");
        metalset("tungsten_alloy",52,ImportedMaterialData.TungstenAlloy,"bookshelf_metal_h_s_l_a_tungsten_alloy");
        metalset("titanium",12,ImportedMaterialData.Ti,"bookshelf_metal_titanium");
        metalset("netherite",51,ImportedMaterialData.Netherite,"bookshelf_metal_netherite");
        metalset("chromium",13,ImportedMaterialData.Cr,"bookshelf_metal_chromium");
        metalset("platinum",4,ImportedMaterialData.Pt,"bookshelf_metal_platinum");
        metalset("octine",45,ImportedMaterialData.Octine,"bookshelf_metal_octine");
        metalset("desh",30,ImportedMaterialData.Desh,"bookshelf_metal_desh");
        metalset("terrasteel",42,ImportedMaterialData.Terrasteel,"bookshelf_metal_terrasteel");
        metalset("tungstensteel",14,ImportedMaterialData.TungstenSteel,"bookshelf_metal_tungstensteel");
        metalset("tungsten_carbide",17,ImportedMaterialData.TungstenCarbide,"bookshelf_metal_tungsten_carbide");
        metalset("duranium",31,ImportedMaterialData.DuraniumAlloy,"bookshelf_metal_duranium");
        metalset("draconium",35,ImportedMaterialData.Draconium,"bookshelf_metal_draconium");
        metalset("ultimet",48,ImportedMaterialData.Ultimet,"bookshelf_metal_ultimet");
        metalset("desh_alloy",55,ImportedMaterialData.DeshAlloy,"bookshelf_metal_workers_alloy");
        metalset("tungsten",26,ImportedMaterialData.W,"bookshelf_metal_tungsten");
        metalset("palladium",59,ImportedMaterialData.Pd,"bookshelf_metal_palladium");
        metalset("iridium",15,ImportedMaterialData.Ir,"bookshelf_metal_iridium");
        metalset("osmium",29,ImportedMaterialData.Os,"bookshelf_metal_osmium_elemental");
        metalset("void_metal",28,ImportedMaterialData.VoidMetal,"bookshelf_metal_void_metal");
        metalset("elven_elementium",41,ImportedMaterialData.ElvenElementium,"bookshelf_metal_elven_elementium");
        metalset("tritanium",32,ImportedMaterialData.TritaniumAlloy,"bookshelf_metal_tritanium");
        metalset("adamantium",33,ImportedMaterialData.Ad,"bookshelf_metal_adamantium");
        metalset("bedrock_hsla",34,ImportedMaterialData.Bedrock_HSLA_Alloy,"bookshelf_metal_bedrock_h_s_l_a_alloy");
        metalset("draconium_awakened",36,ImportedMaterialData.DraconiumAwakened,"bookshelf_metal_draconium_awakened");
        metalset("infinity",50,ImportedMaterialData.Infinity,"bookshelf_metal_infinity");
    }
    public static Map<String,ItemComposition> blocks() { return Collections.unmodifiableMap(DATA); }
    public static Map<String,SourceBlockProperties.Params> harvest() { return Collections.unmodifiableMap(HARVEST); }
    private static void add(String path,int id,GTMaterial metal,String tool,int explicitLevel,boolean hand,MaterialComponent... parts) {
        if (DATA.put(path,ReversibleCraftingData.perItem(List.of(parts),1,"GT6 original metalset CR.REV storage"+id)) != null)
            throw new IllegalStateException("Duplicate original storage identity: "+path);
        HARVEST.put(path,new SourceBlockProperties.Params(id,tool,metal,explicitLevel,hand));
    }
    private static void metalset(String suffix,int id,GTMaterial metal,String bookshelfPath) {
        add("chest_"+suffix,id+0,metal,"pickaxe",0,false,MaterialComponent.of(metal,3243240000L));
        add("reinforced_wood_chest_"+suffix,id+500,metal,"axe",0,true,MaterialComponent.of(metal,1621620000L),MaterialComponent.of(com.gregtech.gregtech.data.generated.GT6Materials.Woods.Wood,2594592000L));
        add(suffix.equals("steel")?"safe":"safe_"+suffix,id+2000,metal,"wrench",-1,false,MaterialComponent.of(metal,17837820000L));
        add("key_safe_"+suffix,id+3000,metal,"wrench",-1,false,MaterialComponent.of(metal,17837820000L));
        add(suffix.equals("stainless_steel")?"drawer_quad":"drawer_quad_"+suffix,id+4000,metal,"wrench",-1,false,MaterialComponent.of(metal,13261248000L));
        add("mass_storage_"+suffix,id+6000,metal,"wrench",-1,false,MaterialComponent.of(metal,11963952000L));
        add("bottle_crate_"+suffix,id+8600,metal,"pickaxe",0,true,MaterialComponent.of(metal,1117116000L));
        add(suffix.equals("steel")?"advanced_crafting_table":"advanced_crafting_table_"+suffix,id+5000,metal,"wrench",-1,false,MaterialComponent.of(metal,2738736000L),MaterialComponent.of(com.gregtech.gregtech.data.generated.GT6Materials.Woods.Wood,2594592000L));
        add(suffix.equals("steel")?"charging_crafting_table":"charging_crafting_table_"+suffix,id+5500,metal,"wrench",-1,false,MaterialComponent.of(ImportedMaterialData.Au,5189184000L),MaterialComponent.of(ImportedMaterialData.Rubber,5189184000L),MaterialComponent.of(metal,2882880000L),MaterialComponent.of(com.gregtech.gregtech.data.generated.GT6Materials.Woods.Wood,2594592000L));
        add("logistics_mass_storage_"+suffix,id+6200,metal,"wrench",-1,false,MaterialComponent.of(metal,12252240000L),MaterialComponent.of(ImportedMaterialData.Os,162162000L),MaterialComponent.of(ImportedMaterialData.Al,720720000L),MaterialComponent.of(ImportedMaterialData.Pt,648648000L),MaterialComponent.of(ImportedMaterialData.Emerald,648648000L));
        add(bookshelfPath,id+7100,metal,"wrench",-1,false,MaterialComponent.of(metal,2738736000L));
        add(suffix.equals("steel")?"scaffold":"scaffold_"+suffix,id+8400,metal,"wrench",0,false,MaterialComponent.of(metal,1441440000L));
    }
}
