/* Copyright GregTech-6 Team / Gregorius Techneticies; LGPL-3.0-or-later.
 * Loader_MultiTileEntities.metalset, CR.REV, OP and automatic craftingChest data.
 * Generated by tools/integration/generate_storage_material_data.py. */
package com.gregtech.gregtech.content.machine;

import com.gregtech.gregtech.api.material.*;
import com.gregtech.gregtech.data.ImportedMaterialData;
import com.gregtech.gregtech.data.SourceBlockProperties;
import java.util.*;

/** Original storage recipes, source IDs and explicit block-group/metadata choices. */
public final class OriginalStorageMaterialData {
    private OriginalStorageMaterialData() {}
    private static final Map<String,ItemComposition> DATA = new LinkedHashMap<>();
    private static final Map<String,SourceBlockProperties.Params> HARVEST = new LinkedHashMap<>();
    static {
        metalset("lead",0,ImportedMaterialData.Pb);
        metalset("bismuth",16,ImportedMaterialData.Bi);
        metalset("antimony",47,ImportedMaterialData.Sb);
        metalset("nickel",22,ImportedMaterialData.Ni);
        metalset("constantan",37,ImportedMaterialData.Constantan);
        metalset("bronze",9,ImportedMaterialData.Bronze);
        metalset("arsenic_copper",57,ImportedMaterialData.ArsenicCopper);
        metalset("aluminium",1,ImportedMaterialData.Al);
        metalset("brass",8,ImportedMaterialData.Brass);
        metalset("tin_alloy",5,ImportedMaterialData.TinAlloy);
        metalset("cobalt",21,ImportedMaterialData.Co);
        metalset("ardite",38,ImportedMaterialData.Ardite);
        metalset("arsenic_bronze",58,ImportedMaterialData.ArsenicBronze);
        metalset("bismuth_bronze",56,ImportedMaterialData.BismuthBronze);
        metalset("germanium",23,ImportedMaterialData.Ge);
        metalset("invar",6,ImportedMaterialData.Invar);
        metalset("steel",10,ImportedMaterialData.Steel);
        metalset("hsla",18,ImportedMaterialData.HSLA);
        metalset("gold",2,ImportedMaterialData.Au);
        metalset("silver",3,ImportedMaterialData.Ag);
        metalset("manganese",46,ImportedMaterialData.Mn);
        metalset("manyullyn",39,ImportedMaterialData.Manyullyn);
        metalset("lumium",54,ImportedMaterialData.Lumium);
        metalset("knightmetal",25,ImportedMaterialData.Knightmetal);
        metalset("steel_galvanized",19,ImportedMaterialData.SteelGalvanized);
        metalset("meteorite",43,ImportedMaterialData.Meteorite);
        metalset("meteoric_steel",24,ImportedMaterialData.MeteoricSteel);
        metalset("gilded_iron",20,ImportedMaterialData.GildedIron);
        metalset("molybdenum",49,ImportedMaterialData.Mo);
        metalset("syrmorite",44,ImportedMaterialData.Syrmorite);
        metalset("electrum",7,ImportedMaterialData.Electrum);
        metalset("stainless_steel",11,ImportedMaterialData.StainlessSteel);
        metalset("thaumium",27,ImportedMaterialData.Thaumium);
        metalset("manasteel",40,ImportedMaterialData.Manasteel);
        metalset("efrine",53,ImportedMaterialData.Efrine);
        metalset("tungsten_alloy",52,ImportedMaterialData.TungstenAlloy);
        metalset("titanium",12,ImportedMaterialData.Ti);
        metalset("netherite",51,ImportedMaterialData.Netherite);
        metalset("chromium",13,ImportedMaterialData.Cr);
        metalset("platinum",4,ImportedMaterialData.Pt);
        metalset("octine",45,ImportedMaterialData.Octine);
        metalset("desh",30,ImportedMaterialData.Desh);
        metalset("terrasteel",42,ImportedMaterialData.Terrasteel);
        metalset("tungstensteel",14,ImportedMaterialData.TungstenSteel);
        metalset("tungsten_carbide",17,ImportedMaterialData.TungstenCarbide);
        metalset("duranium",31,ImportedMaterialData.DuraniumAlloy);
        metalset("draconium",35,ImportedMaterialData.Draconium);
        metalset("ultimet",48,ImportedMaterialData.Ultimet);
        metalset("desh_alloy",55,ImportedMaterialData.DeshAlloy);
        metalset("tungsten",26,ImportedMaterialData.W);
        metalset("palladium",59,ImportedMaterialData.Pd);
        metalset("iridium",15,ImportedMaterialData.Ir);
        metalset("osmium",29,ImportedMaterialData.Os);
        metalset("void_metal",28,ImportedMaterialData.VoidMetal);
        metalset("elven_elementium",41,ImportedMaterialData.ElvenElementium);
        metalset("tritanium",32,ImportedMaterialData.TritaniumAlloy);
        metalset("adamantium",33,ImportedMaterialData.Ad);
        metalset("bedrock_hsla",34,ImportedMaterialData.Bedrock_HSLA_Alloy);
        metalset("draconium_awakened",36,ImportedMaterialData.DraconiumAwakened);
        metalset("infinity",50,ImportedMaterialData.Infinity);
    }
    public static Map<String,ItemComposition> blocks() { return Collections.unmodifiableMap(DATA); }
    public static Map<String,SourceBlockProperties.Params> harvest() { return Collections.unmodifiableMap(HARVEST); }
    private static void add(String path,int id,GTMaterial metal,long metalAmount,long woodAmount,String tool,int explicitLevel,boolean hand) {
        var parts = new ArrayList<MaterialComponent>(); parts.add(MaterialComponent.of(metal,metalAmount));
        if (woodAmount > 0) parts.add(MaterialComponent.of(com.gregtech.gregtech.data.generated.GT6Materials.Woods.Wood,woodAmount));
        DATA.put(path,ReversibleCraftingData.perItem(parts,1,"GT6 original metalset CR.REV storage"+id));
        HARVEST.put(path,new SourceBlockProperties.Params(id,tool,metal,explicitLevel,hand));
    }
    private static void metalset(String suffix,int id,GTMaterial metal) {
        add("chest_"+suffix,id+0,metal,3243240000L,0L,"pickaxe",0,false);
        add("reinforced_wood_chest_"+suffix,id+500,metal,1621620000L,2594592000L,"axe",0,true);
        add(suffix.equals("steel")?"safe":"safe_"+suffix,id+2000,metal,17837820000L,0L,"wrench",-1,false);
        add("key_safe_"+suffix,id+3000,metal,17837820000L,0L,"wrench",-1,false);
        add(suffix.equals("stainless_steel")?"drawer_quad":"drawer_quad_"+suffix,id+4000,metal,13261248000L,0L,"wrench",-1,false);
        add("mass_storage_"+suffix,id+6000,metal,11963952000L,0L,"wrench",-1,false);
        add("bottle_crate_"+suffix,id+8600,metal,1117116000L,0L,"pickaxe",0,true);
    }
}
