package com.gregtech.gregtech.content.tool;

// Generated by tools/generate_anvil_variants.py; source data is kept beside the generator.
public final class AnvilDefinitions {
    private AnvilDefinitions() {}
    public static void registerAll() {
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_stone", "Stone", 10000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_blackstone", "Blackstone", 100000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_graniteblack", "GraniteBlack", 100000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_granitered", "GraniteRed", 100000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_lead", "Lead", 800000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_bronze", "Bronze", 1000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_arseniccopper", "ArsenicCopper", 1000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_arsenicbronze", "ArsenicBronze", 2000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_syrmorite", "Syrmorite", 2000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_ironwood", "Ironwood", 7500000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil", "Steel", 10000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_desh", "Desh", 12500000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_efrine", "Efrine", 20000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_thaumium", "Thaumium", 25000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_manasteel", "Manasteel", 25000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_blacksteel", "BlackSteel", 30000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_bluesteel", "BlueSteel", 40000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_redsteel", "RedSteel", 50000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_vanadiumsteel", "VanadiumSteel", 70000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_octine", "Octine", 80000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_fierysteel", "FierySteel", 90000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_hslatungstenalloy", "HSLATungstenAlloy", 100000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_titanium", "Titanium", 100000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_netherite", "Netherite", 150000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_terrasteel", "Terrasteel", 200000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_voidmetal", "VoidMetal", 300000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_titaniumgold", "TitaniumGold", 400000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_tungstensteel", "Tungstensteel", 1000000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_tungsten", "Tungsten", 2000000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_iridium", "Iridium", 10000000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_gaiaspirit", "GaiaSpirit", 100000000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_adamantium", "Adamantium", 1000000000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_draconium", "Draconium", 1000000000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_draconiumawakened", "DraconiumAwakened", 2000000000000L);
        com.gregtech.gregtech.registry.GTToolBlocks.anvil("anvil_infinity", "Infinity", 1000000000000000L);
    }
}
