/**
 * Copyright (c) 2025 GregTech-6 Team
 *
 * This file is part of GregTech.
 *
 * GregTech is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GregTech is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with GregTech. If not, see <http://www.gnu.org/licenses/>.
 */


package com.gregtech.gregtech.content.tool;
/** Original inherited ToolStats classifications; generated by tools/import_origin_tool_flags.py. */
public final class OriginalToolFlags {
private OriginalToolFlags() {}
public record Flags(boolean mining,boolean weapon,boolean ranged) {}
private static final java.util.Map<String,Flags> FLAGS=new java.util.HashMap<>();
static {
FLAGS.put("SWORD",new Flags(true,true,false));
FLAGS.put("PICKAXE",new Flags(true,false,false));
FLAGS.put("SHOVEL",new Flags(true,false,false));
FLAGS.put("SPADE",new Flags(true,false,false));
FLAGS.put("AXE",new Flags(true,true,false));
FLAGS.put("DOUBLEAXE",new Flags(true,true,false));
FLAGS.put("HOE",new Flags(true,false,false));
FLAGS.put("SAW",new Flags(true,false,false));
FLAGS.put("HARDHAMMER",new Flags(true,true,false));
FLAGS.put("SOFTHAMMER",new Flags(false,true,false));
FLAGS.put("WRENCH",new Flags(true,false,false));
FLAGS.put("FILE",new Flags(true,false,false));
FLAGS.put("CROWBAR",new Flags(true,true,false));
FLAGS.put("SCREWDRIVER",new Flags(false,false,false));
FLAGS.put("CLUB",new Flags(false,true,false));
FLAGS.put("WIRECUTTER",new Flags(true,false,false));
FLAGS.put("SCOOP",new Flags(true,false,false));
FLAGS.put("BRANCHCUTTER",new Flags(true,false,false));
FLAGS.put("UNIVERSALSPADE",new Flags(true,true,false));
FLAGS.put("KNIFE",new Flags(true,true,false));
FLAGS.put("BUTCHERYKNIFE",new Flags(false,true,false));
FLAGS.put("SENSE",new Flags(true,true,false));
FLAGS.put("PLOW",new Flags(true,false,false));
FLAGS.put("PLUNGER",new Flags(true,false,false));
FLAGS.put("ROLLINGPIN",new Flags(true,false,false));
FLAGS.put("CHISEL",new Flags(true,false,false));
FLAGS.put("FLINTANDTINDER",new Flags(true,false,false));
FLAGS.put("MONKEYWRENCH",new Flags(true,false,false));
FLAGS.put("BENDINGCYLINDER",new Flags(true,false,false));
FLAGS.put("BENDINGCYLINDERSMALL",new Flags(true,false,false));
FLAGS.put("CONSTRUCTIONPICK",new Flags(true,false,false));
FLAGS.put("MAGNIFYINGGLASS",new Flags(true,false,false));
FLAGS.put("SCISSORS",new Flags(true,false,false));
FLAGS.put("PINCERS",new Flags(true,false,false));
FLAGS.put("GEMPICK",new Flags(true,false,false));
FLAGS.put("HANDDRILL",new Flags(false,false,false));
FLAGS.put("BUILDERWAND",new Flags(false,false,false));
FLAGS.put("MININGDRILLLV",new Flags(true,false,false));
FLAGS.put("MININGDRILLMV",new Flags(true,false,false));
FLAGS.put("MININGDRILLHV",new Flags(true,false,false));
FLAGS.put("CHAINSAWLV",new Flags(true,true,false));
FLAGS.put("CHAINSAWMV",new Flags(true,true,false));
FLAGS.put("CHAINSAWHV",new Flags(true,true,false));
FLAGS.put("WRENCHLV",new Flags(true,false,false));
FLAGS.put("WRENCHMV",new Flags(true,false,false));
FLAGS.put("WRENCHHV",new Flags(true,false,false));
FLAGS.put("JACKHAMMERHVNormal",new Flags(true,false,false));
FLAGS.put("JACKHAMMERHVNoOres",new Flags(true,false,false));
FLAGS.put("BUZZSAWLV",new Flags(true,false,false));
FLAGS.put("SCREWDRIVERLV",new Flags(false,false,false));
FLAGS.put("DRILLLV",new Flags(false,false,false));
FLAGS.put("MIXERLV",new Flags(false,false,false));
FLAGS.put("MONKEYWRENCHLV",new Flags(true,false,false));
FLAGS.put("MONKEYWRENCHMV",new Flags(true,false,false));
FLAGS.put("MONKEYWRENCHHV",new Flags(true,false,false));
FLAGS.put("TRIMMERLV",new Flags(true,false,false));
FLAGS.put("POCKETMULTITOOL",new Flags(true,false,false));
FLAGS.put("POCKETKNIFE",new Flags(true,true,false));
FLAGS.put("POCKETSAW",new Flags(true,false,false));
FLAGS.put("POCKETFILE",new Flags(true,false,false));
FLAGS.put("POCKETSCREWDRIVER",new Flags(false,false,false));
FLAGS.put("POCKETWIRECUTTER",new Flags(true,false,false));
FLAGS.put("POCKETSCISSORS",new Flags(true,false,false));
FLAGS.put("POCKETCHISEL",new Flags(true,false,false));
FLAGS.put("PISTOL",new Flags(false,false,true));
FLAGS.put("CARBINE",new Flags(false,false,true));
FLAGS.put("RIFLE",new Flags(false,false,true));
}
public static Flags of(String name){var flags=FLAGS.get(name.replace("_",""));if(flags==null)throw new IllegalArgumentException("Unknown original tool "+name);return flags;}
}
