package com.gregtech.gregtech.content.tool;

/** Generated by tools/rebuild_container_tool_models.py; same bounds as the visible mesh. */
public final class OriginalToolShapes {
    private OriginalToolShapes() {}
    public static int[][] bounds(String id) {
        return switch (id) {
            case "anvil" -> new int[][] {{2,0,4,14,4,12}, {4,4,6,12,8,10}, {1,8,4,15,12,12}, {15,8,5,16,12,11}, {0,9,4,1,11,12}};
            case "scaffold" -> new int[][] {{0,14,0,16,16,16}, {2,12,0,4,14,16}, {6,10,0,10,14,16}, {12,12,0,14,14,16}};
            case "advanced_button" -> new int[][] {{4,4,14,12,12,16}};
            case "mixing_bowl" -> new int[][] {{0,0,0,2,8,16}, {0,0,0,16,8,2}, {14,0,0,16,8,16}, {0,0,14,16,8,16}, {0,0,0,16,2,16}};
            case "mixing_bowl_table" -> new int[][] {{0,8,0,2,16,16}, {0,8,0,16,16,2}, {14,8,0,16,16,16}, {0,8,14,16,16,16}, {0,8,0,16,10,16}, {0,0,0,16,8,16}};
            case "bathing_pot" -> new int[][] {{0,0,0,2,8,16}, {0,0,0,16,8,2}, {14,0,0,16,8,16}, {0,0,14,16,8,16}, {0,0,0,16,2,16}};
            case "bathing_pot_table" -> new int[][] {{0,8,0,2,16,16}, {0,8,0,16,16,2}, {14,8,0,16,16,16}, {0,8,14,16,16,16}, {0,8,0,16,10,16}, {0,0,0,16,8,16}};
            case "bathing_pot_wood" -> new int[][] {{0,0,0,2,8,16}, {0,0,0,16,8,2}, {14,0,0,16,8,16}, {0,0,14,16,8,16}, {0,0,0,16,2,16}};
            case "bathing_pot_table_wood" -> new int[][] {{0,8,0,2,16,16}, {0,8,0,16,16,2}, {14,8,0,16,16,16}, {0,8,14,16,16,16}, {0,8,0,16,10,16}, {0,0,0,16,8,16}};
            case "juicer" -> new int[][] {{2,0,2,4,4,14}, {2,0,2,14,4,4}, {12,0,2,14,4,14}, {2,0,12,14,4,14}, {2,0,2,14,1,14}, {6,0,6,10,7,10}};
            case "plant_pot" -> new int[][] {{0,10,0,16,16,16}, {1,0,1,15,10,15}};
            case "bumbliary" -> new int[][] {{0,0,0,16,16,16}};
            case "sap_bag" -> new int[][] {{5,0,0,11,7,6}};
            case "fluid_funnel" -> new int[][] {{5,9,0,11,10,6}, {6,8,0,10,9,4}, {7,7,0,9,8,2}};
            case "tap" -> new int[][] {{6,6,2,10,7,4}, {7,4,0,9,6,4}, {7,3,4,9,6,6}};
            case "nozzle" -> new int[][] {{6,3,1,10,7,2}, {7,4,0,9,6,6}};
            case "cap_nozzle" -> new int[][] {{6,3,1,10,7,6}, {7,4,0,9,6,2}};
            case "coin_mold" -> new int[][] {{0,0,0,16,12,16}, {4,12,4,12,14,12}};
            default -> throw new IllegalArgumentException("Unknown tool mesh: " + id);
        };
    }
}
