package com.gregtech.gregtech.content.bumble;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * GT6's bumblebee species and the comb each one produces
 * ({@code MultiItemBumbles.make(...)} and {@code bumbleProductStack:189-213}).
 *
 * <p>GT6 stores them as metas of one item ({@code meta = species id + type}), where the
 * <em>species tier</em> ({@code meta / 100}) picks the comb. The port registers one item per
 * species and type ({@code <species>_{drone,princess,queen,dead}}), so the same table is keyed
 * by those ids here.</p>
 *
 * <p>GENERATED by tools/extract_gt6_bumbles.py - do not edit by hand.</p>
 */
public final class GTBumbleSpecies {

    /** One GT6 species: its id, port item prefix, display name and comb item id. */
    public static final class Species {
        private final int id;
        private final String prefix;
        private final String name;
        private final String comb;

        Species(int id, String prefix, String name, String comb) {
            this.id = id; this.prefix = prefix; this.name = name; this.comb = comb;
        }

        /** GT6's species id (the bee meta with a type of 0). */
        public int id() { return id; }

        /** The port's item id prefix, e.g. {@code surfing_bumblebee}. */
        public String prefix() { return prefix; }

        /** GT6's display name, e.g. {@code Surfing Bumblebee}. */
        public String name() { return name; }

        /** The comb item id this species produces, e.g. {@code water_comb}. */
        public String comb() { return comb; }

        /** The port's item id for one bee type, e.g. {@code surfing_bumblebee_princess}. */
        public String beeId(String type) { return prefix + "_" + type; }
    }

    /** GT6's species, in its registration order. */
    public static final List<Species> SPECIES = List.of(
            new Species(0, "wild_bumblebee", "Wild Bumblebee", "honey_comb"),
            new Species(10, "captive_bumblebee", "Captive Bumblebee", "honey_comb"),
            new Species(20, "common_bumblebee", "Common Bumblebee", "honey_comb"),
            new Species(30, "cultivated_bumblebee", "Cultivated Bumblebee", "honey_comb"),
            new Species(100, "surfing_bumblebee", "Surfing Bumblebee", "water_comb"),
            new Species(110, "swimming_bumblebee", "Swimming Bumblebee", "water_comb"),
            new Species(120, "diving_bumblebee", "Diving Bumblebee", "water_comb"),
            new Species(130, "subnautic_bumblebee", "Subnautic Bumblebee", "water_comb"),
            new Species(200, "apprentice_bumblebee", "Apprentice Bumblebee", "magic_comb"),
            new Species(210, "magician_bumblebee", "Magician Bumblebee", "magic_comb"),
            new Species(220, "wizard_bumblebee", "Wizard Bumblebee", "magic_comb"),
            new Species(230, "dumblebee", "Dumblebee", "magic_comb"),
            new Species(300, "nether_bumblebee", "Nether Bumblebee", "nether_comb"),
            new Species(310, "hellish_bumblebee", "Hellish Bumblebee", "nether_comb"),
            new Species(320, "impish_bumblebee", "Impish Bumblebee", "nether_comb"),
            new Species(330, "demonic_bumblebee", "Demonic Bumblebee", "nether_comb"),
            new Species(400, "end_bumblebee", "End Bumblebee", "end_comb"),
            new Species(410, "void_bumblebee", "Void Bumblebee", "end_comb"),
            new Species(420, "alienated_bumblebee", "Alienated Bumblebee", "end_comb"),
            new Species(430, "nihilistic_bumblebee", "Nihilistic Bumblebee", "end_comb"),
            new Species(500, "stoned_bumblebee", "Stoned Bumblebee", "rock_comb"),
            new Species(510, "rocking_bumblebee", "Rocking Bumblebee", "rock_comb"),
            new Species(520, "hard_rock_bumblebee", "Hard Rock Bumblebee", "rock_comb"),
            new Species(530, "bumbelvis", "Bumbelvis", "rock_comb"),
            new Species(600, "jungle_bumblebee", "Jungle Bumblebee", "jungle_comb"),
            new Species(610, "jungle_bumblebee_t2", "Jungle Bumblebee (T2)", "jungle_comb"),
            new Species(620, "jungle_bumblebee_t3", "Jungle Bumblebee (T3)", "jungle_comb"),
            new Species(630, "bumblezan", "Bumblezan", "jungle_comb"),
            new Species(700, "frosty_bumblebee", "Frosty Bumblebee", "frozen_comb"),
            new Species(710, "north_pole_bumblebee", "North Pole Bumblebee", "frozen_comb"),
            new Species(720, "bumble_elf", "Bumble Elf", "frozen_comb"),
            new Species(730, "bumble_claus", "Bumble Claus", "frozen_comb"),
            new Species(800, "bumbleshroom", "Bumbleshroom", "shroomy_comb"),
            new Species(810, "bumble_toad", "Bumble Toad", "shroomy_comb"),
            new Species(820, "bumble_bro", "Bumble Bro", "shroomy_comb"),
            new Species(830, "bumble_peach", "Bumble Peach", "shroomy_comb"),
            new Species(900, "sandy_bumblebee", "Sandy Bumblebee", "sandy_comb"),
            new Species(910, "sandy_bumblebee_t2", "Sandy Bumblebee (T2)", "sandy_comb"),
            new Species(920, "sandy_bumblebee_t3", "Sandy Bumblebee (T3)", "sandy_comb"),
            new Species(930, "bumbobee", "Bumbobee", "sandy_comb"),
            new Species(10000, "creative_bumblebee", "Creative Bumblebee", "clay_comb"),
            new Species(10010, "builder_bumblebee", "Builder Bumblebee", "clay_comb"),
            new Species(10020, "masonic_bumblebee", "Masonic Bumblebee", "clay_comb"),
            new Species(10030, "illuminumblebee", "Illuminumblebee", "clay_comb"),
            new Species(10100, "industrial_bumblebee", "Industrial Bumblebee", "sticky_comb"),
            new Species(10110, "overseer_bumblebee", "Overseer Bumblebee", "sticky_comb"),
            new Species(10120, "bumble_tycoon", "Bumble Tycoon", "sticky_comb"),
            new Species(10130, "monopolistic_bumblebee", "Monopolistic Bumblebee", "sticky_comb"),
            new Species(10200, "bumbleknight", "Bumbleknight", "royal_comb"),
            new Species(10210, "colonial_bumblebee", "Colonial Bumblebee", "royal_comb"),
            new Species(10220, "royal_bumblebee", "Royal Bumblebee", "royal_comb"),
            new Species(10230, "bumblemonarch", "Bumblemonarch", "royal_comb"),
            new Species(10300, "bumblegoth", "Bumblegoth", "soul_comb"),
            new Species(10310, "occult_bumblebee", "Occult Bumblebee", "soul_comb"),
            new Species(10320, "antichristumblebee", "Antichristumblebee", "soul_comb"),
            new Species(10330, "satanic_bumblebee", "Satanic Bumblebee", "soul_comb"),
            new Species(10400, "forgetful_bumblebee", "Forgetful Bumblebee", "amnesic_comb"),
            new Species(10410, "amnesic_bumblebee", "Amnesic Bumblebee", "amnesic_comb"),
            new Species(10420, "bumbleheimers", "Bumbleheimers", "amnesic_comb"),
            new Species(10430, "bumble_in_black", "Bumble in Black", "amnesic_comb"),
            new Species(10500, "private_bumble", "Private Bumble", "military_comb"),
            new Species(10510, "lt_bumbleson", "Lt. Bumbleson", "military_comb"),
            new Species(10520, "colonel_bumble_obeeill", "Colonel Bumble O'Beeill", "military_comb"),
            new Species(10530, "general_bumblemond", "General Bumblemond", "military_comb"),
            new Species(20000, "blazing_bumblebee", "Blazing Bumblebee", "pyro_comb"),
            new Species(20010, "flaming_bumblebee", "Flaming Bumblebee", "pyro_comb"),
            new Species(20020, "bumbletrantor", "Bumbletrantor", "pyro_comb"),
            new Species(20030, "pyro_bumble", "Pyro Bumble", "pyro_comb"),
            new Species(20100, "blizzful_bumblebee", "Blizzful Bumblebee", "cryo_comb"),
            new Species(20110, "freezing_bumblebee", "Freezing Bumblebee", "cryo_comb"),
            new Species(20120, "mr_bumblefreeze", "Mr. Bumblefreeze", "cryo_comb"),
            new Species(20130, "cryo_bumble", "Cryo Bumble", "cryo_comb"),
            new Species(20200, "blitzing_bumblebee", "Blitzing Bumblebee", "aero_comb"),
            new Species(20210, "storming_bumblebee", "Storming Bumblebee", "aero_comb"),
            new Species(20220, "bumbleaang", "Bumbleaang", "aero_comb"),
            new Species(20230, "aero_bumble", "Aero Bumble", "aero_comb"),
            new Species(20300, "basalzed_bumblebee", "Basalzed Bumblebee", "tera_comb"),
            new Species(20310, "quakeing_bumblebee", "Quakeing Bumblebee", "tera_comb"),
            new Species(20320, "earth_bound_bumblebee", "Earth Bound Bumblebee", "tera_comb"),
            new Species(20330, "tera_bumble", "Tera Bumble", "tera_comb")
    );

    private static final Map<Integer, Species> BY_ID = new LinkedHashMap<>();
    private static final Map<String, Species> BY_PREFIX = new LinkedHashMap<>();

    static {
        for (Species species : SPECIES) {
            BY_ID.put(species.id(), species);
            BY_PREFIX.put(species.prefix(), species);
        }
    }

    /** The species with GT6's id, or null. */
    public static Species byId(int id) { return BY_ID.get(id); }

    /** The species whose port item prefix matches, or null. */
    public static Species byPrefix(String prefix) { return BY_PREFIX.get(prefix); }

    /** The comb a species produces, or null. GT6: {@code meta / 100} picks the comb row. */
    public static String combOf(int speciesId) {
        Species species = BY_ID.get(speciesId - speciesId % 10);
        return species == null ? null : species.comb();
    }

    private GTBumbleSpecies() {}
}
