package com.gregtech.gregtech.item;
import com.gregtech.gregtech.content.tool.*;import com.gregtech.gregtech.item.behavior.ItemBehaviors;import net.minecraft.world.item.*;import net.minecraft.world.item.context.UseOnContext;import net.minecraft.world.*;import net.minecraft.world.entity.*;import net.minecraft.world.entity.player.Player;import net.minecraft.world.entity.animal.*;import net.minecraft.network.chat.Component;import net.minecraft.world.level.Level;
/** Full brokestar paint/entity policy over the existing original full/used/empty spray ledger. */
public final class PaintSprayItem extends TechItem {
private final PaintingRules.Dye dye;
public PaintSprayItem(PaintingRules.Dye dye,Properties props){super("Spray Paint ("+dye.id()+")",props);this.dye=dye;}
private ItemBehaviors.Consumable can(){return new ItemBehaviors.Consumable(ItemBehaviors.stack("gregtech:empty_spray_can"),ItemBehaviors.stack("gregtech:"+dye.usedId()),ItemBehaviors.stack("gregtech:"+dye.fullId()),PaintingRules.CAPACITY);}
@Override public Component getName(ItemStack stack){return Component.translatable(getDescriptionId());}
@Override public InteractionResult onItemUseFirst(ItemStack stack,UseOnContext c){var pos=c.getClickedPos();var point=c.getClickLocation();var outcome=ItemBehaviors.useSpray(c.getLevel(),pos,c.getClickedFace(),c.getPlayer(),stack,can(),(level,p,side,uses,player,holder,x,y,z)->{if(uses<=0)return 0;long spent=PaintTargets.color(level,p,dye.index());if(spent>0)level.playSound(null,p,net.minecraft.sounds.SoundEvents.FIRE_EXTINGUISH,net.minecraft.sounds.SoundSource.PLAYERS,1,1);return spent;},(float)(point.x-pos.getX()),(float)(point.y-pos.getY()),(float)(point.z-pos.getZ()));if(c.getPlayer()!=null)c.getPlayer().setItemInHand(c.getHand(),outcome.stack());return outcome.acted()?InteractionResult.SUCCESS:InteractionResult.PASS;}
@Override public InteractionResult interactLivingEntity(ItemStack stack,Player player,LivingEntity target,InteractionHand hand){if(stack.getCount()!=1)return InteractionResult.PASS;int current=target instanceof Sheep sheep?sheep.getColor().getId():target instanceof Wolf wolf?wolf.getCollarColor().getId():-1;var facts=new PaintingRules.EntityFacts(target.isAlive(),target instanceof Sheep,target instanceof Sheep sheep&&sheep.isSheared(),target instanceof Wolf,target instanceof Wolf wolf&&wolf.isTame(),current);int color=PaintingRules.entityDyeId(facts,dye.index());if(color<0)return InteractionResult.PASS;if(target.level().isClientSide)return InteractionResult.SUCCESS;var ledger=can();var prepared=ledger.prepared(stack);if(ledger.remaining(prepared)<=0){player.setItemInHand(hand,ledger.usedUp(prepared));return InteractionResult.PASS;}var desired=DyeColor.byId(color);if(target instanceof Sheep sheep)sheep.setColor(desired);else ((com.gregtech.gregtech.mixin.WolfCollarAccessor)target).gregtech$setCollarColor(desired);player.setItemInHand(hand,ItemBehaviors.creative(player)?prepared:ledger.spent(prepared,PaintingRules.ENTITY_COST));return InteractionResult.CONSUME;}
@Override public boolean isBarVisible(ItemStack stack){return can().remaining(stack)<PaintingRules.CAPACITY;}
@Override public int getBarWidth(ItemStack stack){return (int)Math.max(0,Math.min(13,Math.round(can().remaining(stack)*13.0/PaintingRules.CAPACITY)));}
@Override public int getBarColor(ItemStack stack){return dye.rgb();}
@Override public void appendHoverText(ItemStack stack,Item.TooltipContext context,java.util.List<Component> lines,TooltipFlag flag){super.appendHoverText(stack,context,lines,flag);lines.add(Component.translatable("gregtech.spray.remaining",can().remaining(stack)/10.0));}
}
