package com.gregtech.gregtech.item;

import net.minecraft.world.item.Item;

/** Pure technological item — carries a display name, no functionality. */
public class TechItem extends Item implements com.gregtech.gregtech.api.recipe.RecipeCatalystLike {
    private final String englishName;
    private final boolean catalyst;

    public TechItem(String englishName, Properties properties) {
        this(englishName, false, properties);
    }

    public TechItem(String englishName, boolean catalyst, Properties properties) {
        super(properties);
        this.englishName = englishName;
        this.catalyst = catalyst;
    }

    public String englishName() { return englishName; }

    @Override
    public void appendHoverText(net.minecraft.world.item.ItemStack stack,
            net.minecraft.world.item.Item.TooltipContext context,
            java.util.List<net.minecraft.network.chat.Component> tooltip,
            net.minecraft.world.item.TooltipFlag flag) {
        super.appendHoverText(stack, context, tooltip, flag);
        // GT6 addItem tooltips live in the lang files as <descriptionId>.tooltip
        String key = getDescriptionId() + ".tooltip";
        if (net.minecraft.locale.Language.getInstance().has(key)) {
            var line = net.minecraft.network.chat.Component.translatable(key);
            // Original language files intentionally leave some species tooltips empty.
            if (!line.getString().isEmpty()) tooltip.add(line.withStyle(net.minecraft.ChatFormatting.GRAY));
        }
        // §108: GT6 prints the food line of a FoodStat item in red next to the tooltip
        // (FoodStat.java:198). The 200 keys for it are generated by
        // tools/generate_food_item_assets.py; an item without one shows nothing.
        String foodKey = getDescriptionId() + ".food";
        if (net.minecraft.locale.Language.getInstance().has(foodKey)) {
            tooltip.add(net.minecraft.network.chat.Component.translatable(foodKey)
                    .withStyle(net.minecraft.ChatFormatting.RED));
        }
        // §114: GT6's IBehavior.getAdditionalToolTips - the data-storage tooltips of the USB stick and
        // the USB drive read the stack's NBT, so they cannot be lang keys; the behaviour layer renders
        // them (Behavior_DataStorage / Behavior_DataStorage16).
        if(com.gregtech.gregtech.content.data.UsbDataMedia.isStick(stack))com.gregtech.gregtech.item.behavior.BehaviorDataStorage.tooltip(stack,tooltip);
        else if(com.gregtech.gregtech.content.data.UsbDataMedia.isDrive(stack))com.gregtech.gregtech.item.behavior.BehaviorDataStorage16.tooltip(stack,tooltip);
    }

    /**
     * Catalyst items (extruder/slicer/press/food-mold shapes) must be present for a
     * recipe to match but are never consumed by it — GT6 modelled this with
     * zero-size recipe inputs, which 1.20 {@code ItemStack} cannot represent.
     */
    public boolean isCatalyst() { return catalyst; }
}
