/* Derived from GregTech-6 Team / Gregorius Techneticies; LGPL-3.0-or-later.
 * Original authors and license retained; see NOTICE and source provenance. */
package com.gregtech.gregtech.content.food;

import java.util.*;

/** MultiItemCans FoodStat and sandwich declarations; existing native item identities are retained. */
public final class CannedFoodCatalog {
    private CannedFoodCatalog() {}
    public record Can(FoodNutritionRows.Entry food, float temperatureEffect, int rebreathe, int layer,
                      boolean hidden, boolean catFood, boolean dogFood) {
        public String id() { return food.id(); }
        public int useDuration() { return Math.max(16, food.food().level() * 8); }
    }
    public static final List<Can> ROWS = List.of(
        new Can(new FoodNutritionRows.Entry("tiny_food_can_unknown", "Tiny Food Can (Unknown)", 1, new FoodNutritionRows.Food(2, 0.1f, 5, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 46), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:46
        new Can(new FoodNutritionRows.Entry("small_food_can_unknown", "Small Food Can (Unknown)", 2, new FoodNutritionRows.Food(4, 0.2f, 10, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 47), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:47
        new Can(new FoodNutritionRows.Entry("tall_food_can_unknown", "Tall Food Can (Unknown)", 3, new FoodNutritionRows.Food(6, 0.3f, 15, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 48), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:48
        new Can(new FoodNutritionRows.Entry("wide_food_can_unknown", "Wide Food Can (Unknown)", 4, new FoodNutritionRows.Food(8, 0.4f, 20, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 49), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:49
        new Can(new FoodNutritionRows.Entry("large_food_can_unknown", "Large Food Can (Unknown)", 5, new FoodNutritionRows.Food(10, 0.5f, 25, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 50), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:50
        new Can(new FoodNutritionRows.Entry("huge_food_can_unknown", "Huge Food Can (Unknown)", 6, new FoodNutritionRows.Food(12, 0.6f, 30, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 51), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:51
        new Can(new FoodNutritionRows.Entry("tiny_food_can_rotten", "Tiny Food Can (Rotten)", 11, new FoodNutritionRows.Food(2, 0.1f, 5, 310, false, true), new FoodNutritionRows.Stats(4, 0, 4, 4, 0, 0), "gregtech:empty_food_can", 1, true, 53), 0.1f, 0, 29, true, false, false), // MultiItemCans.java:53
        new Can(new FoodNutritionRows.Entry("small_food_can_rotten", "Small Food Can (Rotten)", 12, new FoodNutritionRows.Food(4, 0.2f, 10, 310, false, true), new FoodNutritionRows.Stats(8, 0, 8, 8, 0, 0), "gregtech:empty_food_can", 1, true, 54), 0.1f, 0, 29, true, false, false), // MultiItemCans.java:54
        new Can(new FoodNutritionRows.Entry("tall_food_can_rotten", "Tall Food Can (Rotten)", 13, new FoodNutritionRows.Food(6, 0.3f, 15, 310, false, true), new FoodNutritionRows.Stats(12, 0, 12, 12, 0, 0), "gregtech:empty_food_can", 1, true, 55), 0.1f, 0, 29, true, false, false), // MultiItemCans.java:55
        new Can(new FoodNutritionRows.Entry("wide_food_can_rotten", "Wide Food Can (Rotten)", 14, new FoodNutritionRows.Food(8, 0.4f, 20, 310, false, true), new FoodNutritionRows.Stats(16, 0, 16, 16, 0, 0), "gregtech:empty_food_can", 1, true, 56), 0.1f, 0, 29, true, false, false), // MultiItemCans.java:56
        new Can(new FoodNutritionRows.Entry("large_food_can_rotten", "Large Food Can (Rotten)", 15, new FoodNutritionRows.Food(10, 0.5f, 25, 310, false, true), new FoodNutritionRows.Stats(20, 0, 20, 20, 0, 0), "gregtech:empty_food_can", 1, true, 57), 0.1f, 0, 29, true, false, false), // MultiItemCans.java:57
        new Can(new FoodNutritionRows.Entry("huge_food_can_rotten", "Huge Food Can (Rotten)", 16, new FoodNutritionRows.Food(12, 0.6f, 30, 310, false, true), new FoodNutritionRows.Stats(24, 0, 24, 24, 0, 0), "gregtech:empty_food_can", 1, true, 58), 0.1f, 0, 29, true, false, false), // MultiItemCans.java:58
        new Can(new FoodNutritionRows.Entry("tiny_food_can_vegetables", "Tiny Food Can (Vegetables)", 21, new FoodNutritionRows.Food(2, 0.1f, 10, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 5, 0, 0), "gregtech:empty_food_can", 1, true, 60), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:60
        new Can(new FoodNutritionRows.Entry("small_food_can_vegetables", "Small Food Can (Vegetables)", 22, new FoodNutritionRows.Food(4, 0.2f, 20, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 10, 0, 0), "gregtech:empty_food_can", 1, true, 61), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:61
        new Can(new FoodNutritionRows.Entry("tall_food_can_vegetables", "Tall Food Can (Vegetables)", 23, new FoodNutritionRows.Food(6, 0.3f, 30, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 15, 0, 0), "gregtech:empty_food_can", 1, true, 62), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:62
        new Can(new FoodNutritionRows.Entry("wide_food_can_vegetables", "Wide Food Can (Vegetables)", 24, new FoodNutritionRows.Food(8, 0.4f, 40, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 20, 0, 0), "gregtech:empty_food_can", 1, true, 63), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:63
        new Can(new FoodNutritionRows.Entry("large_food_can_vegetables", "Large Food Can (Vegetables)", 25, new FoodNutritionRows.Food(10, 0.5f, 50, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 25, 0, 0), "gregtech:empty_food_can", 1, true, 64), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:64
        new Can(new FoodNutritionRows.Entry("huge_food_can_vegetables", "Huge Food Can (Vegetables)", 26, new FoodNutritionRows.Food(12, 0.6f, 60, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 30, 0, 0), "gregtech:empty_food_can", 1, true, 65), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:65
        new Can(new FoodNutritionRows.Entry("tiny_food_can_fruits", "Tiny Food Can (Fruits)", 31, new FoodNutritionRows.Food(2, 0.1f, 15, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 10, 0, 0), "gregtech:empty_food_can", 1, true, 67), 0.3f, 0, 0, false, false, false), // MultiItemCans.java:67
        new Can(new FoodNutritionRows.Entry("small_food_can_fruits", "Small Food Can (Fruits)", 32, new FoodNutritionRows.Food(4, 0.2f, 30, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 20, 0, 0), "gregtech:empty_food_can", 1, true, 68), 0.3f, 0, 0, false, false, false), // MultiItemCans.java:68
        new Can(new FoodNutritionRows.Entry("tall_food_can_fruits", "Tall Food Can (Fruits)", 33, new FoodNutritionRows.Food(6, 0.3f, 45, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 30, 0, 0), "gregtech:empty_food_can", 1, true, 69), 0.3f, 0, 0, false, false, false), // MultiItemCans.java:69
        new Can(new FoodNutritionRows.Entry("wide_food_can_fruits", "Wide Food Can (Fruits)", 34, new FoodNutritionRows.Food(8, 0.4f, 60, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 40, 0, 0), "gregtech:empty_food_can", 1, true, 70), 0.3f, 0, 0, false, false, false), // MultiItemCans.java:70
        new Can(new FoodNutritionRows.Entry("large_food_can_fruits", "Large Food Can (Fruits)", 35, new FoodNutritionRows.Food(10, 0.5f, 75, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 50, 0, 0), "gregtech:empty_food_can", 1, true, 71), 0.3f, 0, 0, false, false, false), // MultiItemCans.java:71
        new Can(new FoodNutritionRows.Entry("huge_food_can_fruits", "Huge Food Can (Fruits)", 36, new FoodNutritionRows.Food(12, 0.6f, 90, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 60, 0, 0), "gregtech:empty_food_can", 1, true, 72), 0.3f, 0, 0, false, false, false), // MultiItemCans.java:72
        new Can(new FoodNutritionRows.Entry("tiny_food_can_bread", "Tiny Food Can (Bread)", 41, new FoodNutritionRows.Food(2, 0.1f, 2, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 74), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:74
        new Can(new FoodNutritionRows.Entry("small_food_can_bread", "Small Food Can (Bread)", 42, new FoodNutritionRows.Food(4, 0.2f, 4, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 75), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:75
        new Can(new FoodNutritionRows.Entry("tall_food_can_bread", "Tall Food Can (Bread)", 43, new FoodNutritionRows.Food(6, 0.3f, 6, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 76), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:76
        new Can(new FoodNutritionRows.Entry("wide_food_can_bread", "Wide Food Can (Bread)", 44, new FoodNutritionRows.Food(8, 0.4f, 8, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 77), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:77
        new Can(new FoodNutritionRows.Entry("large_food_can_bread", "Large Food Can (Bread)", 45, new FoodNutritionRows.Food(10, 0.5f, 10, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 78), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:78
        new Can(new FoodNutritionRows.Entry("huge_food_can_bread", "Huge Food Can (Bread)", 46, new FoodNutritionRows.Food(12, 0.6f, 12, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 79), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:79
        new Can(new FoodNutritionRows.Entry("tiny_food_can_meat", "Tiny Food Can (Meat)", 51, new FoodNutritionRows.Food(2, 0.1f, 5, 310, false, false), new FoodNutritionRows.Stats(0, 0, 4, 0, 4, 0), "gregtech:empty_food_can", 1, true, 81), 0.1f, 0, 29, false, true, true), // MultiItemCans.java:81
        new Can(new FoodNutritionRows.Entry("small_food_can_meat", "Small Food Can (Meat)", 52, new FoodNutritionRows.Food(4, 0.2f, 10, 310, false, false), new FoodNutritionRows.Stats(0, 0, 8, 0, 8, 0), "gregtech:empty_food_can", 1, true, 82), 0.1f, 0, 29, false, true, true), // MultiItemCans.java:82
        new Can(new FoodNutritionRows.Entry("tall_food_can_meat", "Tall Food Can (Meat)", 53, new FoodNutritionRows.Food(6, 0.3f, 15, 310, false, false), new FoodNutritionRows.Stats(0, 0, 12, 0, 12, 0), "gregtech:empty_food_can", 1, true, 83), 0.1f, 0, 29, false, true, true), // MultiItemCans.java:83
        new Can(new FoodNutritionRows.Entry("wide_food_can_meat", "Wide Food Can (Meat)", 54, new FoodNutritionRows.Food(8, 0.4f, 20, 310, false, false), new FoodNutritionRows.Stats(0, 0, 16, 0, 16, 0), "gregtech:empty_food_can", 1, true, 84), 0.1f, 0, 29, false, true, true), // MultiItemCans.java:84
        new Can(new FoodNutritionRows.Entry("large_food_can_meat", "Large Food Can (Meat)", 55, new FoodNutritionRows.Food(10, 0.5f, 25, 310, false, false), new FoodNutritionRows.Stats(0, 0, 20, 0, 20, 0), "gregtech:empty_food_can", 1, true, 85), 0.1f, 0, 29, false, true, true), // MultiItemCans.java:85
        new Can(new FoodNutritionRows.Entry("huge_food_can_meat", "Huge Food Can (Meat)", 56, new FoodNutritionRows.Food(12, 0.6f, 30, 310, false, false), new FoodNutritionRows.Stats(0, 0, 24, 0, 24, 0), "gregtech:empty_food_can", 1, true, 86), 0.1f, 0, 29, false, true, true), // MultiItemCans.java:86
        new Can(new FoodNutritionRows.Entry("tiny_food_can_fish", "Tiny Food Can (Fish)", 61, new FoodNutritionRows.Food(2, 0.1f, 5, 310, false, false), new FoodNutritionRows.Stats(0, 0, 2, 0, 2, 0), "gregtech:empty_food_can", 1, true, 88), 0.1f, 0, 25, false, true, false), // MultiItemCans.java:88
        new Can(new FoodNutritionRows.Entry("small_food_can_fish", "Small Food Can (Fish)", 62, new FoodNutritionRows.Food(4, 0.2f, 10, 310, false, false), new FoodNutritionRows.Stats(0, 0, 4, 0, 4, 0), "gregtech:empty_food_can", 1, true, 89), 0.1f, 0, 25, false, true, false), // MultiItemCans.java:89
        new Can(new FoodNutritionRows.Entry("tall_food_can_fish", "Tall Food Can (Fish)", 63, new FoodNutritionRows.Food(6, 0.3f, 15, 310, false, false), new FoodNutritionRows.Stats(0, 0, 8, 0, 8, 0), "gregtech:empty_food_can", 1, true, 90), 0.1f, 0, 25, false, true, false), // MultiItemCans.java:90
        new Can(new FoodNutritionRows.Entry("wide_food_can_fish", "Wide Food Can (Fish)", 64, new FoodNutritionRows.Food(8, 0.4f, 20, 310, false, false), new FoodNutritionRows.Stats(0, 0, 10, 0, 10, 0), "gregtech:empty_food_can", 1, true, 91), 0.1f, 0, 25, false, true, false), // MultiItemCans.java:91
        new Can(new FoodNutritionRows.Entry("large_food_can_fish", "Large Food Can (Fish)", 65, new FoodNutritionRows.Food(10, 0.5f, 25, 310, false, false), new FoodNutritionRows.Stats(0, 0, 12, 0, 12, 0), "gregtech:empty_food_can", 1, true, 92), 0.1f, 0, 25, false, true, false), // MultiItemCans.java:92
        new Can(new FoodNutritionRows.Entry("huge_food_can_fish", "Huge Food Can (Fish)", 66, new FoodNutritionRows.Food(12, 0.6f, 30, 310, false, false), new FoodNutritionRows.Stats(0, 0, 14, 0, 14, 0), "gregtech:empty_food_can", 1, true, 93), 0.1f, 0, 25, false, true, false), // MultiItemCans.java:93
        new Can(new FoodNutritionRows.Entry("tiny_food_can_chum", "Tiny Food Can (Chum)", 71, new FoodNutritionRows.Food(2, 0.1f, 5, 310, false, true), new FoodNutritionRows.Stats(0, 0, 10, 0, 0, 0), "gregtech:empty_food_can", 1, true, 95), 0.1f, 0, 39, true, false, false), // MultiItemCans.java:95
        new Can(new FoodNutritionRows.Entry("small_food_can_chum", "Small Food Can (Chum)", 72, new FoodNutritionRows.Food(4, 0.2f, 10, 310, false, true), new FoodNutritionRows.Stats(0, 0, 20, 0, 0, 0), "gregtech:empty_food_can", 1, true, 96), 0.1f, 0, 39, true, false, false), // MultiItemCans.java:96
        new Can(new FoodNutritionRows.Entry("tall_food_can_chum", "Tall Food Can (Chum)", 73, new FoodNutritionRows.Food(6, 0.3f, 15, 310, false, true), new FoodNutritionRows.Stats(0, 0, 30, 0, 0, 0), "gregtech:empty_food_can", 1, true, 97), 0.1f, 0, 39, true, false, false), // MultiItemCans.java:97
        new Can(new FoodNutritionRows.Entry("wide_food_can_chum", "Wide Food Can (Chum)", 74, new FoodNutritionRows.Food(8, 0.4f, 20, 310, false, true), new FoodNutritionRows.Stats(0, 0, 40, 0, 0, 0), "gregtech:empty_food_can", 1, true, 98), 0.1f, 0, 39, true, false, false), // MultiItemCans.java:98
        new Can(new FoodNutritionRows.Entry("large_food_can_chum", "Large Food Can (Chum)", 75, new FoodNutritionRows.Food(10, 0.5f, 25, 310, false, true), new FoodNutritionRows.Stats(0, 0, 50, 0, 0, 0), "gregtech:empty_food_can", 1, true, 99), 0.1f, 0, 39, true, false, false), // MultiItemCans.java:99
        new Can(new FoodNutritionRows.Entry("huge_food_can_chum", "Huge Food Can (Chum)", 76, new FoodNutritionRows.Food(12, 0.6f, 30, 310, false, true), new FoodNutritionRows.Stats(0, 0, 60, 0, 0, 0), "gregtech:empty_food_can", 1, true, 100), 0.1f, 0, 39, true, false, false), // MultiItemCans.java:100
        new Can(new FoodNutritionRows.Entry("tiny_food_can_cookies", "Tiny Food Can (Cookies)", 81, new FoodNutritionRows.Food(2, 0.1f, 2, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 102), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:102
        new Can(new FoodNutritionRows.Entry("small_food_can_cookies", "Small Food Can (Cookies)", 82, new FoodNutritionRows.Food(4, 0.2f, 4, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 103), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:103
        new Can(new FoodNutritionRows.Entry("tall_food_can_cookies", "Tall Food Can (Cookies)", 83, new FoodNutritionRows.Food(6, 0.3f, 6, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 104), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:104
        new Can(new FoodNutritionRows.Entry("wide_food_can_cookies", "Wide Food Can (Cookies)", 84, new FoodNutritionRows.Food(8, 0.4f, 8, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 105), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:105
        new Can(new FoodNutritionRows.Entry("large_food_can_cookies", "Large Food Can (Cookies)", 85, new FoodNutritionRows.Food(10, 0.5f, 10, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 106), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:106
        new Can(new FoodNutritionRows.Entry("huge_food_can_cookies", "Huge Food Can (Cookies)", 86, new FoodNutritionRows.Food(12, 0.6f, 12, 310, false, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 107), 0.1f, 0, 0, false, false, false), // MultiItemCans.java:107
        new Can(new FoodNutritionRows.Entry("canned_space_air", "Canned Space Air", 32764, new FoodNutritionRows.Food(0, 0.0f, 0, 303, true, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 109), 0.2f, 400, 0, false, false, false), // MultiItemCans.java:109
        new Can(new FoodNutritionRows.Entry("canned_hot_air", "Canned Hot Air", 32765, new FoodNutritionRows.Food(0, 0.0f, 0, 313, true, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 110), 0.5f, 400, 0, false, false, false), // MultiItemCans.java:110
        new Can(new FoodNutritionRows.Entry("canned_air", "Canned Air", 32766, new FoodNutritionRows.Food(0, 0.0f, 0, 309, true, false), new FoodNutritionRows.Stats(0, 0, 0, 0, 0, 0), "gregtech:empty_food_can", 1, true, 111), 0.2f, 400, 0, false, false, false) // MultiItemCans.java:111
    );
    private static final Map<String,Can> BY_ID;
    static { var map = new LinkedHashMap<String,Can>(); for(var can:ROWS) map.put(can.id(),can); BY_ID=Map.copyOf(map); }
    public static Can forId(String id) { return id == null ? null : BY_ID.get(id); }
    /** Source IItemRottable conversion; this does not invent a timed spoilage mechanic. */
    public static String rottenId(String id) {
        var can=forId(id); if(can==null || can.food().meta()<20 || can.food().meta()>=32000) return id;
        int target=10+can.food().meta()%10;
        return ROWS.stream().filter(row->row.food().meta()==target).findFirst().orElseThrow().id();
    }
}
