package com.gregtech.gregtech.content.food;
import java.util.List;
/** Original GT6 CS.FoodsGT, preserving source row order and omissions. */
public final class FoodStatisticRows {
 private FoodStatisticRows(){}
 public record Row(String itemId,int alcohol,int caffeine,int dehydration,int sugar,int fat,int radiation){}
 public static final List<Row> ROWS=List.of(
 new Row("minecraft:apple",0, 0, 0, 8, 0, 0),
 new Row("minecraft:baked_potato",0, 0, 0, 4, 0, 0),
 new Row("minecraft:beef",0, 0, 0, 0, 16, 0),
 new Row("minecraft:carrot",0, 0, 0, 8, 0, 0),
 new Row("minecraft:chicken",0, 0, 0, 0, 12, 0),
 new Row("minecraft:cocoa_beans",0, 0, 4, 4, 0, 0),
 new Row("minecraft:cod",0, 0, 0, 0, 12, 0),
 new Row("minecraft:cooked_beef",0, 0, 0, 0, 16, 0),
 new Row("minecraft:cooked_chicken",0, 0, 0, 0, 12, 0),
 new Row("minecraft:cooked_cod",0, 0, 0, 0, 12, 0),
 new Row("minecraft:cooked_porkchop",0, 0, 0, 0, 16, 0),
 new Row("minecraft:cooked_salmon",0, 0, 0, 0, 12, 0),
 new Row("minecraft:cookie",0, 0, 0, 10, 0, 0),
 new Row("minecraft:mushroom_stew",0, 10, 0, 5, 0, 0),
 new Row("minecraft:mutton",0, 0, 0, 0, 16, 0),
 new Row("minecraft:poisonous_potato",0, 0, 0, 4, 0, 0),
 new Row("minecraft:porkchop",0, 0, 0, 0, 16, 0),
 new Row("minecraft:potato",0, 0, 0, 4, 0, 0),
 new Row("minecraft:rabbit",0, 0, 0, 0, 12, 0),
 new Row("minecraft:rotten_flesh",10, 0, 0, 0, 8, 0),
 new Row("gregtech:lemon",0, 0, 0, 4, 0, 0),
 new Row("gregtech:lemon_slice",0, 0, 0, 1, 0, 0),
 new Row("gregtech:tomato",0, 0, 0, 4, 0, 0),
 new Row("gregtech:tomato_slice",0, 0, 0, 1, 0, 0),
 new Row("gregtech:maxim_tomato",0, 0, 0, 10, 0, 0),
 new Row("gregtech:onion",0, 0, 0, 4, 0, 0),
 new Row("gregtech:onion_slice",0, 0, 0, 1, 0, 0),
 new Row("gregtech:cucumber",0, 0, 0, 4, 0, 0),
 new Row("gregtech:cucumber_slice",0, 0, 0, 1, 0, 0),
 new Row("gregtech:pickle",4, 0, 0, 4, 0, 0),
 new Row("gregtech:pickle_slice",1, 0, 0, 1, 0, 0),
 new Row("gregtech:chili_pepper",0, 0, 10, 0, 0, 0),
 new Row("gregtech:green_grapes",0, 0, 0, 12, 0, 0),
 new Row("gregtech:green_raisins",0, 0, 0, 12, 0, 0),
 new Row("gregtech:white_grapes",0, 0, 0, 12, 0, 0),
 new Row("gregtech:white_raisins",0, 0, 0, 12, 0, 0),
 new Row("gregtech:red_grapes",0, 0, 0, 12, 0, 0),
 new Row("gregtech:red_raisins",0, 0, 0, 12, 0, 0),
 new Row("gregtech:purple_grapes",0, 0, 0, 12, 0, 0),
 new Row("gregtech:purple_raisins",0, 0, 0, 12, 0, 0),
 new Row("gregtech:chocolate_raisins",0, 0, 0, 40, 0, 0),
 new Row("gregtech:carrot_slice",0, 0, 0, 2, 0, 0),
 new Row("gregtech:banana",0, 0, 0, 8, 0, 4),
 new Row("gregtech:banana_slice",0, 0, 0, 2, 0, 1),
 new Row("gregtech:pomegranate",0, 0, 0, 8, 0, 0),
 new Row("gregtech:pomeraisins",0, 0, 0, 2, 0, 0),
 new Row("gregtech:blueberry",0, 0, 0, 8, 0, 0),
 new Row("gregtech:gooseberry",0, 0, 0, 8, 0, 0),
 new Row("gregtech:candleberry",0, 0, 0, 8, 0, 0),
 new Row("gregtech:cranberry",0, 0, 0, 8, 0, 0),
 new Row("gregtech:black_currants",0, 0, 0, 6, 0, 0),
 new Row("gregtech:white_currants",0, 0, 0, 8, 0, 0),
 new Row("gregtech:red_currants",0, 0, 0, 8, 0, 0),
 new Row("gregtech:blackberry",0, 0, 0, 8, 0, 0),
 new Row("gregtech:raspberry",0, 0, 0, 8, 0, 0),
 new Row("gregtech:strawberry",0, 0, 0, 8, 0, 0),
 new Row("gregtech:apple",0, 0, 0, 4, 0, 0),
 new Row("gregtech:apple_slice",0, 0, 0, 1, 0, 0),
 new Row("gregtech:apple_2",0, 0, 0, 8, 0, 0),
 new Row("gregtech:apple_slice_2",0, 0, 0, 2, 0, 0),
 new Row("gregtech:apple_slice_3",0, 0, 0, 2, 0, 0),
 new Row("gregtech:apple_3",0, 0, 0, 12, 0, 0),
 new Row("gregtech:apple_slice_4",0, 0, 0, 3, 0, 0),
 new Row("gregtech:peanut",0, 0, 0, 0, 16, 0),
 new Row("gregtech:hazelnut",0, 0, 0, 0, 16, 0),
 new Row("gregtech:ananas",0, 0, 0, 8, 0, 0),
 new Row("gregtech:ananas_slice",0, 0, 0, 2, 0, 0),
 new Row("gregtech:coconut",0, 0, 0, 8, 8, 0),
 new Row("gregtech:cheese",0, 0, 8, 0, 8, 0),
 new Row("gregtech:cheese_slice",0, 0, 2, 0, 2, 0),
 new Row("gregtech:boiled_egg",0, 0, 0, 4, 8, 0),
 new Row("gregtech:boiled_egg_2",0, 0, 0, 4, 8, 0),
 new Row("gregtech:fried_egg",0, 0, 0, 4, 8, 0),
 new Row("gregtech:scrambled_egg",0, 0, 0, 4, 8, 0),
 new Row("gregtech:sliced_egg",0, 0, 0, 1, 2, 0),
 new Row("gregtech:egg_yolk",0, 0, 0, 2, 4, 0),
 new Row("gregtech:egg_white",0, 0, 0, 2, 4, 0),
 new Row("gregtech:raw_ham",0, 0, 0, 0, 24, 0),
 new Row("gregtech:cooked_ham",0, 0, 0, 0, 24, 0),
 new Row("gregtech:raw_ham_slice",0, 0, 0, 0, 6, 0),
 new Row("gregtech:cooked_ham_slice",0, 0, 0, 0, 6, 0),
 new Row("gregtech:raw_bacon",0, 0, 0, 0, 6, 0),
 new Row("gregtech:grilled_bacon",0, 0, 0, 0, 6, 0),
 new Row("gregtech:raw_ribs",0, 0, 0, 0, 24, 0),
 new Row("gregtech:grilled_ribs",0, 0, 0, 0, 24, 0),
 new Row("gregtech:barbecue_ribs",0, 0, 0, 30, 24, 0),
 new Row("gregtech:raw_rib_eye_steak",0, 0, 0, 0, 24, 0),
 new Row("gregtech:grilled_rib_eye_steak",0, 0, 0, 0, 24, 0),
 new Row("gregtech:dogmeat",0, 0, 0, 0, 12, 0),
 new Row("gregtech:grilled_dogmeat",0, 0, 0, 0, 12, 0),
 new Row("gregtech:mutton",0, 0, 0, 0, 12, 0),
 new Row("gregtech:grilled_mutton",0, 0, 0, 0, 12, 0),
 new Row("gregtech:horse_meat",0, 0, 0, 0, 8, 0),
 new Row("gregtech:grilled_horse_meat",0, 0, 0, 0, 8, 0),
 new Row("gregtech:mule_meat",0, 0, 0, 0, 8, 0),
 new Row("gregtech:grilled_mule_meat",0, 0, 0, 0, 8, 0),
 new Row("gregtech:donkey_meat",0, 0, 0, 0, 12, 0),
 new Row("gregtech:grilled_donkey_meat",0, 0, 0, 0, 12, 0),
 new Row("gregtech:scrap_meat",0, 0, 4, 0, 12, 0),
 new Row("gregtech:cookie_shaped_dough",0, 0, 0, 5, 0, 0),
 new Row("gregtech:cookie_shaped_raisin_dough",0, 0, 0, 10, 0, 0),
 new Row("gregtech:raisin_cookie",0, 0, 0, 15, 0, 0),
 new Row("gregtech:cookie_shaped_chocolate_raisin_dough",0, 0, 0, 20, 0, 0),
 new Row("gregtech:cookie",0, 0, 0, 25, 0, 0),
 new Row("gregtech:cookie_shaped_abyssal_dough",0, 0, 0, 5, 0, 0),
 new Row("gregtech:raw_cake_bottom",0, 0, 0, 20, 0, 0),
 new Row("gregtech:cake_bottom",0, 0, 0, 20, 0, 0),
 new Row("gregtech:raw_pizza_margherita",0, 0, 8, 0, 12, 0),
 new Row("gregtech:pizza_margherita",0, 0, 8, 0, 12, 0),
 new Row("gregtech:raw_mince_meat_pizza",0, 0, 4, 0, 16, 0),
 new Row("gregtech:mince_meat_pizza",0, 0, 4, 0, 16, 0),
 new Row("gregtech:raw_veggie_pizza",0, 0, 0, 16, 0, 0),
 new Row("gregtech:veggie_pizza",0, 0, 0, 16, 0, 0),
 new Row("gregtech:raw_pizza_hawaii",0, 0, 4, 8, 8, 0),
 new Row("gregtech:pizza_hawaii",0, 0, 4, 8, 8, 0),
 new Row("gregtech:veggie_burger",0, 0, 0, 12, 0, 0),
 new Row("gregtech:cheese_burger",0, 0, 8, 0, 8, 0),
 new Row("gregtech:hamburger",0, 0, 4, 0, 12, 0),
 new Row("gregtech:chum_burger",0, 0, 20, 0, 0, 0),
 new Row("gregtech:tofu_burger",0, 0, 4, 4, 0, 0),
 new Row("gregtech:soylent_burger",0, 0, 4, 0, 12, 0),
 new Row("gregtech:fish_burger",0, 0, 3, 0, 8, 0),
 new Row("gregtech:veggie_sandwich",0, 0, 0, 24, 0, 0),
 new Row("gregtech:cheese_sandwich",0, 0, 16, 0, 16, 0),
 new Row("gregtech:bacon_sandwich",0, 0, 12, 0, 18, 0),
 new Row("gregtech:steak_sandwich",0, 0, 8, 0, 16, 0),
 new Row("gregtech:large_veggie_sandwich",0, 0, 0, 36, 0, 0),
 new Row("gregtech:large_cheese_sandwich",0, 0, 24, 0, 24, 0),
 new Row("gregtech:large_bacon_sandwich",0, 0, 16, 0, 36, 0),
 new Row("gregtech:large_steak_sandwich",0, 0, 12, 0, 32, 0),
 new Row("gregtech:potato_strips",0, 0, 0, 5, 0, 0),
 new Row("gregtech:fries",0, 0, 10, 10, 0, 0),
 new Row("gregtech:fries_2",0, 0, 10, 10, 0, 0),
 new Row("gregtech:potato_chips",0, 0, 10, 10, 0, 0),
 new Row("gregtech:bag_of_potato_chips",0, 0, 10, 10, 0, 0),
 new Row("gregtech:chili_chips",0, 0, 30, 10, 0, 0),
 new Row("gregtech:bag_of_chili_chips",0, 0, 30, 10, 0, 0),
 new Row("gregtech:chum",0, 0, 20, 0, 0, 0),
 new Row("gregtech:chum_on_a_stick",0, 0, 20, 0, 0, 0),
 new Row("gregtech:flattened_egg_dough",0, 0, 0, 5, 5, 0),
 new Row("gregtech:ice_cream",0, 0, 5, 10, 0, 0),
 new Row("gregtech:stracciatella_ice_cream",0, 0, 5, 20, 0, 0),
 new Row("gregtech:raisin_ice_cream",0, 0, 5, 20, 0, 0),
 new Row("gregtech:vanilla_ice_cream",0, 0, 5, 10, 0, 0),
 new Row("gregtech:chocolate_ice_cream",0, 0, 5, 20, 0, 0),
 new Row("gregtech:mocha_ice_cream",0, 20, 5, 10, 0, 0),
 new Row("gregtech:caramel_ice_cream",0, 0, 5, 30, 0, 0),
 new Row("gregtech:mint_ice_cream",0, 0, 5, 10, 0, 0),
 new Row("gregtech:mint_chocolate_chip_ice_cream",0, 0, 5, 20, 0, 0),
 new Row("gregtech:strawberry_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:cherry_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:blueberry_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:currant_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:blackberry_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:raspberry_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:cranberry_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:gooseberry_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:nutella_ice_cream",0, 0, 5, 15, 15, 0),
 new Row("gregtech:lemon_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:maple_ice_cream",0, 0, 5, 30, 0, 0),
 new Row("gregtech:pistachio_ice_cream",0, 0, 5, 10, 10, 0),
 new Row("gregtech:bacon_ice_cream",0, 0, 5, 20, 0, 0),
 new Row("gregtech:kiwi_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:melon_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:banana_ice_cream",0, 0, 5, 15, 0, 2),
 new Row("gregtech:grape_ice_cream",0, 0, 5, 20, 0, 0),
 new Row("gregtech:apple_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:peanut_butter_ice_cream",0, 0, 5, 15, 15, 0),
 new Row("gregtech:ananas_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:chum_ice_cream",0, 0, 20, 10, 0, 0),
 new Row("gregtech:honey_ice_cream",0, 0, 5, 25, 0, 0),
 new Row("gregtech:bear_ice_cream",0, 0, 5, 10, 5, 0),
 new Row("gregtech:neapolitan_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:spumoni_chocolate_ice_cream",0, 0, 5, 18, 0, 0),
 new Row("gregtech:spumoni_vanilla_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:superman_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:rainbow_ice_cream",0, 0, 5, 15, 0, 0),
 new Row("gregtech:honey_comb",0, 0, 0, 20, 0, 0),
 new Row("gregtech:water_comb",0, 0, 0, 20, 0, 0),
 new Row("gregtech:jungle_comb",0, 0, 0, 20, 0, 0),
 new Row("gregtech:shroomy_comb",0, 0, 0, 20, 0, 0),
 new Row("gregtech:royal_comb",0, 0, 0, 20, 0, 0),
 new Row("gregtech:radaway",0, 0, 0, 0, 0, -50),
 new Row("gregtech:cure_all",-999, -999, -999, -999, -999, -999),
 new Row("gregtech:sugary_dough",0, 0, 0, 20, 0, 0),
 new Row("gregtech:chocolate_dough",0, 0, 0, 20, 0, 0),
 new Row("gregtech:egg_dough",0, 0, 0, 10, 0, 0),
 new Row("gregtech:sugary_raisin_dough",0, 0, 0, 30, 0, 0),
 new Row("gregtech:sugary_chocolate_raisin_dough",0, 0, 0, 40, 0, 0),
 new Row("gregtech:tofu_bar",0, 0, 4, 4, 0, 0),
 new Row("gregtech:emerald_green_bar",0, 0, 4, 0, 12, 0),
 new Row("gregtech:raw_meat_bar",0, 0, 4, 0, 12, 0),
 new Row("gregtech:cooked_meat_bar",0, 0, 4, 0, 4, 0),
 new Row("gregtech:chocolate_bar",0, 0, 0, 40, 0, 0),
 new Row("gregtech:cheese_bar",0, 0, 8, 0, 8, 0),
 new Row("gregtech:raw_fish_bar",0, 0, 3, 0, 8, 0),
 new Row("gregtech:cooked_fish_bar",0, 0, 3, 0, 8, 0),
 new Row("gregtech:butter",0, 0, 0, 0, 80, 0),
 new Row("gregtech:salted_butter",0, 0, 40, 0, 80, 0),
 new Row("gregtech:potato_on_a_stick",0, 0, 0, 4, 0, 0),
 new Row("gregtech:roasted_potato_on_a_stick",0, 0, 0, 4, 0, 0));
 public static final List<String> SKIPPED=List.of(
            "cropAcorn (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropAlmond (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropBeechnut (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropBrazilNut (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropButternut (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropCandleberry (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port's candleberry takes its numbers from its own FoodStat at MultiItemFood.java:403 (0,0,0,8,0,0))",
            "cropCandlenut (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropCashew (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropChestnut (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropChilipepper (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port's chili_pepper takes its numbers from its own FoodStat at MultiItemFood.java:307 (0,0,10,0,0,0))",
            "cropCinnamon (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port's cinnamon_bark declares no FoodStat, so GT6 gives it no statistics)",
            "cropCoconut (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port's coconut takes its numbers from its own FoodStat at MultiItemFood.java:486 (0,0,0,8,8,0))",
            "cropCoffee (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropCorn (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropCurryleaf (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropDevilishMaize (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropGingkoNut (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropHazelnut (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port's hazelnut is in ROWS with the same numbers, read from its FoodStat at MultiItemFood.java:472)",
            "cropHemp (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropNutmeg (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropPeanut (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port's peanut is in ROWS with the same numbers, read from its FoodStat at MultiItemFood.java:467)",
            "cropPecan (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropPeppercorn (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropPistachio (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropStarAnise (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropSunflower (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropTea (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "cropWalnut (RM.crop puts only non-MultiItemRandom stacks into FoodsGT (RM.java:776), so GT6's own item never got these numbers from here; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "foodBaconcooked (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port's grilled_bacon takes its numbers from its own FoodStat at MultiItemFood.java:542 (0,0,0,0,6,0))",
            "foodBaconraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port's raw_bacon is in ROWS with the same numbers, read from its FoodStat at MultiItemFood.java:541)",
            "foodCaramel (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "foodCheese (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port's cheese is in ROWS with the same numbers, read from its FoodStat at MultiItemFood.java:490)",
            "foodSilkentofu (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "foodTaffy (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllcrabyraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAlldograw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllhamraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllhorseraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllhydraraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllostrichraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllratraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllribcooked (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllribraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAlltitanraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllturkeyraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllturtleraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))",
            "listAllvenisonraw (GT6 guards the listener body with !ST.isGT, so it only ever fed other mods' items; the port has no item under this GT6 ore-dictionary name (it is another mod's crop or food, and GT6 registers no item of its own for it))"
    );
}
