/* Derived from GregTech-6 Team / Gregorius Techneticies; LGPL-3.0-or-later.
 * Original authors and license retained; see NOTICE and source provenance. */
package com.gregtech.gregtech.content.food;

import java.util.List;

/** GregTech-6 Team's MultiItemFood FoodStat callbacks for native sandwich ingredients. */
public final class SandwichIngredientEffects {
    private SandwichIngredientEffects() {}
    public record Effect(String item, String effect, int duration, int amplifier, int chance, boolean ambient) {}
    public static final List<Effect> ROWS = List.of(
        new Effect("lemon_slice", "immersiveengineering:conductive", 300, 0, 70, true),
        new Effect("chili_pepper", "immersiveengineering:flammable", 300, 0, 70, true),
        new Effect("chili_pepper", "minecraft:nausea", 200, 1, 40, true),
        new Effect("banana_slice", "immersiveengineering:slippery", 300, 1, 70, true),
        new Effect("scrambled_egg", "immersiveengineering:slippery", 300, 0, 30, true),
        new Effect("scrambled_egg", "immersiveengineering:sticky", 300, 0, 30, true),
        new Effect("egg_yolk", "immersiveengineering:slippery", 300, 0, 30, true),
        new Effect("egg_white", "immersiveengineering:sticky", 300, 0, 30, true),
        new Effect("barbecue_ribs", "minecraft:instant_health", 1, 0, 10, true),
        new Effect("barbecue_ribs", "minecraft:speed", 200, 0, 20, true),
        new Effect("scrap_meat", "minecraft:hunger", 300, 0, 70, true),
        new Effect("scrap_meat", "minecraft:nausea", 300, 0, 10, true),
        new Effect("chum", "minecraft:hunger", 1000, 4, 100, false),
        new Effect("chum", "minecraft:nausea", 300, 1, 80, false),
        new Effect("peppermint", "minecraft:slowness", -1, -1, 100, false),
        new Effect("blue_pill", "minecraft:nausea", -1, -1, 100, false),
        new Effect("red_pill", "minecraft:blindness", -1, -1, 100, false),
        new Effect("antidote", "minecraft:poison", -1, -1, 100, false),
        new Effect("cure_all", "immersiveengineering:flammable", -1, -1, 100, false),
        new Effect("cure_all", "immersiveengineering:slippery", -1, -1, 100, false),
        new Effect("cure_all", "immersiveengineering:conductive", -1, -1, 100, false),
        new Effect("cure_all", "immersiveengineering:sticky", -1, -1, 100, false),
        new Effect("cure_all", "minecraft:mining_fatigue", -1, -1, 100, false),
        new Effect("cure_all", "minecraft:slowness", -1, -1, 100, false),
        new Effect("cure_all", "minecraft:hunger", -1, -1, 100, false),
        new Effect("cure_all", "minecraft:instant_damage", -1, -1, 100, false),
        new Effect("cure_all", "minecraft:nausea", -1, -1, 100, false),
        new Effect("cure_all", "minecraft:blindness", -1, -1, 100, false),
        new Effect("cure_all", "minecraft:weakness", -1, -1, 100, false),
        new Effect("cure_all", "minecraft:poison", -1, -1, 100, false),
        new Effect("cure_all", "minecraft:wither", -1, -1, 100, false),
        new Effect("cure_all", "minecraft:regeneration", 100, 100, 100, false),
        new Effect("cure_all", "minecraft:saturation", 100, 100, 100, false),
        new Effect("raw_meat_bar", "minecraft:hunger", 300, 0, 50, true),
        new Effect("raw_fish_bar", "minecraft:hunger", 300, 0, 50, true),
        new Effect("butter", "immersiveengineering:slippery", 300, 1, 90, true),
        new Effect("salted_butter", "immersiveengineering:slippery", 300, 1, 90, true),
        new Effect("grape_vinegar", "minecraft:instant_health", 1, 1, 70, false),
        new Effect("cave_johnsons_grenade_juice", "immersiveengineering:conductive", 300, 0, 70, false),
        new Effect("chili_sauce", "immersiveengineering:flammable", 300, 0, 70, false),
        new Effect("chili_sauce", "minecraft:nausea", 1000, 0, 10, false),
        new Effect("chili_sauce", "minecraft:fire_resistance", 1000, 0, 60, false),
        new Effect("hot_sauce", "immersiveengineering:flammable", 300, 0, 70, false),
        new Effect("hot_sauce", "minecraft:nausea", 2000, 0, 30, false),
        new Effect("hot_sauce", "minecraft:fire_resistance", 2000, 0, 70, false),
        new Effect("diabolo_sauce", "immersiveengineering:flammable", 300, 1, 70, false),
        new Effect("diabolo_sauce", "minecraft:nausea", 3000, 1, 50, false),
        new Effect("diabolo_sauce", "minecraft:fire_resistance", 3000, 0, 80, false),
        new Effect("diablo_sauce", "immersiveengineering:flammable", 300, 1, 70, false),
        new Effect("diablo_sauce", "minecraft:nausea", 4000, 1, 70, false),
        new Effect("diablo_sauce", "minecraft:fire_resistance", 4000, 0, 90, false),
        new Effect("there_is_no_cow_sauce", "immersiveengineering:flammable", 300, 2, 90, false),
        new Effect("there_is_no_cow_sauce", "minecraft:nausea", 9999, 2, 999, false),
        new Effect("there_is_no_cow_sauce", "minecraft:fire_resistance", 9999, 9, 999, false),
        new Effect("barbecue_sauce", "minecraft:instant_health", 1, 0, 10, false),
        new Effect("barbecue_sauce", "minecraft:speed", 200, 0, 20, false),
        new Effect("apple_cider_vinegar", "minecraft:resistance", 400, 2, 70, false),
        new Effect("olive_oil", "minecraft:hunger", 400, 1, 70, false),
        new Effect("olive_oil", "immersiveengineering:slippery", 300, 1, 70, false),
        new Effect("olive_oil", "immersiveengineering:flammable", 300, 0, 70, false),
        new Effect("sunflower_oil", "minecraft:hunger", 400, 1, 70, false),
        new Effect("sunflower_oil", "immersiveengineering:slippery", 300, 1, 70, false),
        new Effect("sunflower_oil", "immersiveengineering:flammable", 300, 0, 70, false),
        new Effect("nut_oil", "minecraft:hunger", 400, 1, 70, false),
        new Effect("nut_oil", "immersiveengineering:slippery", 300, 1, 70, false),
        new Effect("nut_oil", "immersiveengineering:flammable", 300, 0, 70, false),
        new Effect("seed_oil", "minecraft:hunger", 400, 1, 70, false),
        new Effect("seed_oil", "immersiveengineering:slippery", 300, 1, 70, false),
        new Effect("seed_oil", "immersiveengineering:flammable", 300, 0, 70, false),
        new Effect("hemp_oil", "minecraft:hunger", 400, 1, 70, false),
        new Effect("hemp_oil", "immersiveengineering:slippery", 300, 1, 70, false),
        new Effect("hemp_oil", "immersiveengineering:flammable", 300, 0, 70, false),
        new Effect("lin_oil", "minecraft:hunger", 400, 1, 70, false),
        new Effect("lin_oil", "immersiveengineering:slippery", 300, 1, 70, false),
        new Effect("lin_oil", "immersiveengineering:flammable", 300, 0, 70, false),
        new Effect("fish_oil", "minecraft:hunger", 400, 1, 70, false),
        new Effect("fish_oil", "immersiveengineering:slippery", 300, 1, 70, false),
        new Effect("fish_oil", "immersiveengineering:flammable", 300, 0, 70, false),
        new Effect("whale_oil", "minecraft:hunger", 400, 1, 70, false),
        new Effect("whale_oil", "immersiveengineering:slippery", 300, 1, 70, false),
        new Effect("whale_oil", "immersiveengineering:flammable", 300, 0, 70, false),
        new Effect("mayo", "immersiveengineering:slippery", 300, 1, 70, false),
        new Effect("dressing", "immersiveengineering:slippery", 300, 1, 70, false),
        new Effect("honey", "immersiveengineering:sticky", 300, 0, 70, false),
        new Effect("royal_jelly", "immersiveengineering:sticky", 300, 0, 70, false),
        new Effect("royal_jelly", "minecraft:regeneration", 150, 1, 100, false),
        new Effect("ambrosia", "immersiveengineering:sticky", 300, 0, 70, false),
        new Effect("ambrosia", "minecraft:regeneration", 150, 0, 100, false),
        new Effect("rice_vinegar", "minecraft:strength", 300, 2, 70, false),
        new Effect("chocolate_cream", "immersiveengineering:sticky", 300, 0, 70, false),
        new Effect("nutella", "immersiveengineering:sticky", 300, 0, 70, false),
        new Effect("green_slime_bottle", "minecraft:jump_boost", 600, 0, 50, false),
        new Effect("green_slime_bottle", "immersiveengineering:sticky", 300, 0, 90, false),
        new Effect("pink_slime_bottle", "minecraft:jump_boost", 1200, 1, 75, false),
        new Effect("pink_slime_bottle", "immersiveengineering:sticky", 300, 0, 90, false),
        new Effect("blue_slime_bottle", "minecraft:jump_boost", 600, 0, 50, false),
        new Effect("blue_slime_bottle", "immersiveengineering:sticky", 300, 0, 90, false),
        new Effect("tomato_ketchup", "minecraft:instant_health", 1, 0, 10, false),
        new Effect("tomato_ketchup", "minecraft:speed", 200, 0, 20, false),
        new Effect("maple_syrup", "immersiveengineering:sticky", 300, 0, 70, false),
        new Effect("peanut_butter", "immersiveengineering:sticky", 300, 0, 70, false),
        new Effect("rainbow_sap", "minecraft:regeneration", 60, 4, 100, false),
        new Effect("rainbow_sap", "immersiveengineering:sticky", 300, 0, 30, false),
        new Effect("rainbow_sap", "minecraft:haste", 900, 2, 100, false),
        new Effect("bottle_of_poison", "minecraft:poison", 450, 1, 100, false)
    );
    private static final List<Effect> CANNED = List.of(
        new Effect("tiny_food_can_rotten", "minecraft:hunger", 300, 0, 40, false),
        new Effect("small_food_can_rotten", "minecraft:hunger", 300, 0, 50, false),
        new Effect("tall_food_can_rotten", "minecraft:hunger", 300, 0, 60, false),
        new Effect("wide_food_can_rotten", "minecraft:hunger", 300, 0, 70, false),
        new Effect("large_food_can_rotten", "minecraft:hunger", 300, 0, 80, false),
        new Effect("huge_food_can_rotten", "minecraft:hunger", 300, 0, 90, false),
        new Effect("tiny_food_can_chum", "minecraft:hunger", 1000, 4, 100, false),
        new Effect("tiny_food_can_chum", "minecraft:nausea", 300, 1, 80, false),
        new Effect("small_food_can_chum", "minecraft:hunger", 1000, 4, 100, false),
        new Effect("small_food_can_chum", "minecraft:nausea", 300, 1, 80, false),
        new Effect("tall_food_can_chum", "minecraft:hunger", 1000, 4, 100, false),
        new Effect("tall_food_can_chum", "minecraft:nausea", 300, 1, 80, false),
        new Effect("wide_food_can_chum", "minecraft:hunger", 1000, 4, 100, false),
        new Effect("wide_food_can_chum", "minecraft:nausea", 300, 1, 80, false),
        new Effect("large_food_can_chum", "minecraft:hunger", 1000, 4, 100, false),
        new Effect("large_food_can_chum", "minecraft:nausea", 300, 1, 80, false),
        new Effect("huge_food_can_chum", "minecraft:hunger", 1000, 4, 100, false),
        new Effect("huge_food_can_chum", "minecraft:nausea", 300, 1, 80, false)
    );
    public static List<Effect> forItem(String item) {
        return item.startsWith("gregtech:")
                ? java.util.stream.Stream.concat(ROWS.stream(), CANNED.stream()).filter(row -> row.item().equals(item.substring(9))).toList() : List.of();
    }
}
