package com.gregtech.gregtech.client;
import com.gregtech.gregtech.registry.*;import com.gregtech.gregtech.api.machine.EngineType;import com.gregtech.gregtech.blockentity.machine.*;import net.neoforged.neoforge.client.event.*;import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;import net.neoforged.api.distmarker.Dist;
@EventBusSubscriber(modid = com.gregtech.gregtech.api.mod.GregTechIdentity.MOD_ID,bus=EventBusSubscriber.Bus.MOD,value=Dist.CLIENT)
public final class EngineClientSetup {private EngineClientSetup(){}private static int core(EngineType type,int tint){return switch(type){case STEAM->0x0000FF;case ELECTRIC,FLUX->0x00FF00;case ROTATION->tint;case DIESEL->0xFF6600;};}
@SubscribeEvent public static void blocks(RegisterColorHandlersEvent.Block e){for(var h:GTEngines.all()){var b=h.get();e.register((state,level,pos,t)->{if(t==0)return b.tintRgb();if(t!=1)return 0xFFFFFF;if(level!=null&&pos!=null){var be=level.getBlockEntity(pos);if(be instanceof PistonEngineBlockEntity piston)return piston.coreColor();if(be instanceof KineticSteamEngineBlockEntity steam)return steamColor(steam.pressureState());}return core(b.engineType(),b.tintRgb());},b);}for(var h:GTMagnets.all())e.register((s,l,p,t)->t==0?h.get().tintRgb():0xFFFFFF,h.get());for(var h:GTPumps.all())e.register((s,l,p,t)->t==0?h.get().spec().material().getColor():0xFFFFFF,h.get());e.register((s,l,p,t)->t==0?GTLogisticsTank.BLOCK.get().spec().material().getColor():0xFFFFFF,GTLogisticsTank.BLOCK.get());for(var h:GTBoilers.all())e.register((s,l,p,t)->t==0?h.get().spec().material().getColor():0xFFFFFF,h.get());}
@SubscribeEvent public static void items(RegisterColorHandlersEvent.Item e){for(var h:GTEngines.all()){var b=h.get();e.register(ItemColorARGB.opaque((s,t)->t==0?b.tintRgb():t==1?core(b.engineType(),b.tintRgb()):0xFFFFFF),b.asItem());}for(var h:GTMagnets.all())e.register(ItemColorARGB.opaque((s,t)->t==0?h.get().tintRgb():0xFFFFFF),h.get().asItem());for(var h:GTPumps.all())e.register(ItemColorARGB.opaque((s,t)->t==0?h.get().spec().material().getColor():0xFFFFFF),h.get().asItem());e.register(ItemColorARGB.opaque((s,t)->t==0?GTLogisticsTank.BLOCK.get().spec().material().getColor():0xFFFFFF),GTLogisticsTank.BLOCK.get().asItem());for(var h:GTBoilers.all())e.register(ItemColorARGB.opaque((s,t)->t==0?h.get().spec().material().getColor():0xFFFFFF),h.get().asItem());}
private static int steamColor(int state){int p=Math.max(0,Math.min(31,state));return p<16?((p*17)<<8)|(255-p*17):((p-16)*17<<16)|((255-(p-16)*17)<<8);}
@SubscribeEvent @SuppressWarnings("unchecked") public static void renderers(EntityRenderersEvent.RegisterRenderers e){e.registerBlockEntityRenderer(GTBlockEntities.STEAM_BOILER.get(),BoilerBarometerRenderer::new);e.registerBlockEntityRenderer(GTBlockEntities.SANDWICH_BLOCK.get(),SandwichRenderer::new);for(var h:GTEngines.all())if(h.get().engineType()==EngineType.STEAM)e.registerBlockEntityRenderer((net.minecraft.world.level.block.entity.BlockEntityType<KineticSteamEngineBlockEntity>)h.get().getBeType(),SteamEngineRenderer::new);}
}
