"""Resolve adopted metalset storage CR.REV data and registration metadata.

Sources are read-only. Seven native families have direct or recursively known
inputs; charging/logistics/locker rows are deliberately outside this importer.
"""
from pathlib import Path
from collections import Counter
import argparse, hashlib, json, re, sys
REPO=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(REPO/'tools/integration'))
from generate_machine_material_data import masked, norm, calls, recipe, amount, java_material, U

FAMILIES={0:'chest_',500:'reinforced_wood_chest_',2000:'safe_',3000:'key_safe_',
          4000:'drawer_quad_',6000:'mass_storage_',8600:'bottle_crate_'}
GROUPS={'aMetal':('pickaxe',False),'aWooden':('axe',True),'aMachine':('wrench',False),'aUtilMetal':('pickaxe',True)}

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--source',type=Path,required=True)
 ap.add_argument('--out',type=Path,required=True);ap.add_argument('--audit',type=Path,required=True);ns=ap.parse_args()
 relatives=['src/main/java/gregtech/loaders/b/Loader_MultiTileEntities.java','src/main/java/gregapi/data/OP.java',
            'src/main/java/gregapi/load/LoaderOreDictReRegistrations.java','src/main/java/gregapi/data/ANY.java','LICENSE']
 texts=[masked((ns.source/p).read_text(encoding='utf-8')) for p in relatives[:-1]]
 mte,op,automatic,any_source=texts
 weights={m[1]:amount(m[2].split(',')[0]) for m in re.finditer(r'^\s*(\w+)\s*=\s*create\([^\n]*?\.setMaterialStats\(([^)]*)\)',op,re.M)}
 chest=list(calls(automatic,'OreDictManager.INSTANCE.setAutomaticItemData'))
 chest=[a for _,a in chest if norm(a[0])=='OD.craftingChest']
 assert len(chest)==1 and norm(chest[0][1])=='newOreDictItemData(ANY.Wood,U*4)'
 assert re.search(r'Wood\s*\.[^\n]*setAllToTheOutputOf\(\s*MT.Wood\s*\)',any_source)
 end=mte.index('\n\t}',mte.index('private static void metalset('))
 method=mte[:end][mte.index('private static void metalset('):]
 registrations={}; family_rows={}
 for pos,a in calls(method,'aRegistry.add'):
  expr=norm(a[2]);offset=0 if expr=='aID' else int(expr.removesuffix('+aID'))
  if offset not in FAMILIES:continue
  patterns,keys=recipe(a[9:]);tool,hand=GROUPS[norm(a[7])]
  registrations[offset]=(patterns,keys)
  family_rows[offset]=dict(source_offset=offset,pattern=patterns,ingredients=keys,harvest=norm(a[5]),
                           group=norm(a[7]),tool=tool,hand=hand)
 def resolve(offset):
  patterns,keys=registrations[offset];totals=Counter()
  for char,count in Counter(''.join(patterns)).items():
   if char not in keys:continue # CR tools are lowercase implicit ingredient keys.
   expr=norm(keys[char]);match=re.fullmatch(r'OP\.(\w+)\.dat\(aMat\)',expr)
   if match:parts=Counter(metal=weights[match[1]])
   elif expr=='OD.craftingChest':parts=Counter(Wood=4*U)
   elif expr=='aRegistry.getItem(aID)':parts=resolve(0)
   else:raise ValueError('Unexpected adopted storage input '+expr)
   for mat,value in parts.items():totals[mat]+=value*count
  return totals
 for offset,row in family_rows.items():row['material_units']=dict(resolve(offset))
 catalog=(REPO/'core/src/main/java/com/gregtech/gregtech/registry/GTStorageMetals.java').read_text(encoding='utf-8')
 suffixes=re.findall(r'new Spec\("([^"]+)"',catalog)
 metalsets=[(pos,a) for pos,a in calls(mte,'metalset') if len(a)==10 and norm(a[5]).startswith(('MT.','ANY.'))]
 assert len(metalsets)==len(suffixes)==60
 aliases={m[1]:norm(m[2]) for m in re.finditer(r'^\s*(\w+)\s*\.[^\n]*?\.setAllToTheOutputOf\(([^)]*)\)',any_source,re.M)}
 rows=[]
 for suffix,(pos,a) in zip(suffixes,metalsets):
  original=norm(a[5]);target=aliases[original[4:]] if original.startswith('ANY.') else original
  rows.append(dict(suffix=suffix,source_id=int(a[6]),source_material=original,
                   java_material=java_material(target.removeprefix('MT.')),source_line=mte[:pos].count('\n')+1))
 java=['''/* Copyright GregTech-6 Team / Gregorius Techneticies; LGPL-3.0-or-later.
 * Loader_MultiTileEntities.metalset, CR.REV, OP and automatic craftingChest data.
 * Generated by tools/integration/generate_storage_material_data.py. */
package com.gregtech.gregtech.content.machine;

import com.gregtech.gregtech.api.material.*;
import com.gregtech.gregtech.data.ImportedMaterialData;
import com.gregtech.gregtech.data.SourceBlockProperties;
import java.util.*;

/** Original storage recipes, source IDs and explicit block-group/metadata choices. */
public final class OriginalStorageMaterialData {
    private OriginalStorageMaterialData() {}
    private static final Map<String,ItemComposition> DATA = new LinkedHashMap<>();
    private static final Map<String,SourceBlockProperties.Params> HARVEST = new LinkedHashMap<>();
    static {
''']
 for row in rows:java.append(f'        metalset("{row["suffix"]}",{row["source_id"]},{row["java_material"]});\n')
 java.append('''    }
    public static Map<String,ItemComposition> blocks() { return Collections.unmodifiableMap(DATA); }
    public static Map<String,SourceBlockProperties.Params> harvest() { return Collections.unmodifiableMap(HARVEST); }
    private static void add(String path,int id,GTMaterial metal,long metalAmount,long woodAmount,String tool,int explicitLevel,boolean hand) {
        var parts = new ArrayList<MaterialComponent>(); parts.add(MaterialComponent.of(metal,metalAmount));
        if (woodAmount > 0) parts.add(MaterialComponent.of(com.gregtech.gregtech.data.generated.GT6Materials.Woods.Wood,woodAmount));
        DATA.put(path,ReversibleCraftingData.perItem(parts,1,"GT6 original metalset CR.REV storage"+id));
        HARVEST.put(path,new SourceBlockProperties.Params(id,tool,metal,explicitLevel,hand));
    }
    private static void metalset(String suffix,int id,GTMaterial metal) {
''')
 for offset,prefix in FAMILIES.items():
  v=family_rows[offset];weights=v['material_units'];expr=f'"{prefix}"+suffix'
  if offset==2000:expr='suffix.equals("steel")?"safe":'+expr
  if offset==4000:expr='suffix.equals("stainless_steel")?"drawer_quad":'+expr
  level=-1 if v['harvest']=='aMat.mToolQuality' else int(v['harvest'])
  java.append(f'        add({expr},id+{offset},metal,{weights["metal"]}L,{weights.get("Wood",0)}L,"{v["tool"]}",{level},{str(v["hand"]).lower()});\n')
 java.append('    }\n}\n');ns.out.parent.mkdir(parents=True,exist_ok=True);ns.out.write_text(''.join(java),encoding='utf-8')
 audit=dict(families=family_rows,metalsets=rows,identities=420,
             source_files=[dict(path=str(ns.source/p),sha256=hashlib.sha256((ns.source/p).read_bytes()).hexdigest()) for p in relatives],
             authors=['GregTech-6 Team','Gregorius Techneticies'],license='LGPL-3.0-or-later',
             boundaries='Seven adopted native metalset families; exact original units. No invented material for charging/logistics/lockers or unrelated legacy IDs. Native suffix order and material identities verified by shared source contracts.')
 ns.audit.parent.mkdir(parents=True,exist_ok=True);ns.audit.write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps(dict(identities=420,families=len(FAMILIES),metalsets=len(rows),units={k:v['material_units'] for k,v in family_rows.items()})))
if __name__=='__main__':main()
