"""Map adopted block identities to canonical MTE harvest metadata, without guessing tiers.

Input audit is produced by generate_machine_material_data.py. Source trees are read-only;
group/tool/adventure exemptions come from Loader_MultiTileEntities and vanilla Material.
"""
from pathlib import Path
import argparse, hashlib, json, re, sys

REPO=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(REPO/'tools/integration'))
from generate_machine_material_data import masked,norm,java_material
sys.path.insert(0,str(REPO/'tools'))
from extract_basic_machine_recipes import split_top_level

GROUPS={'aMachine':('wrench',False),'aMetal':('pickaxe',False),'aMetalChips':('shovel',False),
        'aMetalWires':('cutter',False),'aStone':('pickaxe',False),'aWooden':('axe',True),
        'aBush':('axe',True),'aWool':('shears',True),'aTNT':('pickaxe',True),
        'aUtilMetal':('pickaxe',True),'aUtilStone':('pickaxe',True),'aUtilWood':('axe',True),'aUtilWool':('shears',True)}

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--source',type=Path,required=True)
    ap.add_argument('--material-audit',type=Path,required=True);ap.add_argument('--out',type=Path,required=True)
    ap.add_argument('--audit',type=Path,required=True);ns=ap.parse_args()
    data=json.loads(ns.material_audit.read_text(encoding='utf-8'))
    raw=masked((ns.source/'src/main/java/gregapi/data/MT.java').read_text(encoding='utf-8'))
    arrays={m[1]:split_top_level(m[2]) for m in re.finditer(r'(\w+)\s*=\s*\{([^{}]*)\}',raw)}
    any_raw=masked((ns.source/'src/main/java/gregapi/data/ANY.java').read_text(encoding='utf-8'))
    aliases={m[1]:norm(m[2]) for m in re.finditer(r'^\s*(\w+)\s*\.[^\n]*?\.setAllToTheOutputOf\(([^)]*)\)',any_raw,re.M)}
    # Quality belongs to the registered hull, before output unification (Quartz steals MilkyQuartz).
    quality_aliases={m[1]:norm(m[2]) for m in re.finditer(r'^\s*(\w+)\s*\.[^\n]*?\.steal\(([^)]*)\)',any_raw,re.M)}
    def material(expr):
        expr=norm(expr)
        found=re.fullmatch(r'MT.DATA.(\w+)\[(\d+)\]',expr)
        if found:return material(arrays[found[1]][int(found[2])])
        if expr.startswith('ANY.'):return material(quality_aliases.get(expr[4:],aliases[expr[4:]]))
        symbol=expr.removeprefix('MT.')
        if re.fullmatch(r'(?:STONES\.)?\w+',symbol) and re.search(r'\b'+re.escape(symbol.split('.')[-1])+r'\s*=',(REPO/'core/src/main/java/com/gregtech/gregtech/data/ImportedMaterialData.java').read_text(encoding='utf-8')):
            return java_material(symbol)
        raise ValueError('Unsupported source harvest material: '+expr)
    source={x['id']:x for x in data['source_registration_parameters']}
    def params(row):
        src=source[row['source_id']]; tool,hand=GROUPS[src['block_group']]
        expr=src['harvest_expression'];mat='null';level=0
        if expr.isdigit():level=int(expr)
        elif expr.endswith('.mToolQuality'):mat=material(src['quality_material'] if expr=='aMat.mToolQuality' else expr[:-13]);level=-1
        else:raise ValueError('Unsupported original block metadata: '+expr)
        return dict(source_id=row['source_id'],source_line=src['line'],tool=tool,hand_harvestable=hand,
                    material=mat,explicit_level=level,original_expression=expr,block_group=src['block_group'])
    blocks={x['path']:params(x) for x in [*data['block_rows'],*data['source_without_known_data'],*data['source_invalid_recipes']]}
    basics={x['machine']+'/'+str(x['tier']):params(x) for x in data['rows']}
    header='''/* Copyright GregTech-6 Team / Gregorius Techneticies; LGPL-3.0-or-later.
 * Loader_MultiTileEntities, MultiTileEntityBlock.getHarvestLevel and LH.getToolTipHarvest.
 * Generated by tools/integration/generate_source_block_properties.py. */
package com.gregtech.gregtech.data;

import com.gregtech.gregtech.api.material.GTMaterial;
import com.gregtech.gregtech.content.transport.HopperCatalog;
import java.util.*;

/** Audited original tool/metadata identities. Qualities remain live shared material values. */
public final class SourceBlockProperties {
    private SourceBlockProperties() {}
    public record Params(int sourceId, String tool, GTMaterial material, int explicitLevel, boolean handHarvestable) {
        public int level() { return Math.max(0, Math.min(15, explicitLevel < 0 ? material.getToolQuality() : explicitLevel)); }
    }
    private static final Map<String, Params> BLOCKS = new LinkedHashMap<>(), BASICS = new LinkedHashMap<>();
    static { blocks0(); blocks1(); blocks2(); blocks3(); basics0(); basics1(); basics2(); basics3();
        BLOCKS.putAll(com.gregtech.gregtech.content.machine.OriginalStorageMaterialData.harvest());
        // Original metalset lines145..146 pass explicit metadata0, even for high-tier metals.
        for (var entry : HopperCatalog.ALL) {
            String suffix = entry.spec().id().substring(entry.queue() ? "queue_hopper_".length() : "hopper_".length());
            int sourceId = BLOCKS.get("chest_"+suffix).sourceId() + (entry.queue() ? 8200 : 8000);
            BLOCKS.put(entry.spec().id(), new Params(sourceId,"wrench",entry.spec().material(),0,false));
        }
    }
    public static Optional<Params> block(String path) { return Optional.ofNullable(BLOCKS.get(path)); }
    public static Optional<Params> basic(String machine, int tier) { return Optional.ofNullable(BASICS.get(machine+"/"+tier)); }
    public static Map<String, Params> blocks() { return Collections.unmodifiableMap(BLOCKS); }
    public static Map<String, Params> basics() { return Collections.unmodifiableMap(BASICS); }
'''
    java=[header]
    for label,table,target in [('blocks',blocks,'BLOCKS'),('basics',basics,'BASICS')]:
        items=list(table.items()); size=(len(items)+3)//4
        for group in range(4):
            java.append(f'    private static void {label}{group}() {{\n')
            for name,v in items[group*size:(group+1)*size]:
                java.append(f'        {target}.put("{name}", new Params({v["source_id"]},"{v["tool"]}",{v["material"]},{v["explicit_level"]},{str(v["hand_harvestable"]).lower()}));\n')
            java.append('    }\n')
    java.append('}\n');ns.out.parent.mkdir(parents=True,exist_ok=True);ns.out.write_text(''.join(java),encoding='utf-8')
    paths=['src/main/java/gregtech/loaders/b/Loader_MultiTileEntities.java','src/main/java/gregapi/block/multitileentity/MultiTileEntityBlock.java','src/main/java/gregapi/data/ANY.java',
           'src/main/java/gregapi/block/multitileentity/MultiTileEntityClassContainer.java','src/main/java/gregapi/data/MT.java','LICENSE']
    audit=dict(blocks=blocks,basics=basics,additional_dynamic_hoppers=120,additional_dynamic_storage=720,
               source_files=[dict(path=str(ns.source/p),sha256=hashlib.sha256((ns.source/p).read_bytes()).hexdigest()) for p in paths],
               authors=['GregTech-6 Team','Gregorius Techneticies'],license='LGPL-3.0-or-later',
               boundaries='Adopted fixed source IDs, audited twelve-family storage metalsets, and120 hoppers with actual original metalset IDs and explicit metadata0. Other blocks keep native harvest policy; no invented source identity.')
    ns.audit.parent.mkdir(parents=True,exist_ok=True);ns.audit.write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(json.dumps(dict(blocks=len(blocks),basics=len(basics),dynamic_hoppers=120,dynamic_storage=720,hand_harvestable=sum(x['hand_harvestable'] for x in blocks.values()))))

if __name__=='__main__':main()
