package com.gregtech.gregtech.block;

import com.gregtech.gregtech.block.stone.StoneType;
import net.minecraft.util.StringRepresentable;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * The background ("host") rock an ore block generated in - the port of GT6's one-ore-block-per-stone
 * variants ({@code BlocksGT.ore[stone]}).
 *
 * <p>§103.B: this used to live on {@link com.gregtech.gregtech.blockentity.OreBlockEntity} as a
 * {@code String}, i.e. one block entity per ore block (~497 per chunk, 1.8M in a 3.6k-chunk session at
 * ~150&nbsp;B each counting the chunk's block-entity map entry and the client's {@code BlockEntityInfo}).
 * Putting it on the block <em>state</em> instead removes the block entity entirely, and it is the only
 * thing that entity carried.
 *
 * <p>The ids are exactly the ones the block entity wrote before, so a world generated by an older build
 * keeps its meaning if a migration is ever added; {@link #id()} is what goes into the ore block's
 * {@code stone} property.
 */
public enum OreHostStone implements StringRepresentable {
    // --- vanilla hosts (the ids OreBlockEntity used) ---
    STONE("stone"),
    GRANITE("granite"),
    DIORITE("diorite"),
    ANDESITE("andesite"),
    DEEPSLATE("deepslate"),
    TUFF("tuff"),
    NETHERRACK("netherrack"),
    END_STONE("end_stone"),
    /** Bedrock-background ores are unbreakable and drop nothing (GT6 bedrock deposits). */
    BEDROCK("bedrock"),
    // --- loose sediments: valid hosts for SMALL ores only (GT6 sand/gravel small ores) ---
    SAND("sand"),
    RED_SAND("red_sand"),
    GRAVEL("gravel"),
    // --- GT6's own rocks (StoneType.registryId(), e.g. stone_basalt) ---
    GRANITE_BLACK("stone_granite_black"),
    GRANITE_RED("stone_granite_red"),
    BASALT("stone_basalt"),
    MARBLE("stone_marble"),
    LIMESTONE("stone_limestone"),
    GT_GRANITE("stone_granite"),
    GT_DIORITE("stone_diorite"),
    GT_ANDESITE("stone_andesite"),
    KOMATIITE("stone_komatiite"),
    GREENSCHIST("stone_greenschist"),
    BLUESCHIST("stone_blueschist"),
    KIMBERLITE("stone_kimberlite"),
    QUARTZITE("stone_quartzite"),
    PRISMARINE_LIGHT("stone_prismarine_light"),
    PRISMARINE_DARK("stone_prismarine_dark"),
    SLATE("stone_slate"),
    SHALE("stone_shale"),
    CHALK("stone_chalk"),
    DOLOMITE("stone_dolomite"),
    GABBRO("stone_gabbro"),
    GNEISS("stone_gneiss"),
    GYPSUM("stone_gypsum"),
    OILSHALE("stone_oilshale"),
    RHYOLITE("stone_rhyolite"),
    SALT("stone_salt"),
    SYLVITE("stone_sylvite"),
    TALC("stone_talc");

    /** {@code id -> value}, for parsing an id (an old block entity's tag, a block state property value). */
    private static final Map<String, OreHostStone> BY_ID = new LinkedHashMap<>();

    static {
        for (OreHostStone stone : values()) {
            BY_ID.put(stone.id, stone);
        }
    }

    private final String id;

    OreHostStone(String id) {
        this.id = id;
    }

    /** The canonical host-stone id, identical to what {@code OreBlockEntity.TAG_STONE} used to hold. */
    public String id() {
        return id;
    }

    /** Bedrock-backed ores (GT6 bedrock deposits): unbreakable, no drops. */
    public boolean isBedrock() {
        return this == BEDROCK;
    }

    /** Loose sediments — a host for small ores only (GT6 sand/gravel small ores). */
    public boolean isSediment() {
        return this == SAND || this == RED_SAND || this == GRAVEL;
    }

    @Override
    public String getSerializedName() {
        return id;
    }

    /** The host of a GT6 {@link StoneType}, by its registry id ({@code stone_basalt} → {@link #BASALT}). */
    public static OreHostStone of(StoneType type) {
        OreHostStone stone = BY_ID.get(type.registryId());
        return stone == null ? STONE : stone;
    }

    /** Parse an id; unknown ids (other mods' stones, leftovers) fall back to {@link #STONE}. */
    public static OreHostStone byId(String id) {
        if (id == null || id.isEmpty()) {
            return STONE;
        }
        OreHostStone stone = BY_ID.get(id);
        return stone == null ? STONE : stone;
    }
}
