package com.gregtech.gregtech.worldgen;

import java.util.ArrayList;
import java.util.List;

/**
 * GT6 stone layer + contact ore tables from {@code Loader_Worldgen} (the source of
 * the worldgenerationnew.cfg stonelayers/doublelayers sections). Layer order matters:
 * {@link GTCellNoise} indexes into {@link #LAYERS}.
 *
 * <p>GENERATED by tools/transpile_gt6_stonelayers.py — do not edit by hand.</p>
 */
public final class GTStoneLayersGen {
    /** Per-block ore roll inside a layer: probability = 1/chanceDiv, within [minY,maxY] (old coords). */
    public record OreDef(String material, boolean indicators, int chanceDiv, int minY, int maxY) {}

    /**
     * stoneType = StoneType enum name, or null. blockId = registry id of a whole-block
     * ore seam (GT6 BlockRockOres), or null. Both null = vanilla stone layer.
     * noDeep layers keep the host below the deep threshold (GT6 turned them to slate).
     */
    public record LayerDef(String stoneType, String blockId, String material, boolean noDeep, List<OreDef> ores) {}

    public record ContactDef(boolean bothSides, String materialA, String materialB, List<OreDef> ores) {}

    public static final List<LayerDef> LAYERS = new ArrayList<>();
    public static final List<ContactDef> CONTACTS = new ArrayList<>();

    private GTStoneLayersGen() {}

    private static OreDef ore(String material, boolean indicators, int chanceDiv, int minY, int maxY) {
        return new OreDef(material, indicators, chanceDiv, minY, maxY);
    }

    private static void layer(String stoneType, String blockId, String material, boolean noDeep, OreDef... ores) {
        LAYERS.add(new LayerDef(stoneType, blockId, material, noDeep, List.of(ores)));
    }

    private static void contact(boolean bothSides, String a, String b, OreDef... ores) {
        CONTACTS.add(new ContactDef(bothSides, a, b, List.of(ores)));
    }

    static {
        layer(null, "block_ore_anthracite", "Coal", true);
        layer(null, "block_ore_lignite", "Lignite", true);
        layer(null, "block_ore_salt", "NaCl", true);
        layer(null, "block_ore_rocksalt", "KCl", true);
        layer(null, "block_ore_bauxite", "Bauxite", true);
        layer(null, "block_ore_oil", "Oilshale", true);
        layer(null, "block_ore_gypsum", "Gypsum", true);
        layer(null, "block_ore_milkyquartz", "MilkyQuartz", true);
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false);
        layer(null, null, "Chert", false);
        layer(null, null, "Chert", false);
        layer(null, null, "Chert", false);
        layer(null, null, "Pumice", false);
        layer(null, null, "Eclogite", false);
        layer(null, null, "Greywacke", false);
        layer(null, null, "Migmatite", false);
        layer(null, null, "Stone", false, ore("Peridot", true, 64, 32, 64));
        layer(null, null, "Dacite", false);
        layer(null, null, "Dacite", false, ore("Nikolite", true, 32, 0, 20));
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false);
        layer(null, null, "Stone", false, ore("Emerald", false, 48, 16, 60), ore("Diamond", false, 128, 8, 24), ore("Lapis", false, 48, 16, 48), ore("Redstone", false, 32, 8, 24), ore("Cinnabar", false, 128, 8, 24), ore("Au", false, 64, 8, 32), ore("Au", false, 32, 33, 64), ore("Cu", false, 16, 20, 50), ore("Fe", false, 16, 40, 80), ore("Coal", false, 8, 60, 100), ore("Stone", false, 48, 0, 255), ore("NaCl", false, 32, 50, 80));
        layer(null, null, "Stone", false, ore("Fe2O3", true, 6, 30, 70), ore("Jasper", true, 64, 32, 64), ore("JasperBlue", true, 64, 32, 64), ore("JasperGreen", true, 64, 32, 64), ore("JasperYellow", true, 64, 32, 64), ore("JasperRainforest", true, 64, 32, 64), ore("JasperOcean", true, 64, 32, 64), ore("TigerEyeYellow", true, 64, 32, 64), ore("TigerEyeGreen", true, 64, 32, 64), ore("TigerEyeRed", true, 64, 32, 64), ore("TigerEyeBlue", true, 64, 32, 64), ore("TigerEyeBlack", true, 64, 32, 64), ore("TigerIron", true, 64, 32, 64));
        layer(null, null, "Stone", false);
        layer("GABBRO", null, "Gabbro", false);
        layer("GABBRO", null, "Gabbro", false);
        layer("GABBRO", null, "Gabbro", false);
        layer("KOMATIITE", null, "Komatiite", false);
        layer("KOMATIITE", null, "Komatiite", false, ore("MgCO3", true, 16, 20, 50), ore("Cinnabar", true, 12, 0, 32), ore("Redstone", true, 8, 0, 30), ore("Pyrite", true, 12, 0, 30));
        layer("KIMBERLITE", null, "Kimberlite", false);
        layer("KIMBERLITE", null, "Kimberlite", false, ore("Diamond", true, 48, 0, 12), ore("Spinel", true, 48, 24, 48), ore("BalasRuby", true, 48, 24, 48));
        layer("BASALT", null, "Basalt", false);
        layer("BASALT", null, "Basalt", false);
        layer("BASALT", null, "Basalt", false);
        layer("BASALT", null, "Basalt", false);
        layer("BASALT", null, "Basalt", false);
        layer("BASALT", null, "Basalt", false);
        layer("BASALT", null, "Basalt", false, ore("Asbestos", true, 16, 16, 48), ore("FluoriteWhite", true, 16, 0, 48), ore("S", true, 8, 0, 32));
        layer("BASALT", null, "Basalt", false, ore("Bastnasite", true, 24, 24, 32), ore("Monazite", true, 32, 24, 32), ore("MnO2", true, 8, 16, 48));
        layer("BASALT", null, "Basalt", false, ore("Peridot", true, 32, 0, 32), ore("Uvarovite", true, 32, 8, 40), ore("Grossular", true, 32, 16, 48), ore("Chromite", true, 8, 32, 64));
        layer("RHYOLITE", null, "Rhyolite", false);
        layer("RHYOLITE", null, "Rhyolite", false);
        layer("RHYOLITE", null, "Rhyolite", false);
        layer("RHYOLITE", null, "Rhyolite", false);
        layer("ANDESITE", null, "Andesite", false);
        layer("ANDESITE", null, "Andesite", false);
        layer("ANDESITE", null, "Andesite", false, ore("Bromargyrite", true, 8, 0, 32));
        layer("ANDESITE", null, "Andesite", false, ore("Au", true, 12, 0, 32), ore("Au", true, 8, 33, 64));
        layer("TALC", null, "Talc", false);
        layer("CHALK", null, "Chalk", false);
        layer("CHALK", null, "Chalk", false);
        layer("MARBLE", null, "Marble", false);
        layer("MARBLE", null, "Marble", false);
        layer("MARBLE", null, "Marble", false);
        layer("MARBLE", null, "Marble", false);
        layer("MARBLE", null, "Marble", false);
        layer("MARBLE", null, "Marble", false);
        layer("MARBLE", null, "Marble", false, ore("Cassiterite", true, 16, 20, 80), ore("Dioptase", true, 64, 24, 48));
        layer("MARBLE", null, "Marble", false, ore("Cassiterite", true, 16, 20, 80), ore("Stannite", true, 16, 38, 82), ore("Kesterite", true, 16, 38, 82), ore("Sphalerite", true, 8, 10, 30), ore("Chalcopyrite", true, 8, 0, 20), ore("Pyrite", true, 12, 0, 30));
        layer("DOLOMITE", null, "Dolomite", false);
        layer("DOLOMITE", null, "Dolomite", false);
        layer("DOLOMITE", null, "Dolomite", false, ore("Bone", true, 8, 30, 60));
        layer("LIMESTONE", null, "Limestone", false);
        layer("LIMESTONE", null, "Limestone", false);
        layer("LIMESTONE", null, "Limestone", false);
        layer("LIMESTONE", null, "Limestone", false);
        layer("LIMESTONE", null, "Limestone", false, ore("NaCl", true, 8, 40, 80));
        layer("LIMESTONE", null, "Limestone", false, ore("Stibnite", true, 24, 10, 30), ore("Galena", true, 8, 30, 120), ore("Pb", true, 16, 50, 70));
        layer("LIMESTONE", null, "Limestone", false, ore("Pyrite", true, 16, 0, 30), ore("Arsenopyrite", true, 16, 0, 20), ore("Galena", true, 8, 5, 25), ore("Galena", true, 8, 80, 120), ore("Wulfenite", true, 32, 30, 45), ore("Powellite", true, 32, 35, 50), ore("Molybdenite", true, 128, 30, 50), ore("Tetrahedrite", true, 8, 40, 80), ore("Cu", true, 16, 40, 80));
        layer("LIMESTONE", null, "Limestone", false, ore("Scheelite", true, 64, 0, 16), ore("Wolframite", true, 64, 0, 16), ore("Ferberite", true, 64, 0, 16), ore("Huebnerite", true, 64, 0, 16), ore("Tungstate", true, 64, 0, 16), ore("YellowLimonite", true, 8, 16, 48), ore("BrownLimonite", true, 8, 32, 64), ore("Malachite", true, 12, 16, 64), ore("Azurite", true, 24, 16, 64));
        layer("GRANITE_BLACK", null, "GraniteBlack", false);
        layer("GRANITE_BLACK", null, "GraniteBlack", false);
        layer("GRANITE_BLACK", null, "GraniteBlack", false, ore("Cooperite", true, 32, 0, 16), ore("Sperrylite", true, 32, 0, 16), ore("Ir", true, 64, 0, 8), ore("Emerald", true, 64, 24, 48), ore("Aquamarine", true, 64, 8, 32), ore("Morganite", true, 64, 24, 48), ore("Heliodor", true, 64, 24, 48), ore("Goshenite", true, 64, 24, 48), ore("Bixbite", true, 64, 24, 48), ore("Maxixe", true, 64, 24, 48));
        layer("GRANITE_RED", null, "GraniteRed", false);
        layer("GRANITE_RED", null, "GraniteRed", false);
        layer("GRANITE_RED", null, "GraniteRed", false, ore("Pitchblende", true, 32, 0, 18), ore("Uraninite", true, 32, 0, 16));
        layer("GRANITE", null, "S", true);
        layer("GRANITE", null, "KNO3", true);
        layer("GRANITE", null, "Lignite", true);
        layer("GRANITE", null, "Granite", false, ore("BlueTopaz", true, 64, 8, 32), ore("Topaz", true, 64, 24, 48));
        layer("GRANITE", null, "Granite", false, ore("Apatite", true, 8, 32, 64), ore("PO4", true, 24, 36, 60), ore("Phosphorite", true, 24, 40, 56), ore("PhosphorusRed", true, 24, 44, 52));
        layer("DIORITE", null, "Diorite", false);
        layer("DIORITE", null, "Diorite", false);
        layer("DIORITE", null, "Diorite", false);
        layer("DIORITE", null, "Diorite", false, ore("Sapphire", true, 64, 24, 48), ore("GreenSapphire", true, 64, 24, 48), ore("YellowSapphire", true, 64, 24, 48), ore("OrangeSapphire", true, 64, 24, 48), ore("BlueSapphire", true, 64, 8, 32), ore("PurpleSapphire", true, 64, 24, 48), ore("Ruby", true, 64, 24, 48));
        layer("DIORITE", null, "Diorite", false, ore("Garnierite", true, 8, 16, 48), ore("Pentlandite", true, 8, 24, 56), ore("Cobaltite", true, 8, 32, 64), ore("Craponite", true, 64, 24, 48), ore("Amethyst", true, 64, 24, 48));
        layer("GNEISS", null, "Gneiss", false);
        layer("GNEISS", null, "Gneiss", false);
        layer("GNEISS", null, "Gneiss", false);
        layer("GNEISS", null, "Gneiss", false, ore("Graphite", true, 8, 0, 64), ore("Asbestos", true, 8, 0, 48));
        layer(null, null, "Pinkschist", false);
        layer(null, null, "Grayschist", false);
        layer("GREENSCHIST", null, "Greenschist", false);
        layer("GREENSCHIST", null, "Greenschist", false);
        layer(null, null, "Stone", false, ore("Andradite", true, 32, 8, 40), ore("Almandine", true, 32, 16, 48));
        layer("BLUESCHIST", null, "Blueschist", false);
        layer("BLUESCHIST", null, "Blueschist", false);
        layer(null, null, "Stone", false, ore("Spessartine", true, 32, 8, 40), ore("Pyrope", true, 32, 16, 48));
        layer("SHALE", null, "Shale", false);
        layer("SHALE", null, "Shale", false);
        layer("SHALE", null, "Shale", false);
        layer("SHALE", null, "Shale", false);
        layer("SHALE", null, "Shale", false);
        layer("SHALE", null, "Shale", false);
        layer("SLATE", null, "Slate", false);
        layer("SLATE", null, "Slate", false);
        layer("SLATE", null, "Slate", false);
        layer("SLATE", null, "Slate", false);
        layer("SLATE", null, "Slate", false);
        layer("SLATE", null, "Slate", false);
        layer("SLATE", null, "Slate", false);
        layer("SLATE", null, "Slate", false);
        layer("SLATE", null, "Slate", false);
        layer("SLATE", null, "Slate", false);
        layer("QUARTZITE", null, "RedSand", false, ore("Niter", true, 6, 40, 70));
        layer("QUARTZITE", null, "Sand", false, ore("Niter", true, 6, 40, 70));
        layer("QUARTZITE", null, "Sand", false, ore("Niter", true, 6, 40, 70));
        layer("QUARTZITE", null, "Siltstone", false);
        layer("QUARTZITE", null, "Siltstone", false);
        layer("QUARTZITE", null, "Quartzite", false);
        layer("QUARTZITE", null, "Quartzite", false);
        layer("QUARTZITE", null, "Quartzite", false, ore("CertusQuartz", true, 16, 16, 48), ore("Barite", true, 32, 0, 32));

        contact(true, "Coal", "Stone", ore("Amber", true, 4, 30, 70), ore("Amber", true, 8, 30, 70), ore("AmberDominican", true, 8, 30, 70));
        contact(true, "Lignite", "Stone", ore("Amber", true, 4, 30, 70), ore("Amber", true, 8, 30, 70), ore("AmberDominican", true, 8, 30, 70));
        contact(true, "Oilshale", "Stone", ore("Amber", true, 4, 30, 70), ore("Amber", true, 8, 30, 70), ore("AmberDominican", true, 8, 30, 70));
        contact(true, "Komatiite", "Basalt", ore("Perlite", true, 4, 0, 16));
        contact(true, "Gabbro", "Basalt", ore("Perlite", true, 4, 0, 16));
        contact(true, "Limestone", "Basalt", ore("Ilmenite", true, 8, 0, 32), ore("TiO2", true, 12, 0, 32));
        contact(false, "Dolomite", "Diorite", ore("Opal", true, 64, 48, 64), ore("Diatomite", true, 16, 16, 64));
        contact(true, "Dolomite", "KCl", ore("KIO3", true, 12, 32, 64));
        contact(true, "Dolomite", "Quartzite", ore("Kyanite", true, 16, 32, 72), ore("Lepidolite", true, 32, 16, 48), ore("Spodumene", true, 32, 32, 64));
        contact(true, "Talc", "NaCl", ore("Borax", true, 8, 16, 48));
        contact(true, "Chalk", "Quartzite", ore("Asbestos", true, 4, 0, 48), ore("Talc", true, 4, 0, 80), ore("Glauconite", true, 4, 32, 80));
        contact(true, "Rhyolite", "Quartzite", ore("Alunite", true, 4, 32, 80));
        contact(true, "Gneiss", "Gypsum", ore("Mirabilite", true, 8, 16, 64), ore("Trona", true, 8, 16, 64));
        contact(true, "Granite", "NaCl", ore("Zeolite", true, 8, 16, 48));
        contact(true, "Granite", "KCl", ore("Pollucite", true, 8, 16, 48));
        contact(true, "GraniteRed", "Gneiss", ore("Vermiculite", true, 8, 48, 80), ore("Asbestos", true, 64, 16, 48));
        contact(true, "GraniteBlack", "Gneiss", ore("Mica", true, 8, 16, 48), ore("Biotite", true, 16, 16, 48));
        contact(true, "GraniteBlack", "Marble", ore("Lapis", true, 8, 0, 48), ore("Sodalite", true, 16, 0, 48), ore("Lazurite", true, 16, 0, 48), ore("Pyrite", true, 16, 0, 48));
        contact(false, "GraniteBlack", "Basalt", ore("Diamond", true, 64, 0, 32), ore("DiamondPink", true, 32, 0, 32), ore("Graphite", true, 8, 0, 32));
        contact(true, "GraniteBlack", "Granite", ore("Zircon", true, 24, 0, 32));
        contact(true, "GraniteBlack", "GraniteRed", ore("Zircon", true, 24, 0, 32));
    }
}
