package com.gregtech.gregtech.api.machine;
import com.gregtech.gregtech.api.material.GTMaterial;
import java.util.*;
/** Original GTMachines burning-box catalog; shared identities, material tints and ratings. */
public final class BurningBoxDefinitions {
 private BurningBoxDefinitions(){}
 public record Entry(BurningBoxFuelType fuelType,MachineSpec spec){}
 private static final List<Entry> ALL=create();
 private static List<Entry> create(){var values=new ArrayList<Entry>();
  values.add(entry("burning_box_solid_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Bronze,BurningBoxFuelType.SOLID,7500,24,7.0F,7.0F));
  values.add(entry("burning_box_solid_lead",com.gregtech.gregtech.content.material.generated.ElementMaterials.Lead,BurningBoxFuelType.SOLID,5000,16,4.0F,4.0F));
  values.add(entry("burning_box_solid_bismuth",com.gregtech.gregtech.content.material.generated.ElementMaterials.Bismuth,BurningBoxFuelType.SOLID,4500,20,4.0F,4.0F));
  values.add(entry("burning_box_solid_arsenic_copper",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicCopper,BurningBoxFuelType.SOLID,8000,24,7.0F,7.0F));
  values.add(entry("burning_box_solid_arsenic_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicBronze,BurningBoxFuelType.SOLID,9000,28,7.0F,7.0F));
  values.add(entry("burning_box_solid_invar",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Invar,BurningBoxFuelType.SOLID,10000,16,4.0F,4.0F));
  values.add(entry("burning_box_solid_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Steel,BurningBoxFuelType.SOLID,7000,32,6.0F,6.0F));
  values.add(entry("burning_box_solid_chromium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Chromium,BurningBoxFuelType.SOLID,8500,112,4.0F,4.0F));
  values.add(entry("burning_box_solid_titanium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Titanium,BurningBoxFuelType.SOLID,8500,96,9.0F,9.0F));
  values.add(entry("burning_box_solid_netherite",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Netherite,BurningBoxFuelType.SOLID,9000,96,9.0F,9.0F));
  values.add(entry("burning_box_solid_tungsten",com.gregtech.gregtech.content.material.generated.ElementMaterials.Tungsten,BurningBoxFuelType.SOLID,10000,128,10.0F,10.0F));
  values.add(entry("burning_box_solid_tungsten_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Tungstensteel,BurningBoxFuelType.SOLID,9000,128,12.5F,12.5F));
  values.add(entry("burning_box_solid_ta4hfc5",com.gregtech.gregtech.content.material.generated.CompoundMaterials.TantalumHafniumCarbide,BurningBoxFuelType.SOLID,10000,256,12.5F,12.5F));
  values.add(entry("burning_box_solid_ultimet",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Ultimet,BurningBoxFuelType.SOLID,9000,256,12.5F,12.5F));
  values.add(entry("burning_box_solid_dense_lead",com.gregtech.gregtech.content.material.generated.ElementMaterials.Lead,BurningBoxFuelType.SOLID,5000,64,4.0F,4.0F));
  values.add(entry("burning_box_solid_dense_bismuth",com.gregtech.gregtech.content.material.generated.ElementMaterials.Bismuth,BurningBoxFuelType.SOLID,4500,80,4.0F,4.0F));
  values.add(entry("burning_box_solid_dense_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Bronze,BurningBoxFuelType.SOLID,7500,96,7.0F,7.0F));
  values.add(entry("burning_box_solid_dense_arsenic_copper",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicCopper,BurningBoxFuelType.SOLID,8000,96,7.0F,7.0F));
  values.add(entry("burning_box_solid_dense_arsenic_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicBronze,BurningBoxFuelType.SOLID,9000,112,7.0F,7.0F));
  values.add(entry("burning_box_solid_dense_invar",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Invar,BurningBoxFuelType.SOLID,10000,64,4.0F,4.0F));
  values.add(entry("burning_box_solid_dense_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Steel,BurningBoxFuelType.SOLID,7000,128,6.0F,6.0F));
  values.add(entry("burning_box_solid_dense_chromium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Chromium,BurningBoxFuelType.SOLID,8500,448,4.0F,4.0F));
  values.add(entry("burning_box_solid_dense_titanium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Titanium,BurningBoxFuelType.SOLID,8500,384,9.0F,9.0F));
  values.add(entry("burning_box_solid_dense_netherite",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Netherite,BurningBoxFuelType.SOLID,9000,384,9.0F,9.0F));
  values.add(entry("burning_box_solid_dense_tungsten",com.gregtech.gregtech.content.material.generated.ElementMaterials.Tungsten,BurningBoxFuelType.SOLID,10000,512,10.0F,10.0F));
  values.add(entry("burning_box_solid_dense_tungsten_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Tungstensteel,BurningBoxFuelType.SOLID,9000,512,12.5F,12.5F));
  values.add(entry("burning_box_solid_dense_ta4hfc5",com.gregtech.gregtech.content.material.generated.CompoundMaterials.TantalumHafniumCarbide,BurningBoxFuelType.SOLID,10000,1024,12.5F,12.5F));
  values.add(entry("burning_box_solid_dense_ultimet",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Ultimet,BurningBoxFuelType.SOLID,9000,1024,12.5F,12.5F));
  values.add(entry("burning_box_liquid_lead",com.gregtech.gregtech.content.material.generated.ElementMaterials.Lead,BurningBoxFuelType.LIQUID,5000,16,4.0F,4.0F));
  values.add(entry("burning_box_liquid_bismuth",com.gregtech.gregtech.content.material.generated.ElementMaterials.Bismuth,BurningBoxFuelType.LIQUID,4500,20,4.0F,4.0F));
  values.add(entry("burning_box_liquid_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Bronze,BurningBoxFuelType.LIQUID,7500,24,7.0F,7.0F));
  values.add(entry("burning_box_liquid_arsenic_copper",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicCopper,BurningBoxFuelType.LIQUID,8000,24,7.0F,7.0F));
  values.add(entry("burning_box_liquid_arsenic_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicBronze,BurningBoxFuelType.LIQUID,9000,28,7.0F,7.0F));
  values.add(entry("burning_box_liquid_invar",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Invar,BurningBoxFuelType.LIQUID,10000,16,4.0F,4.0F));
  values.add(entry("burning_box_liquid_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Steel,BurningBoxFuelType.LIQUID,7000,32,6.0F,6.0F));
  values.add(entry("burning_box_liquid_chromium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Chromium,BurningBoxFuelType.LIQUID,8500,112,4.0F,4.0F));
  values.add(entry("burning_box_liquid_titanium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Titanium,BurningBoxFuelType.LIQUID,8500,96,9.0F,9.0F));
  values.add(entry("burning_box_liquid_netherite",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Netherite,BurningBoxFuelType.LIQUID,9000,96,9.0F,9.0F));
  values.add(entry("burning_box_liquid_tungsten",com.gregtech.gregtech.content.material.generated.ElementMaterials.Tungsten,BurningBoxFuelType.LIQUID,10000,128,10.0F,10.0F));
  values.add(entry("burning_box_liquid_tungsten_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Tungstensteel,BurningBoxFuelType.LIQUID,9000,128,12.5F,12.5F));
  values.add(entry("burning_box_liquid_ta4hfc5",com.gregtech.gregtech.content.material.generated.CompoundMaterials.TantalumHafniumCarbide,BurningBoxFuelType.LIQUID,10000,256,12.5F,12.5F));
  values.add(entry("burning_box_liquid_ultimet",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Ultimet,BurningBoxFuelType.LIQUID,9000,256,12.5F,12.5F));
  values.add(entry("burning_box_gas_lead",com.gregtech.gregtech.content.material.generated.ElementMaterials.Lead,BurningBoxFuelType.GAS,5000,16,4.0F,4.0F));
  values.add(entry("burning_box_gas_bismuth",com.gregtech.gregtech.content.material.generated.ElementMaterials.Bismuth,BurningBoxFuelType.GAS,4500,20,4.0F,4.0F));
  values.add(entry("burning_box_gas_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Bronze,BurningBoxFuelType.GAS,7500,24,7.0F,7.0F));
  values.add(entry("burning_box_gas_arsenic_copper",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicCopper,BurningBoxFuelType.GAS,8000,24,7.0F,7.0F));
  values.add(entry("burning_box_gas_arsenic_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicBronze,BurningBoxFuelType.GAS,9000,28,7.0F,7.0F));
  values.add(entry("burning_box_gas_invar",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Invar,BurningBoxFuelType.GAS,10000,16,4.0F,4.0F));
  values.add(entry("burning_box_gas_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Steel,BurningBoxFuelType.GAS,7000,32,6.0F,6.0F));
  values.add(entry("burning_box_gas_chromium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Chromium,BurningBoxFuelType.GAS,8500,112,4.0F,4.0F));
  values.add(entry("burning_box_gas_titanium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Titanium,BurningBoxFuelType.GAS,8500,96,9.0F,9.0F));
  values.add(entry("burning_box_gas_netherite",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Netherite,BurningBoxFuelType.GAS,9000,96,9.0F,9.0F));
  values.add(entry("burning_box_gas_tungsten",com.gregtech.gregtech.content.material.generated.ElementMaterials.Tungsten,BurningBoxFuelType.GAS,10000,128,10.0F,10.0F));
  values.add(entry("burning_box_gas_tungsten_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Tungstensteel,BurningBoxFuelType.GAS,9000,128,12.5F,12.5F));
  values.add(entry("burning_box_gas_ta4hfc5",com.gregtech.gregtech.content.material.generated.CompoundMaterials.TantalumHafniumCarbide,BurningBoxFuelType.GAS,10000,256,12.5F,12.5F));
  values.add(entry("burning_box_gas_ultimet",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Ultimet,BurningBoxFuelType.GAS,9000,256,12.5F,12.5F));
  values.add(entry("burning_box_fluidbed_lead",com.gregtech.gregtech.content.material.generated.ElementMaterials.Lead,BurningBoxFuelType.FLUIDIZED_BED,5000,16,4.0F,4.0F));
  values.add(entry("burning_box_fluidbed_bismuth",com.gregtech.gregtech.content.material.generated.ElementMaterials.Bismuth,BurningBoxFuelType.FLUIDIZED_BED,4500,20,4.0F,4.0F));
  values.add(entry("burning_box_fluidbed_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Bronze,BurningBoxFuelType.FLUIDIZED_BED,7500,24,7.0F,7.0F));
  values.add(entry("burning_box_fluidbed_arsenic_copper",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicCopper,BurningBoxFuelType.FLUIDIZED_BED,8000,24,7.0F,7.0F));
  values.add(entry("burning_box_fluidbed_arsenic_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicBronze,BurningBoxFuelType.FLUIDIZED_BED,9000,28,7.0F,7.0F));
  values.add(entry("burning_box_fluidbed_invar",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Invar,BurningBoxFuelType.FLUIDIZED_BED,10000,16,4.0F,4.0F));
  values.add(entry("burning_box_fluidbed_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Steel,BurningBoxFuelType.FLUIDIZED_BED,7000,32,6.0F,6.0F));
  values.add(entry("burning_box_fluidbed_chromium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Chromium,BurningBoxFuelType.FLUIDIZED_BED,8500,112,4.0F,4.0F));
  values.add(entry("burning_box_fluidbed_titanium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Titanium,BurningBoxFuelType.FLUIDIZED_BED,8500,96,9.0F,9.0F));
  values.add(entry("burning_box_fluidbed_netherite",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Netherite,BurningBoxFuelType.FLUIDIZED_BED,9000,96,9.0F,9.0F));
  values.add(entry("burning_box_fluidbed_tungsten",com.gregtech.gregtech.content.material.generated.ElementMaterials.Tungsten,BurningBoxFuelType.FLUIDIZED_BED,10000,128,10.0F,10.0F));
  values.add(entry("burning_box_fluidbed_tungsten_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Tungstensteel,BurningBoxFuelType.FLUIDIZED_BED,9000,128,12.5F,12.5F));
  values.add(entry("burning_box_fluidbed_ta4hfc5",com.gregtech.gregtech.content.material.generated.CompoundMaterials.TantalumHafniumCarbide,BurningBoxFuelType.FLUIDIZED_BED,10000,256,12.5F,12.5F));
  values.add(entry("burning_box_fluidbed_ultimet",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Ultimet,BurningBoxFuelType.FLUIDIZED_BED,9000,256,12.5F,12.5F));
  values.add(entry("burning_box_liquid_dense_lead",com.gregtech.gregtech.content.material.generated.ElementMaterials.Lead,BurningBoxFuelType.LIQUID,5000,64,4.0F,4.0F));
  values.add(entry("burning_box_liquid_dense_bismuth",com.gregtech.gregtech.content.material.generated.ElementMaterials.Bismuth,BurningBoxFuelType.LIQUID,4500,80,4.0F,4.0F));
  values.add(entry("burning_box_liquid_dense_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Bronze,BurningBoxFuelType.LIQUID,7500,96,7.0F,7.0F));
  values.add(entry("burning_box_liquid_dense_arsenic_copper",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicCopper,BurningBoxFuelType.LIQUID,8000,96,7.0F,7.0F));
  values.add(entry("burning_box_liquid_dense_arsenic_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicBronze,BurningBoxFuelType.LIQUID,9000,112,7.0F,7.0F));
  values.add(entry("burning_box_liquid_dense_invar",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Invar,BurningBoxFuelType.LIQUID,10000,64,4.0F,4.0F));
  values.add(entry("burning_box_liquid_dense_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Steel,BurningBoxFuelType.LIQUID,7000,128,6.0F,6.0F));
  values.add(entry("burning_box_liquid_dense_chromium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Chromium,BurningBoxFuelType.LIQUID,8500,448,4.0F,4.0F));
  values.add(entry("burning_box_liquid_dense_titanium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Titanium,BurningBoxFuelType.LIQUID,8500,384,9.0F,9.0F));
  values.add(entry("burning_box_liquid_dense_netherite",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Netherite,BurningBoxFuelType.LIQUID,9000,384,9.0F,9.0F));
  values.add(entry("burning_box_liquid_dense_tungsten",com.gregtech.gregtech.content.material.generated.ElementMaterials.Tungsten,BurningBoxFuelType.LIQUID,10000,512,10.0F,10.0F));
  values.add(entry("burning_box_liquid_dense_tungsten_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Tungstensteel,BurningBoxFuelType.LIQUID,9000,512,12.5F,12.5F));
  values.add(entry("burning_box_liquid_dense_ta4hfc5",com.gregtech.gregtech.content.material.generated.CompoundMaterials.TantalumHafniumCarbide,BurningBoxFuelType.LIQUID,10000,1024,12.5F,12.5F));
  values.add(entry("burning_box_liquid_dense_ultimet",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Ultimet,BurningBoxFuelType.LIQUID,9000,1024,12.5F,12.5F));
  values.add(entry("burning_box_gas_dense_lead",com.gregtech.gregtech.content.material.generated.ElementMaterials.Lead,BurningBoxFuelType.GAS,5000,64,4.0F,4.0F));
  values.add(entry("burning_box_gas_dense_bismuth",com.gregtech.gregtech.content.material.generated.ElementMaterials.Bismuth,BurningBoxFuelType.GAS,4500,80,4.0F,4.0F));
  values.add(entry("burning_box_gas_dense_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Bronze,BurningBoxFuelType.GAS,7500,96,7.0F,7.0F));
  values.add(entry("burning_box_gas_dense_arsenic_copper",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicCopper,BurningBoxFuelType.GAS,8000,96,7.0F,7.0F));
  values.add(entry("burning_box_gas_dense_arsenic_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicBronze,BurningBoxFuelType.GAS,9000,112,7.0F,7.0F));
  values.add(entry("burning_box_gas_dense_invar",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Invar,BurningBoxFuelType.GAS,10000,64,4.0F,4.0F));
  values.add(entry("burning_box_gas_dense_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Steel,BurningBoxFuelType.GAS,7000,128,6.0F,6.0F));
  values.add(entry("burning_box_gas_dense_chromium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Chromium,BurningBoxFuelType.GAS,8500,448,4.0F,4.0F));
  values.add(entry("burning_box_gas_dense_titanium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Titanium,BurningBoxFuelType.GAS,8500,384,9.0F,9.0F));
  values.add(entry("burning_box_gas_dense_netherite",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Netherite,BurningBoxFuelType.GAS,9000,384,9.0F,9.0F));
  values.add(entry("burning_box_gas_dense_tungsten",com.gregtech.gregtech.content.material.generated.ElementMaterials.Tungsten,BurningBoxFuelType.GAS,10000,512,10.0F,10.0F));
  values.add(entry("burning_box_gas_dense_tungsten_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Tungstensteel,BurningBoxFuelType.GAS,9000,512,12.5F,12.5F));
  values.add(entry("burning_box_gas_dense_ta4hfc5",com.gregtech.gregtech.content.material.generated.CompoundMaterials.TantalumHafniumCarbide,BurningBoxFuelType.GAS,10000,1024,12.5F,12.5F));
  values.add(entry("burning_box_gas_dense_ultimet",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Ultimet,BurningBoxFuelType.GAS,9000,1024,12.5F,12.5F));
  values.add(entry("burning_box_fluidbed_dense_lead",com.gregtech.gregtech.content.material.generated.ElementMaterials.Lead,BurningBoxFuelType.FLUIDIZED_BED,5000,64,4.0F,4.0F));
  values.add(entry("burning_box_fluidbed_dense_bismuth",com.gregtech.gregtech.content.material.generated.ElementMaterials.Bismuth,BurningBoxFuelType.FLUIDIZED_BED,4500,80,4.0F,4.0F));
  values.add(entry("burning_box_fluidbed_dense_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Bronze,BurningBoxFuelType.FLUIDIZED_BED,7500,96,7.0F,7.0F));
  values.add(entry("burning_box_fluidbed_dense_arsenic_copper",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicCopper,BurningBoxFuelType.FLUIDIZED_BED,8000,96,7.0F,7.0F));
  values.add(entry("burning_box_fluidbed_dense_arsenic_bronze",com.gregtech.gregtech.content.material.generated.CompoundMaterials.ArsenicBronze,BurningBoxFuelType.FLUIDIZED_BED,9000,112,7.0F,7.0F));
  values.add(entry("burning_box_fluidbed_dense_invar",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Invar,BurningBoxFuelType.FLUIDIZED_BED,10000,64,4.0F,4.0F));
  values.add(entry("burning_box_fluidbed_dense_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Steel,BurningBoxFuelType.FLUIDIZED_BED,7000,128,6.0F,6.0F));
  values.add(entry("burning_box_fluidbed_dense_chromium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Chromium,BurningBoxFuelType.FLUIDIZED_BED,8500,448,4.0F,4.0F));
  values.add(entry("burning_box_fluidbed_dense_titanium",com.gregtech.gregtech.content.material.generated.ElementMaterials.Titanium,BurningBoxFuelType.FLUIDIZED_BED,8500,384,9.0F,9.0F));
  values.add(entry("burning_box_fluidbed_dense_netherite",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Netherite,BurningBoxFuelType.FLUIDIZED_BED,9000,384,9.0F,9.0F));
  values.add(entry("burning_box_fluidbed_dense_tungsten",com.gregtech.gregtech.content.material.generated.ElementMaterials.Tungsten,BurningBoxFuelType.FLUIDIZED_BED,10000,512,10.0F,10.0F));
  values.add(entry("burning_box_fluidbed_dense_tungsten_steel",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Tungstensteel,BurningBoxFuelType.FLUIDIZED_BED,9000,512,12.5F,12.5F));
  values.add(entry("burning_box_fluidbed_dense_ta4hfc5",com.gregtech.gregtech.content.material.generated.CompoundMaterials.TantalumHafniumCarbide,BurningBoxFuelType.FLUIDIZED_BED,10000,1024,12.5F,12.5F));
  values.add(entry("burning_box_fluidbed_dense_ultimet",com.gregtech.gregtech.content.material.generated.CompoundMaterials.Ultimet,BurningBoxFuelType.FLUIDIZED_BED,9000,1024,12.5F,12.5F));
  values.add(new Entry(BurningBoxFuelType.SOLID,InitialSmelteryDefinitions.brickBurningBox()));
  return List.copyOf(values);
 }
 private static Entry entry(String id,GTMaterial material,BurningBoxFuelType type,int efficiency,long output,float hardness,float resistance){
  String texture=switch(type){case SOLID->"burning_solid";case LIQUID->"burning_liquid";case GAS->"burning_gas";case FLUIDIZED_BED->"burning_fluidbed";};
  return new Entry(type,new MachineSpec(id,material.getLocalName(),material.getColor(),efficiency,output,texture,hardness,resistance));
 }
 public static List<Entry> all(){return ALL;}
 public static MachineSpec spec(String id){return ALL.stream().filter(e->e.spec().id().equals(id)).findFirst().orElseThrow(()->new IllegalArgumentException(id)).spec();}
}
