package com.gregtech.gregtech.api.machine;
import com.gregtech.gregtech.api.material.GTMaterialRegistry;import java.util.List;
/** Full original GTMachines hull specification, ceramic keeps its already shared identity. */
public final class OriginalCrucibleDefinitions{private OriginalCrucibleDefinitions(){}private static final class Catalog{
static final List<CrucibleSpec> ALL=List.of(InitialSmelteryDefinitions.ceramicCrucible(),
CrucibleSpec.of("smelting_crucible_stone", GTMaterialRegistry.get("Stone"), 1000, 5.0F, 5.0F, false, 1100, 3220, 2.65F,
                    CrucibleSpec.STONE_CRUCIBLE_HULL_UNITS),
CrucibleSpec.of("smelting_crucible_basalt", GTMaterialRegistry.get("Basalt"), 1001, 15.0F, 15.0F, false, 1100, 3220, 2.65F,
                    CrucibleSpec.STONE_CRUCIBLE_HULL_UNITS),
CrucibleSpec.of("smelting_crucible_granite_black", GTMaterialRegistry.get("GraniteBlack"), 1002, 15.0F, 15.0F, false, 1100, 3220, 2.65F,
                    CrucibleSpec.STONE_CRUCIBLE_HULL_UNITS),
CrucibleSpec.of("smelting_crucible_granite_red", GTMaterialRegistry.get("GraniteRed"), 1003, 15.0F, 15.0F, false, 1100, 3220, 2.65F,
                    CrucibleSpec.STONE_CRUCIBLE_HULL_UNITS),
CrucibleSpec.of("smelting_crucible_nether_brick", GTMaterialRegistry.get("NetherBrick"), 1004, 5.0F, 5.0F, false, 1100, 3220, 2.65F,
                    CrucibleSpec.STONE_CRUCIBLE_HULL_UNITS),
CrucibleSpec.of("smelting_crucible_umber", GTMaterialRegistry.get("Umber"), 1006, 5.0F, 5.0F, false, 1100, 3220, 2.65F,
                    CrucibleSpec.STONE_CRUCIBLE_HULL_UNITS),
CrucibleSpec.of("smelting_crucible_livingrock", GTMaterialRegistry.get("Livingrock"), 1007, 5.0F, 5.0F, false, 1100, 3220, 2.65F,
                    CrucibleSpec.STONE_CRUCIBLE_HULL_UNITS),
CrucibleSpec.of("smelting_crucible_holystone", GTMaterialRegistry.get("Holystone"), 1008, 5.0F, 5.0F, false, 1100, 3220, 2.65F,
                    CrucibleSpec.STONE_CRUCIBLE_HULL_UNITS),
CrucibleSpec.of("smelting_crucible_betweenstone", GTMaterialRegistry.get("Betweenstone"), 1009, 5.0F, 5.0F, false, 1100, 3220, 2.65F,
                    CrucibleSpec.STONE_CRUCIBLE_HULL_UNITS),
CrucibleSpec.of("smelting_crucible_quartz", GTMaterialRegistry.get("MilkyQuartz"), 1018, 5.0F, 5.0F, false, 1986, 3220, 2.2F,
                    CrucibleSpec.STONE_CRUCIBLE_HULL_UNITS),
CrucibleSpec.of("smelting_crucible_carbon", GTMaterialRegistry.get("Carbon"), 1019, 10.0F, 10.0F, false),
CrucibleSpec.of("smelting_crucible_bronze", GTMaterialRegistry.get("Bronze"), 1020, 7.0F, 7.0F, false, 1357, 2835, 8.96F),
CrucibleSpec.of("smelting_crucible_invar", GTMaterialRegistry.get("Invar"), 1021, 4.0F, 4.0F, false, 1700, 3000, 8.0F),
CrucibleSpec.of("smelting_crucible_steel", GTMaterialRegistry.get("Steel"), 1022, 6.0F, 6.0F, false, 2046, 3134, 7.85F),
CrucibleSpec.of("smelting_crucible_hsla", GTMaterialRegistry.get("HSLASteel"), 1041, 6.0F, 6.0F, false, 2046, 3134, 7.85F),
CrucibleSpec.of("smelting_crucible_titanium", GTMaterialRegistry.get("Titanium"), 1023, 9.0F, 9.0F, false),
CrucibleSpec.of("smelting_crucible_tungsten", GTMaterialRegistry.get("Tungsten"), 1024, 10.0F, 10.0F, true),
CrucibleSpec.of("smelting_crucible_stainless_steel", GTMaterialRegistry.get("StainlessSteel"), 1025, 6.0F, 6.0F, true, 2046, 3134, 8.0F),
CrucibleSpec.of("smelting_crucible_dark_iron", GTMaterialRegistry.get("DarkIron"), 1026, 6.0F, 6.0F, false, 1811, 3134, 7.87F),
CrucibleSpec.of("smelting_crucible_knightmetal", GTMaterialRegistry.get("Knightmetal"), 1027, 6.0F, 6.0F, false, 2046, 3134, 7.85F),
CrucibleSpec.of("smelting_crucible_fiery_steel", GTMaterialRegistry.get("FierySteel"), 1028, 6.0F, 6.0F, false, 2046, 3134, 7.85F),
CrucibleSpec.of("smelting_crucible_octine", GTMaterialRegistry.get("Octine"), 1042, 6.0F, 6.0F, false, 2046, 3134, 7.85F),
CrucibleSpec.of("smelting_crucible_thaumium", GTMaterialRegistry.get("Thaumium"), 1029, 6.0F, 6.0F, true, 2046, 3134, 7.85F),
CrucibleSpec.of("smelting_crucible_void_metal", GTMaterialRegistry.get("VoidMetal"), 1030, 10.0F, 10.0F, true, 2046, 3134, 7.85F),
CrucibleSpec.of("smelting_crucible_meteoric_iron", GTMaterialRegistry.get("MeteoricIron"), 1031, 6.0F, 6.0F, false, 2011, 3334, 7.87F),
CrucibleSpec.of("smelting_crucible_meteoric_steel", GTMaterialRegistry.get("MeteoricSteel"), 1032, 6.0F, 6.0F, false, 2246, 3334, 7.85F),
CrucibleSpec.of("smelting_crucible_chromium", GTMaterialRegistry.get("Chromium"), 1033, 9.0F, 9.0F, true),
CrucibleSpec.of("smelting_crucible_molybdenum", GTMaterialRegistry.get("Molybdenum"), 1034, 9.0F, 9.0F, false),
CrucibleSpec.of("smelting_crucible_niobium", GTMaterialRegistry.get("Niobium"), 1035, 9.0F, 9.0F, false),
CrucibleSpec.of("smelting_crucible_tantalum", GTMaterialRegistry.get("Tantalum"), 1036, 9.0F, 9.0F, false),
CrucibleSpec.of("smelting_crucible_osmium", GTMaterialRegistry.get("OsmiumElemental"), 1037, 9.0F, 9.0F, false),
CrucibleSpec.of("smelting_crucible_vanadium", GTMaterialRegistry.get("Vanadium"), 1038, 9.0F, 9.0F, false),
CrucibleSpec.of("smelting_crucible_iridium", GTMaterialRegistry.get("Iridium"), 1039, 9.0F, 9.0F, true),
CrucibleSpec.of("smelting_crucible_niobium_titanium", GTMaterialRegistry.get("NiobiumTitanium"), 1040, 9.0F, 9.0F, false),
CrucibleSpec.of("smelting_crucible_ta4hfc5", GTMaterialRegistry.get("TantalumHafniumCarbide"), 1043, 9.0F, 9.0F, false),
CrucibleSpec.of("smelting_crucible_netherite", GTMaterialRegistry.get("Netherite"), 1044, 6.0F, 6.0F, true, 2046, 3134, 8.0F),
CrucibleSpec.of("smelting_crucible_bedrock_hsla_alloy", GTMaterialRegistry.get("BedrockHSLAAlloy"), 1048, 100.0F, 100.0F, false),
CrucibleSpec.of("smelting_crucible_ad", GTMaterialRegistry.get("Adamantium"), 1049, 100.0F, 100.0F, true));}
public static List<CrucibleSpec> all(){return Catalog.ALL;}
public static CrucibleSpec get(String id){return all().stream().filter(s->s.id().equals(id)).findFirst().orElseThrow(()->new IllegalArgumentException(id));}}
