package com.gregtech.gregtech.data;

import java.util.List;
import java.util.Map;

/**
 * Crafting recipes for the multiblock machines and their structural parts, copied from the
 * original GregTech 6 {@code Loader_MultiTileEntities} Multiblock Machines and Logistics registrations.
 * <p>
 * GENERATED by {@code tools/generate_multiblock_recipe_table.py} - do not edit by hand.
 * Keys use the spec grammar of {@link BasicMachineCraftingRecipes} and are resolved by
 * {@link MachineRecipeIngredients}. Original 170xx/17996 controllers retain their GT6
 * ingredients; old axial aliases use one-item conversions from their 172xx controllers.
 * </p>
 */
public final class MultiblockCraftingRecipes {
    /** One craftable block: port id, GT6 name or legacy conversion, pattern and keys. */
    public record Entry(String blockId, String originalName, String pattern, Map<Character, String> keys) {
        public String[] rows() { return pattern.split("\\|", -1); }
    }

    public static final List<Entry> ENTRIES = List.of(
            new Entry("distillation_tower_main", "Distillation Tower", "PPP|PMP|PPP", Map.of('M', "item:gregtech:distillation_tower_part", 'P', "pipe:nonuple@StainlessSteel")),
            new Entry("cryo_distillation_main", "Cryo Distillation Tower", "PPP|PMP|PPP", Map.of('M', "item:gregtech:cryo_distillation_wall", 'P', "pipe:nonuple@Copper")),
            new Entry("fusion_reactor_main", "Fusion Reactor", "FFF|FMF|FFF", Map.of('F', "il:FIELD_GENERATORS", 'M', "item:gregtech:fusion_reactor_wall")),
            new Entry("largecentrifuge_tungsten_steel", "Large Centrifuge", "CMC|RCR", Map.of('C', "circuit:6", 'M', "item:gregtech:centrifuge_part", 'R', "item:gregtech:crystal_processor_ruby")),
            new Entry("largeelectrolyzer_stainless_steel", "Large Electrolyzer", "CMC|RCR", Map.of('C', "circuit:6", 'M', "item:gregtech:electrolyzer_part", 'R', "item:gregtech:crystal_processor_ruby")),
            new Entry("largecoagulator_stainless_steel", "Large Coagulator Array", "CRC|PMP|PPP", Map.of('C', "circuit:6", 'M', "item:gregtech:tank_wall", 'P', "mat:plateDense@StainlessSteel", 'R', "item:gregtech:crystal_processor_ruby")),
            new Entry("largeautoclave_stainless_steel", "Large Autoclave", "CRC|PMP|PPP", Map.of('C', "circuit:6", 'M', "item:gregtech:tank_wall_dense", 'P', "mat:plateDense@StainlessSteel", 'R', "item:gregtech:crystal_processor_ruby")),
            new Entry("largebath_stainless_steel", "Large Bathing Vat", "CRC|PMP|APA", Map.of('A', "item:gregtech:compact_robot_arm_mv", 'C', "circuit:6", 'M', "item:gregtech:tank_wall", 'P', "mat:plateDense@StainlessSteel", 'R', "item:gregtech:crystal_processor_ruby")),
            new Entry("largemixer_stainless_steel", "Large Batch Mixer", "PSP|PSP|RMC", Map.of('C', "circuit:6", 'M', "item:gregtech:tank_wall", 'P', "mat:plateDense@StainlessSteel", 'R', "item:gregtech:crystal_processor_ruby", 'S', "mat:stickLong@StainlessSteel")),
            new Entry("largefermenter_stainless_steel", "Large Fermenter", "PPP|CRC|PMP", Map.of('C', "circuit:6", 'M', "item:gregtech:tank_wall", 'P', "mat:plateDense@StainlessSteel", 'R', "item:gregtech:crystal_processor_ruby")),
            new Entry("largeoven_invar", "Large Electric Oven", "PPP|PwP|RMC", Map.of('C', "circuit:6", 'M', "item:gregtech:invar_wall", 'P', "mat:plateDense@Invar", 'R', "item:gregtech:crystal_processor_ruby", 'w', "item:gregtech:tool_wrench")),
            new Entry("largesluice_titanium", "Large Sluice", "GGG|SwS|RMC", Map.of('C', "circuit:6", 'G', "mat:gearGt@Titanium", 'M', "item:gregtech:titanium_wall", 'R', "item:gregtech:crystal_processor_ruby", 'S', "mat:stick@Titanium", 'w', "item:gregtech:tool_wrench")),
            new Entry("largecrusher_tungsten_steel", "Large Crusher", "GSG|SGS|RMC", Map.of('C', "circuit:6", 'G', "mat:gearGt@Tungstensteel", 'M', "item:gregtech:tungstensteel_wall", 'R', "item:gregtech:crystal_processor_ruby", 'S', "mat:gearGtSmall@Tungstensteel")),
            new Entry("largeshredder_tungsten_steel", "Large Shredder", "SGS|GSG|RMC", Map.of('C', "circuit:6", 'G', "mat:gearGt@Tungstensteel", 'M', "item:gregtech:tungstensteel_wall", 'R', "item:gregtech:crystal_processor_ruby", 'S', "mat:gearGtSmall@Tungstensteel")),
            new Entry("largesqueezer_steel", "Large Squeezer", "GSG|GSG|RMC", Map.of('C', "circuit:6", 'G', "mat:gearGt@Steel", 'M', "item:gregtech:steel_wall", 'R', "item:gregtech:crystal_processor_ruby", 'S', "mat:gearGtSmall@Steel")),
            new Entry("largemassfab_lead", "Large Matter Fabricator", "FFF|FMF|FFF", Map.of('F', "il:FIELD_GENERATORS", 'M', "item:gregtech:dense_lead_wall")),
            new Entry("heat_exchanger_main", "Large Heat Exchanger", "DDD|PMP|DDD", Map.of('D', "mat:plateDense@AnnealedCopper", 'M', "item:gregtech:dense_tungsten_wall", 'P', "pipe:huge@Copper")),
            new Entry("bedrock_drill_main", "Bedrock Mining Drill Controller", "PYP|CMC|GIG", Map.of('C', "circuit:6", 'G', "mat:gearGt@Tungstensteel", 'I', "mat:toolHeadDrill@Tungstensteel", 'M', "item:gregtech:bedrock_drill_wall", 'P', "item:gregtech:crystal_processor_ruby", 'Y', "il:CONVEYERS")),
            new Entry("lightning_rod_main", "Lightning Rod Electric Output", "CWC|PMP|CWC", Map.of('C', "circuit:6", 'M', "item:gregtech:lightning_rod_wall", 'P', "item:gregtech:crystal_processor_sapphire", 'W', "wire:16@NiobiumTitanium")),
            new Entry("coke_oven_main", "Coke Oven", "hRT|PMR|dRT", Map.of('M', "item:gregtech:coke_oven_wall", 'P', "mat:plate@Iron", 'R', "mat:stick@Iron", 'T', "mat:screw@Iron", 'd', "item:gregtech:tool_screwdriver", 'h', "item:gregtech:tool_hammer")),
            new Entry("implosion_compressor_main", "Implosion Compressor", "CPC|PAP|RMR", Map.of('A', "il:ROBOT_ARMS", 'C', "circuit:6", 'M', "item:gregtech:implosion_compressor_wall", 'P', "mat:plateDense@Tungstensteel", 'R', "item:gregtech:crystal_processor_ruby")),
            new Entry("large_boiler_main", "Stainless Steel Boiler Main Barometer", "PPh|PMP|wPP", Map.of('M', "item:gregtech:boiler_wall", 'P', "mat:plateDense@StainlessSteel", 'h', "item:gregtech:tool_hammer", 'w', "item:gregtech:tool_wrench")),
            new Entry("large_crucible_main", "Large Stainless Steel Crucible", "hMy", Map.of('M', "item:gregtech:large_crucible_wall", 'h', "item:gregtech:tool_hammer", 'y', "item:gregtech:tool_chisel")),
            new Entry("wood_tank_main_valve", "Wood Tank Main Valve", " R |rMs| R ", Map.of('M', "item:gregtech:wood_wall", 'R', "mat:ring@Lead", 'r', "item:gregtech:tool_soft_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_stainless_steel_tank_main_valve", "Small Stainless Steel Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:tank_wall", 'R', "mat:ring@StainlessSteel", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_tungstensteel_tank_main_valve", "Small Tungstensteel Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:tungstensteel_wall", 'R', "mat:ring@Tungstensteel", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_tungsten_tank_main_valve", "Small Tungsten Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:tungsten_wall", 'R', "mat:ring@Tungsten", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_adamantium_tank_main_valve", "Small Adamantium Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:adamantium_wall", 'R', "mat:ring@Adamantium", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_titanium_tank_main_valve", "Small Titanium Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:titanium_wall", 'R', "mat:ring@Titanium", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_invar_tank_main_valve", "Small Invar Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:invar_wall", 'R', "mat:ring@Invar", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_dense_stainless_steel_tank_main_valve", "Small Dense Stainless Steel Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:tank_wall_dense", 'R', "mat:ring@StainlessSteel", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_dense_tungstensteel_tank_main_valve", "Small Dense Tungstensteel Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:implosion_compressor_wall", 'R', "mat:ring@Tungstensteel", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_dense_tungsten_tank_main_valve", "Small Dense Tungsten Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:dense_tungsten_wall", 'R', "mat:ring@Tungsten", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_dense_adamantium_tank_main_valve", "Small Dense Adamantium Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:dense_adamantium_wall", 'R', "mat:ring@Adamantium", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_dense_titanium_tank_main_valve", "Small Dense Titanium Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:dense_titanium_wall", 'R', "mat:ring@Titanium", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("small_dense_invar_tank_main_valve", "Small Dense Invar Tank Main Valve", " R |hMs| R ", Map.of('M', "item:gregtech:dense_invar_wall", 'R', "mat:ring@Invar", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_stainless_steel_tank_main_valve", "Large Stainless Steel Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_stainless_steel_tank_main_valve", 'P', "mat:plate@StainlessSteel", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_tungstensteel_tank_main_valve", "Large Tungstensteel Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_tungstensteel_tank_main_valve", 'P', "mat:plate@Tungstensteel", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_tungsten_tank_main_valve", "Large Tungsten Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_tungsten_tank_main_valve", 'P', "mat:plate@Tungsten", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_adamantium_tank_main_valve", "Large Adamantium Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_adamantium_tank_main_valve", 'P', "mat:plate@Adamantium", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_titanium_tank_main_valve", "Large Titanium Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_titanium_tank_main_valve", 'P', "mat:plate@Titanium", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_invar_tank_main_valve", "Large Invar Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_invar_tank_main_valve", 'P', "mat:plate@Invar", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_dense_stainless_steel_tank_main_valve", "Large Dense Stainless Steel Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_dense_stainless_steel_tank_main_valve", 'P', "mat:plateDense@StainlessSteel", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_dense_tungstensteel_tank_main_valve", "Large Dense Tungstensteel Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_dense_tungstensteel_tank_main_valve", 'P', "mat:plateDense@Tungstensteel", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_dense_tungsten_tank_main_valve", "Large Dense Tungsten Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_dense_tungsten_tank_main_valve", 'P', "mat:plateDense@Tungsten", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_dense_adamantium_tank_main_valve", "Large Dense Adamantium Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_dense_adamantium_tank_main_valve", 'P', "mat:plateDense@Adamantium", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_dense_titanium_tank_main_valve", "Large Dense Titanium Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_dense_titanium_tank_main_valve", 'P', "mat:plateDense@Titanium", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("large_dense_invar_tank_main_valve", "Large Dense Invar Tank Main Valve", "PPP|hMs|PPP", Map.of('M', "item:gregtech:small_dense_invar_tank_main_valve", 'P', "mat:plateDense@Invar", 'h', "item:gregtech:tool_hammer", 's', "item:gregtech:tool_saw")),
            new Entry("von_da_graagg_generator", "Von da Graagg Generator", "CSC|PMP|CEC", Map.of('C', "circuit:6", 'E', "item:minecraft:ender_eye", 'M', "block:casingMachine@SteelGalvanized", 'P', "item:gregtech:crystal_processor_ruby", 'S', "item:minecraft:nether_star")),
            new Entry("large_turbine_main", "Magnalium Steam Turbine Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:magnalium_steam_turbine_main_housing")),
            new Entry("large_steam_turbine_trinitanium", "Trinitanium Steam Turbine Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:trinitanium_steam_turbine_main_housing")),
            new Entry("large_steam_turbine_graphene", "Graphene Steam Turbine Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:graphene_steam_turbine_main_housing")),
            new Entry("large_steam_turbine_vibramantium", "Vibramantium Steam Turbine Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:vibramantium_steam_turbine_main_housing")),
            new Entry("large_dynamo_main", "Stainless Steel Dynamo Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:stainless_steel_dynamo_main_housing")),
            new Entry("large_dynamo_titanium", "Titanium Dynamo Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:titanium_dynamo_main_housing")),
            new Entry("large_dynamo_tungstensteel", "Tungstensteel Dynamo Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:tungstensteel_dynamo_main_housing")),
            new Entry("large_dynamo_adamantium", "Adamantium Dynamo Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:adamantium_dynamo_main_housing")),
            new Entry("large_gas_turbine_main", "Magnalium Gas Turbine Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:magnalium_gas_turbine_main_housing")),
            new Entry("large_gas_turbine_trinitanium", "Trinitanium Gas Turbine Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:trinitanium_gas_turbine_main_housing")),
            new Entry("large_gas_turbine_graphene", "Graphene Gas Turbine Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:graphene_gas_turbine_main_housing")),
            new Entry("large_gas_turbine_vibramantium", "Vibramantium Gas Turbine Main Housing (legacy conversion)", "M", Map.of('M', "item:gregtech:vibramantium_gas_turbine_main_housing")),
            new Entry("lightning_rod_electric_output", "Lightning Rod Electric Output", "CWC|PMP|CWC", Map.of('C', "circuit:6", 'M', "block:casingMachine@Tungsten", 'P', "item:gregtech:crystal_processor_sapphire", 'W', "wire:16@NiobiumTitanium")),
            new Entry("bedrock_mining_drill_controller", "Bedrock Mining Drill Controller", "PYP|CMC|GIG", Map.of('C', "circuit:6", 'G', "mat:gearGt@Tungstensteel", 'I', "mat:toolHeadDrill@Tungstensteel", 'M', "block:casingMachineDense@Titanium", 'P', "item:gregtech:crystal_processor_ruby", 'Y', "il:CONVEYERS")),
            new Entry("tungsten_wall", "Tungsten Wall", "wPP|hPP", Map.of('P', "mat:plate@Tungsten", 'h', "item:gregtech:tool_hammer", 'w', "item:gregtech:tool_wrench")),
            new Entry("adamantium_wall", "Adamantium Wall", "wPP|hPP", Map.of('P', "mat:plate@Adamantium", 'h', "item:gregtech:tool_hammer", 'w', "item:gregtech:tool_wrench")),
            new Entry("centrifuge_part", "Centrifuge Part", "TwT|GMG|TdT", Map.of('G', "mat:gearGt@Tungstensteel", 'M', "block:casingMachine@Tungstensteel", 'T', "mat:screw@Tungstensteel", 'd', "item:gregtech:tool_screwdriver", 'w', "item:gregtech:tool_wrench")),
            new Entry("electrolyzer_part", "Electrolyzer Part", "WwW|WMW|CCC", Map.of('C', "circuit:6", 'M', "block:casingMachine@StainlessSteel", 'W', "wire:1@Platinum", 'w', "item:gregtech:tool_wrench")),
            new Entry("heat_transmitter", "Heat Transmitter", "MPM|hRw|MPM", Map.of('M', "mat:plate@Invar", 'P', "mat:plateTriple@Copper", 'R', "mat:stickLong@Copper", 'h', "item:gregtech:tool_hammer", 'w', "item:gregtech:tool_wrench")),
            new Entry("distillation_tower_part", "Distillation Tower Part", "TMT|hPd|TMT", Map.of('M', "mat:plate@StainlessSteel", 'P', "pipe:small@StainlessSteel", 'T', "mat:screw@StainlessSteel", 'd', "item:gregtech:tool_screwdriver", 'h', "item:gregtech:tool_hammer")),
            new Entry("sluice_part", "Sluice Part", "GGG|PMP|PwP", Map.of('G', "mat:gearGt@Titanium", 'M', "block:casingMachine@Titanium", 'P', "pipe:medium@Titanium", 'w', "item:gregtech:tool_wrench")),
            new Entry("crusher_wheels", "Crusher Wheels", "DDD|GDG|GMG", Map.of('D', "mat:gem@Diamond", 'G', "mat:gearGt@Tungstensteel", 'M', "block:casingMachineDouble@Tungstensteel")),
            new Entry("shredder_blades", "Shredder Blades", "DGD|GwG|GMG", Map.of('D', "mat:plateGem@Diamond", 'G', "mat:gearGt@Tungstensteel", 'M', "block:casingMachineDouble@Tungstensteel", 'w', "item:gregtech:tool_wrench")),
            new Entry("large_niobium_titanium_coil", "Large Niobium-Titanium Coil", "WWW|WxW|WWW", Map.of('W', "wire:4@NiobiumTitanium", 'x', "item:gregtech:tool_wire_cutter")),
            new Entry("large_nichrome_coil", "Large Nichrome Coil", "WWW|WxW|WWW", Map.of('W', "wire:4@Nichrome", 'x', "item:gregtech:tool_wire_cutter")),
            new Entry("large_carborundum_coil", "Large Carborundum Coil", "WWW|WxW|WWW", Map.of('W', "wire:4@Carborundum", 'x', "item:gregtech:tool_wire_cutter")),
            new Entry("large_osmium_coil", "Large Osmium Coil", "WWW|WxW|WWW", Map.of('W', "wire:4@OsmiumElemental", 'x', "item:gregtech:tool_wire_cutter")),
            new Entry("large_iridium_coil", "Large Iridium Coil", "WWW|WxW|WWW", Map.of('W', "wire:4@Iridium", 'x', "item:gregtech:tool_wire_cutter")),
            new Entry("versatile_processor_unit", "Versatile Quadcore Processor Unit", "DCS|CMC|RCE", Map.of('C', "circuit:6", 'D', "item:gregtech:crystal_processor_diamond", 'E', "item:gregtech:crystal_processor_emerald", 'M', "block:casingMachine@SteelGalvanized", 'R', "item:gregtech:crystal_processor_ruby", 'S', "item:gregtech:crystal_processor_sapphire")),
            new Entry("logic_processor_unit", "Logic Quadcore Processor Unit", "PCP|CMC|PCP", Map.of('C', "circuit:6", 'M', "block:casingMachine@SteelGalvanized", 'P', "item:gregtech:crystal_processor_diamond")),
            new Entry("control_processor_unit", "Control Quadcore Processor Unit", "PCP|CMC|PCP", Map.of('C', "circuit:6", 'M', "block:casingMachine@SteelGalvanized", 'P', "item:gregtech:crystal_processor_ruby")),
            new Entry("conversion_processor_unit", "Conversion Quadcore Processor Unit", "PCP|CMC|PCP", Map.of('C', "circuit:6", 'M', "block:casingMachine@SteelGalvanized", 'P', "item:gregtech:crystal_processor_sapphire")),
            new Entry("fusion_ventilation_unit", "Ventilation Unit", "FwF|CMC|EdE", Map.of('C', "circuit:3", 'E', "il:MOTORS", 'F', "item:gregtech:air_vent", 'M', "block:casingMachine@SteelGalvanized", 'd', "item:gregtech:tool_screwdriver", 'w', "item:gregtech:tool_wrench")),
            new Entry("logistics_core", "Logistics Core", "CCC|PMP|CCC", Map.of('C', "circuit:6", 'M', "block:casingMachine@SteelGalvanized", 'P', "item:gregtech:crystal_processor_emerald")),
            new Entry("logistics_wire", "Logistics Wire", "PEP|dFx|POP", Map.of('E', "mat:gem@Emerald", 'F', "item:gregtech:laser_fiber_wire", 'O', "mat:wireFine@OsmiumElemental", 'P', "mat:foil@Plastic", 'd', "item:gregtech:tool_screwdriver", 'x', "item:gregtech:tool_wire_cutter"))
    );

    /** Recipe entries for one port block id (a block can have at most one). */
    public static Entry find(String blockId) {
        for (Entry entry : ENTRIES) {
            if (entry.blockId().equals(blockId)) return entry;
        }
        return null;
    }

    /** Original GT6 registration names covered by this table. */
    public static java.util.Set<String> coveredMachines() {
        java.util.Set<String> names = new java.util.TreeSet<>();
        for (Entry entry : ENTRIES) names.add(entry.originalName());
        return java.util.Collections.unmodifiableSet(names);
    }

    private MultiblockCraftingRecipes() {}
}
