package com.gregtech.gregtech.loaders.c;

import java.util.List;

/**
 * The port's alloying table (transcribed from {@link Loader_Recipes_Alloys}) in reverse-queryable
 * form: every entry is one {@code mix(out(...), ...)} call, i.e. what a molten alloy is made of.
 *
 * <p>Used by the material dictionary to print which alloys a material takes part in. Amounts are
 * in material units (1 unit = 144 mB), exactly like the recipes themselves.</p>
 *
 * <p>GENERATED by tools/extract_alloy_table.py - do not edit by hand.</p>
 */
public final class GTAlloyTable {
    /** One alloy: the output and its inputs (material names and units). */
    public record Alloy(String output, int units, List<Input> inputs) {
        public record Input(String material, int units) {}
    }

    public static final List<Alloy> ALLOYS = List.of(
        new Alloy("Constantan", 2, List.of(new Alloy.Input("Copper", 1), new Alloy.Input("Nickel", 1))),
        new Alloy("Constantan", 2, List.of(new Alloy.Input("AnnealedCopper", 1), new Alloy.Input("Nickel", 1))),
        new Alloy("ArsenicCopper", 4, List.of(new Alloy.Input("Copper", 3), new Alloy.Input("Arsenic", 1))),
        new Alloy("ArsenicCopper", 4, List.of(new Alloy.Input("AnnealedCopper", 3), new Alloy.Input("Arsenic", 1))),
        new Alloy("Bronze", 4, List.of(new Alloy.Input("Copper", 3), new Alloy.Input("Tin", 1))),
        new Alloy("Bronze", 4, List.of(new Alloy.Input("AnnealedCopper", 3), new Alloy.Input("Tin", 1))),
        new Alloy("Brass", 4, List.of(new Alloy.Input("Copper", 3), new Alloy.Input("Zinc", 1))),
        new Alloy("Brass", 4, List.of(new Alloy.Input("AnnealedCopper", 3), new Alloy.Input("Zinc", 1))),
        new Alloy("AluminiumBrass", 4, List.of(new Alloy.Input("Copper", 1), new Alloy.Input("Aluminium", 3))),
        new Alloy("AluminiumBrass", 4, List.of(new Alloy.Input("AnnealedCopper", 1), new Alloy.Input("Aluminium", 3))),
        new Alloy("RedAlloy", 1, List.of(new Alloy.Input("Copper", 1), new Alloy.Input("Redstone", 4))),
        new Alloy("RedAlloy", 1, List.of(new Alloy.Input("AnnealedCopper", 1), new Alloy.Input("Redstone", 4))),
        new Alloy("SterlingSilver", 5, List.of(new Alloy.Input("Copper", 1), new Alloy.Input("Silver", 4))),
        new Alloy("SterlingSilver", 5, List.of(new Alloy.Input("AnnealedCopper", 1), new Alloy.Input("Silver", 4))),
        new Alloy("PurpleAlloy", 2, List.of(new Alloy.Input("Copper", 1), new Alloy.Input("Silver", 1), new Alloy.Input("Redstone", 4), new Alloy.Input("Nikolite", 4))),
        new Alloy("PurpleAlloy", 2, List.of(new Alloy.Input("AnnealedCopper", 1), new Alloy.Input("Silver", 1), new Alloy.Input("Redstone", 4), new Alloy.Input("Nikolite", 4))),
        new Alloy("Signalum", 4, List.of(new Alloy.Input("Copper", 3), new Alloy.Input("Silver", 1), new Alloy.Input("Redstone", 10))),
        new Alloy("Signalum", 4, List.of(new Alloy.Input("AnnealedCopper", 3), new Alloy.Input("Silver", 1), new Alloy.Input("Redstone", 10))),
        new Alloy("Signalum", 8, List.of(new Alloy.Input("Copper", 1), new Alloy.Input("Silver", 2), new Alloy.Input("RedAlloy", 5))),
        new Alloy("Signalum", 8, List.of(new Alloy.Input("AnnealedCopper", 1), new Alloy.Input("Silver", 2), new Alloy.Input("RedAlloy", 5))),
        new Alloy("BlackBronze", 5, List.of(new Alloy.Input("Copper", 3), new Alloy.Input("Silver", 1), new Alloy.Input("Gold", 1))),
        new Alloy("BlackBronze", 5, List.of(new Alloy.Input("AnnealedCopper", 3), new Alloy.Input("Silver", 1), new Alloy.Input("Gold", 1))),
        new Alloy("Hepatizon", 8, List.of(new Alloy.Input("Copper", 3), new Alloy.Input("Tin", 1), new Alloy.Input("Gold", 4))),
        new Alloy("Hepatizon", 8, List.of(new Alloy.Input("AnnealedCopper", 3), new Alloy.Input("Tin", 1), new Alloy.Input("Gold", 4))),
        new Alloy("BlackBronze", 5, List.of(new Alloy.Input("Copper", 3), new Alloy.Input("Electrum", 2))),
        new Alloy("BlackBronze", 5, List.of(new Alloy.Input("AnnealedCopper", 3), new Alloy.Input("Electrum", 2))),
        new Alloy("RoseGold", 5, List.of(new Alloy.Input("Copper", 1), new Alloy.Input("Gold", 4))),
        new Alloy("RoseGold", 5, List.of(new Alloy.Input("AnnealedCopper", 1), new Alloy.Input("Gold", 4))),
        new Alloy("ArsenicBronze", 5, List.of(new Alloy.Input("Copper", 3), new Alloy.Input("Tin", 1), new Alloy.Input("Arsenic", 1))),
        new Alloy("ArsenicBronze", 5, List.of(new Alloy.Input("AnnealedCopper", 3), new Alloy.Input("Tin", 1), new Alloy.Input("Arsenic", 1))),
        new Alloy("BismuthBronze", 5, List.of(new Alloy.Input("Copper", 3), new Alloy.Input("Zinc", 1), new Alloy.Input("Bismuth", 1))),
        new Alloy("BismuthBronze", 5, List.of(new Alloy.Input("AnnealedCopper", 3), new Alloy.Input("Zinc", 1), new Alloy.Input("Bismuth", 1))),
        new Alloy("Invar", 3, List.of(new Alloy.Input("Iron", 2), new Alloy.Input("Nickel", 1))),
        new Alloy("Invar", 3, List.of(new Alloy.Input("WroughtIron", 2), new Alloy.Input("Nickel", 1))),
        new Alloy("Invar", 3, List.of(new Alloy.Input("PigIron", 2), new Alloy.Input("Nickel", 1))),
        new Alloy("Invar", 3, List.of(new Alloy.Input("MeteoricIron", 2), new Alloy.Input("Nickel", 1))),
        new Alloy("Kanthal", 3, List.of(new Alloy.Input("Iron", 1), new Alloy.Input("Aluminium", 1), new Alloy.Input("Chromium", 1))),
        new Alloy("Kanthal", 3, List.of(new Alloy.Input("WroughtIron", 1), new Alloy.Input("Aluminium", 1), new Alloy.Input("Chromium", 1))),
        new Alloy("Kanthal", 3, List.of(new Alloy.Input("PigIron", 1), new Alloy.Input("Aluminium", 1), new Alloy.Input("Chromium", 1))),
        new Alloy("Kanthal", 3, List.of(new Alloy.Input("MeteoricIron", 1), new Alloy.Input("Aluminium", 1), new Alloy.Input("Chromium", 1))),
        new Alloy("TinAlloy", 2, List.of(new Alloy.Input("Iron", 1), new Alloy.Input("Tin", 1))),
        new Alloy("TinAlloy", 2, List.of(new Alloy.Input("WroughtIron", 1), new Alloy.Input("Tin", 1))),
        new Alloy("TinAlloy", 2, List.of(new Alloy.Input("PigIron", 1), new Alloy.Input("Tin", 1))),
        new Alloy("TinAlloy", 2, List.of(new Alloy.Input("MeteoricIron", 1), new Alloy.Input("Tin", 1))),
        new Alloy("Angmallen", 2, List.of(new Alloy.Input("Iron", 1), new Alloy.Input("Gold", 1))),
        new Alloy("Angmallen", 2, List.of(new Alloy.Input("WroughtIron", 1), new Alloy.Input("Gold", 1))),
        new Alloy("Angmallen", 2, List.of(new Alloy.Input("PigIron", 1), new Alloy.Input("Gold", 1))),
        new Alloy("Angmallen", 2, List.of(new Alloy.Input("MeteoricIron", 1), new Alloy.Input("Gold", 1))),
        new Alloy("StainlessSteel", 9, List.of(new Alloy.Input("Iron", 6), new Alloy.Input("Nickel", 1), new Alloy.Input("Chromium", 1), new Alloy.Input("Manganese", 1))),
        new Alloy("StainlessSteel", 9, List.of(new Alloy.Input("WroughtIron", 6), new Alloy.Input("Nickel", 1), new Alloy.Input("Chromium", 1), new Alloy.Input("Manganese", 1))),
        new Alloy("StainlessSteel", 9, List.of(new Alloy.Input("PigIron", 6), new Alloy.Input("Nickel", 1), new Alloy.Input("Chromium", 1), new Alloy.Input("Manganese", 1))),
        new Alloy("StainlessSteel", 9, List.of(new Alloy.Input("MeteoricIron", 6), new Alloy.Input("Nickel", 1), new Alloy.Input("Chromium", 1), new Alloy.Input("Manganese", 1))),
        new Alloy("StainlessSteel", 9, List.of(new Alloy.Input("Iron", 4), new Alloy.Input("Invar", 3), new Alloy.Input("Chromium", 1), new Alloy.Input("Manganese", 1))),
        new Alloy("StainlessSteel", 9, List.of(new Alloy.Input("WroughtIron", 4), new Alloy.Input("Invar", 3), new Alloy.Input("Chromium", 1), new Alloy.Input("Manganese", 1))),
        new Alloy("StainlessSteel", 9, List.of(new Alloy.Input("PigIron", 4), new Alloy.Input("Invar", 3), new Alloy.Input("Chromium", 1), new Alloy.Input("Manganese", 1))),
        new Alloy("StainlessSteel", 9, List.of(new Alloy.Input("MeteoricIron", 4), new Alloy.Input("Invar", 3), new Alloy.Input("Chromium", 1), new Alloy.Input("Manganese", 1))),
        new Alloy("StainlessSteel", 36, List.of(new Alloy.Input("Iron", 24), new Alloy.Input("Nichrome", 5), new Alloy.Input("Chromium", 3), new Alloy.Input("Manganese", 4))),
        new Alloy("StainlessSteel", 36, List.of(new Alloy.Input("WroughtIron", 24), new Alloy.Input("Nichrome", 5), new Alloy.Input("Chromium", 3), new Alloy.Input("Manganese", 4))),
        new Alloy("StainlessSteel", 36, List.of(new Alloy.Input("PigIron", 24), new Alloy.Input("Nichrome", 5), new Alloy.Input("Chromium", 3), new Alloy.Input("Manganese", 4))),
        new Alloy("StainlessSteel", 36, List.of(new Alloy.Input("MeteoricIron", 24), new Alloy.Input("Nichrome", 5), new Alloy.Input("Chromium", 3), new Alloy.Input("Manganese", 4))),
        new Alloy("ElectrotineAlloy", 1, List.of(new Alloy.Input("Iron", 1), new Alloy.Input("Nikolite", 8))),
        new Alloy("ElectrotineAlloy", 1, List.of(new Alloy.Input("WroughtIron", 1), new Alloy.Input("Nikolite", 8))),
        new Alloy("ElectrotineAlloy", 1, List.of(new Alloy.Input("PigIron", 1), new Alloy.Input("Nikolite", 8))),
        new Alloy("ElectrotineAlloy", 1, List.of(new Alloy.Input("MeteoricIron", 1), new Alloy.Input("Nikolite", 8))),
        new Alloy("TungstenSteel", 2, List.of(new Alloy.Input("Steel", 1), new Alloy.Input("Tungsten", 1))),
        new Alloy("TungstenSteel", 2, List.of(new Alloy.Input("MeteoricSteel", 1), new Alloy.Input("Tungsten", 1))),
        new Alloy("TungstenSteel", 2, List.of(new Alloy.Input("HSLA", 1), new Alloy.Input("Tungsten", 1))),
        new Alloy("TungstenSteel", 2, List.of(new Alloy.Input("Knightmetal", 1), new Alloy.Input("Tungsten", 1))),
        new Alloy("Lumium", 4, List.of(new Alloy.Input("Tin", 3), new Alloy.Input("Silver", 1), new Alloy.Input("Glowstone", 4))),
        new Alloy("BlueAlloy", 1, List.of(new Alloy.Input("Nikolite", 4), new Alloy.Input("Silver", 1))),
        new Alloy("PurpleAlloy", 1, List.of(new Alloy.Input("RedAlloy", 1), new Alloy.Input("BlueAlloy", 1))),
        new Alloy("RedstoneAlloy", 1, List.of(new Alloy.Input("Silicon", 1), new Alloy.Input("Redstone", 1))),
        new Alloy("NikolineAlloy", 1, List.of(new Alloy.Input("Silicon", 1), new Alloy.Input("Nikolite", 1))),
        new Alloy("Nichrome", 5, List.of(new Alloy.Input("Chromium", 1), new Alloy.Input("Nickel", 4))),
        new Alloy("Netherite", 1, List.of(new Alloy.Input("Gold", 4), new Alloy.Input("AncientDebris", 4))),
        new Alloy("TitaniumGold", 4, List.of(new Alloy.Input("Gold", 1), new Alloy.Input("Titanium", 3))),
        new Alloy("Hepatizon", 2, List.of(new Alloy.Input("Gold", 1), new Alloy.Input("Bronze", 1))),
        new Alloy("Electrum", 2, List.of(new Alloy.Input("Gold", 1), new Alloy.Input("Silver", 1))),
        new Alloy("GoldInductive", 2, List.of(new Alloy.Input("Gold", 1), new Alloy.Input("Redstone", 1))),
        new Alloy("SolderingAlloy", 10, List.of(new Alloy.Input("Tin", 9), new Alloy.Input("Antimony", 1))),
        new Alloy("BatteryAlloy", 5, List.of(new Alloy.Input("Lead", 4), new Alloy.Input("Antimony", 1))),
        new Alloy("Celenegil", 2, List.of(new Alloy.Input("Orichalcum", 1), new Alloy.Input("Platinum", 1))),
        new Alloy("Manyullyn", 2, List.of(new Alloy.Input("Ardite", 1), new Alloy.Input("Cobalt", 1))),
        new Alloy("Magnalium", 3, List.of(new Alloy.Input("Magnesium", 1), new Alloy.Input("Aluminium", 2))),
        new Alloy("CobaltBrass", 9, List.of(new Alloy.Input("Brass", 7), new Alloy.Input("Aluminium", 1), new Alloy.Input("Cobalt", 1))),
        new Alloy("BismuthBronze", 5, List.of(new Alloy.Input("Brass", 4), new Alloy.Input("Bismuth", 1))),
        new Alloy("ArsenicBronze", 5, List.of(new Alloy.Input("Bronze", 4), new Alloy.Input("Arsenic", 1))),
        new Alloy("ArsenicBronze", 5, List.of(new Alloy.Input("ArsenicCopper", 4), new Alloy.Input("Tin", 1))),
        new Alloy("Ultimet", 9, List.of(new Alloy.Input("Cobalt", 5), new Alloy.Input("Chromium", 2), new Alloy.Input("Nickel", 1), new Alloy.Input("Molybdenum", 1))),
        new Alloy("Ultimet", 36, List.of(new Alloy.Input("Cobalt", 20), new Alloy.Input("Chromium", 7), new Alloy.Input("Nichrome", 5), new Alloy.Input("Molybdenum", 4))),
        new Alloy("Osmiridium", 2, List.of(new Alloy.Input("Osmium", 1), new Alloy.Input("Iridium", 1))),
        new Alloy("HSSG", 9, List.of(new Alloy.Input("TungstenSteel", 5), new Alloy.Input("Chromium", 1), new Alloy.Input("Molybdenum", 2), new Alloy.Input("Vanadium", 1))),
        new Alloy("HSSE", 9, List.of(new Alloy.Input("HSSG", 6), new Alloy.Input("Cobalt", 1), new Alloy.Input("Manganese", 1), new Alloy.Input("Silicon", 1))),
        new Alloy("HSSS", 9, List.of(new Alloy.Input("HSSG", 6), new Alloy.Input("Osmiridium", 2), new Alloy.Input("Iridium", 1))),
        new Alloy("HSSS", 9, List.of(new Alloy.Input("HSSG", 6), new Alloy.Input("Osmium", 1), new Alloy.Input("Iridium", 2)))
    );

    private GTAlloyTable() {}
}
