package com.gregtech.gregtech.loaders.c;

/**
 * GT6's comb processing: the twenty {@code RM.Centrifuge.addRecipe1} rows of
 * {@code MultiItemFood.java:251-270}, which turn a comb into its fluid, wax and side products.
 *
 * <p>GT6 registers those rows inside its food item class, which
 * {@code tools/transpile_gt6_chem.py} never scans, so the port had the comb items
 * ({@code transpile_gt6_multiitems.py}) but nothing to do with them.</p>
 *
 * <p>GENERATED by tools/extract_gt6_comb_recipes.py - do not edit by hand.
 * Spec resolution happens in {@link GTGeneratedChem}.</p>
 */
final class GTCombGen {
    private static final String[] NONE = new String[0];

    private GTCombGen() {}

    private static String[] sp(String... specs) { return specs; }

    private static long[] ch(long... chances) { return chances; }

    private static void r(long eut, long dur, long[] chances, String[] itemIn,
                          String[] fluidIn, String[] fluidOut, String[] itemOut) {
        GTGeneratedChem.register("Centrifuge", eut, dur, chances, itemIn, fluidIn, fluidOut, itemOut);
    }

    static void load() {
        // GT6 also yields IL.FR_Propolis.get(1) (another mod's item); dropped here.
        r(16, 64, ch(10000, 1000), sp("tech:honey_comb:1"), NONE, sp("f:Honey:100"), sp("i:dust:WaxBee:1"));
        r(16, 64, ch(10000, 1000), sp("tech:water_comb:1"), NONE, sp("w:1000"), sp("i:dust:WaxBee:1"));
        r(16, 64, ch(10000, 1000), sp("tech:magic_comb:1"), NONE, sp("f:Ambrosia:100"), sp("i:dust:WaxMagic:1"));
        r(16, 64, ch(10000, 1000), sp("tech:nether_comb:1"), NONE, sp("f:Blaze:144"), sp("i:dust:WaxRefractory:1"));
        // GT6 also yields IL.FR_Propolis_Pulsating.get(1), IL.EtFu_Chorus_Fruit.get(1) (another mod's item); dropped here.
        r(16, 64, ch(10000, 1000, 1000), sp("tech:end_comb:1"), NONE, sp("f:Dragon_Breath:125"), sp("i:dust:Endstone:1"));
        r(16, 64, ch(10000, 1000), sp("tech:rock_comb:1"), NONE, sp("f:Concrete:144"), sp("i:dust:Stone:1"));
        r(16, 64, ch(10000, 1000), sp("tech:jungle_comb:1"), NONE, sp("m:Chocolate:144"), sp("i:dust:Cocoa:1", "v:string:1"));
        r(16, 64, ch(10000, 1000), sp("tech:frozen_comb:1"), NONE, sp("f:Ice:1000"), sp("i:dust:Ice:1"));
        r(16, 64, ch(6000, 6000), sp("tech:shroomy_comb:1"), NONE, sp("f:Soup_Mushroom:1000"), sp("v:red_mushroom_block:1", "v:brown_mushroom_block:1"));
        r(16, 64, ch(10000, 1000), sp("tech:sandy_comb:1"), NONE, sp("f:Juice_Cactus:100"), sp("v:sand:1"));
        r(16, 64, ch(2000, 2000, 2000, 2000, 2000, 2000), sp("tech:clay_comb:1"), NONE, sp("f:Concrete:144"), sp("i:dust:Clay:1", "i:dust:ClayBrown:1", "i:dust:ClayRed:1", "i:dust:Bentonite:1", "i:dust:Palygorskite:1", "i:dust:Kaolinite:1"));
        // GT6 also yields IL.FR_Propolis_Sticky.get(1, IL.IC2_Resin.get(1, IL.Resin.get(1))) (another mod's item); dropped here.
        r(16, 64, ch(10000, 3000), sp("tech:sticky_comb:1"), NONE, sp("f:Latex:144"), sp("i:dust:WaxBee:1"));
        r(16, 64, ch(10000), sp("tech:royal_comb:1"), NONE, sp("f:Honey:50", "f:RoyalJelly:10"), sp("i:dust:WaxBee:1"));
        r(16, 64, ch(10000, 9000), sp("tech:soul_comb:1"), NONE, sp("f:Oil_Soulsand:50"), sp("i:dust:WaxSoulful:1", "i:dust:SoulSand:1"));
        r(16, 64, ch(10000, 1000), sp("tech:amnesic_comb:1"), NONE, sp("f:Lubricant:1000"), sp("i:dust:WaxAmnesic:1"));
        r(16, 64, ch(10000, 500, 500, 250), sp("tech:military_comb:1"), NONE, sp("f:Potion_Harm_1:50"), sp("i:dust:Bone:1", "v:bone:1", "v:rotten_flesh:1", "v:spider_eye:1"));
        r(16, 64, ch(10000, 1000), sp("tech:pyro_comb:1"), NONE, sp("f:Blaze:72"), sp("i:dustTiny:Blaze:9", "i:stick:Blaze:1"));
        r(16, 64, ch(10000, 1000), sp("tech:cryo_comb:1"), NONE, sp("f:Ice:500"), sp("i:dustTiny:Blizz:9", "i:stick:Blizz:1"));
        r(16, 64, ch(10000, 500, 500), sp("tech:aero_comb:1"), NONE, sp("f:Dragon_Breath:50"), sp("i:dustTiny:Blitz:9", "i:stick:Blitz:1", "i:stick:Breeze:1"));
        r(16, 64, ch(10000, 1000), sp("tech:tera_comb:1"), NONE, sp("f:Concrete:144"), sp("i:dustTiny:Basalz:9", "i:stick:Basalz:1"));
    }
}
