package com.gregtech.gregtech.loaders.c;

/**
 * GT6 ore processing recipes transpiled from {@code Loader_Recipes_Ores} (the port's own ore chains are registered earlier and win every collision)
 * (138 of 280 RM calls translated into 138 recipes; the rest
 * reference cross-mod content or untranslatable expressions).
 *
 * <p>GENERATED by tools/transpile_gt6_chem.py ores — do not edit by hand.
 * Spec resolution happens in {@link GTGeneratedChem}.</p>
 */
final class GTOresGen {
    private static final String[] NONE = new String[0];

    private GTOresGen() {}

    private static String[] sp(String... specs) { return specs; }

    private static long[] ch(long... chances) { return chances; }

    private static void r(String map, long eut, long dur, long[] chances,
                          String[] itemIn, String[] fluidIn, String[] fluidOut, String[] itemOut) {
        GTGeneratedChem.register(map, eut, dur, chances, itemIn, fluidIn, fluidOut, itemOut);
    }

    static void load() {
        r("Mixer", 16, 16, null, sp("omd:SluiceSand:111"), sp("w:100"), sp("f:Sluice:100"), NONE);
        r("Mixer", 16, 16, null, sp("omd:SluiceSand:1000"), sp("w:900"), sp("f:Sluice:900"), NONE);
        r("Drying", 16, 100, null, NONE, sp("f:Sluice:100"), sp("f:DistW:50"), sp("omd:SluiceSand:111"));
        r("Centrifuge", 64, 16, ch(9640, 100, 100, 100, 100, 100), NONE, sp("f:Sluice:100"), sp("w:50"), sp("i:dustTiny:Stone:1", "i:dustTiny:Cu:2", "i:dustTiny:Sn:1", "i:dustTiny:Zn:1", "i:dustTiny:Sb:1", "i:dustTiny:Cr:1"));
        r("MagneticSeparator", 16, 16, ch(9640, 72, 72, 72, 72, 72), sp("i:dustTiny:SluiceSand:1"), NONE, NONE, sp("i:dustTiny:Stone:1", "i:dustTiny:Fe:2", "i:dustTiny:Nd:1", "i:dustTiny:Ni:1", "i:dustTiny:Co:1", "i:dustTiny:Mn:1"));
        r("MagneticSeparator", 16, 36, ch(9640, 162, 162, 162, 162, 162), sp("i:dustSmall:SluiceSand:1"), NONE, NONE, sp("i:dustSmall:Stone:1", "i:dustTiny:Fe:2", "i:dustTiny:Nd:1", "i:dustTiny:Ni:1", "i:dustTiny:Co:1", "i:dustTiny:Mn:1"));
        r("MagneticSeparator", 16, 144, ch(9640, 648, 648, 648, 648, 648), sp("i:dust:SluiceSand:1"), NONE, NONE, sp("i:dust:Stone:1", "i:dustTiny:Fe:2", "i:dustTiny:Nd:1", "i:dustTiny:Ni:1", "i:dustTiny:Co:1", "i:dustTiny:Mn:1"));
        r("MagneticSeparator", 16, 1296, ch(9640, 5832, 5832, 5832, 5832, 5832), sp("i:blockDust:SluiceSand:1"), NONE, NONE, sp("i:dust:Stone:9", "i:dustTiny:Fe:2", "i:dustTiny:Nd:1", "i:dustTiny:Ni:1", "i:dustTiny:Co:1", "i:dustTiny:Mn:1"));
        r("Centrifuge", 256, 144, ch(7000, 3000, 3000, 3000, 3000, 3000), sp("i:dust:Bedrock:1"), NONE, NONE, sp("i:dust:Deepslate:1", "i:dustTiny:Adamantite:1", "i:dustTiny:Draconium:1", "i:dustTiny:Monazite:2", "i:dustTiny:Zircon:3", "i:dustTiny:Graphite:3"));
        r("Centrifuge", 256, 1296, ch(7000, 3000, 3000, 3000, 3000, 3000), sp("i:blockDust:Bedrock:1"), NONE, NONE, sp("i:dust:Deepslate:9", "i:dustTiny:Adamantite:9", "i:dustTiny:Draconium:9", "i:dustTiny:Monazite:18", "i:dustTiny:Zircon:27", "i:dustTiny:Graphite:27"));
        r("MagneticSeparator", 64, 144, ch(7000, 3000, 3000, 3000, 3000, 3000), sp("i:dust:Bedrock:1"), NONE, NONE, sp("i:dust:Deepslate:1", "i:dustTiny:Adamantine:1", "i:dustTiny:Atl:1", "i:dustTiny:RareEarth:2", "i:dustTiny:Nd:3", "i:dustTiny:V2O5:3"));
        r("MagneticSeparator", 64, 1296, ch(7000, 3000, 3000, 3000, 3000, 3000), sp("i:blockDust:Bedrock:1"), NONE, NONE, sp("i:dust:Deepslate:9", "i:dustTiny:Adamantine:9", "i:dustTiny:Atl:9", "i:dustTiny:RareEarth:18", "i:dustTiny:Nd:27", "i:dustTiny:V2O5:27"));
        r("MagneticSeparator", 16, 16, ch(3000, 12, 12, 12, 12, 12), sp("i:dustTiny:MoonTurf:1"), NONE, NONE, sp("i:dustTiny:Basalt:1", "i:dustTiny:MeteoricIron:9", "i:dustTiny:Nd:1", "i:dustTiny:Ni:1", "i:dustTiny:Co:1", "i:dustTiny:Mn:1"));
        r("MagneticSeparator", 16, 36, ch(3000, 27, 27, 27, 27, 27), sp("i:dustSmall:MoonTurf:1"), NONE, NONE, sp("i:dustSmall:Basalt:1", "i:dustTiny:MeteoricIron:9", "i:dustTiny:Nd:1", "i:dustTiny:Ni:1", "i:dustTiny:Co:1", "i:dustTiny:Mn:1"));
        r("MagneticSeparator", 16, 144, ch(3000, 108, 108, 108, 108, 108), sp("i:dust:MoonTurf:1"), NONE, NONE, sp("i:dust:Basalt:1", "i:dustTiny:MeteoricIron:9", "i:dustTiny:Nd:1", "i:dustTiny:Ni:1", "i:dustTiny:Co:1", "i:dustTiny:Mn:1"));
        r("MagneticSeparator", 16, 1296, ch(3000, 972, 972, 972, 972, 972), sp("i:blockDust:MoonTurf:1"), NONE, NONE, sp("i:dust:Basalt:9", "i:dustTiny:MeteoricIron:9", "i:dustTiny:Nd:1", "i:dustTiny:Ni:1", "i:dustTiny:Co:1", "i:dustTiny:Mn:1"));
        r("Drying", 16, 2592, null, sp("i:crushedPurified:Biotite:1"), NONE, sp("m:Ar:90"), sp("i:crushedCentrifuged:Biotite:1"));
        r("Drying", 16, 288, null, sp("i:crushedPurifiedTiny:Biotite:1"), NONE, sp("m:Ar:10"), sp("i:crushedCentrifugedTiny:Biotite:1"));
        r("Centrifuge", 64, 16, ch(72, 72, 72, 72, 72, 72), sp("i:dustTiny:RareEarth:1"), NONE, NONE, sp("i:dustTiny:Nd:8", "i:dustTiny:Y:8", "i:dustTiny:La:8", "i:dustTiny:Ce:8", "i:dustTiny:Cd:8", "i:dustTiny:Cs:8"));
        r("Centrifuge", 64, 36, ch(162, 162, 162, 162, 162, 162), sp("i:dustSmall:RareEarth:1"), NONE, NONE, sp("i:dustTiny:Nd:8", "i:dustTiny:Y:8", "i:dustTiny:La:8", "i:dustTiny:Ce:8", "i:dustTiny:Cd:8", "i:dustTiny:Cs:8"));
        r("Centrifuge", 64, 144, ch(648, 648, 648, 648, 648, 648), sp("i:dust:RareEarth:1"), NONE, NONE, sp("i:dustTiny:Nd:8", "i:dustTiny:Y:8", "i:dustTiny:La:8", "i:dustTiny:Ce:8", "i:dustTiny:Cd:8", "i:dustTiny:Cs:8"));
        r("Centrifuge", 64, 16, ch(80, 80, 80, 80, 80, 80), sp("i:crushedCentrifugedTiny:RareEarth:1"), NONE, NONE, sp("i:dustTiny:Nd:8", "i:dustTiny:Y:8", "i:dustTiny:La:8", "i:dustTiny:Ce:8", "i:dustTiny:Cd:8", "i:dustTiny:Cs:8"));
        r("Centrifuge", 64, 144, ch(720, 720, 720, 720, 720, 720), sp("i:crushedCentrifuged:RareEarth:1"), NONE, NONE, sp("i:dustTiny:Nd:8", "i:dustTiny:Y:8", "i:dustTiny:La:8", "i:dustTiny:Ce:8", "i:dustTiny:Cd:8", "i:dustTiny:Cs:8"));
        r("Centrifuge", 64, 16, ch(72, 72, 72, 72, 72, 72), sp("i:dustTiny:PlatinumGroupSludge:1"), NONE, NONE, sp("i:dustTiny:Ru:8", "i:dustTiny:Rh:8", "i:dustTiny:Pd:8", "i:dustTiny:Os:8", "i:dustTiny:Ir:8", "i:dustTiny:Pt:8"));
        r("Centrifuge", 64, 36, ch(162, 162, 162, 162, 162, 162), sp("i:dustSmall:PlatinumGroupSludge:1"), NONE, NONE, sp("i:dustTiny:Ru:8", "i:dustTiny:Rh:8", "i:dustTiny:Pd:8", "i:dustTiny:Os:8", "i:dustTiny:Ir:8", "i:dustTiny:Pt:8"));
        r("Centrifuge", 64, 144, ch(648, 648, 648, 648, 648, 648), sp("i:dust:PlatinumGroupSludge:1"), NONE, NONE, sp("i:dustTiny:Ru:8", "i:dustTiny:Rh:8", "i:dustTiny:Pd:8", "i:dustTiny:Os:8", "i:dustTiny:Ir:8", "i:dustTiny:Pt:8"));
        r("Centrifuge", 64, 16, ch(80, 80, 80, 80, 80, 80), sp("i:crushedCentrifugedTiny:PlatinumGroupSludge:1"), NONE, NONE, sp("i:dustTiny:Ru:8", "i:dustTiny:Rh:8", "i:dustTiny:Pd:8", "i:dustTiny:Os:8", "i:dustTiny:Ir:8", "i:dustTiny:Pt:8"));
        r("Centrifuge", 64, 144, ch(720, 720, 720, 720, 720, 720), sp("i:crushedCentrifuged:PlatinumGroupSludge:1"), NONE, NONE, sp("i:dustTiny:Ru:8", "i:dustTiny:Rh:8", "i:dustTiny:Pd:8", "i:dustTiny:Os:8", "i:dustTiny:Ir:8", "i:dustTiny:Pt:8"));
        r("Centrifuge", 64, 288, ch(8000, 250, 250, 250, 250, 250), NONE, sp("f:Lava:100"), NONE, sp("i:dustTiny:Basalt:1", "i:nugget:Cu:8", "i:nugget:Sn:4", "i:nugget:Pb:2", "i:nugget:Au:1", "i:nugget:Ag:1"));
        r("Centrifuge", 64, 144, ch(9000, 300, 300, 300, 300, 300), NONE, sp("f:Lava_Pahoehoe:100"), NONE, sp("i:dustTiny:Basalt:1", "i:nugget:Cu:8", "i:nugget:Sn:4", "i:nugget:Pb:2", "i:nugget:Au:1", "i:nugget:Ag:1"));
        r("Centrifuge", 64, 144, ch(9500, 1000, 1000, 1000, 1000, 1000), NONE, sp("f:Lava_Volcanic:100"), NONE, sp("i:dustTiny:Basalt:4", "i:nugget:Cu:8", "i:nugget:Sn:4", "i:nugget:Pb:2", "i:nugget:Au:1", "i:nugget:Ag:1"));
        r("Centrifuge", 64, 144, ch(8000, 1000, 1000, 1000), sp("v:soul_sand:1"), NONE, sp("f:Oil_Soulsand:45"), sp("i:dust:Sand:9", "i:dustTiny:Niter:9", "i:dustTiny:Coal:9", "i:dustTiny:Bone:9"));
        r("Centrifuge", 64, 16, ch(8000, 1000, 1000, 1000), sp("i:dust:SoulSand:1"), NONE, sp("f:Oil_Soulsand:5"), sp("i:dust:Sand:1", "i:dustTiny:Niter:1", "i:dustTiny:Coal:1", "i:dustTiny:Bone:1"));
        r("Centrifuge", 64, 144, ch(8000, 1000, 500, 500, 100), sp("i:blockDust:Netherrack:1"), NONE, NONE, sp("i:dust:Stone:9", "i:dustTiny:S:18", "i:dustTiny:Redstone:9", "i:dustTiny:Coal:9", "i:dustTiny:Au:9"));
        r("Centrifuge", 64, 16, ch(8000, 1000, 500, 500, 100), sp("i:dust:Netherrack:1"), NONE, NONE, sp("i:dust:Stone:1", "i:dustTiny:S:2", "i:dustTiny:Redstone:1", "i:dustTiny:Coal:1", "i:dustTiny:Au:1"));
        r("Centrifuge", 64, 144, ch(8000, 100, 300, 100, 10), sp("i:blockDust:Endstone:1"), NONE, sp("m:He:125", "m:He_3:18", "m:NO2:250", "m:CO2:250", "m:H:125", "m:D:125"), sp("i:dust:Sand:9", "i:dustTiny:Pt:9", "i:dustTiny:WO3:9", "i:dustTiny:Endium:9", "i:gem:Sugilite:9"));
        r("Centrifuge", 64, 16, ch(8000, 100, 300, 100, 10), sp("i:dust:Endstone:1"), NONE, sp("m:He:14", "m:He_3:2", "m:NO2:28", "m:CO2:28", "m:H:14", "m:D:14"), sp("i:dust:Sand:1", "i:dustTiny:Pt:1", "i:dustTiny:WO3:1", "i:dustTiny:Endium:1", "i:gem:Sugilite:1"));
        r("Centrifuge", 64, 144, ch(8000, 100, 300, 100, 10), sp("i:blockDust:EndSandWhite:1"), NONE, sp("m:He:125", "m:He_3:18", "m:NO2:250", "m:CO2:250", "m:H:125", "m:D:125"), sp("i:dust:Sand:9", "i:dustTiny:Pt:9", "i:dustTiny:WO3:9", "i:dustTiny:Endium:9", "i:gem:Sugilite:9"));
        r("Centrifuge", 64, 16, ch(8000, 100, 300, 100, 10), sp("i:dust:EndSandWhite:1"), NONE, sp("m:He:14", "m:He_3:2", "m:NO2:28", "m:CO2:28", "m:H:14", "m:D:14"), sp("i:dust:Sand:1", "i:dustTiny:Pt:1", "i:dustTiny:WO3:1", "i:dustTiny:Endium:1", "i:gem:Sugilite:1"));
        r("Centrifuge", 64, 144, ch(8000, 100, 300, 100, 10), sp("i:blockDust:EndSandBlack:1"), NONE, sp("m:He:125", "m:He_3:18", "m:NO2:250", "m:CO2:250", "m:H:125", "m:D:125"), sp("i:dust:Sand:9", "i:dustTiny:Pt:9", "i:dustTiny:WO3:9", "i:dustTiny:Endium:9", "i:gem:Sugilite:9"));
        r("Centrifuge", 64, 16, ch(8000, 100, 300, 100, 10), sp("i:dust:EndSandBlack:1"), NONE, sp("m:He:14", "m:He_3:2", "m:NO2:28", "m:CO2:28", "m:H:14", "m:D:14"), sp("i:dust:Sand:1", "i:dustTiny:Pt:1", "i:dustTiny:WO3:1", "i:dustTiny:Endium:1", "i:gem:Sugilite:1"));
        r("Centrifuge", 64, 144, ch(8000, 100, 100), sp("i:blockDust:SpaceRock:1"), NONE, sp("m:He:125", "m:He_3:18", "m:NO2:250", "m:CO2:250", "m:H:125", "m:D:125"), sp("i:dust:Sand:9", "i:dustTiny:Pt:9", "i:dustTiny:MeteoricIron:9"));
        r("Centrifuge", 64, 16, ch(8000, 100, 100), sp("i:dust:SpaceRock:1"), NONE, sp("m:He:14", "m:He_3:2", "m:NO2:28", "m:CO2:28", "m:H:14", "m:D:14"), sp("i:dust:Sand:1", "i:dustTiny:Pt:1", "i:dustTiny:MeteoricIron:1"));
        r("Centrifuge", 64, 288, ch(8000, 1000, 1000, 1000, 1000, 100), sp("i:blockDust:MoonTurf:1"), NONE, sp("m:He:125", "m:He_3:18", "m:NO2:250", "m:CO2:250", "m:H:125", "m:D:125"), sp("i:dust:Sand:9", "i:dustTiny:Basalt:9", "i:dustTiny:Al2O3:9", "i:dustTiny:Ilmenite:9", "i:dustTiny:MnO2:9", "i:dustTiny:MeteoricIron:9"));
        r("Centrifuge", 64, 32, ch(8000, 1000, 1000, 1000, 1000, 100), sp("i:dust:MoonTurf:1"), NONE, sp("m:He:14", "m:He_3:2", "m:NO2:28", "m:CO2:28", "m:H:14", "m:D:14"), sp("i:dust:Sand:1", "i:dustTiny:Basalt:1", "i:dustTiny:Al2O3:1", "i:dustTiny:Ilmenite:1", "i:dustTiny:MnO2:1", "i:dustTiny:MeteoricIron:1"));
        r("Bath", 0, 256, ch(10000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:Au:1"), sp("m:AquaRegia:6500"), sp("m:ChloroauricAcid:3000", "m:NO:1000", "w:3000"), sp("i:crushedCentrifuged:Au:1", "i:crushedCentrifugedTiny:Cu:2", "i:crushedCentrifugedTiny:Cu:2", "i:crushedCentrifugedTiny:Cu:2", "i:crushedCentrifugedTiny:Cu:2", "i:crushedCentrifugedTiny:Cu:2"));
        r("Bath", 0, 256, ch(10000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:Au:9"), sp("m:AquaRegia:6500"), sp("m:ChloroauricAcid:3000", "m:NO:1000", "w:3000"), sp("i:crushedCentrifuged:Au:1", "i:crushedCentrifugedTiny:Cu:2", "i:crushedCentrifugedTiny:Cu:2", "i:crushedCentrifugedTiny:Cu:2", "i:crushedCentrifugedTiny:Cu:2", "i:crushedCentrifugedTiny:Cu:2"));
        r("Bath", 0, 256, ch(10000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:Cu:1"), sp("m:AquaRegia:6500"), sp("m:ChloroauricAcid:3000", "m:NO:1000", "w:3000"), sp("i:crushedCentrifuged:Cu:1", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2"));
        r("Bath", 0, 256, ch(10000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:Cu:9"), sp("m:AquaRegia:6500"), sp("m:ChloroauricAcid:3000", "m:NO:1000", "w:3000"), sp("i:crushedCentrifuged:Cu:1", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2"));
        r("Bath", 0, 256, ch(10000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:Midasium:1"), sp("m:AquaRegia:6500"), sp("m:ChloroauricAcid:3000", "m:NO:1000", "w:3000"), sp("i:crushedCentrifuged:Midasium:1", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2"));
        r("Bath", 0, 256, ch(10000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:Midasium:9"), sp("m:AquaRegia:6500"), sp("m:ChloroauricAcid:3000", "m:NO:1000", "w:3000"), sp("i:crushedCentrifuged:Midasium:1", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2", "i:crushedCentrifugedTiny:Co:2"));
        r("Bath", 0, 256, ch(10000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:Sn:1"), sp("m:AquaRegia:13000"), sp("m:StannicChloride:2500", "m:HCl:4000", "m:NO2:3000"), sp("i:crushedCentrifuged:Sn:1", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2"));
        r("Bath", 0, 256, ch(10000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:Sn:9"), sp("m:AquaRegia:13000"), sp("m:StannicChloride:2500", "m:HCl:4000", "m:NO2:3000"), sp("i:crushedCentrifuged:Sn:1", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2"));
        r("Bath", 0, 256, ch(10000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:Cassiterite:1"), sp("m:AquaRegia:13000"), sp("m:StannicChloride:2500", "m:HCl:4000", "m:NO2:3000"), sp("i:crushedCentrifuged:Cassiterite:1", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2"));
        r("Bath", 0, 256, ch(10000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:Cassiterite:9"), sp("m:AquaRegia:13000"), sp("m:StannicChloride:2500", "m:HCl:4000", "m:NO2:3000"), sp("i:crushedCentrifuged:Cassiterite:1", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2", "i:crushedCentrifugedTiny:Zn:2"));
        r("Bath", 0, 256, null, sp("i:blockDust:Amber:1"), sp("m:Cryotheum:100"), NONE, sp("i:gemExquisite:Amber:1"));
        r("Bath", 0, 256, null, sp("i:crushed:Amber:1"), sp("m:Cryotheum:50"), NONE, sp("i:gemFlawless:Amber:1"));
        r("Bath", 0, 256, null, sp("i:crushedTiny:Amber:9"), sp("m:Cryotheum:50"), NONE, sp("i:gemFlawless:Amber:1"));
        r("Bath", 0, 256, null, sp("i:blockDust:Glowstone:1"), sp("m:Cryotheum:100"), NONE, sp("i:gemExquisite:Glowstone:1"));
        r("Bath", 0, 256, null, sp("i:crushed:Glowstone:1"), sp("m:Cryotheum:50"), NONE, sp("i:gemFlawless:Glowstone:1"));
        r("Bath", 0, 256, null, sp("i:crushedTiny:Glowstone:9"), sp("m:Cryotheum:50"), NONE, sp("i:gemFlawless:Glowstone:1"));
        r("Sifting", 16, 144, ch(8000, 2000), sp("tech:bop_grass_smoldering:1"), NONE, NONE, sp("v:dirt:1", "omd:Ash:250"));
        r("Sifting", 16, 144, ch(4500, 3000, 250, 100), sp("v:dirt:1"), NONE, NONE, sp("omd:Sand:1000", "omd:Stone:1000", "omd:ClayBrown:1000", "tech:clay_ball_brown:1"));
        r("Sifting", 16, 144, ch(4500, 3000, 250, 100, 4500), sp("tech:salt_dirt_1:1"), NONE, NONE, sp("omd:Sand:1000", "omd:Stone:1000", "omd:ClayBrown:1000", "tech:clay_ball_brown:1", "i:dust:NaCl:1"));
        r("Sifting", 16, 144, ch(4500, 3000, 250, 100, 9000), sp("tech:salt_dirt_2:1"), NONE, NONE, sp("omd:Sand:1000", "omd:Stone:1000", "omd:ClayBrown:1000", "tech:clay_ball_brown:1", "i:dust:NaCl:1"));
        r("Sifting", 16, 144, ch(4500, 3000, 250, 100, 9000), sp("tech:salt_dirt_3:1"), NONE, NONE, sp("omd:Sand:1000", "omd:Stone:1000", "omd:ClayBrown:1000", "tech:clay_ball_brown:1", "i:dust:NaCl:2"));
        r("Sifting", 16, 144, ch(4500, 3000, 1000, 400), sp("tech:bop_coarse_loamy:1"), NONE, NONE, sp("omd:Sand:1000", "omd:Stone:1000", "omd:Palygorskite:1000", "tech:clay_ball_blue:1"));
        r("Sifting", 16, 144, ch(4500, 6000, 250, 100), sp("tech:bop_coarse_silty:1"), NONE, NONE, sp("omd:Sand:1000", "omd:Siltstone:1000", "omd:Kaolinite:1000", "tech:clay_ball_white:1"));
        r("Sifting", 16, 144, ch(9000, 3000, 250, 100), sp("tech:bop_coarse_sandy:1"), NONE, NONE, sp("omd:Sand:2000", "omd:Stone:1000", "omd:Bentonite:1000", "tech:clay_ball_yellow:1"));
        r("Sifting", 16, 144, ch(9000, 2500, 250, 100), sp("tech:bop_dirt_dried:1"), NONE, NONE, sp("omd:Sand:1000", "omd:Stone:1000", "omd:Bentonite:1000", "tech:clay_ball_yellow:1"));
        r("Sifting", 16, 144, ch(9000, 2500, 250, 100), sp("tech:bop_dirt_hard:1"), NONE, NONE, sp("omd:Sand:1000", "omd:Stone:1000", "omd:Bentonite:1000", "tech:clay_ball_yellow:1"));
        r("Sifting", 16, 144, ch(9000, 2000), sp("tech:bop_mud:1"), NONE, NONE, sp("v:dirt:1", "tech:macu_bait_worm:2"));
        r("Sifting", 16, 144, ch(9000, 2000), sp("tech:ere_mud:1"), NONE, NONE, sp("v:dirt:1", "tech:macu_bait_worm:2"));
        r("Sifting", 16, 144, ch(9000, 2000), sp("tech:btl_mud:1"), NONE, NONE, sp("v:dirt:1", "tech:macu_bait_worm:2"));
        r("Sifting", 16, 144, ch(8000, 1000, 500, 500, 500), sp("v:dirt:1"), NONE, NONE, sp("v:dirt:1", "omd:Ash:250", "tech:macu_bait_ant:2", "tech:macu_bait_maggot:1", "tech:macu_bait_worm:1"));
        r("Sifting", 16, 144, ch(8000, 1000, 1000), sp("v:mycelium:1"), NONE, NONE, sp("v:dirt:1", "v:brown_mushroom:1", "v:red_mushroom:1"));
        r("Sifting", 16, 144, ch(1000, 500, 50, 50, 25, 250, 500, 50, 25), sp("omd:SoulSand:1000"), NONE, NONE, sp("omd:Netherrack:1000", "i:rockGt:Netherrack:1", "omd:ClayRed:1000", "tech:clay_ball_red:1", "omd:Niter:250", "omd:NetherQuartz:250", "i:gem:NetherQuartz:1", "v:bone:1", "v:nether_wart:1"));
        r("Sifting", 16, 144, ch(1000, 500, 50, 50, 25, 250, 500, 50, 25), sp("v:soul_sand:1"), NONE, NONE, sp("omd:Netherrack:9000", "i:rockGt:Netherrack:9", "omd:ClayRed:9000", "tech:clay_ball_red:9", "omd:Niter:2250", "omd:NetherQuartz:2250", "i:gem:NetherQuartz:9", "v:bone:9", "v:nether_wart:9"));
        r("Sifting", 16, 144, ch(9000, 2000), sp("tech:aether_sand:1"), NONE, NONE, sp("omd:Sand:9000", "tech:macu_bait_ant:1"));
        r("Sifting", 16, 144, ch(9000, 2000), sp("tech:bop_quicksand:1"), NONE, NONE, sp("omd:Sand:9000", "tech:macu_bait_ant:1"));
        r("Sifting", 16, 144, ch(10000), sp("tech:bop_sand_hard:1"), NONE, NONE, sp("omd:Sand:9000"));
        r("Sifting", 16, 144, ch(10000, 90, 360, 1350, 1800, 3600, 4500), sp("i:crushedPurified:Asbestos:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:Asbestos:9", "i:gemExquisite:Jade:1", "i:gemFlawless:Jade:1", "i:gem:Jade:1", "i:gemFlawed:Jade:2", "i:gemChipped:Jade:4", "i:dust:Jade:1"));
        r("Sifting", 16, 16, ch(10000, 10, 40, 150, 200, 400, 500), sp("i:crushedPurifiedTiny:Asbestos:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:Asbestos:1", "i:gemExquisite:Jade:1", "i:gemFlawless:Jade:1", "i:gem:Jade:1", "i:gemFlawed:Jade:2", "i:gemChipped:Jade:4", "i:dust:Jade:1"));
        r("Sifting", 16, 144, ch(10000, 90, 360, 1350, 1800, 3600, 4500), sp("i:crushedPurified:Sn:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:Sn:9", "i:gemExquisite:Zircon:1", "i:gemFlawless:Zircon:1", "i:gem:Zircon:1", "i:gemFlawed:Zircon:2", "i:gemChipped:Zircon:4", "i:dust:Zircon:1"));
        r("Sifting", 16, 16, ch(10000, 10, 40, 150, 200, 400, 500), sp("i:crushedPurifiedTiny:Sn:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:Sn:1", "i:gemExquisite:Zircon:1", "i:gemFlawless:Zircon:1", "i:gem:Zircon:1", "i:gemFlawed:Zircon:2", "i:gemChipped:Zircon:4", "i:dust:Zircon:1"));
        r("Sifting", 16, 144, ch(10000, 90, 360, 1350, 1800, 3600, 4500), sp("i:crushedPurified:Cassiterite:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:Cassiterite:9", "i:gemExquisite:Zircon:1", "i:gemFlawless:Zircon:1", "i:gem:Zircon:1", "i:gemFlawed:Zircon:2", "i:gemChipped:Zircon:4", "i:dust:Zircon:1"));
        r("Sifting", 16, 16, ch(10000, 10, 40, 150, 200, 400, 500), sp("i:crushedPurifiedTiny:Cassiterite:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:Cassiterite:1", "i:gemExquisite:Zircon:1", "i:gemFlawless:Zircon:1", "i:gem:Zircon:1", "i:gemFlawed:Zircon:2", "i:gemChipped:Zircon:4", "i:dust:Zircon:1"));
        r("Sifting", 16, 144, ch(7200, 900, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:ChargedCertusQuartz:1"), NONE, NONE, sp("i:gem:ChargedCertusQuartz:1", "i:gem:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1"));
        r("Sifting", 16, 16, ch(800, 100, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:ChargedCertusQuartz:1"), NONE, NONE, sp("i:gem:ChargedCertusQuartz:1", "i:gem:CertusQuartz:1", "i:dustTiny:CertusQuartz:1"));
        r("Sifting", 16, 144, ch(900, 7200, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:CertusQuartz:1"), NONE, NONE, sp("i:gem:ChargedCertusQuartz:1", "i:gem:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1", "i:dustTiny:CertusQuartz:1"));
        r("Sifting", 16, 16, ch(100, 800, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:CertusQuartz:1"), NONE, NONE, sp("i:gem:ChargedCertusQuartz:1", "i:gem:CertusQuartz:1", "i:dustTiny:CertusQuartz:1"));
        r("Sifting", 16, 144, ch(7200, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:NetherQuartz:1"), NONE, NONE, sp("i:gem:NetherQuartz:1", "i:dustTiny:NetherQuartz:1", "i:dustTiny:NetherQuartz:1", "i:dustTiny:NetherQuartz:1", "i:dustTiny:NetherQuartz:1", "i:dustTiny:NetherQuartz:1", "i:dustTiny:NetherQuartz:1", "i:dustTiny:NetherQuartz:1", "i:dustTiny:NetherQuartz:1", "i:dustTiny:NetherQuartz:1"));
        r("Sifting", 16, 16, ch(800, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:NetherQuartz:1"), NONE, NONE, sp("i:gem:NetherQuartz:1", "i:dustTiny:NetherQuartz:1"));
        r("Sifting", 16, 144, ch(7200, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:VoidQuartz:1"), NONE, NONE, sp("i:gem:VoidQuartz:1", "i:dustTiny:VoidQuartz:1", "i:dustTiny:VoidQuartz:1", "i:dustTiny:VoidQuartz:1", "i:dustTiny:VoidQuartz:1", "i:dustTiny:VoidQuartz:1", "i:dustTiny:VoidQuartz:1", "i:dustTiny:VoidQuartz:1", "i:dustTiny:VoidQuartz:1", "i:dustTiny:VoidQuartz:1"));
        r("Sifting", 16, 16, ch(800, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:VoidQuartz:1"), NONE, NONE, sp("i:gem:VoidQuartz:1", "i:dustTiny:VoidQuartz:1"));
        r("Sifting", 16, 144, ch(7200, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:MilkyQuartz:1"), NONE, NONE, sp("i:gem:MilkyQuartz:1", "i:dustTiny:MilkyQuartz:1", "i:dustTiny:MilkyQuartz:1", "i:dustTiny:MilkyQuartz:1", "i:dustTiny:MilkyQuartz:1", "i:dustTiny:MilkyQuartz:1", "i:dustTiny:MilkyQuartz:1", "i:dustTiny:MilkyQuartz:1", "i:dustTiny:MilkyQuartz:1", "i:dustTiny:MilkyQuartz:1"));
        r("Sifting", 16, 16, ch(800, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:MilkyQuartz:1"), NONE, NONE, sp("i:gem:MilkyQuartz:1", "i:dustTiny:MilkyQuartz:1"));
        r("Sifting", 16, 144, ch(7200, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurified:Fluix:1"), NONE, NONE, sp("i:gem:Fluix:1", "i:dustTiny:Fluix:1", "i:dustTiny:Fluix:1", "i:dustTiny:Fluix:1", "i:dustTiny:Fluix:1", "i:dustTiny:Fluix:1", "i:dustTiny:Fluix:1", "i:dustTiny:Fluix:1", "i:dustTiny:Fluix:1", "i:dustTiny:Fluix:1"));
        r("Sifting", 16, 16, ch(800, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000), sp("i:crushedPurifiedTiny:Fluix:1"), NONE, NONE, sp("i:gem:Fluix:1", "i:dustTiny:Fluix:1"));
        r("Sifting", 16, 144, ch(7500, 5000, 2500, 2500, 2500), sp("tech:tropic_sand_black:1"), NONE, NONE, sp("i:dust:Basalt:3", "i:dust:RedSand:3", "i:nugget:Au:6", "i:nugget:Cu:12", "i:nugget:Ni:3"));
        r("MagneticSeparator", 16, 144, ch(7500, 5000, 2500, 2500, 2500), sp("tech:tropic_sand_black:1"), NONE, NONE, sp("i:dust:Basalt:3", "i:dust:RedSand:6", "i:dustTiny:Au:12", "i:dustTiny:Cu:6", "i:dustTiny:Ni:6"));
        r("Centrifuge", 16, 288, ch(7500, 5000, 2500, 2500, 2500), sp("tech:tropic_sand_black:1"), NONE, NONE, sp("i:dust:Basalt:6", "i:dust:RedSand:3", "i:dustTiny:V2O5:12", "i:dustTiny:Cu:6", "i:dustTiny:Ni:3"));
        r("Lightning", 512, 2304, ch(8000), sp("tag:1", "i:crushedPurified:Dolamide:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:Dolamide:18"));
        r("Lightning", 512, 256, ch(8000), sp("tag:1", "i:crushedPurifiedTiny:Dolamide:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:Dolamide:2"));
        r("Nanofab", 64, 2048, null, sp("tag:0", "i:crushedCentrifuged:Dolamide:1"), NONE, NONE, sp("i:gem:Dilithium:2"));
        r("Nanofab", 64, 2048, null, sp("tag:0", "i:crushedCentrifugedTiny:Dolamide:9"), NONE, NONE, sp("i:gem:Dilithium:2"));
        r("Nanofab", 512, 2048, null, sp("tag:0", "i:dust:Dolamide:2"), NONE, NONE, sp("i:gem:Dilithium:1"));
        r("Nanofab", 512, 4096, null, sp("tag:0", "i:dust:Dilithium:2"), NONE, NONE, sp("i:gem:Dilithium:1"));
        r("Mixer", 16, 256, null, sp("i:crushedPurified:Yellorite:1", "i:dust:Al:1"), NONE, NONE, sp("i:crushedCentrifuged:Yellorium:1"));
        r("Mixer", 16, 256, null, sp("i:crushedPurifiedTiny:Yellorite:9", "i:dust:Al:1"), NONE, NONE, sp("i:crushedCentrifuged:Yellorium:1"));
        r("Mixer", 16, 256, null, sp("i:crushedPurified:Yellorite:1", "i:dust:Mg:1"), NONE, NONE, sp("i:crushedCentrifuged:Yellorium:1"));
        r("Mixer", 16, 256, null, sp("i:crushedPurifiedTiny:Yellorite:9", "i:dust:Mg:1"), NONE, NONE, sp("i:crushedCentrifuged:Yellorium:1"));
        r("Mixer", 16, 256, null, sp("i:crushedPurified:U_238:1", "i:dust:Al:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:U_238:12"));
        r("Mixer", 16, 256, null, sp("i:crushedPurifiedTiny:U_238:9", "i:dust:Al:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:U_238:12"));
        r("Mixer", 16, 256, null, sp("i:crushedPurified:U_238:1", "i:dust:Mg:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:U_238:12"));
        r("Mixer", 16, 256, null, sp("i:crushedPurifiedTiny:U_238:9", "i:dust:Mg:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:U_238:12"));
        r("Mixer", 16, 256, null, sp("i:crushedPurified:U_235:1", "i:dust:Al:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:U_235:12"));
        r("Mixer", 16, 256, null, sp("i:crushedPurifiedTiny:U_235:9", "i:dust:Al:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:U_235:12"));
        r("Mixer", 16, 256, null, sp("i:crushedPurified:U_235:1", "i:dust:Mg:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:U_235:12"));
        r("Mixer", 16, 256, null, sp("i:crushedPurifiedTiny:U_235:9", "i:dust:Mg:1"), NONE, NONE, sp("i:crushedCentrifugedTiny:U_235:12"));
        r("Centrifuge", 256, 256, ch(10000, 150, 150), sp("i:crushedCentrifugedTiny:Be:1"), NONE, NONE, sp("i:dustTiny:Be:1", "i:dustTiny:Be_7:8", "i:dustTiny:Be_8:8"));
        r("Centrifuge", 256, 2304, ch(10000, 1350, 1350), sp("i:crushedCentrifuged:Be:1"), NONE, NONE, sp("i:dust:Be:1", "i:dustTiny:Be_7:8", "i:dustTiny:Be_8:8"));
        r("Centrifuge", 256, 256, ch(10000, 300), sp("i:crushedCentrifugedTiny:Li:1"), NONE, NONE, sp("i:dustTiny:Li:1", "i:dustTiny:Li_6:8"));
        r("Centrifuge", 256, 2304, ch(10000, 2700), sp("i:crushedCentrifuged:Li:1"), NONE, NONE, sp("i:dust:Li:1", "i:dustTiny:Li_6:8"));
        r("Centrifuge", 256, 256, ch(10000, 300), sp("i:crushedCentrifugedTiny:B:1"), NONE, NONE, sp("i:dustTiny:B:1", "i:dustTiny:B_11:8"));
        r("Centrifuge", 256, 2304, ch(10000, 2700), sp("i:crushedCentrifuged:B:1"), NONE, NONE, sp("i:dust:B:1", "i:dustTiny:B_11:8"));
        r("Centrifuge", 256, 256, ch(10000, 150, 150), sp("i:crushedCentrifugedTiny:C:1"), NONE, NONE, sp("i:dustTiny:C:1", "i:dustTiny:C_13:8", "i:dustTiny:C_14:8"));
        r("Centrifuge", 256, 2304, ch(10000, 1350, 1350), sp("i:crushedCentrifuged:C:1"), NONE, NONE, sp("i:dust:C:1", "i:dustTiny:C_13:8", "i:dustTiny:C_14:8"));
        r("Centrifuge", 512, 256, ch(10000, 300), sp("i:crushedCentrifugedTiny:Co:1"), NONE, NONE, sp("i:dustTiny:Co:1", "i:dustTiny:Co_60:8"));
        r("Centrifuge", 512, 2304, ch(10000, 2700), sp("i:crushedCentrifuged:Co:1"), NONE, NONE, sp("i:dust:Co:1", "i:dustTiny:Co_60:8"));
        r("Centrifuge", 1024, 256, ch(10000, 200, 100), sp("i:crushedCentrifugedTiny:U_238:1"), NONE, NONE, sp("i:dustTiny:U_238:1", "i:dustTiny:U_235:8", "i:dustTiny:U_233:8"));
        r("Centrifuge", 1024, 2304, ch(10000, 1800, 900), sp("i:crushedCentrifuged:U_238:1"), NONE, NONE, sp("i:dust:U_238:1", "i:dustTiny:U_235:8", "i:dustTiny:U_233:8"));
        r("Centrifuge", 1024, 256, ch(10000, 150, 150), sp("i:crushedCentrifugedTiny:Pu:1"), NONE, NONE, sp("i:dustTiny:Pu:1", "i:dustTiny:Pu_241:8", "i:dustTiny:Pu_243:8"));
        r("Centrifuge", 1024, 2304, ch(10000, 1350, 1350), sp("i:crushedCentrifuged:Pu:1"), NONE, NONE, sp("i:dust:Pu:1", "i:dustTiny:Pu_241:8", "i:dustTiny:Pu_243:8"));
        r("Centrifuge", 1024, 256, ch(10000, 300), sp("i:crushedCentrifugedTiny:Am:1"), NONE, NONE, sp("i:dustTiny:Am:1", "i:dustTiny:Am_241:8"));
        r("Centrifuge", 1024, 2304, ch(10000, 2700), sp("i:crushedCentrifuged:Am:1"), NONE, NONE, sp("i:dust:Am:1", "i:dustTiny:Am_241:8"));
        r("Centrifuge", 1536, 256, ch(10000, 300), sp("i:crushedCentrifugedTiny:Fl:1"), NONE, NONE, sp("i:dustTiny:Fl:1", "i:dustTiny:Fl_298:8"));
        r("Centrifuge", 1536, 2304, ch(10000, 2700), sp("i:crushedCentrifuged:Fl:1"), NONE, NONE, sp("i:dust:Fl:1", "i:dustTiny:Fl_298:8"));
    }
}
