package com.gregtech.gregtech.loaders.c;

/**
 * GT6 recipes transpiled from {@code Loader_Recipes_Temporary}
 * (34 of 90 RM calls translated into 34 recipes; the rest
 * reference cross-mod content or untranslatable expressions).
 *
 * <p>GENERATED by tools/transpile_gt6_chem.py temporary — do not edit by hand.
 * Spec resolution happens in {@link GTGeneratedChem}.</p>
 */
final class GTTemporaryGen {
    private static final String[] NONE = new String[0];

    private GTTemporaryGen() {}

    private static String[] sp(String... specs) { return specs; }

    private static long[] ch(long... chances) { return chances; }

    private static void r(String map, long eut, long dur, long[] chances,
                          String[] itemIn, String[] fluidIn, String[] fluidOut, String[] itemOut) {
        GTGeneratedChem.register(map, eut, dur, chances, itemIn, fluidIn, fluidOut, itemOut);
    }

    static void load() {
        r("Extruder", 512, 512, null, sp("i:dust:Graphite:1", "tech:extruder_shape_rod:1"), NONE, NONE, sp("i:stick:Graphite:1"));
        r("Extruder", 512, 512, null, sp("i:dust:Graphite:2", "tech:extruder_shape_longrod:1"), NONE, NONE, sp("i:stickLong:Graphite:1"));
        r("Injector", 16, 16, null, sp("omd:Lapis:1000"), sp("f:DistW:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Lapis:2000"), sp("f:SpDew:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Lapis:2000"), sp("f:MnWtr:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Lapis:2000"), sp("w:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Lazurite:1000"), sp("f:DistW:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Lazurite:2000"), sp("f:SpDew:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Lazurite:2000"), sp("f:MnWtr:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Lazurite:2000"), sp("w:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Sodalite:1000"), sp("f:DistW:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Sodalite:2000"), sp("f:SpDew:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Sodalite:2000"), sp("f:MnWtr:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Injector", 16, 16, null, sp("omd:Sodalite:2000"), sp("w:1000"), sp("f:Coolant_IC2:1000"), NONE);
        r("Bath", 0, 16, null, sp("tech:neli_reed:1"), sp("w:250"), NONE, sp("v:paper:1"));
        r("Loom", 16, 16, null, sp("tag:0", "tech:neli_reed:1"), NONE, NONE, sp("v:paper:1"));
        r("Shredder", 16, 16, null, sp("tech:neli_reed:1"), NONE, NONE, sp("tech:remains_plant:1"));
        r("Mixer", 16, 16, null, sp("tech:neli_foxfire_lily:1", "i:dustTiny:Blaze:1"), NONE, NONE, sp("tech:neli_foxfire_powder:1"));
        r("Mixer", 16, 144, null, sp("tech:neli_foxfire_lily:9", "i:dust:Blaze:1"), NONE, NONE, sp("tech:neli_foxfire_powder:9"));
        r("Distillery", 16, 32, null, sp("tech:neli_wart_crimson:1"), sp("f:DistW:500"), sp("f:Potion_Awkward:500"), NONE);
        r("Distillery", 16, 32, null, sp("tech:neli_wart_warped:1"), sp("f:DistW:500"), sp("f:Potion_Thick:500"), NONE);
        r("Distillery", 16, 32, null, sp("tech:neli_wart_warped:1"), sp("f:Potion_Awkward:500"), sp("f:Potion_NightVision_1:500"), NONE);
        r("Distillery", 16, 32, null, sp("tech:neli_wart_soggy:1"), sp("f:DistW:500"), sp("f:Potion_Mundane:500"), NONE);
        r("Distillery", 16, 32, null, sp("tech:neli_wart_soggy:1"), sp("f:Potion_Awkward:500"), sp("f:Potion_FireResistance_1:500"), NONE);
        r("Distillery", 16, 48, null, sp("tech:neli_wither_rose:1"), sp("f:Potion_Thick:750"), sp("f:Potion_Harm_2:750"), NONE);
        r("Distillery", 16, 48, null, sp("tech:neli_bone_rose:1"), sp("f:Potion_Mundane:750"), sp("f:Potion_Jump_1:750"), NONE);
        r("Distillery", 16, 48, null, sp("tech:neli_soul_rose:1"), sp("f:Potion_Awkward:250"), sp("f:Potion_Invisibility_1:250"), NONE);
        r("Distillery", 16, 48, null, sp("tech:neli_foxfire_powder:1"), sp("f:Potion_Mundane:750"), sp("f:Potion_Strength_2:750"), NONE);
        r("Sifting", 16, 200, ch(5000, 5000), sp("tech:rh_sand_olivine:1"), NONE, NONE, sp("i:gem:Peridot:1", "i:dust:Peridot:1"));
        r("Sifting", 16, 200, ch(9000, 1000), sp("tech:rh_sand_gypsum:1"), NONE, NONE, sp("i:dust:Gypsum:1", "i:dust:S:1"));
        r("Sifting", 16, 200, ch(9900, 500, 500), sp("tech:rh_sand_magnetite:1"), NONE, NONE, sp("i:dust:GraniticMineralSand:1", "i:rockGt:GraniteBlack:1", "i:nugget:Au:1"));
        r("MagneticSeparator", 16, 144, ch(9900, 500, 500, 500), sp("tech:rh_sand_magnetite:1"), NONE, NONE, sp("i:dust:GraniticMineralSand:1", "i:rockGt:GraniteBlack:1", "i:nugget:Au:1", "i:dustTiny:Au:2"));
        r("Centrifuge", 16, 256, ch(9000, 1000), sp("tech:rh_sand_magnetite:1"), NONE, NONE, sp("i:dust:GraniticMineralSand:1", "i:dust:V2O5:1"));
        r("Sifting", 16, 200, ch(9900, 200, 100, 50), sp("tech:rh_sand_coral:1"), NONE, NONE, sp("v:sand:1", "i:gem:Azurite:1", "i:gem:Eudialyte:1", "i:gem:Zr:1"));
    }
}
