package com.gregtech.gregtech.content.recipe;

import com.gregtech.gregtech.api.material.GTMaterial;
import com.gregtech.gregtech.api.material.GTMaterialRegistry;
import com.gregtech.gregtech.api.prefix.PrefixRegistry;
import com.gregtech.gregtech.data.MaterialGroups;
import com.gregtech.gregtech.data.MaterialPrefix;
import com.gregtech.gregtech.data.generated.GT6Materials;
import java.util.List;

/** Generated from original GT6 MultiItemRandomTools and MTE firing rows; LGPL, original authors retained. */
public final class ClayMoldCatalog {
    private ClayMoldCatalog() {}
    public static final String SHAPE_KEY = "gt.mold.shape";
    public record Raw(String id, int shape) {}
    public record Form(String prefix, String family) {
        public String tag() { return ("molds/forms/" + prefix + "/" + family).toLowerCase(java.util.Locale.ROOT); }
        public boolean accepts(MaterialPrefix actual, GTMaterial material) {
            // OP.casingSmall is the original spelling of the port's itemCasing prefix.
            String name = prefix.equals("casingSmall") ? "itemCasing" : prefix;
            if (actual != PrefixRegistry.byName(name)) return false;
            if (family.equals("all")) return true;
            GTMaterial group = switch (family) {
                case "AnyWoodPlastic" -> MaterialGroups.WoodPlastic;
                case "AnyStone" -> MaterialGroups.Stone;
                case "AnyWax" -> MaterialGroups.Wax;
                case "AnyIron" -> MaterialGroups.Iron;
                case "AnyCu" -> MaterialGroups.Cu;
                default -> null;
            };
            if (group != null) {
                if (group.getReRegistrations().stream().anyMatch(m -> m.resolve() == material.resolve())) return true;
                return switch (family) {
                    case "AnyStone" -> FactoryFamilies.STONE.contains(material.resolve());
                    case "AnyWax" -> FactoryFamilies.WAX.contains(material.resolve());
                    // ANY:145 nests ANY.Plastic; original re-registration propagates that family.
                    case "AnyWoodPlastic" -> MaterialGroups.Plastic.getReRegistrations().stream()
                            .anyMatch(m -> m.resolve() == material.resolve());
                    default -> false;
                };
            }
            String concrete = switch (family) {
                case "Cu" -> "Copper"; case "Sn" -> "Tin"; case "Zn" -> "Zinc";
                case "Pb" -> "Lead"; case "Bi" -> "Bismuth"; case "Au" -> "Gold";
                default -> family;
            };
            return GTMaterialRegistry.get(concrete).resolve() == material.resolve();
        }
    }
    private static final class FactoryFamilies {
        private static java.util.Set<GTMaterial> members(GTMaterial... values) {
            return java.util.Arrays.stream(values).filter(GTMaterial::isValid).map(GTMaterial::resolve)
                    .collect(java.util.stream.Collectors.toUnmodifiableSet());
        }
        static final java.util.Set<GTMaterial> STONE=members(
                GT6Materials.Stones.Stone,
                GT6Materials.Stones.Concrete,
                GT6Materials.Stones.Netherrack,
                GT6Materials.Stones.NetherBrick,
                GT6Materials.Stones.Endstone,
                GT6Materials.Stones.PrismarineLight,
                GT6Materials.Stones.PrismarineDark,
                GT6Materials.Stones.Greenstone,
                GT6Materials.Stones.Bluestone,
                GT6Materials.Stones.Epidote,
                GT6Materials.Stones.SpaceRock,
                GT6Materials.Stones.MoonRock,
                GT6Materials.Stones.MoonTurf,
                GT6Materials.Stones.MarsRock,
                GT6Materials.Stones.MarsSand,
                GT6Materials.Stones.SkyStone,
                GT6Materials.Stones.Holystone,
                GT6Materials.Stones.Livingrock,
                GT6Materials.Stones.Deadrock,
                GT6Materials.Stones.Betweenstone,
                GT6Materials.Stones.Pitstone,
                GT6Materials.Stones.Cragrock,
                GT6Materials.Stones.Umber,
                GT6Materials.Stones.Shale,
                GT6Materials.Stones.Redrock,
                GT6Materials.Stones.Komatiite,
                GT6Materials.Stones.Pumice,
                GT6Materials.Stones.Gabbro,
                GT6Materials.Stones.Basalt,
                GT6Materials.Stones.Marble,
                GT6Materials.Stones.Limestone,
                GT6Materials.Stones.Greenschist,
                GT6Materials.Stones.Blueschist,
                GT6Materials.Stones.Grayschist,
                GT6Materials.Stones.Pinkschist,
                GT6Materials.Stones.Gneiss,
                GT6Materials.Stones.Kimberlite,
                GT6Materials.Stones.Quartzite,
                GT6Materials.Compounds.GraniteRed,
                GT6Materials.Compounds.GraniteBlack,
                GT6Materials.Compounds.Granite,
                GT6Materials.Stones.Andesite,
                GT6Materials.Stones.Diorite,
                GT6Materials.Stones.Greywacke,
                GT6Materials.Stones.Siltstone,
                GT6Materials.Stones.Rhyolite,
                GT6Materials.Stones.Migmatite,
                GT6Materials.Stones.Chert,
                GT6Materials.Stones.Dacite,
                GT6Materials.Stones.Slate,
                GT6Materials.Stones.Deepslate,
                GT6Materials.Stones.Eclogite,
                GT6Materials.Stones.PhobosRock,
                GT6Materials.Stones.DeimosRock,
                GT6Materials.Stones.VenusRock,
                GT6Materials.Stones.MercuryRock,
                GT6Materials.Stones.CeresRock,
                GT6Materials.Stones.JupiterRock,
                GT6Materials.Stones.IoRock,
                GT6Materials.Stones.EuropaRock,
                GT6Materials.Stones.GanymedeRock,
                GT6Materials.Stones.CallistoRock,
                GT6Materials.Stones.SaturnRock,
                GT6Materials.Stones.RheaRock,
                GT6Materials.Stones.TitanRock,
                GT6Materials.Stones.OberonRock,
                GT6Materials.Stones.IapetusRock,
                GT6Materials.Stones.UranusRock,
                GT6Materials.Stones.TitaniaRock,
                GT6Materials.Stones.NeptuneRock,
                GT6Materials.Stones.TritonRock,
                GT6Materials.Stones.PlutoRock,
                GT6Materials.Stones.ErisRock,
                GT6Materials.Stones.Kepler22bRock
        );
        static final java.util.Set<GTMaterial> WAX=members(
                GT6Materials.Compounds.Wax,
                GT6Materials.Compounds.WaxBee,
                GT6Materials.Compounds.WaxRefractory,
                GT6Materials.Compounds.WaxParaffin,
                GT6Materials.Compounds.WaxPlant,
                GT6Materials.Compounds.WaxMagic,
                GT6Materials.Compounds.WaxAmnesic,
                GT6Materials.Compounds.WaxSoulful
        );
    }
    public static final List<Raw> RAW = List.of(
            new Raw("clay_mold", 0),
            new Raw("clay_ingot_mold", 15153614),
            new Raw("clay_billet_mold", 13597056),
            new Raw("clay_chunk_mold", 25952256),
            new Raw("clay_plate_mold", 33554431),
            new Raw("clay_tiny_plate_mold", 473536),
            new Raw("clay_bolt_mold", 4224),
            new Raw("clay_rod_mold", 31744),
            new Raw("clay_long_rod_mold", 17043521),
            new Raw("clay_item_casing_mold", 31388732),
            new Raw("clay_ring_mold", 469440),
            new Raw("clay_gear_mold", 22506965),
            new Raw("clay_small_gear_mold", 11512810),
            new Raw("clay_sword_mold", 4667854),
            new Raw("clay_pickaxe_mold", 476160),
            new Raw("clay_spade_mold", 15153472),
            new Raw("clay_shovel_mold", 4667840),
            new Raw("clay_universal_spade_mold", 4665792),
            new Raw("clay_axe_mold", 473344),
            new Raw("clay_double_axe_mold", 1048096),
            new Raw("clay_saw_mold", 1047552),
            new Raw("clay_hammer_mold", 15149518),
            new Raw("clay_file_mold", 15153284),
            new Raw("clay_screwdriver_mold", 135300),
            new Raw("clay_chisel_mold", 14815364),
            new Raw("clay_arrow_mold", 135616),
            new Raw("clay_hoe_mold", 210944),
            new Raw("clay_sense_mold", 523264),
            new Raw("clay_plow_mold", 33554404),
            new Raw("clay_builders_wand_mold", 163274),
            new Raw("clay_nugget_mold", 4096)
    );
    public static final List<Form> FORMS = List.of(
            new Form("arrowGtPlastic", "all"),
            new Form("arrowGtWood", "all"),
            new Form("billet", "AnyCu"),
            new Form("billet", "AnyIron"),
            new Form("billet", "AnyStone"),
            new Form("billet", "AnyWax"),
            new Form("billet", "AnyWoodPlastic"),
            new Form("billet", "ArsenicBronze"),
            new Form("billet", "ArsenicCopper"),
            new Form("billet", "Au"),
            new Form("billet", "Bi"),
            new Form("billet", "BismuthBronze"),
            new Form("billet", "Brass"),
            new Form("billet", "Bronze"),
            new Form("billet", "Glass"),
            new Form("billet", "Pb"),
            new Form("billet", "Sn"),
            new Form("billet", "Zn"),
            new Form("bolt", "AnyCu"),
            new Form("bolt", "AnyIron"),
            new Form("bolt", "AnyStone"),
            new Form("bolt", "AnyWax"),
            new Form("bolt", "AnyWoodPlastic"),
            new Form("bolt", "ArsenicBronze"),
            new Form("bolt", "ArsenicCopper"),
            new Form("bolt", "Au"),
            new Form("bolt", "Bi"),
            new Form("bolt", "BismuthBronze"),
            new Form("bolt", "Brass"),
            new Form("bolt", "Bronze"),
            new Form("bolt", "Glass"),
            new Form("bolt", "Pb"),
            new Form("bolt", "Sn"),
            new Form("bolt", "Zn"),
            new Form("casingSmall", "AnyCu"),
            new Form("casingSmall", "AnyIron"),
            new Form("casingSmall", "AnyStone"),
            new Form("casingSmall", "AnyWax"),
            new Form("casingSmall", "AnyWoodPlastic"),
            new Form("casingSmall", "ArsenicBronze"),
            new Form("casingSmall", "ArsenicCopper"),
            new Form("casingSmall", "Au"),
            new Form("casingSmall", "Bi"),
            new Form("casingSmall", "BismuthBronze"),
            new Form("casingSmall", "Brass"),
            new Form("casingSmall", "Bronze"),
            new Form("casingSmall", "Glass"),
            new Form("casingSmall", "Pb"),
            new Form("casingSmall", "Sn"),
            new Form("casingSmall", "Zn"),
            new Form("chunkGt", "AnyCu"),
            new Form("chunkGt", "AnyIron"),
            new Form("chunkGt", "AnyStone"),
            new Form("chunkGt", "AnyWax"),
            new Form("chunkGt", "AnyWoodPlastic"),
            new Form("chunkGt", "ArsenicBronze"),
            new Form("chunkGt", "ArsenicCopper"),
            new Form("chunkGt", "Au"),
            new Form("chunkGt", "Bi"),
            new Form("chunkGt", "BismuthBronze"),
            new Form("chunkGt", "Brass"),
            new Form("chunkGt", "Bronze"),
            new Form("chunkGt", "Glass"),
            new Form("chunkGt", "Pb"),
            new Form("chunkGt", "Sn"),
            new Form("chunkGt", "Zn"),
            new Form("gearGt", "AnyCu"),
            new Form("gearGt", "AnyIron"),
            new Form("gearGt", "AnyStone"),
            new Form("gearGt", "AnyWax"),
            new Form("gearGt", "AnyWoodPlastic"),
            new Form("gearGt", "ArsenicBronze"),
            new Form("gearGt", "ArsenicCopper"),
            new Form("gearGt", "Au"),
            new Form("gearGt", "Bi"),
            new Form("gearGt", "BismuthBronze"),
            new Form("gearGt", "Brass"),
            new Form("gearGt", "Bronze"),
            new Form("gearGt", "Glass"),
            new Form("gearGt", "Pb"),
            new Form("gearGt", "Sn"),
            new Form("gearGt", "Zn"),
            new Form("gearGtSmall", "AnyCu"),
            new Form("gearGtSmall", "AnyIron"),
            new Form("gearGtSmall", "AnyStone"),
            new Form("gearGtSmall", "AnyWax"),
            new Form("gearGtSmall", "AnyWoodPlastic"),
            new Form("gearGtSmall", "ArsenicBronze"),
            new Form("gearGtSmall", "ArsenicCopper"),
            new Form("gearGtSmall", "Au"),
            new Form("gearGtSmall", "Bi"),
            new Form("gearGtSmall", "BismuthBronze"),
            new Form("gearGtSmall", "Brass"),
            new Form("gearGtSmall", "Bronze"),
            new Form("gearGtSmall", "Glass"),
            new Form("gearGtSmall", "Pb"),
            new Form("gearGtSmall", "Sn"),
            new Form("gearGtSmall", "Zn"),
            new Form("ingot", "AnyCu"),
            new Form("ingot", "AnyIron"),
            new Form("ingot", "AnyStone"),
            new Form("ingot", "AnyWax"),
            new Form("ingot", "AnyWoodPlastic"),
            new Form("ingot", "ArsenicBronze"),
            new Form("ingot", "ArsenicCopper"),
            new Form("ingot", "Au"),
            new Form("ingot", "Bi"),
            new Form("ingot", "BismuthBronze"),
            new Form("ingot", "Brass"),
            new Form("ingot", "Brick"),
            new Form("ingot", "Bronze"),
            new Form("ingot", "Glass"),
            new Form("ingot", "Pb"),
            new Form("ingot", "Sn"),
            new Form("ingot", "Zn"),
            new Form("nugget", "AnyCu"),
            new Form("nugget", "AnyIron"),
            new Form("nugget", "AnyStone"),
            new Form("nugget", "AnyWax"),
            new Form("nugget", "AnyWoodPlastic"),
            new Form("nugget", "ArsenicBronze"),
            new Form("nugget", "ArsenicCopper"),
            new Form("nugget", "Au"),
            new Form("nugget", "Bi"),
            new Form("nugget", "BismuthBronze"),
            new Form("nugget", "Brass"),
            new Form("nugget", "Bronze"),
            new Form("nugget", "Glass"),
            new Form("nugget", "Pb"),
            new Form("nugget", "Sn"),
            new Form("nugget", "Zn"),
            new Form("plate", "AnyCu"),
            new Form("plate", "AnyIron"),
            new Form("plate", "AnyStone"),
            new Form("plate", "AnyWax"),
            new Form("plate", "AnyWoodPlastic"),
            new Form("plate", "ArsenicBronze"),
            new Form("plate", "ArsenicCopper"),
            new Form("plate", "Au"),
            new Form("plate", "Bi"),
            new Form("plate", "BismuthBronze"),
            new Form("plate", "Brass"),
            new Form("plate", "Bronze"),
            new Form("plate", "Glass"),
            new Form("plate", "Pb"),
            new Form("plate", "Sn"),
            new Form("plate", "Zn"),
            new Form("plateGem", "AnyCu"),
            new Form("plateGem", "AnyIron"),
            new Form("plateGem", "AnyStone"),
            new Form("plateGem", "AnyWax"),
            new Form("plateGem", "AnyWoodPlastic"),
            new Form("plateGem", "ArsenicBronze"),
            new Form("plateGem", "ArsenicCopper"),
            new Form("plateGem", "Au"),
            new Form("plateGem", "Bi"),
            new Form("plateGem", "BismuthBronze"),
            new Form("plateGem", "Brass"),
            new Form("plateGem", "Bronze"),
            new Form("plateGem", "Glass"),
            new Form("plateGem", "Pb"),
            new Form("plateGem", "Sn"),
            new Form("plateGem", "Zn"),
            new Form("plateGemTiny", "AnyCu"),
            new Form("plateGemTiny", "AnyIron"),
            new Form("plateGemTiny", "AnyStone"),
            new Form("plateGemTiny", "AnyWax"),
            new Form("plateGemTiny", "AnyWoodPlastic"),
            new Form("plateGemTiny", "ArsenicBronze"),
            new Form("plateGemTiny", "ArsenicCopper"),
            new Form("plateGemTiny", "Au"),
            new Form("plateGemTiny", "Bi"),
            new Form("plateGemTiny", "BismuthBronze"),
            new Form("plateGemTiny", "Brass"),
            new Form("plateGemTiny", "Bronze"),
            new Form("plateGemTiny", "Glass"),
            new Form("plateGemTiny", "Pb"),
            new Form("plateGemTiny", "Sn"),
            new Form("plateGemTiny", "Zn"),
            new Form("plateTiny", "AnyCu"),
            new Form("plateTiny", "AnyIron"),
            new Form("plateTiny", "AnyStone"),
            new Form("plateTiny", "AnyWax"),
            new Form("plateTiny", "AnyWoodPlastic"),
            new Form("plateTiny", "ArsenicBronze"),
            new Form("plateTiny", "ArsenicCopper"),
            new Form("plateTiny", "Au"),
            new Form("plateTiny", "Bi"),
            new Form("plateTiny", "BismuthBronze"),
            new Form("plateTiny", "Brass"),
            new Form("plateTiny", "Bronze"),
            new Form("plateTiny", "Glass"),
            new Form("plateTiny", "Pb"),
            new Form("plateTiny", "Sn"),
            new Form("plateTiny", "Zn"),
            new Form("ring", "AnyCu"),
            new Form("ring", "AnyIron"),
            new Form("ring", "AnyStone"),
            new Form("ring", "AnyWax"),
            new Form("ring", "AnyWoodPlastic"),
            new Form("ring", "ArsenicBronze"),
            new Form("ring", "ArsenicCopper"),
            new Form("ring", "Au"),
            new Form("ring", "Bi"),
            new Form("ring", "BismuthBronze"),
            new Form("ring", "Brass"),
            new Form("ring", "Bronze"),
            new Form("ring", "Glass"),
            new Form("ring", "Pb"),
            new Form("ring", "Sn"),
            new Form("ring", "Zn"),
            new Form("stick", "AnyCu"),
            new Form("stick", "AnyIron"),
            new Form("stick", "AnyStone"),
            new Form("stick", "AnyWax"),
            new Form("stick", "AnyWoodPlastic"),
            new Form("stick", "ArsenicBronze"),
            new Form("stick", "ArsenicCopper"),
            new Form("stick", "Au"),
            new Form("stick", "Bi"),
            new Form("stick", "BismuthBronze"),
            new Form("stick", "Brass"),
            new Form("stick", "Bronze"),
            new Form("stick", "Glass"),
            new Form("stick", "Pb"),
            new Form("stick", "Sn"),
            new Form("stick", "Zn"),
            new Form("stickLong", "AnyCu"),
            new Form("stickLong", "AnyIron"),
            new Form("stickLong", "AnyStone"),
            new Form("stickLong", "AnyWax"),
            new Form("stickLong", "AnyWoodPlastic"),
            new Form("stickLong", "ArsenicBronze"),
            new Form("stickLong", "ArsenicCopper"),
            new Form("stickLong", "Au"),
            new Form("stickLong", "Bi"),
            new Form("stickLong", "BismuthBronze"),
            new Form("stickLong", "Brass"),
            new Form("stickLong", "Bronze"),
            new Form("stickLong", "Glass"),
            new Form("stickLong", "Pb"),
            new Form("stickLong", "Sn"),
            new Form("stickLong", "Zn"),
            new Form("toolHeadArrow", "all"),
            new Form("toolHeadAxe", "all"),
            new Form("toolHeadAxeDouble", "all"),
            new Form("toolHeadBuilderwand", "all"),
            new Form("toolHeadChisel", "all"),
            new Form("toolHeadFile", "all"),
            new Form("toolHeadHammer", "all"),
            new Form("toolHeadHoe", "all"),
            new Form("toolHeadPickaxe", "all"),
            new Form("toolHeadPlow", "all"),
            new Form("toolHeadRawArrow", "all"),
            new Form("toolHeadRawAxe", "all"),
            new Form("toolHeadRawAxeDouble", "all"),
            new Form("toolHeadRawChisel", "all"),
            new Form("toolHeadRawHoe", "all"),
            new Form("toolHeadRawPickaxe", "all"),
            new Form("toolHeadRawPlow", "all"),
            new Form("toolHeadRawSaw", "all"),
            new Form("toolHeadRawSense", "all"),
            new Form("toolHeadRawShovel", "all"),
            new Form("toolHeadRawSpade", "all"),
            new Form("toolHeadRawSword", "all"),
            new Form("toolHeadRawUniversalSpade", "all"),
            new Form("toolHeadSaw", "all"),
            new Form("toolHeadScrewdriver", "all"),
            new Form("toolHeadSense", "all"),
            new Form("toolHeadShovel", "all"),
            new Form("toolHeadSpade", "all"),
            new Form("toolHeadSword", "all"),
            new Form("toolHeadUniversalSpade", "all")
    );
    public static final List<String> FILES = List.of(
            "clay_molds/form_clay_mold.json",
            "clay_molds/imprint_137_all.json",
            "clay_molds/imprint_138_all.json",
            "clay_molds/imprint_139_all.json",
            "clay_molds/imprint_140_all.json",
            "clay_molds/imprint_141_all.json",
            "clay_molds/imprint_142_all.json",
            "clay_molds/imprint_143_all.json",
            "clay_molds/imprint_144_all.json",
            "clay_molds/imprint_145_all.json",
            "clay_molds/imprint_146_all.json",
            "clay_molds/imprint_147_all.json",
            "clay_molds/imprint_148_all.json",
            "clay_molds/imprint_149_all.json",
            "clay_molds/imprint_150_all.json",
            "clay_molds/imprint_151_all.json",
            "clay_molds/imprint_152_all.json",
            "clay_molds/imprint_153_all.json",
            "clay_molds/imprint_154_all.json",
            "clay_molds/imprint_155_all.json",
            "clay_molds/imprint_156_all.json",
            "clay_molds/imprint_157_all.json",
            "clay_molds/imprint_158_all.json",
            "clay_molds/imprint_159_all.json",
            "clay_molds/imprint_160_all.json",
            "clay_molds/imprint_161_all.json",
            "clay_molds/imprint_162_all.json",
            "clay_molds/imprint_163_all.json",
            "clay_molds/imprint_164_all.json",
            "clay_molds/imprint_165_all.json",
            "clay_molds/imprint_166_all.json",
            "clay_molds/imprint_167_all.json",
            "clay_molds/imprint_168_all.json",
            "clay_molds/imprint_169_all.json",
            "clay_molds/imprint_170_all.json",
            "clay_molds/imprint_171_all.json",
            "clay_molds/imprint_172_all.json",
            "clay_molds/imprint_175_all.json",
            "clay_molds/imprint_176_all.json",
            "clay_molds/imprint_177_all.json",
            "clay_molds/imprint_178_all.json",
            "clay_molds/imprint_179_all.json",
            "clay_molds/imprint_180_all.json",
            "clay_molds/imprint_181_all.json",
            "clay_molds/imprint_182_all.json",
            "clay_molds/imprint_183_all.json",
            "clay_molds/imprint_184_all.json",
            "clay_molds/imprint_185_all.json",
            "clay_molds/imprint_186_all.json",
            "clay_molds/imprint_187_all.json",
            "clay_molds/imprint_188_all.json",
            "clay_molds/imprint_189_all.json",
            "clay_molds/imprint_190_all.json",
            "clay_molds/imprint_191_all.json",
            "clay_molds/imprint_192_all.json",
            "clay_molds/imprint_193_all.json",
            "clay_molds/imprint_194_all.json",
            "clay_molds/imprint_195_all.json",
            "clay_molds/imprint_196_all.json",
            "clay_molds/imprint_197_all.json",
            "clay_molds/imprint_198_all.json",
            "clay_molds/imprint_199_all.json",
            "clay_molds/imprint_200_all.json",
            "clay_molds/imprint_201_all.json",
            "clay_molds/imprint_202_all.json",
            "clay_molds/imprint_203_all.json",
            "clay_molds/imprint_204_all.json",
            "clay_molds/imprint_205_all.json",
            "clay_molds/imprint_206_all.json",
            "clay_molds/imprint_207_all.json",
            "clay_molds/imprint_208_all.json",
            "clay_molds/imprint_212_anycu.json",
            "clay_molds/imprint_212_anyiron.json",
            "clay_molds/imprint_212_anystone.json",
            "clay_molds/imprint_212_anywax.json",
            "clay_molds/imprint_212_anywoodplastic.json",
            "clay_molds/imprint_212_arsenicbronze.json",
            "clay_molds/imprint_212_arseniccopper.json",
            "clay_molds/imprint_212_au.json",
            "clay_molds/imprint_212_bi.json",
            "clay_molds/imprint_212_bismuthbronze.json",
            "clay_molds/imprint_212_brass.json",
            "clay_molds/imprint_212_bronze.json",
            "clay_molds/imprint_212_glass.json",
            "clay_molds/imprint_212_pb.json",
            "clay_molds/imprint_212_sn.json",
            "clay_molds/imprint_212_zn.json",
            "clay_molds/imprint_213_anycu.json",
            "clay_molds/imprint_213_anyiron.json",
            "clay_molds/imprint_213_anystone.json",
            "clay_molds/imprint_213_anywax.json",
            "clay_molds/imprint_213_anywoodplastic.json",
            "clay_molds/imprint_213_arsenicbronze.json",
            "clay_molds/imprint_213_arseniccopper.json",
            "clay_molds/imprint_213_au.json",
            "clay_molds/imprint_213_bi.json",
            "clay_molds/imprint_213_bismuthbronze.json",
            "clay_molds/imprint_213_brass.json",
            "clay_molds/imprint_213_bronze.json",
            "clay_molds/imprint_213_glass.json",
            "clay_molds/imprint_213_pb.json",
            "clay_molds/imprint_213_sn.json",
            "clay_molds/imprint_213_zn.json",
            "clay_molds/imprint_214_anycu.json",
            "clay_molds/imprint_214_anyiron.json",
            "clay_molds/imprint_214_anystone.json",
            "clay_molds/imprint_214_anywax.json",
            "clay_molds/imprint_214_anywoodplastic.json",
            "clay_molds/imprint_214_arsenicbronze.json",
            "clay_molds/imprint_214_arseniccopper.json",
            "clay_molds/imprint_214_au.json",
            "clay_molds/imprint_214_bi.json",
            "clay_molds/imprint_214_bismuthbronze.json",
            "clay_molds/imprint_214_brass.json",
            "clay_molds/imprint_214_bronze.json",
            "clay_molds/imprint_214_glass.json",
            "clay_molds/imprint_214_pb.json",
            "clay_molds/imprint_214_sn.json",
            "clay_molds/imprint_214_zn.json",
            "clay_molds/imprint_215_anycu.json",
            "clay_molds/imprint_215_anyiron.json",
            "clay_molds/imprint_215_anystone.json",
            "clay_molds/imprint_215_anywax.json",
            "clay_molds/imprint_215_anywoodplastic.json",
            "clay_molds/imprint_215_arsenicbronze.json",
            "clay_molds/imprint_215_arseniccopper.json",
            "clay_molds/imprint_215_au.json",
            "clay_molds/imprint_215_bi.json",
            "clay_molds/imprint_215_bismuthbronze.json",
            "clay_molds/imprint_215_brass.json",
            "clay_molds/imprint_215_bronze.json",
            "clay_molds/imprint_215_glass.json",
            "clay_molds/imprint_215_pb.json",
            "clay_molds/imprint_215_sn.json",
            "clay_molds/imprint_215_zn.json",
            "clay_molds/imprint_216_anycu.json",
            "clay_molds/imprint_216_anyiron.json",
            "clay_molds/imprint_216_anystone.json",
            "clay_molds/imprint_216_anywax.json",
            "clay_molds/imprint_216_anywoodplastic.json",
            "clay_molds/imprint_216_arsenicbronze.json",
            "clay_molds/imprint_216_arseniccopper.json",
            "clay_molds/imprint_216_au.json",
            "clay_molds/imprint_216_bi.json",
            "clay_molds/imprint_216_bismuthbronze.json",
            "clay_molds/imprint_216_brass.json",
            "clay_molds/imprint_216_bronze.json",
            "clay_molds/imprint_216_glass.json",
            "clay_molds/imprint_216_pb.json",
            "clay_molds/imprint_216_sn.json",
            "clay_molds/imprint_216_zn.json",
            "clay_molds/imprint_217_anycu.json",
            "clay_molds/imprint_217_anyiron.json",
            "clay_molds/imprint_217_anystone.json",
            "clay_molds/imprint_217_anywax.json",
            "clay_molds/imprint_217_anywoodplastic.json",
            "clay_molds/imprint_217_arsenicbronze.json",
            "clay_molds/imprint_217_arseniccopper.json",
            "clay_molds/imprint_217_au.json",
            "clay_molds/imprint_217_bi.json",
            "clay_molds/imprint_217_bismuthbronze.json",
            "clay_molds/imprint_217_brass.json",
            "clay_molds/imprint_217_bronze.json",
            "clay_molds/imprint_217_glass.json",
            "clay_molds/imprint_217_pb.json",
            "clay_molds/imprint_217_sn.json",
            "clay_molds/imprint_217_zn.json",
            "clay_molds/imprint_218_anycu.json",
            "clay_molds/imprint_218_anyiron.json",
            "clay_molds/imprint_218_anystone.json",
            "clay_molds/imprint_218_anywax.json",
            "clay_molds/imprint_218_anywoodplastic.json",
            "clay_molds/imprint_218_arsenicbronze.json",
            "clay_molds/imprint_218_arseniccopper.json",
            "clay_molds/imprint_218_au.json",
            "clay_molds/imprint_218_bi.json",
            "clay_molds/imprint_218_bismuthbronze.json",
            "clay_molds/imprint_218_brass.json",
            "clay_molds/imprint_218_bronze.json",
            "clay_molds/imprint_218_glass.json",
            "clay_molds/imprint_218_pb.json",
            "clay_molds/imprint_218_sn.json",
            "clay_molds/imprint_218_zn.json",
            "clay_molds/imprint_219_anycu.json",
            "clay_molds/imprint_219_anyiron.json",
            "clay_molds/imprint_219_anystone.json",
            "clay_molds/imprint_219_anywax.json",
            "clay_molds/imprint_219_anywoodplastic.json",
            "clay_molds/imprint_219_arsenicbronze.json",
            "clay_molds/imprint_219_arseniccopper.json",
            "clay_molds/imprint_219_au.json",
            "clay_molds/imprint_219_bi.json",
            "clay_molds/imprint_219_bismuthbronze.json",
            "clay_molds/imprint_219_brass.json",
            "clay_molds/imprint_219_bronze.json",
            "clay_molds/imprint_219_glass.json",
            "clay_molds/imprint_219_pb.json",
            "clay_molds/imprint_219_sn.json",
            "clay_molds/imprint_219_zn.json",
            "clay_molds/imprint_220_anycu.json",
            "clay_molds/imprint_220_anyiron.json",
            "clay_molds/imprint_220_anystone.json",
            "clay_molds/imprint_220_anywax.json",
            "clay_molds/imprint_220_anywoodplastic.json",
            "clay_molds/imprint_220_arsenicbronze.json",
            "clay_molds/imprint_220_arseniccopper.json",
            "clay_molds/imprint_220_au.json",
            "clay_molds/imprint_220_bi.json",
            "clay_molds/imprint_220_bismuthbronze.json",
            "clay_molds/imprint_220_brass.json",
            "clay_molds/imprint_220_bronze.json",
            "clay_molds/imprint_220_glass.json",
            "clay_molds/imprint_220_pb.json",
            "clay_molds/imprint_220_sn.json",
            "clay_molds/imprint_220_zn.json",
            "clay_molds/imprint_221_anycu.json",
            "clay_molds/imprint_221_anyiron.json",
            "clay_molds/imprint_221_anystone.json",
            "clay_molds/imprint_221_anywax.json",
            "clay_molds/imprint_221_anywoodplastic.json",
            "clay_molds/imprint_221_arsenicbronze.json",
            "clay_molds/imprint_221_arseniccopper.json",
            "clay_molds/imprint_221_au.json",
            "clay_molds/imprint_221_bi.json",
            "clay_molds/imprint_221_bismuthbronze.json",
            "clay_molds/imprint_221_brass.json",
            "clay_molds/imprint_221_bronze.json",
            "clay_molds/imprint_221_glass.json",
            "clay_molds/imprint_221_pb.json",
            "clay_molds/imprint_221_sn.json",
            "clay_molds/imprint_221_zn.json",
            "clay_molds/imprint_222_anycu.json",
            "clay_molds/imprint_222_anyiron.json",
            "clay_molds/imprint_222_anystone.json",
            "clay_molds/imprint_222_anywax.json",
            "clay_molds/imprint_222_anywoodplastic.json",
            "clay_molds/imprint_222_arsenicbronze.json",
            "clay_molds/imprint_222_arseniccopper.json",
            "clay_molds/imprint_222_au.json",
            "clay_molds/imprint_222_bi.json",
            "clay_molds/imprint_222_bismuthbronze.json",
            "clay_molds/imprint_222_brass.json",
            "clay_molds/imprint_222_bronze.json",
            "clay_molds/imprint_222_glass.json",
            "clay_molds/imprint_222_pb.json",
            "clay_molds/imprint_222_sn.json",
            "clay_molds/imprint_222_zn.json",
            "clay_molds/imprint_223_anycu.json",
            "clay_molds/imprint_223_anyiron.json",
            "clay_molds/imprint_223_anystone.json",
            "clay_molds/imprint_223_anywax.json",
            "clay_molds/imprint_223_anywoodplastic.json",
            "clay_molds/imprint_223_arsenicbronze.json",
            "clay_molds/imprint_223_arseniccopper.json",
            "clay_molds/imprint_223_au.json",
            "clay_molds/imprint_223_bi.json",
            "clay_molds/imprint_223_bismuthbronze.json",
            "clay_molds/imprint_223_brass.json",
            "clay_molds/imprint_223_bronze.json",
            "clay_molds/imprint_223_glass.json",
            "clay_molds/imprint_223_pb.json",
            "clay_molds/imprint_223_sn.json",
            "clay_molds/imprint_223_zn.json",
            "clay_molds/imprint_224_anycu.json",
            "clay_molds/imprint_224_anyiron.json",
            "clay_molds/imprint_224_anystone.json",
            "clay_molds/imprint_224_anywax.json",
            "clay_molds/imprint_224_anywoodplastic.json",
            "clay_molds/imprint_224_arsenicbronze.json",
            "clay_molds/imprint_224_arseniccopper.json",
            "clay_molds/imprint_224_au.json",
            "clay_molds/imprint_224_bi.json",
            "clay_molds/imprint_224_bismuthbronze.json",
            "clay_molds/imprint_224_brass.json",
            "clay_molds/imprint_224_bronze.json",
            "clay_molds/imprint_224_glass.json",
            "clay_molds/imprint_224_pb.json",
            "clay_molds/imprint_224_sn.json",
            "clay_molds/imprint_224_zn.json",
            "clay_molds/imprint_225_anycu.json",
            "clay_molds/imprint_225_anyiron.json",
            "clay_molds/imprint_225_anystone.json",
            "clay_molds/imprint_225_anywax.json",
            "clay_molds/imprint_225_anywoodplastic.json",
            "clay_molds/imprint_225_arsenicbronze.json",
            "clay_molds/imprint_225_arseniccopper.json",
            "clay_molds/imprint_225_au.json",
            "clay_molds/imprint_225_bi.json",
            "clay_molds/imprint_225_bismuthbronze.json",
            "clay_molds/imprint_225_brass.json",
            "clay_molds/imprint_225_bronze.json",
            "clay_molds/imprint_225_glass.json",
            "clay_molds/imprint_225_pb.json",
            "clay_molds/imprint_225_sn.json",
            "clay_molds/imprint_225_zn.json",
            "clay_molds/imprint_226_anycu.json",
            "clay_molds/imprint_226_anyiron.json",
            "clay_molds/imprint_226_anystone.json",
            "clay_molds/imprint_226_anywax.json",
            "clay_molds/imprint_226_anywoodplastic.json",
            "clay_molds/imprint_226_arsenicbronze.json",
            "clay_molds/imprint_226_arseniccopper.json",
            "clay_molds/imprint_226_au.json",
            "clay_molds/imprint_226_bi.json",
            "clay_molds/imprint_226_bismuthbronze.json",
            "clay_molds/imprint_226_brass.json",
            "clay_molds/imprint_226_bronze.json",
            "clay_molds/imprint_226_glass.json",
            "clay_molds/imprint_226_pb.json",
            "clay_molds/imprint_226_sn.json",
            "clay_molds/imprint_226_zn.json",
            "clay_molds/imprint_227_anycu.json",
            "clay_molds/imprint_227_anyiron.json",
            "clay_molds/imprint_227_anystone.json",
            "clay_molds/imprint_227_anywax.json",
            "clay_molds/imprint_227_anywoodplastic.json",
            "clay_molds/imprint_227_arsenicbronze.json",
            "clay_molds/imprint_227_arseniccopper.json",
            "clay_molds/imprint_227_au.json",
            "clay_molds/imprint_227_bi.json",
            "clay_molds/imprint_227_bismuthbronze.json",
            "clay_molds/imprint_227_brass.json",
            "clay_molds/imprint_227_bronze.json",
            "clay_molds/imprint_227_glass.json",
            "clay_molds/imprint_227_pb.json",
            "clay_molds/imprint_227_sn.json",
            "clay_molds/imprint_227_zn.json",
            "clay_molds/imprint_228_anycu.json",
            "clay_molds/imprint_228_anyiron.json",
            "clay_molds/imprint_228_anystone.json",
            "clay_molds/imprint_228_anywax.json",
            "clay_molds/imprint_228_anywoodplastic.json",
            "clay_molds/imprint_228_arsenicbronze.json",
            "clay_molds/imprint_228_arseniccopper.json",
            "clay_molds/imprint_228_au.json",
            "clay_molds/imprint_228_bi.json",
            "clay_molds/imprint_228_bismuthbronze.json",
            "clay_molds/imprint_228_brass.json",
            "clay_molds/imprint_228_bronze.json",
            "clay_molds/imprint_228_glass.json",
            "clay_molds/imprint_228_pb.json",
            "clay_molds/imprint_228_sn.json",
            "clay_molds/imprint_228_zn.json",
            "clay_molds/imprint_229_anycu.json",
            "clay_molds/imprint_229_anyiron.json",
            "clay_molds/imprint_229_anystone.json",
            "clay_molds/imprint_229_anywax.json",
            "clay_molds/imprint_229_anywoodplastic.json",
            "clay_molds/imprint_229_arsenicbronze.json",
            "clay_molds/imprint_229_arseniccopper.json",
            "clay_molds/imprint_229_au.json",
            "clay_molds/imprint_229_bi.json",
            "clay_molds/imprint_229_bismuthbronze.json",
            "clay_molds/imprint_229_brass.json",
            "clay_molds/imprint_229_bronze.json",
            "clay_molds/imprint_229_glass.json",
            "clay_molds/imprint_229_pb.json",
            "clay_molds/imprint_229_sn.json",
            "clay_molds/imprint_229_zn.json",
            "clay_molds/imprint_230_anycu.json",
            "clay_molds/imprint_230_anyiron.json",
            "clay_molds/imprint_230_anystone.json",
            "clay_molds/imprint_230_anywax.json",
            "clay_molds/imprint_230_anywoodplastic.json",
            "clay_molds/imprint_230_arsenicbronze.json",
            "clay_molds/imprint_230_arseniccopper.json",
            "clay_molds/imprint_230_au.json",
            "clay_molds/imprint_230_bi.json",
            "clay_molds/imprint_230_bismuthbronze.json",
            "clay_molds/imprint_230_brass.json",
            "clay_molds/imprint_230_bronze.json",
            "clay_molds/imprint_230_glass.json",
            "clay_molds/imprint_230_pb.json",
            "clay_molds/imprint_230_sn.json",
            "clay_molds/imprint_230_zn.json",
            "clay_molds/imprint_231_anycu.json",
            "clay_molds/imprint_231_anyiron.json",
            "clay_molds/imprint_231_anystone.json",
            "clay_molds/imprint_231_anywax.json",
            "clay_molds/imprint_231_anywoodplastic.json",
            "clay_molds/imprint_231_arsenicbronze.json",
            "clay_molds/imprint_231_arseniccopper.json",
            "clay_molds/imprint_231_au.json",
            "clay_molds/imprint_231_bi.json",
            "clay_molds/imprint_231_bismuthbronze.json",
            "clay_molds/imprint_231_brass.json",
            "clay_molds/imprint_231_bronze.json",
            "clay_molds/imprint_231_glass.json",
            "clay_molds/imprint_231_pb.json",
            "clay_molds/imprint_231_sn.json",
            "clay_molds/imprint_231_zn.json",
            "clay_molds/reclaim_clay_arrow_mold.json",
            "clay_molds/reclaim_clay_axe_mold.json",
            "clay_molds/reclaim_clay_billet_mold.json",
            "clay_molds/reclaim_clay_bolt_mold.json",
            "clay_molds/reclaim_clay_builders_wand_mold.json",
            "clay_molds/reclaim_clay_chisel_mold.json",
            "clay_molds/reclaim_clay_chunk_mold.json",
            "clay_molds/reclaim_clay_double_axe_mold.json",
            "clay_molds/reclaim_clay_file_mold.json",
            "clay_molds/reclaim_clay_gear_mold.json",
            "clay_molds/reclaim_clay_hammer_mold.json",
            "clay_molds/reclaim_clay_hoe_mold.json",
            "clay_molds/reclaim_clay_ingot_mold.json",
            "clay_molds/reclaim_clay_item_casing_mold.json",
            "clay_molds/reclaim_clay_long_rod_mold.json",
            "clay_molds/reclaim_clay_mold.json",
            "clay_molds/reclaim_clay_nugget_mold.json",
            "clay_molds/reclaim_clay_pickaxe_mold.json",
            "clay_molds/reclaim_clay_plate_mold.json",
            "clay_molds/reclaim_clay_plow_mold.json",
            "clay_molds/reclaim_clay_ring_mold.json",
            "clay_molds/reclaim_clay_rod_mold.json",
            "clay_molds/reclaim_clay_saw_mold.json",
            "clay_molds/reclaim_clay_screwdriver_mold.json",
            "clay_molds/reclaim_clay_sense_mold.json",
            "clay_molds/reclaim_clay_shovel_mold.json",
            "clay_molds/reclaim_clay_small_gear_mold.json",
            "clay_molds/reclaim_clay_spade_mold.json",
            "clay_molds/reclaim_clay_sword_mold.json",
            "clay_molds/reclaim_clay_tiny_plate_mold.json",
            "clay_molds/reclaim_clay_universal_spade_mold.json"
    );
}
