/* Gregorius Techneticies / GregTech-6 Team source data, LGPL-3.0-or-later. */
package com.gregtech.gregtech.content.recipe;

import java.util.*;

/** Generated by tools/generate_original_form_conversions.py from Loader_Recipes_Handlers and OP. */
public final class OriginalFormConversions {
    private OriginalFormConversions() {}
    public record Conversion(String input, int inputCount, String output, int outputCount, boolean single) {}
    public record Form(String prefix, String material) {
        public Form { prefix = com.gregtech.gregtech.api.prefix.PrefixRegistry.sourceName(prefix); }
    }
    public static final Form UNKNOWN = new Form("", "");
    public static final List<Conversion> FIXED = List.of(
            new Conversion("oreRaw", 1, "gem", 1, true), // :552
            new Conversion("oreRaw", 1, "rawOreChunk", 3, true), // :553
            new Conversion("crushed", 1, "crushedTiny", 9, true), // :554
            new Conversion("crushed", 1, "gemFlawed", 1, true), // :555
            new Conversion("crushedPurified", 1, "crushedPurifiedTiny", 9, true), // :556
            new Conversion("crushedPurified", 1, "gemFlawed", 1, true), // :557
            new Conversion("crushedCentrifuged", 1, "crushedCentrifugedTiny", 9, true), // :558
            new Conversion("crushedCentrifuged", 1, "gemFlawed", 1, true), // :559
            new Conversion("ingot", 1, "nugget", 9, true), // :560
            new Conversion("ingot", 1, "chunkGt", 4, true), // :561
            new Conversion("billet", 1, "nugget", 6, true), // :562
            new Conversion("dust", 1, "dustTiny", 9, true), // :563
            new Conversion("dust", 1, "dustSmall", 4, true), // :564
            new Conversion("dustTiny", 1, "dustDiv72", 8, true), // :565
            new Conversion("dustSmall", 1, "dustDiv72", 18, true), // :566
            new Conversion("blockRaw", 1, "oreRaw", 9, true), // :567
            new Conversion("blockDust", 1, "dust", 9, true), // :568
            new Conversion("blockDust", 1, "dustSmall", 36, true), // :569
            new Conversion("blockIngot", 1, "ingot", 9, true), // :570
            new Conversion("blockIngot", 1, "chunkGt", 36, true), // :571
            new Conversion("blockGem", 1, "gem", 9, true), // :572
            new Conversion("blockPlate", 1, "plate", 9, true), // :573
            new Conversion("blockPlateGem", 1, "plateGem", 9, true), // :574
            new Conversion("rawOreChunk", 3, "oreRaw", 1, false), // :576
            new Conversion("crushedTiny", 9, "crushed", 1, false), // :577
            new Conversion("crushedPurifiedTiny", 9, "crushedPurified", 1, false), // :578
            new Conversion("crushedCentrifugedTiny", 9, "crushedCentrifuged", 1, false), // :579
            new Conversion("ingot", 2, "billet", 3, false), // :580
            new Conversion("ingot", 3, "nugget", 27, false), // :581
            new Conversion("ingot", 4, "billet", 6, false), // :582
            new Conversion("ingot", 5, "nugget", 45, false), // :583
            new Conversion("ingot", 6, "billet", 9, false), // :584
            new Conversion("ingot", 7, "nugget", 63, false), // :585
            new Conversion("ingot", 8, "billet", 12, false), // :586
            new Conversion("ingot", 9, "blockIngot", 1, false), // :587
            new Conversion("billet", 2, "nugget", 12, false), // :588
            new Conversion("billet", 3, "ingot", 2, false), // :589
            new Conversion("billet", 4, "nugget", 24, false), // :590
            new Conversion("billet", 5, "nugget", 30, false), // :591
            new Conversion("billet", 6, "ingot", 4, false), // :592
            new Conversion("billet", 7, "nugget", 42, false), // :593
            new Conversion("billet", 8, "nugget", 48, false), // :594
            new Conversion("billet", 9, "ingot", 6, false), // :595
            new Conversion("chunkGt", 4, "ingot", 1, false), // :596
            new Conversion("chunkGt", 8, "billet", 3, false), // :597
            new Conversion("nugget", 6, "billet", 1, false), // :598
            new Conversion("nugget", 9, "ingot", 1, false), // :599
            new Conversion("dustDiv72", 8, "dustTiny", 1, false), // :600
            new Conversion("dustTiny", 9, "dust", 1, false), // :601
            new Conversion("dustSmall", 4, "dust", 1, false), // :602
            new Conversion("dustSmall", 8, "dust", 2, false), // :603
            new Conversion("oreRaw", 9, "blockRaw", 1, false), // :604
            new Conversion("dust", 9, "blockDust", 1, false), // :605
            new Conversion("gem", 9, "blockGem", 1, false), // :606
            new Conversion("plate", 9, "blockPlate", 1, false), // :607
            new Conversion("plateGem", 9, "blockPlateGem", 1, false), // :608
            new Conversion("plateTiny", 5, "casingSmall", 1, false), // :609
            new Conversion("plateTiny", 9, "casingSmall", 2, false), // :610
            new Conversion("plateGemTiny", 5, "casingSmall", 1, false), // :611
            new Conversion("plateGemTiny", 9, "casingSmall", 2, false)); // :612
    public static final Set<String> STANDARD_ORES = Set.of(
            "ore", "oreBlackgranite", "oreRedgranite", "oreVanillastone", "oreVanillagranite", "oreAndesite", "oreDiorite", "oreDeepslate", "oreBlackstone", "oreMoon", "oreMars", "oreSpace", "orePhobos", "oreDeimos", "oreVenus", "oreMercury", "oreCeres", "oreJupiter", "oreIo", "oreEuropa", "oreGanymede", "oreCallisto", "oreSaturn", "oreRhea", "oreTitan", "oreOberon", "oreIapetus", "oreUranus", "oreTitania", "oreNeptune", "oreTriton", "orePluto", "oreEris", "oreKepler22b", "oreHolystone", "oreLivingrock", "oreDeadrock", "oreBetweenstone", "orePitstone", "oreUmberstone", "oreKomatiite", "oreBasalt", "oreMarble", "oreLimestone", "oreSiltstone", "oreShale", "oreSlate", "oreGreenschist", "oreBlueschist", "orePinkschist", "oreGrayschist", "oreGneiss", "oreLightprismarine", "oreDarkprismarine", "oreKimberlite", "oreQuartzite", "oreNetherrack", "oreEndstone", "oreSandstone");
    public static final Set<String> DENSE_ORES = Set.of(
            "oreNether", "oreDense", "oreEnd");

    public static FormConversionSelector selector(Conversion conversion) {
        if (!conversion.single()) return FormConversionSelector.NONE;
        int variants = 0, offset = 0;
        for (Conversion candidate : FIXED) if (candidate.single() && candidate.input().equals(conversion.input())) {
            if (candidate.equals(conversion)) offset = variants;
            variants++;
        }
        return new FormConversionSelector(Math.max(1, variants), offset);
    }

    private static final List<Conversion> RULES = rules();
    private static List<Conversion> rules() {
        var rules = new ArrayList<>(FIXED);
        for (String prefix : STANDARD_ORES) rules.add(new Conversion(prefix, 1, "oreRaw", 1, true));
        for (String prefix : DENSE_ORES) rules.add(new Conversion(prefix, 1, "oreRaw", 2, true));
        for (int big = 1; big <= 16; big++) for (int small = 1; small < big; small++) if (big % small == 0) {
            String bigPrefix = "wireGt" + String.format(Locale.ROOT, "%02d", big);
            String smallPrefix = "wireGt" + String.format(Locale.ROOT, "%02d", small);
            if (big / small < 10) rules.add(new Conversion(smallPrefix, big / small, bigPrefix, 1, false));
            rules.add(new Conversion(bigPrefix, 1, smallPrefix, big / small, true));
        }
        return List.copyOf(rules);
    }

    /** The source constructors replace plain shaped/shapeless recipes; their output count is irrelevant. */
    public static boolean replaces(List<Form> grid, int width, int height, boolean shapeless,
                                   boolean gtOwned, Form output) {
        if (gtOwned || output == null || output.material().isEmpty()) return false;
        var occupied = grid.stream().filter(Objects::nonNull).toList();
        if (occupied.isEmpty()) return false;
        Form input = occupied.get(0);
        if (input.material().isEmpty()) return false;
        for (Conversion rule : RULES) {
            if (occupied.size() != rule.inputCount() || !input.prefix().equals(rule.input())
                    || !output.prefix().equals(rule.output())) continue;
            if (!shapeless && !rule.single() && rule.inputCount() != 9) {
                // Source XToY accepts the special full 3x3 input array with its upper-left 2x2 occupied.
                if (rule.inputCount() != 4 || width != 3 || height != 3 || grid.size() != 9
                        || grid.get(2) != null || grid.get(5) != null || grid.get(6) != null
                        || grid.get(7) != null || grid.get(8) != null) continue;
            }
            if (!rule.single() && !output.material().equals(input.material())) continue;
            if (occupied.stream().allMatch(form -> form.prefix().equals(input.prefix())
                    && (rule.single() || form.material().equals(input.material())))) return true;
        }
        return false;
    }
}
