#!/usr/bin/env python3
"""Extract GT6's drink statistics (the `DrinksGT` table).

GT6 registers every drinkable fluid in `gregtech/loaders/a/Loader_Fluids.java` as

    new FoodStatDrink(FL.Coffee, "gt.drink.coffee", 2, 0.4F, 0.0F, C+60, 0.1F, 0, 8, 2, 0, 0, EnumAction.drink, F, T, F);

whose `FoodStatDrink` constructor (`gregapi/item/multiitem/food/FoodStatDrink.java:46-52`) puts the entry
into `DrinksGT.REGISTER` keyed by the fluid's name, and whose `FoodStat` half carries the six food
statistics plus the food level and saturation. `FoodStatFluid` (GT6's `MultiItemBottles` food stat) then
looks the drink up per bottle: a GT6 bottle is 250 mB of that fluid.

The port resolves the fluid by GT6's own field name (`RegisteredFluids.get(field)`, which is what the port
copied from `FL`), so the generated rows carry the field name (or, for the `FL.create("...")` brews, the
registry name, which the port also uses verbatim).

Generated (do not edit by hand):
  src/main/java/com/gregtech/gregtech/data/generated/GTDrinksGen.java

Usage: python tools/extract_gt6_drinks.py [--check]
"""

from __future__ import annotations

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GT6 = r'F:\Dev\GregTech6\gregtech6-master\gregtech6-master\src\main\java'
SOURCE = os.path.join(GT6, 'gregtech', 'loaders', 'a', 'Loader_Fluids.java')
OUT = os.path.join(ROOT, 'src', 'main', 'java', 'com', 'gregtech', 'gregtech', 'data', 'generated',
                   'GTDrinksGen.java')


def split_args(text: str):
    """Split a Java argument list on top-level commas, ignoring commas inside string literals."""
    args, depth, current, in_string, escaped = [], 0, '', False, False
    for ch in text:
        if in_string:
            current += ch
            if escaped:
                escaped = False
            elif ch == '\\':
                escaped = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
            current += ch
            continue
        if ch in '([':
            depth += 1
        elif ch in ')]':
            depth -= 1
        if ch == ',' and depth == 0:
            args.append(current.strip())
            current = ''
        else:
            current += ch
    if current.strip():
        args.append(current.strip())
    return args


def fluid_key(expr: str):
    m = re.match(r'FL\.create\(\s*"([^"]+)"', expr)
    if m:
        return m.group(1)
    m = re.match(r'FL\.([A-Za-z_][A-Za-z0-9_]*)', expr)
    if m:
        return m.group(1)
    return None


def as_int(expr: str, default=None):
    expr = expr.strip()
    if re.fullmatch(r'-?\d+', expr):
        return int(expr)
    return default


def main() -> int:
    check = '--check' in sys.argv
    text = io.open(SOURCE, encoding='utf-8', errors='replace').read()

    rows, skipped = {}, []
    for match in re.finditer(r'new FoodStatDrink\((.*?)\)\s*;', text, re.S):
        args = split_args(' '.join(match.group(1).split()))
        if len(args) < 12:
            skipped.append('short row: ' + args[0][:60])
            continue
        key = fluid_key(args[0])
        if key is None:
            skipped.append('unknown fluid expression: ' + args[0][:60])
            continue
        food = as_int(args[2])
        saturation = args[3]
        stats = [as_int(args[i], 0) for i in (7, 8, 9, 10, 11)]
        radiation = as_int(args[12], 0) if len(args) > 12 else 0
        if food is None or any(v is None for v in stats):
            skipped.append('%s: unparsable numbers (%s)' % (key, args[2:12]))
            continue
        try:
            saturation_value = float(re.sub(r'[fFdD]$', '', saturation))
        except ValueError:
            saturation_value = 0.0
        rows.setdefault(key, (food, saturation_value, stats + [radiation])) 

    lines = [
        'package com.gregtech.gregtech.data.generated;',
        '',
        'import com.gregtech.gregtech.content.food.GTDrinks;',
        '',
        'import java.util.List;',
        '',
        '/**',
        ' * GENERATED by tools/extract_gt6_drinks.py - do not edit by hand.',
        ' *',
        ' * <p>GT6\'s {@code DrinksGT} entries as {@code Loader_Fluids} registers them: the fluid (by GT6 field',
        ' * name, or by registry name for the {@code FL.create("...")} brews), the food level and saturation, and',
        ' * the six statistics [alcohol, caffeine, dehydration, sugar, fat, radiation]. A GT6 bottle is 250 mB of',
        ' * the fluid and reads its numbers from this table through {@code FoodStatFluid}.',
        ' */',
        'public final class GTDrinksGen {',
        '    private GTDrinksGen() {}',
        '',
        '    public static final List<GTDrinks.Row> ROWS = List.of(',
    ]
    ordered = sorted(rows)
    for index, key in enumerate(ordered):
        food, saturation, stats = rows[key]
        comma = ',' if index < len(ordered) - 1 else ''
        lines.append('            new GTDrinks.Row("%s", %d, %sf, %s)%s'
                     % (key.replace('"', '\\"'), food, ('%g' % saturation),
                        ', '.join(str(v) for v in stats), comma))
    lines.append('    );')
    lines.append('')
    lines.append('    /** Drink rows whose fluid expression could not be parsed (never silently dropped). */')
    lines.append('    public static final List<String> SKIPPED = List.of(')
    for index, note in enumerate(sorted(set(skipped))):
        comma = ',' if index < len(set(skipped)) - 1 else ''
        lines.append('            "%s"%s' % (note.replace('"', '\\"'), comma))
    lines.append('    );')
    lines.append('}')
    out = '\n'.join(lines) + '\n'

    print('drink rows: %d, skipped: %d' % (len(rows), len(set(skipped))))
    for note in sorted(set(skipped))[:6]:
        print('  SKIPPED ' + note)

    old = io.open(OUT, encoding='utf-8').read() if os.path.isfile(OUT) else None
    if old == out:
        print('unchanged ' + os.path.relpath(OUT, ROOT))
        return 0
    if check:
        print('STALE ' + os.path.relpath(OUT, ROOT))
        return 1
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(out)
    print('wrote ' + os.path.relpath(OUT, ROOT))
    return 0


if __name__ == '__main__':
    sys.exit(main())
