#!/usr/bin/env python3
"""Extract GT6's ``MultiItemBottles`` drink table (bottle id -> the fluid it holds).

GT6 registers ~180 drink bottles as one multi-item (``MultiItemBottles.addItem(meta, "Display",
[tooltip], [oredict], <fluid>.make(250), <aspects...>, FoodStatFluid.INSTANCE, [extra fluids...])``).
The port already registers the *items* (``GTMultiItemsGen``, transpiled by
``tools/transpile_gt6_multiitems.py``) but not what is inside them, so the bottles cannot be drunk
yet.  This tool emits the missing column:

    id, display, GT6 fluid key

``id`` is taken from the port's generated multi-item table (same file order, same ids) and the
display names are cross-checked, so a drift in either generator fails loudly instead of silently
pairing the wrong fluid with a bottle.  ``fluid key`` is the GT6 expression's fluid as written -
``FL.Beer`` -> ``Beer``, ``FL.make("potion.x", 250)`` -> ``potion.x``, ``MT.HolyWater.liquid(...)``
-> ``HolyWater`` - and is resolved on the Java side through the port's own fluid lookups
(``GTDrinks.fluidForField`` / ``GTFluids.still``), never by string surgery here.

Usage: python tools/extract_gt6_bottles.py [--check]
"""

from __future__ import annotations

import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GT6 = Path(r"F:\Dev\GregTech6\gregtech6-master\gregtech6-master\src\main\java")
BOTTLES = GT6 / "gregtech/items/MultiItemBottles.java"
PORT_GEN = ROOT / "src/main/java/com/gregtech/gregtech/registry/GTMultiItemsGen.java"
OUT = ROOT / "src/main/java/com/gregtech/gregtech/data/generated/GTBottlesGen.java"

ADD_ITEM = re.compile(r'addItem\(\s*(\d+)\s*,\s*"((?:\\.|[^"\\])*)"')
# fluid expressions, in the priority order GT6's own FoodStatFluid reads them. GT6 aligns the calls
# with padding spaces ("FL.MnWtr                  .make(250)"), so every dot needs \s* around it.
FL_FIELD = re.compile(r'\bFL\.(\w+)\s*\.make\(')
FL_NAMED = re.compile(r'\bFL\.make\(\s*"([^"]+)"')
MT_LIQUID = re.compile(r'\bMT\.(\w+)\s*\.liquid\(')
OP_BOTTLE = re.compile(r'\bOP\.bottle\s*\.dat\(\s*MT\.(\w+)\s*\)')
# the port's generated entries: "id", "Display", "category", "flag",
GEN_ENTRY = re.compile(r'"([^"]+)"\s*,\s*"((?:\\.|[^"\\])*)"\s*,\s*"([^"]+)"\s*,\s*"([^"]*)"')


def gt6_rows() -> list[tuple[int, str, str | None]]:
    """(meta, display, fluid key) of every MultiItemBottles row, in file order."""
    text = io.open(BOTTLES, encoding="utf-8").read()
    rows: list[tuple[int, str, str | None]] = []
    for line in text.splitlines():
        m = ADD_ITEM.search(line)
        if not m:
            continue
        meta = int(m.group(1))
        display = m.group(2).replace('\\"', '"')
        key = None
        for pattern in (FL_FIELD, FL_NAMED, MT_LIQUID, OP_BOTTLE):
            hit = pattern.search(line)
            if hit:
                key = hit.group(1)
                break
        rows.append((meta, display, key))
    return rows


def port_bottles() -> list[tuple[str, str]]:
    """(id, display) of the port's generated ``bottles`` entries, in file order."""
    text = io.open(PORT_GEN, encoding="utf-8").read()
    return [(m.group(1), m.group(2)) for m in GEN_ENTRY.finditer(text) if m.group(3) == "bottles"]


def java_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build() -> tuple[str, int, list[str]]:
    rows = gt6_rows()
    bottles = port_bottles()
    if len(rows) != len(bottles):
        raise SystemExit(f"row count differs: GT6 {len(rows)} vs port {len(bottles)} "
                         "- re-run tools/transpile_gt6_multiitems.py first")
    for (meta, display, _), (item_id, port_display) in zip(rows, bottles):
        if display != port_display:
            raise SystemExit(f"display drift at meta {meta}: GT6 {display!r} vs port {port_display!r}")

    entries: list[str] = []
    skipped: list[str] = []
    for (meta, display, key), (item_id, _) in zip(rows, bottles):
        if key is None:
            skipped.append(f"{item_id} (meta {meta}, {display}): no fluid expression found")
            continue
        entries.append(f'        "{java_string(item_id)}", "{java_string(display)}", "{java_string(key)}",')

    body = "\n".join(entries)
    skipped_body = ",\n".join(f'            "{java_string(s)}"' for s in skipped)
    skipped_block = ("            // rows without a readable fluid expression\n" + skipped_body
                     if skipped_body else "")
    source = f'''package com.gregtech.gregtech.data.generated;

/**
 * GENERATED by tools/extract_gt6_bottles.py - do not edit by hand.
 *
 * <p>GT6's {{@code MultiItemBottles}} drink table: the port's bottle item id, its display name and the
 * GT6 fluid expression the bottle holds ({{@code FL.Beer}} -> {{@code Beer}}, {{@code FL.make("potion.x",
 * 250)}} -> {{@code potion.x}}, {{@code MT.HolyWater.liquid(...)}} -> {{@code HolyWater}}), in GT6 file
 * order. A bottle is 250&nbsp;mB of that fluid. The key is resolved on the Java side through the port's
 * own lookups ({{@code GTDrinks.fluidForField}} / {{@code GTFluids.still}}), so a renamed port fluid
 * needs no change here.
 */
public final class GTBottlesGen {{
    private GTBottlesGen() {{}}

    /** {{@code id, display, GT6 fluid key}} triples, in GT6 file order. */
    public static final String[] ENTRIES = {{
{body}
    }};

    /** Rows the extractor could not read a fluid out of, with the reason. */
    public static final java.util.List<String> SKIPPED = java.util.List.of(
{skipped_block}
    );
}}
'''
    return source, len(entries), skipped


def main() -> int:
    source, count, skipped = build()
    if "--check" in sys.argv:
        current = io.open(OUT, encoding="utf-8").read() if OUT.exists() else ""
        ok = current == source
        print(f"check: {count} bottle rows, {len(skipped)} skipped -> {'up to date' if ok else 'OUT OF DATE'}")
        return 0 if ok else 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    io.open(OUT, "w", encoding="utf-8", newline="").write(source)
    print(f"wrote {OUT.name}: {count} bottles with a fluid, {len(skipped)} skipped")
    for reason in skipped:
        print("  skipped:", reason)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
