"""Generate the GT6 material *field* table (`MT.java` field -> material name).

GT6 stores materials in fields whose names are often short (`Ma`, `Fe`, `PO4`) while the material
itself is named differently (`Magic`, `Iron`, `Phosphate`). Transcribed GT6 tables that key rows by
the receiver of a call — the enchantment table does, `Ma.addEnchantmentForArmors(...)` — therefore
carry field names, and the port has to resolve them back to materials.

Inputs : gregtech6-master .../gregapi/data/MT.java
Output : src/main/java/com/gregtech/gregtech/loaders/c/GTMaterialFields.java
"""

from __future__ import annotations

import io
import os
import re

GT6 = r"F:\Dev\GregTech6\gregtech6-master\gregtech6-master\src\main\java\gregapi\data\MT.java"
TARGET = os.path.join("src", "main", "java", "com", "gregtech", "gregtech", "loaders", "c",
                      "GTMaterialFields.java")

# `Field, Alias = Field = helper( 8637, "HSLA-Steel" , ...)` and
# `Field, Alias = Field = helper( "Name" ...)` both carry the name as the first string literal.
WITH_ID = re.compile(
    r'^\s*(?P<field>[A-Za-z_]\w*)\s*(?:,\s*(?P<alias>[A-Za-z_]\w*)\s*)?='
    r'\s*(?:[A-Za-z_]\w*\s*=\s*)?[A-Za-z_]\w*\s*\(\s*\d+\s*,\s*"(?P<name>[^"]+)"')
# `Field = helper().qual(...)` — the helper is named after the material (`gold()` -> Gold).
WITHOUT_ID = re.compile(
    r'^\s*(?P<field>[A-Za-z_]\w*)\s*(?:,\s*(?P<alias>[A-Za-z_]\w*)\s*)?='
    r'\s*(?:[A-Za-z_]\w*\s*=\s*)?(?P<helper>[A-Za-z_]\w*)\s*\(\s*\)')


def parse() -> dict:
    """GT6 field name -> material name, in `MT.java` order."""
    fields: dict[str, str] = {}
    for line in io.open(GT6, encoding="utf-8", errors="replace").read().splitlines():
        match = WITH_ID.match(line)
        if match:
            fields.setdefault(match.group("field"), match.group("name"))
            if match.group("alias"):
                # GT6's second column is another *field* name for the same material, not a name.
                pass
            continue
        match = WITHOUT_ID.match(line)
        if match and match.group("helper") not in {"create", "element", "compound"}:
            # `Au , Gold = gold()` — the alias column is the material name when GT6 spells it out.
            name = match.group("alias") or match.group("helper").capitalize()
            fields.setdefault(match.group("field"), name)
    return fields


def main() -> int:
    fields = parse()
    print("GT6 material fields: %d" % len(fields))
    for probe in ("Ma", "Fe", "Au", "Pt", "PO4", "HSLA", "Atl", "Ke", "Polycarbonate"):
        print("   %-16s %s" % (probe, fields.get(probe)))
    lines = [
        "package com.gregtech.gregtech.loaders.c;",
        "",
        "import java.util.LinkedHashMap;",
        "import java.util.Map;",
        "",
        "/**",
        " * GT6's material field names ({@code MT.java}), e.g. {@code Ma} = {@code Magic},",
        " * {@code PO4} = {@code Phosphate}. Transcribed tables that key rows by the receiver of a call",
        " * carry those short names, so they have to be resolved back to materials.",
        " *",
        " * <p>GENERATED by tools/extract_gt6_material_fields.py - do not edit by hand.</p>",
        " */",
        "public final class GTMaterialFields {",
        "    private static final Map<String, String> BY_FIELD = new LinkedHashMap<>();",
        "",
        "    static {",
    ]
    for field, name in fields.items():
        lines.append('        BY_FIELD.put("%s", "%s");' % (field, name.replace('"', '\\"')))
    lines += [
        "    }",
        "",
        "    /** The material a GT6 field names, or null when the field is not a material. */",
        "    public static String materialOf(String field) {",
        "        return BY_FIELD.get(field);",
        "    }",
        "",
        "    /** How many fields the table holds. */",
        "    public static int size() { return BY_FIELD.size(); }",
        "",
        "    private GTMaterialFields() {}",
        "}",
        "",
    ]
    io.open(TARGET, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print("wrote %s" % TARGET.replace("\\", "/"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
