#!/usr/bin/env python3
"""Generate GT6's bumblebee species table (`MultiItemBumbles.java`).

GT6 registers 84 bee species as metas of one item (`make(<meta>, "<Name>", "<tooltip>")`) and maps
each *species tier* (`meta / 100`) to the comb it produces (`bumbleProductStack:189-213`). The port
registers one item per species and type, so it needs the same table keyed by port ids.

Inputs : gregtech6-master .../gregtech/items/MultiItemBumbles.java
Output : src/main/java/com/gregtech/gregtech/content/bumble/GTBumbleSpecies.java
"""

from __future__ import annotations

import io
import os
import re

GT6 = (r"F:\Dev\GregTech6\gregtech6-master\gregtech6-master\src\main\java\gregtech\items"
       r"\MultiItemBumbles.java")
TARGET = os.path.join("src", "main", "java", "com", "gregtech", "gregtech", "content", "bumble",
                      "GTBumbleSpecies.java")

# `make(  100, "Surfing Bumblebee"         , "Too chill to work regularily");`
MAKE = re.compile(r'\bmake\(\s*(\d+)\s*,\s*"((?:\\.|[^"\\])*)"\s*,\s*"((?:\\.|[^"\\])*)?"')
# `case   0: return IL.Comb_Honey      .get(aStacksize);`
COMB = re.compile(r"case\s+(\d+):\s*return\s+IL\.(\w+)\s*\.get")

# GT6 bee type metas inside a species block (meta % 10), and the port's id suffix for them.
TYPES = [("drone", 0), ("princess", 1), ("queen", 2), ("dead", 4)]


def snake(name: str) -> str:
    """The port's item id slug for a GT6 display name (same rule as transpile_gt6_multiitems)."""
    s = name.lower()
    s = re.sub(r"[''.()&,!?]", "", s)
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    return re.sub(r"__+", "_", s)


# GT6 comb field -> port comb item id.
COMBS = {
    "Comb_Honey": "honey_comb", "Comb_Water": "water_comb", "Comb_Magic": "magic_comb",
    "Comb_Nether": "nether_comb", "Comb_End": "end_comb", "Comb_Rock": "rock_comb",
    "Comb_Jungle": "jungle_comb", "Comb_Frozen": "frozen_comb", "Comb_Shroom": "shroomy_comb",
    "Comb_Sandy": "sandy_comb", "Comb_Clay": "clay_comb", "Comb_Sticky": "sticky_comb",
    "Comb_Royal": "royal_comb", "Comb_Soul": "soul_comb", "Comb_Amnesic": "amnesic_comb",
    "Comb_Military": "military_comb", "Comb_Pyro": "pyro_comb", "Comb_Cryo": "cryo_comb",
    "Comb_Aero": "aero_comb", "Comb_Tera": "tera_comb",
}


def main() -> int:
    text = io.open(GT6, encoding="utf-8", errors="replace").read()
    combs = {int(tier): COMBS[field] for tier, field in COMB.findall(text)
             if field in COMBS}
    species = []
    for match in MAKE.finditer(text):
        meta, name = int(match.group(1)), match.group(2)
        species.append((meta, name))
    print("GT6 bee species: %d, comb tiers: %d" % (len(species), len(combs)))

    lines = [
        "package com.gregtech.gregtech.content.bumble;",
        "",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "",
        "/**",
        " * GT6's bumblebee species and the comb each one produces",
        " * ({@code MultiItemBumbles.make(...)} and {@code bumbleProductStack:189-213}).",
        " *",
        " * <p>GT6 stores them as metas of one item ({@code meta = species id + type}), where the",
        " * <em>species tier</em> ({@code meta / 100}) picks the comb. The port registers one item per",
        " * species and type ({@code <species>_{drone,princess,queen,dead}}), so the same table is keyed",
        " * by those ids here.</p>",
        " *",
        " * <p>GENERATED by tools/extract_gt6_bumbles.py - do not edit by hand.</p>",
        " */",
        "public final class GTBumbleSpecies {",
        "",
        "    /** One GT6 species: its id, port item prefix, display name and comb item id. */",
        "    public static final class Species {",
        "        private final int id;",
        "        private final String prefix;",
        "        private final String name;",
        "        private final String comb;",
        "",
        "        Species(int id, String prefix, String name, String comb) {",
        "            this.id = id; this.prefix = prefix; this.name = name; this.comb = comb;",
        "        }",
        "",
        "        /** GT6's species id (the bee meta with a type of 0). */",
        "        public int id() { return id; }",
        "",
        "        /** The port's item id prefix, e.g. {@code surfing_bumblebee}. */",
        "        public String prefix() { return prefix; }",
        "",
        "        /** GT6's display name, e.g. {@code Surfing Bumblebee}. */",
        "        public String name() { return name; }",
        "",
        "        /** The comb item id this species produces, e.g. {@code water_comb}. */",
        "        public String comb() { return comb; }",
        "",
        "        /** The port's item id for one bee type, e.g. {@code surfing_bumblebee_princess}. */",
        "        public String beeId(String type) { return prefix + \"_\" + type; }",
        "    }",
        "",
        "    /** GT6's species, in its registration order. */",
        "    public static final List<Species> SPECIES = List.of(",
    ]
    rows = []
    for meta, name in species:
        tier = meta // 100
        comb = combs.get(tier)
        if comb is None:
            print("   no comb for species %d (%s)" % (meta, name))
            continue
        rows.append('            new Species(%d, "%s", "%s", "%s")' % (meta, snake(name), name, comb))
    lines.append(",\n".join(rows))
    lines += [
        "    );",
        "",
        "    private static final Map<Integer, Species> BY_ID = new LinkedHashMap<>();",
        "    private static final Map<String, Species> BY_PREFIX = new LinkedHashMap<>();",
        "",
        "    static {",
        "        for (Species species : SPECIES) {",
        "            BY_ID.put(species.id(), species);",
        "            BY_PREFIX.put(species.prefix(), species);",
        "        }",
        "    }",
        "",
        "    /** The species with GT6's id, or null. */",
        "    public static Species byId(int id) { return BY_ID.get(id); }",
        "",
        "    /** The species whose port item prefix matches, or null. */",
        "    public static Species byPrefix(String prefix) { return BY_PREFIX.get(prefix); }",
        "",
        "    /** The comb a species produces, or null. GT6: {@code meta / 100} picks the comb row. */",
        "    public static String combOf(int speciesId) {",
        "        Species species = BY_ID.get(speciesId - speciesId % 10);",
        "        return species == null ? null : species.comb();",
        "    }",
        "",
        "    private GTBumbleSpecies() {}",
        "}",
        "",
    ]
    io.open(TARGET, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print("wrote %s (%d species)" % (TARGET.replace("\\", "/"), len(rows)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
