"""Extract GT6's recyclable prefix list from OP.java.

GT6 registers its shredder (recycling) handlers generically (Loader_Recipes_Handlers:152-155):

    for (OreDictPrefix tPrefix : OreDictPrefix.VALUES)
        if (tPrefix.mByProducts.isEmpty() && tPrefix.contains(RECYCLABLE)
            && !tPrefix.containsAny(ORE, ORE_PROCESSING_BASED, DUST_BASED, IS_CONTAINER)
            && !tPrefix.mNameInternal.startsWith("cableGt")
            && !tPrefix.mNameInternal.startsWith("wireGt")
            && !tPrefix.mNameInternal.startsWith("pipe")) { ... }

The port has no RECYCLABLE tag on its prefixes, so the filter result is imported as a generated name
table instead of inventing a prefix list by hand.

Usage: python tools/extract_gt6_recyclable_prefixes.py
"""

from __future__ import annotations

import json
import os
import re

GT6 = r"F:\Dev\GregTech6\gregtech6-master\gregtech6-master\src\main\java"
ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
OP_JAVA = os.path.join(GT6, "gregapi", "data", "OP.java")
OUT_JAVA = os.path.join(ROOT, "src", "main", "java", "com", "gregtech", "gregtech", "data", "generated", "RecyclablePrefixes.java")
OUT_JSON = os.path.join(ROOT, "docs", "recyclable-prefixes.json")

DECL = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*create\(")
EXCLUDED_FLAGS = ("ORE", "ORE_PROCESSING_BASED", "DUST_BASED", "IS_CONTAINER")
EXCLUDED_PREFIXES = ("cableGt", "wireGt", "pipe")


def main() -> None:
    with open(OP_JAVA, "r", encoding="utf-8", errors="replace") as handle:
        text = handle.read()

    # Prefixes that declare byproducts are excluded by GT6 (mByProducts.isEmpty()); they are written as
    # `name.mByProducts.add(...)` in a later section of OP.java.
    with_products = set(re.findall(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*\.mByProducts\.add\(", text, re.M))

    recyclable: list[str] = []
    stats = {"declared": 0, "recyclable": 0, "withByproducts": 0, "excludedFlags": 0, "excludedNames": 0}
    for statement in text.split("\n"):
        match = DECL.match(statement)
        if not match:
            continue
        stats["declared"] += 1
        name = match.group(1)
        if "RECYCLABLE" not in statement:
            continue
        stats["recyclable"] += 1
        if name in with_products:
            stats["withByproducts"] += 1
            continue
        if any(re.search(r"(?<![A-Z_])" + flag + r"(?![A-Z_])", statement) for flag in EXCLUDED_FLAGS):
            stats["excludedFlags"] += 1
            continue
        if name.startswith(EXCLUDED_PREFIXES):
            stats["excludedNames"] += 1
            continue
        recyclable.append(name)

    recyclable = sorted(set(recyclable))
    lines = [
        "package com.gregtech.gregtech.data.generated;",
        "",
        "import java.util.Set;",
        "",
        "/**",
        " * GT6 prefix names whose shredder handler row exists (Loader_Recipes_Handlers:152-155): the prefix is",
        " * RECYCLABLE, declares no byproducts, and is neither ore- nor dust-based, a container, a cable, a wire",
        " * or a pipe. The port imports the filter result because its prefixes carry no RECYCLABLE tag.",
        " * <p>",
        " * GENERATED by tools/extract_gt6_recyclable_prefixes.py - do not edit by hand.",
        " */",
        "public final class RecyclablePrefixes {",
        "    private RecyclablePrefixes() {}",
        "",
        f"    public static final Set<String> NAMES = Set.of({literals(recyclable)});",
        "}",
    ]
    os.makedirs(os.path.dirname(OUT_JAVA), exist_ok=True)
    with open(OUT_JAVA, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")

    report = {"source": OP_JAVA, "counts": stats, "prefixes": recyclable}
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    with open(OUT_JSON, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(report, handle, indent=2, ensure_ascii=False)

    print("recyclable prefixes: " + str(len(recyclable)))
    print("counts: " + json.dumps(stats))
    print("names: " + ", ".join(recyclable))
    print("wrote " + OUT_JAVA)
    print("wrote " + OUT_JSON)


def literals(names: list[str]) -> str:
    if not names:
        return ""
    chunks = ['"' + name + '"' for name in names]
    out = ""
    line = ""
    for chunk in chunks:
        if len(line) + len(chunk) + 2 > 112:
            out += line.rstrip() + "\n"
            line = "                "
        line += chunk + ", "
    return (out + line.rstrip().rstrip(",")) if out else line.rstrip().rstrip(",")


if __name__ == "__main__":
    main()
