"""Generate the material enchantment table from GT6's MT.java.

GT6 gives materials enchantments per use (`addEnchantmentForTools/Damage/Weapons/Ammo/Ranged/
Fishing/Armors(Enchantment.x, level)`, chained calls). The material dictionary prints them, so this
tool transcribes the calls into a generated table with 1.20.1 enchantment ids.
"""

import io
import os
import re
from collections import Counter

SOURCE = r"F:\Dev\GregTech6\gregtech6-master\gregtech6-master\src\main\java\gregapi\data\MT.java"
TARGET = os.path.join("src", "main", "java", "com", "gregtech", "gregtech", "loaders", "c",
                      "GTEnchantmentTable.java")

# GT6 (1.7.10) enchantment field -> 1.20.1 registry id. `field_151370_z` is the obfuscated
# "Luck of the Sea" in 1.7.10 (GT6 uses the raw field name).
IDS = {
    "aquaAffinity": "aqua_affinity",
    "baneOfArthropods": "bane_of_arthropods",
    "blastProtection": "blast_protection",
    "featherFalling": "feather_falling",
    "field_151370_z": "luck_of_the_sea",
    "fireAspect": "fire_aspect",
    "fireProtection": "fire_protection",
    "flame": "flame",
    "fortune": "fortune",
    "infinity": "infinity",
    "knockback": "knockback",
    "looting": "looting",
    "power": "power",
    "projectileProtection": "projectile_protection",
    "protection": "protection",
    "punch": "punch",
    "respiration": "respiration",
    "sharpness": "sharpness",
    "silkTouch": "silk_touch",
    "smite": "smite",
    "thorns": "thorns",
}

# GT6's `addEnchantmentForDamage` forwards to weapons *and* ammo (OreDictMaterial:1091).
KINDS = ["Tools", "Damage", "Weapons", "Ammo", "Ranged", "Fishing", "Armors"]

text = io.open(SOURCE, encoding="utf-8", errors="replace").read()

entries = []
for line in text.splitlines():
    stripped = line.strip()
    if "addEnchantmentFor" not in stripped:
        continue
    material = stripped.split(".", 1)[0].strip()
    if not re.fullmatch(r"[A-Za-z0-9_]+", material):
        continue
    for kind, enchant, level in re.findall(
            r"addEnchantmentFor(\w+)\(Enchantment\.(\w+)\s*,\s*(\d+)\)", stripped):
        if kind not in KINDS or enchant not in IDS:
            continue
        entries.append((material, kind, IDS[enchant], int(level)))

print("enchantment entries: %d (materials: %d)" % (len(entries), len({e[0] for e in entries})))
print("kinds:", dict(Counter(e[1] for e in entries)))
unknown = {e for e in re.findall(r"Enchantment\.(\w+)", text)} - set(IDS)
if unknown:
    print("unmapped GT6 enchantments (skipped):", sorted(unknown))

# One material -> kind -> entries, material order preserved.
order = []
grouped = {}
for material, kind, enchant, level in entries:
    if material not in grouped:
        grouped[material] = {}
        order.append(material)
    grouped[material].setdefault(kind, []).append((enchant, level))

lines = [
    "package com.gregtech.gregtech.loaders.c;",
    "",
    "import java.util.List;",
    "",
    "/**",
    " * The enchantments GT6 gives materials, transcribed from {@code MT.java}'s",
    " * {@code addEnchantmentForTools/Damage/Weapons/Ammo/Ranged/Fishing/Armors} calls.",
    " *",
    " * <p>Used by the material dictionary's enchantment page. GT6 stores them in six lists per",
    " * material; {@code Damage} forwards to both weapons and ammo (OreDictMaterial:1091), so the port",
    " * keeps the kinds separate exactly like the original.</p>",
    " *",
    " * <p>GENERATED by tools/extract_enchantment_table.py - do not edit by hand.</p>",
    " */",
    "public final class GTEnchantmentTable {",
    "    /** One enchantment with the level GT6 grants for a given use. */",
    "    public record Entry(String kind, String enchantment, int level) {}",
    "",
    "    /** Every material GT6 enchants, in MT.java order. */",
    "    public static final List<Material> MATERIALS = List.of(",
]
for index, material in enumerate(order):
    kinds = []
    for kind in KINDS:
        if kind not in grouped[material]:
            continue
        rendered = ", ".join('new Entry("%s", "%s", %d)' % (kind, enchant, level)
                             for enchant, level in grouped[material][kind])
        kinds.append(rendered)
    suffix = "," if index < len(order) - 1 else ""
    lines.append('        new Material("%s", List.of(%s))%s' % (material, ", ".join(kinds), suffix))
lines += [
    "    );",
    "",
    "    /** The enchantments of one material. */",
    "    public record Material(String material, List<Entry> entries) {}",
    "",
    "    private GTEnchantmentTable() {}",
    "}",
    "",
]

io.open(TARGET, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print("wrote %s (%d materials)" % (TARGET.replace("\\", "/"), len(order)))
