"""Generate the alloy reverse table from Loader_Recipes_Alloys.java.

The port's alloy recipes are written as `mix(out("Bronze", 4), "Copper", 3, "Tin", 1)` calls; the
material dictionary needs the reverse direction ("which alloys is Copper part of?"), so this tool
transcribes the calls into a small generated table.
"""

import io
import os
import re

SOURCE = os.path.join("src", "main", "java", "com", "gregtech", "gregtech", "loaders", "c",
                      "Loader_Recipes_Alloys.java")
TARGET = os.path.join("src", "main", "java", "com", "gregtech", "gregtech", "loaders", "c",
                      "GTAlloyTable.java")

text = io.open(SOURCE, encoding="utf-8").read()
flat = re.sub(r"\s+", " ", text)

# Loop variables stand in for material names: `for (String copper : new String[]{"Copper", ...})`.
loop_values = {}
for match in re.finditer(r'for \(String (\w+) : new String\[\]\{([^}]*)\}\)', flat):
    variable, values = match.group(1), match.group(2)
    loop_values[variable] = [v.strip().strip('"') for v in values.split(",") if v.strip()]

alloys = []
for match in re.finditer(r'mix\(out\("([A-Za-z0-9_]+)",\s*(\d+)\)\s*,(.*?)\);', flat):
    output, units, pairs = match.group(1), int(match.group(2)), match.group(3)
    parts = [p.strip().strip('"') for p in pairs.split(",")]
    entries = []
    ok = True
    for i in range(0, len(parts) - 1, 2):
        name, amount = parts[i], parts[i + 1]
        if not re.fullmatch(r"[A-Za-z0-9_]+", name) or not amount.isdigit():
            ok = False
            break
        if name in loop_values:
            entries.append([(value, int(amount)) for value in loop_values[name]])
        else:
            entries.append([(name, int(amount))])
    if not ok or not entries:
        continue
    # Expand the cartesian product of the loop variables.
    combinations = [[]]
    for options in entries:
        combinations = [existing + [option] for existing in combinations for option in options]
    for combination in combinations:
        alloys.append((output, units, combination))

print("alloy recipes found: %d" % len(alloys))
for output, units, inputs in alloys[:5]:
    print("   %s x%d <- %s" % (output, units, " + ".join("%s x%d" % i for i in inputs)))

lines = [
    "package com.gregtech.gregtech.loaders.c;",
    "",
    "import java.util.List;",
    "",
    "/**",
    " * The port's alloying table (transcribed from {@link Loader_Recipes_Alloys}) in reverse-queryable",
    " * form: every entry is one {@code mix(out(...), ...)} call, i.e. what a molten alloy is made of.",
    " *",
    " * <p>Used by the material dictionary to print which alloys a material takes part in. Amounts are",
    " * in material units (1 unit = 144 mB), exactly like the recipes themselves.</p>",
    " *",
    " * <p>GENERATED by tools/extract_alloy_table.py - do not edit by hand.</p>",
    " */",
    "public final class GTAlloyTable {",
    "    /** One alloy: the output and its inputs (material names and units). */",
    "    public record Alloy(String output, int units, List<Input> inputs) {",
    "        public record Input(String material, int units) {}",
    "    }",
    "",
    "    public static final List<Alloy> ALLOYS = List.of(",
]
for index, (output, units, inputs) in enumerate(alloys):
    rendered = ", ".join('new Alloy.Input("%s", %d)' % entry for entry in inputs)
    suffix = "," if index < len(alloys) - 1 else ""
    lines.append('        new Alloy("%s", %d, List.of(%s))%s' % (output, units, rendered, suffix))
lines.append("    );")
lines.append("")
lines.append("    private GTAlloyTable() {}")
lines.append("}")
lines.append("")

io.open(TARGET, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print("wrote %s (%d alloys)" % (TARGET.replace("\\", "/"), len(alloys)))
