"""Port GregTech-6 Team / Gregorius Techneticies (LGPL-3.0-or-later) conversion registrations."""
from pathlib import Path
import argparse, re
from apply_gt6_autocrafting_permissions import SOURCE, ROOT, source_rows

TARGET = ROOT / 'core/src/main/java/com/gregtech/gregtech/content/recipe/OriginalFormConversions.java'

def generate():
    rows, fixed = source_rows(SOURCE)
    ore_source = (SOURCE / 'gregapi/data/OP.java').read_text(encoding='utf-8')
    ordinary, dense = [], []
    for line in ore_source.splitlines():
        name = re.match(r'\s*(\w+)\s*=\s*create\(', line)
        if not name: continue
        if 'STANDARD_ORE' in line and name[1] != 'oreRaw': ordinary.append(name[1])
        if 'DENSE_ORE' in line: dense.append(name[1])
    lines = ['/* Gregorius Techneticies / GregTech-6 Team source data, LGPL-3.0-or-later. */',
             'package com.gregtech.gregtech.content.recipe;', '', 'import java.util.*;', '',
             '/** Generated by tools/generate_original_form_conversions.py from Loader_Recipes_Handlers and OP. */',
             'public final class OriginalFormConversions {', '    private OriginalFormConversions() {}',
             '    public record Conversion(String input, int inputCount, String output, int outputCount, boolean single) {}',
             '    public record Form(String prefix, String material) {}',
             '    public static final Form UNKNOWN = new Form("", "");',
             '    public static final List<Conversion> FIXED = List.of(']
    for i, row in enumerate(fixed.values()):
        lines.append('            new Conversion("%s", %s, "%s", %s, %s)%s // :%s' % (
            row['input'], row['input_count'], row['output'], row['output_count'],
            str(row['kind'] == '1ToY').lower(), ');' if i == len(fixed)-1 else ',', row['line']))
    for name, values in [('STANDARD_ORES', ordinary), ('DENSE_ORES', dense)]:
        lines += ['    public static final Set<String> %s = Set.of(' % name,
                  '            '+', '.join('"'+v+'"' for v in values)+');']
    lines.append('''
    public static FormConversionSelector selector(Conversion conversion) {
        if (!conversion.single()) return FormConversionSelector.NONE;
        int variants = 0, offset = 0;
        for (Conversion candidate : FIXED) if (candidate.single() && candidate.input().equals(conversion.input())) {
            if (candidate.equals(conversion)) offset = variants;
            variants++;
        }
        return new FormConversionSelector(Math.max(1, variants), offset);
    }

    private static final List<Conversion> RULES = rules();
    private static List<Conversion> rules() {
        var rules = new ArrayList<>(FIXED);
        for (String prefix : STANDARD_ORES) rules.add(new Conversion(prefix, 1, "oreRaw", 1, true));
        for (String prefix : DENSE_ORES) rules.add(new Conversion(prefix, 1, "oreRaw", 2, true));
        for (int big = 1; big <= 16; big++) for (int small = 1; small < big; small++) if (big % small == 0) {
            String bigPrefix = "wireGt" + String.format(Locale.ROOT, "%02d", big);
            String smallPrefix = "wireGt" + String.format(Locale.ROOT, "%02d", small);
            if (big / small < 10) rules.add(new Conversion(smallPrefix, big / small, bigPrefix, 1, false));
            rules.add(new Conversion(bigPrefix, 1, smallPrefix, big / small, true));
        }
        return List.copyOf(rules);
    }

    /** The source constructors replace plain shaped/shapeless recipes; their output count is irrelevant. */
    public static boolean replaces(List<Form> grid, int width, int height, boolean shapeless,
                                   boolean gtOwned, Form output) {
        if (gtOwned || output == null || output.material().isEmpty()) return false;
        var occupied = grid.stream().filter(Objects::nonNull).toList();
        if (occupied.isEmpty()) return false;
        Form input = occupied.get(0);
        if (input.material().isEmpty()) return false;
        for (Conversion rule : RULES) {
            if (occupied.size() != rule.inputCount() || !input.prefix().equals(rule.input())
                    || !output.prefix().equals(rule.output())) continue;
            if (!shapeless && !rule.single() && rule.inputCount() != 9) {
                // Source XToY accepts the special full 3x3 input array with its upper-left 2x2 occupied.
                if (rule.inputCount() != 4 || width != 3 || height != 3 || grid.size() != 9
                        || grid.get(2) != null || grid.get(5) != null || grid.get(6) != null
                        || grid.get(7) != null || grid.get(8) != null) continue;
            }
            if (!rule.single() && !output.material().equals(input.material())) continue;
            if (occupied.stream().allMatch(form -> form.prefix().equals(input.prefix())
                    && (rule.single() || form.material().equals(input.material())))) return true;
        }
        return false;
    }
}''')
    return '\n'.join(lines)+'\n'

if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    content=generate()
    if args.check:
        assert TARGET.read_text(encoding='utf-8') == content, 'Source conversion catalog is stale'
    else: TARGET.write_text(content,encoding='utf-8')
    print('Original form conversion catalog matches source' if args.check else 'Original form conversion catalog generated')
