#!/usr/bin/env python3
"""Generate BasicMachineOriginalParams.java from the original GT6 registrations.

The port used synthetic tier tables for machine energy, parallel limits and
hardness/resistance. GT6 sets those per machine and per tier; this generator copies the
original numbers so the two can no longer drift.

The accepted energy range is emitted too (GT6 NBT_INPUT_MIN / NBT_INPUT_MAX, defaulting to
input/2 .. input*2 exactly like MultiTileEntityBasicMachine.readFromNBT2). Without it the
fusion reactor — 8192 TU/t nominal — was clamped to 1..16 TU/t and could never run.

Inputs : tools/gt6_basic_machine_recipes.json    (tab "Basic Machines")
         tools/gt6_multiblock_recipes.json       (tab "Multiblock Machines")
Output : src/main/java/com/gregtech/gregtech/data/BasicMachineOriginalParams.java
"""

from __future__ import annotations

import json
from pathlib import Path

import gt6_machine_map as mapping

ROOT = Path(__file__).resolve().parents[1]
OUT = mapping.JAVA / "data/BasicMachineOriginalParams.java"
BASIC = Path(__file__).with_name("gt6_basic_machine_recipes.json")
MULTIBLOCK = Path(__file__).with_name("gt6_multiblock_recipes.json")

# Port machines registered as single blocks although GT6 registers them as multiblocks;
# their parameters come from the "Multiblock Machines" registrations.
MULTIBLOCK_BACKED = mapping.MULTIBLOCK_MACHINE_NAMES


def params_of(entry: dict) -> dict:
    p = entry.get("params") or {}
    energy = p.get("energy") or "HU"
    inp = p.get("input") if p.get("input") is not None else 32
    # GT6 MultiTileEntityBasicMachine.readFromNBT2:126-128 — with only NBT_INPUT the accepted
    # range is input/2 .. input*2; NBT_INPUT_MIN / NBT_INPUT_MAX override each bound. Resolving
    # the defaults here (instead of at runtime) keeps the Java side a plain copy of GT6.
    return {
        "energy": energy,
        "input": inp,
        "inputMin": p.get("inputMin") if p.get("inputMin") is not None else max(1, inp // 2),
        "inputMax": p.get("inputMax") if p.get("inputMax") is not None else inp * 2,
        "parallel": p.get("parallel") if p.get("parallel") is not None else 1,
        "parallelDuration": bool(p.get("parallelDuration")),
        "hardness": p.get("hardness") if p.get("hardness") is not None else 6.0,
        "resistance": p.get("resistance") if p.get("resistance") is not None else 6.0,
    }


def main() -> int:
    basic = json.loads(BASIC.read_text(encoding="utf-8"))["entries"]
    multiblock = json.loads(MULTIBLOCK.read_text(encoding="utf-8"))["entries"]
    basic_index = mapping.index_entries(basic)
    multiblock_index = mapping.index_entries(multiblock)

    rows: list[str] = []
    missing: list[str] = []

    for machine, tier, original in mapping.single_block_variants():
        entry = mapping.lookup(basic_index, original, tier)
        if entry is None:
            missing.append("%s t%d -> %s" % (machine, tier, original))
            continue
        rows.append(format_row(machine, tier, original, params_of(entry)))

    for machine, original in MULTIBLOCK_BACKED.items():
        entry = mapping.lookup(multiblock_index, original, 1)
        if entry is None:
            missing.append("%s -> %s" % (machine, original))
            continue
        rows.append(format_row(machine, 1, original, params_of(entry)))

    header = '''package com.gregtech.gregtech.data;

import java.util.List;

/**
 * Machine parameters copied from the original GregTech 6 registrations
 * ({@code Loader_MultiTileEntities}, tabs "Basic Machines" and "Multiblock Machines").
 * <p>
 * GENERATED by {@code tools/generate_machine_params_table.py} - do not edit by hand.
 * The port previously derived these from synthetic tier tables, which disagreed with GT6
 * for the kinetic/electric machines (per-tier parallel limits) and for the machines that
 * GT6 registers as multiblocks.
 * </p>
 */
public final class BasicMachineOriginalParams {
    /** One port machine variant. Values are verbatim GT6 registration NBT. */
    public record Params(String machine, int tier, String originalName, String energyType,
                         long energyInput, long energyInputMin, long energyInputMax,
                         int parallel, boolean parallelDuration,
                         float hardness, float resistance) {}

    public static final List<Params> PARAMS = List.of(
'''
    footer = '''    );

    /** Original GT6 parameters for one port machine type and tier, or {@code null} if GT6 has none. */
    public static Params find(String machine, int tier) {
        for (Params params : PARAMS) {
            if (params.machine().equals(machine) && params.tier() == tier) return params;
        }
        return null;
    }

    private BasicMachineOriginalParams() {}
}
'''
    OUT.write_text(header + ",\n".join(rows) + "\n" + footer, encoding="utf-8", newline="\n")
    print("wrote %s (%d entries)" % (OUT, len(rows)))
    if missing:
        print("WARNING no original registration for:")
        for name in missing:
            print("   ", name)
    return 0


def format_row(machine: str, tier: int, original: str, p: dict) -> str:
    return (
        '            new Params("%s", %d, "%s", "%s", %dL, %dL, %dL, %d, %s, %.1fF, %.1fF)'
        % (
            machine,
            tier,
            original.replace('"', '\\"'),
            p["energy"],
            p["input"],
            p["inputMin"],
            p["inputMax"],
            p["parallel"],
            "true" if p["parallelDuration"] else "false",
            p["hardness"],
            p["resistance"],
        )
    )


if __name__ == "__main__":
    raise SystemExit(main())
