"""Generate registrations and shared-model variants from the original GT6 durability data."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def main():
    specs = json.loads((ROOT / 'tools/gt6_anvil_specs.json').read_text(encoding='utf-8'))
    assets = ROOT / 'src/main/resources/assets/gregtech'
    states = (assets / 'blockstates/anvil.json').read_text(encoding='utf-8')
    languages = {code: json.loads((assets / f'lang/{code}.json').read_text(encoding='utf-8')) for code in ('en_us', 'zh_cn')}
    lines = ['package com.gregtech.gregtech.content.tool;', '', '// Generated by tools/generate_anvil_variants.py; source data is kept beside the generator.',
             'public final class AnvilDefinitions {', '    private AnvilDefinitions() {}', '    public static void registerAll() {']
    for spec in specs:
        material = spec['material']
        ident = 'anvil' if material == 'Steel' else 'anvil_' + material.lower()
        lines.append(f'        com.gregtech.gregtech.registry.GTToolBlocks.anvil("{ident}", "{material}", {spec["durability"]}L);')
        (assets / f'blockstates/{ident}.json').write_text(states, encoding='utf-8')
        (assets / f'models/item/{ident}.json').write_text(json.dumps({'parent': 'gregtech:block/tool/anvil'}, indent=2) + '\n', encoding='utf-8')
        for code, lang in languages.items():
            name = lang.get('material.gregtech.' + material.lower(), material)
            lang['block.gregtech.' + ident] = (f'Anvil ({name})' if code == 'en_us' else f'铁砧（{name}）')
    lines += ['    }', '}']
    (ROOT / 'src/main/java/com/gregtech/gregtech/content/tool/AnvilDefinitions.java').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    for code, lang in languages.items():
        lang['gt.tooltip.anvil.durability'] = 'Remaining durability: %s (base uses)' if code == 'en_us' else '剩余耐久：%s（基础使用次数）'
        lang['gt.tooltip.mass_storage.1'] = 'Stores up to 1,000,000 of one item type' if code == 'en_us' else '最多储存 1,000,000 个同种物品'
        (assets / f'lang/{code}.json').write_text(json.dumps(lang, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

if __name__ == '__main__':
    main()
