#!/usr/bin/env python3
"""Generate MaterialRegistryExtras.java (field aliases + display names) from material Java sources."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JAVA_ALIAS_SOURCES = (
    ROOT / "tools/generated/materials-source.java.txt",
    ROOT / "src/main/java/com/gregtech/gregtech/data/ImportedMaterialData.java",
)
JAVA_DISPLAY_SOURCES = JAVA_ALIAS_SOURCES + (
    ROOT / "src/main/java/com/gregtech/gregtech/data/AntimatterMaterials.java",
)
OUT = ROOT / "src/main/java/com/gregtech/gregtech/data/generated/MaterialRegistryExtras.java"

MATERIAL_LINE_RE = re.compile(
    r"(\w+(?:\s*,\s*\w+)*)\s*=\s*(?:\w+\.)?(?:create|metal|element|alloy|ore|gem|dust|gas|wood|stone|elec|cent|clay)\(\s*[^,]+,\s*\"((?:\\.|[^\"\\])*)\""
)
LOCAL_NAME_RE = re.compile(r'\.setLocalName\("((?:\\.|[^"\\])*)"\)')


def sanitize(name: str) -> str:
    return name.replace(" ", "").replace("-", "").replace("'", "")


def java_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def parse_material_blocks(text: str) -> list[str]:
    blocks: list[str] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        if MATERIAL_LINE_RE.search(lines[i]):
            block = lines[i]
            i += 1
            while i < len(lines) and lines[i].strip().startswith("."):
                block += lines[i]
                i += 1
            blocks.append(block)
        else:
            i += 1
    return blocks


def parse_materials(text: str) -> list[tuple[str, str, str | None]]:
    entries: list[tuple[str, str, str | None]] = []
    for block in parse_material_blocks(text):
        match = MATERIAL_LINE_RE.search(block)
        if not match:
            continue
        field = match.group(1).split(",")[0].strip()
        factory_name = match.group(2)
        local_match = LOCAL_NAME_RE.search(block)
        local_name = local_match.group(1) if local_match else None
        entries.append((field, factory_name, local_name))
    return entries


def english_display(factory_name: str, registry: str, local_name: str | None) -> str:
    if local_name and " " in local_name:
        return local_name
    return factory_name


def main() -> None:
    alias_entries: list[tuple[str, str, str | None]] = []
    display_entries: list[tuple[str, str, str | None]] = []

    for path in JAVA_ALIAS_SOURCES:
        if path.is_file():
            alias_entries.extend(parse_materials(path.read_text(encoding="utf-8")))
    for path in JAVA_DISPLAY_SOURCES:
        if path.is_file():
            display_entries.extend(parse_materials(path.read_text(encoding="utf-8")))

    aliases: list[tuple[str, str]] = []
    displays: dict[str, str] = {}
    canonical = {sanitize(factory_name) for _, factory_name, _ in alias_entries}

    for field, factory_name, local_name in alias_entries:
        registry = sanitize(factory_name)
        if field != registry:
            alias_key = sanitize(field)
            # Skip field aliases that would hijack a canonical material name (e.g. wood field Gold → Goldwood vs element Gold).
            if alias_key in canonical and alias_key != registry:
                continue
            aliases.append((field, registry))

    for field, factory_name, local_name in display_entries:
        registry = sanitize(factory_name)
        displays[registry] = english_display(factory_name, registry, local_name)

    alias_lines = [
        f'        GTMaterialRegistry.registerAlias("{java_string(alias)}", "{java_string(registry)}");'
        for alias, registry in sorted(set(aliases))
    ]
    display_lines = [
        f'        GTMaterialRegistry.setDisplayName("{java_string(registry)}", "{java_string(display)}");'
        for registry, display in sorted(displays.items())
    ]

    body = "\n".join(alias_lines + display_lines)
    java = """package com.gregtech.gregtech.data.generated;

import com.gregtech.gregtech.api.material.GTMaterialRegistry;

/**
 * Auto-generated by {@code tools/generate_material_metadata.py}.
 * Registers GT6 field-name aliases (e.g. {@code Cu} → {@code Copper}) and human-readable display names.
 */
public final class MaterialRegistryExtras {
    private MaterialRegistryExtras() {}

    public static void apply() {
""" + body + """
    }
}
"""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(java, encoding="utf-8")
    print(f"Wrote {OUT.name}: {len(set(aliases))} aliases, {len(displays)} display names")


if __name__ == "__main__":
    main()
