"""Import inherited ToolStats classification, used for real material enchantments."""
from pathlib import Path
import hashlib,json,re
root=Path(__file__).resolve().parents[1]
source=root.parent/'gregtech6-master/gregtech6-master/src/main/java'
loader=source/'gregtech/loaders/a/Loader_Tools.java'
raw=loader.read_text(encoding='utf-8')
files={p.stem:p for p in source.rglob('*.java') if p.stem.startswith('GT_Tool_') or p.stem=='ToolStats'}
used={loader}
def flags(cls):
    path=files[cls];used.add(path);text=path.read_text(encoding='utf-8')
    parent=re.search(r'class\s+\w+\s+extends\s+(\w+)',text)
    values=flags(parent[1]) if parent and parent[1] in files else [True,False,False]
    for i,method in enumerate(['isMiningTool','isWeapon','isRangedWeapon']):
        found=re.search(r'boolean\s+'+method+r'\(\)\s*\{\s*return\s+([TF]|true|false)\s*;',text)
        if found:values[i]=found[1] in ('T','true')
    return values
rows=[]
for name,cls in re.findall(r'addTool\(ToolsGT\.(\w+)[^\n]*?new\s+(GT_Tool_\w+)\(',raw):
    rows.append((name.replace('_',''),flags(cls)))
defs=(root/'core/src/main/java/com/gregtech/gregtech/api/tool/ToolDefinition.java').read_text(encoding='utf-8')
names=re.findall(r'^    ([A-Z_]+)\(\d+,',defs,re.M)
assert set(n.replace('_','') for n in names)<=set(n for n,v in rows)
dest=root/'core/src/main/java/com/gregtech/gregtech/content/tool/OriginalToolFlags.java'
lines=[raw.split('package ')[0],'package com.gregtech.gregtech.content.tool;',
       '/** Original inherited ToolStats classifications; generated by tools/import_origin_tool_flags.py. */',
       'public final class OriginalToolFlags {','private OriginalToolFlags() {}',
       'public record Flags(boolean mining,boolean weapon,boolean ranged) {}',
       'private static final java.util.Map<String,Flags> FLAGS=new java.util.HashMap<>();','static {']
for name,value in rows:lines.append('FLAGS.put('+json.dumps(name)+',new Flags('+','.join(str(v).lower() for v in value)+'));')
lines+=['}','public static Flags of(String name){var flags=FLAGS.get(name.replace("_",""));if(flags==null)throw new IllegalArgumentException("Unknown original tool "+name);return flags;}','}']
dest.write_text('\n'.join(lines)+'\n',encoding='utf-8')
(root/'docs/integration/verification/origin-tool-flags-20261004.json').write_text(json.dumps({'sources':[{'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(used)],'original_tools':len(rows),'manual_native_tools':len(names),'scope':'Source classification import; native enchantment verification recorded separately'},indent=2)+'\n',encoding='utf-8')
print('Imported inherited classifications for',len(rows),'source tools; covered',len(names),'native tools')
