"""Read original tab assignments and bind existing native item names to them."""
from pathlib import Path
import collections
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / 'gregtech6-master/gregtech6-master/src/main/java'
src = SOURCE / 'gregtech/loaders/b/Loader_MultiTileEntities.java'
raw = src.read_text(encoding='utf-8')
rows = re.findall(r'aRegistry\.add\(([^,\n]+),\s*"([^"]+)"\s*,\s*([^,]+),\s*(\d+)\s*,\s*([\w.]+)', raw)
groups = collections.OrderedDict()
names = {}
patterns = []
def normal(s): return re.sub('[^a-z0-9]', '', s.lower())
for order, (expr, group, legacy, tab, cls) in enumerate(rows):
    family = re.sub('[^a-z0-9]+', '_', group.lower()).strip('_')
    family = {'axles_and_gearboxes':'axles', 'misc_tool_blocks':'tool_blocks',
              'multiblock_machines':'multiblocks', 'c_foam':'foam'}.get(family, family)
    groups.setdefault(family, {'name':group, 'legacy_tab':int(tab)})
    if re.fullmatch(r'\s*"[^"]+"\s*', expr):
        names.setdefault(normal(expr.strip()[1:-1]), (family,order))
    elif 'aMat.getLocal()' in expr:
        bits = re.findall(r'"([^"]*)"', expr)
        if bits:
            # The localized material belongs at the source expression's insertion point.
            prefix = ''.join(re.findall(r'"([^"]*)"', expr.split('aMat.getLocal()')[0]))
            suffix = ''.join(re.findall(r'"([^"]*)"', expr.split('aMat.getLocal()')[1]))
            patterns.append((normal(prefix),normal(suffix),family,order))

lang = json.loads((ROOT/'core/src/main/resources/assets/gregtech/lang/en_us.json').read_text(encoding='utf-8'))
bound = {}
for key, text in lang.items():
    if not key.startswith(('block.gregtech.','item.gregtech.')) or not isinstance(text,str): continue
    item = key.split('.',2)[2]
    text = normal(text)
    match = names.get(text)
    if match is None:
        for before,after,family,order in patterns:
            if (before or after) and text.startswith(before) and text.endswith(after) and len(text)>len(before)+len(after):
                match = (family,order); break
    if match: bound[item] = match

# Original independent MultiItem pages, retaining their registration order.
gen = (ROOT/'core/src/main/java/com/gregtech/gregtech/registry/GTMultiItemsGen.java').read_text(encoding='utf-8')
for order,(item,name,cat,flag) in enumerate(re.findall(r'"([^"]+)", "([^"]+)", "([^"]+)", "([^"]*)"',gen)):
    bound[item] = ({'randomtools':'equipment','bottles':'bottles','food':'nature_foods','bumbles':'bumblebees'}.get(cat,'equipment'),order)

license = raw[:raw.index('package ')]
dest = ROOT/'core/src/main/java/com/gregtech/gregtech/content/creative/SourceCreativeCatalog.java'
lines = [license,'package com.gregtech.gregtech.content.creative;',
         '/** Original category names/order; generated by tools/import_origin_creative.py. */',
         'public final class SourceCreativeCatalog {',
         'private SourceCreativeCatalog() {}',
         'public record Entry(String family,int order) {}',
         'private static final java.util.Map<String,Entry> ITEMS=new java.util.HashMap<>();',
         'static {']
bindings = sorted(bound.items())
for chunk in range((len(bindings)+399)//400):
    lines.append('init'+str(chunk)+'();')
lines.append('}')
for index,(item,(family,order)) in enumerate(bindings):
    if index % 400 == 0: lines.append('private static void init'+str(index//400)+'(){')
    lines.append('ITEMS.put('+json.dumps(item)+',new Entry('+json.dumps(family)+','+str(order)+'));')
    if index % 400 == 399 or index == len(bindings)-1: lines.append('}')
lines += ['public static Entry entry(String id){return ITEMS.get(id);}', '}']
dest.write_text('\n'.join(lines)+'\n',encoding='utf-8')
report = {'source':str(src),'sha256':hashlib.sha256(src.read_bytes()).hexdigest(),
          'source_groups':groups,'native_name_bindings':len(bound),'scope':'Source import, not runtime verification'}
(ROOT/'docs/integration/verification/origin-creative-source-20261004.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'groups':list(groups), 'bindings':len(bound)}))
