package com.gregtech.gregtech.registry;

import com.gregtech.gregtech.blockentity.RockBlockEntity;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

/** Original surface-rock storage; machine entities belong to their own platform registries. */
public final class GTBlockEntities {
    public static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES =
            DeferredRegister.create(Registries.BLOCK_ENTITY_TYPE, "gregtech");
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.misc.SupporterCertificateBlockEntity>> SUPPORTER_CERTIFICATE=BLOCK_ENTITIES.register("supporter_certificate",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.misc.SupporterCertificateBlockEntity::new,GTToolBlocks.SUPPORTER_CERTIFICATE.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.energy.ReactorCoreBlockEntity>> REACTOR_CORE=BLOCK_ENTITIES.register("reactor_core",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.energy.ReactorCoreBlockEntity::new,GTEnergyNodes.REACTOR_CORE_BLOCK.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.energy.ReactorCore2x2BlockEntity>> REACTOR_CORE_2X2=BLOCK_ENTITIES.register("reactor_core_2x2",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.energy.ReactorCore2x2BlockEntity::new,GTEnergyNodes.REACTOR_CORE_2X2.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.energy.PlacedReactorRodBlockEntity>> PLACED_REACTOR_ROD=BLOCK_ENTITIES.register("placed_reactor_rod",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.energy.PlacedReactorRodBlockEntity::new,GTFuelRods.BLOCKS.values().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<RockBlockEntity>> ROCK =
            BLOCK_ENTITIES.register("rock", () -> BlockEntityType.Builder.of(RockBlockEntity::new, GTBlocks.ROCK.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.tool.DynamiteBlockEntity>> DYNAMITE=BLOCK_ENTITIES.register("dynamite",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.tool.DynamiteBlockEntity::new,GTToolBlocks.DYNAMITE.get(),GTToolBlocks.BOOMSTICK.get(),GTToolBlocks.DYNAMITE_STRONG.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.ItemPipeBlockEntity>> ITEM_PIPE=BLOCK_ENTITIES.register("item_pipe",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.ItemPipeBlockEntity::new,GTItemPipes.all().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.HopperBlockEntity>> HOPPER=BLOCK_ENTITIES.register("hopper",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.HopperBlockEntity::new,com.gregtech.gregtech.content.transport.HopperRegistries.hoppers().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.QueueHopperBlockEntity>> QUEUE_HOPPER=BLOCK_ENTITIES.register("queue_hopper",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.QueueHopperBlockEntity::new,com.gregtech.gregtech.content.transport.HopperRegistries.queues().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.TreeHoleBlockEntity>> TREE_HOLE=BLOCK_ENTITIES.register("tree_hole",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.TreeHoleBlockEntity::new,GTTreeHoles.blocks().toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.tool.PortableContainerBlockEntity>> PORTABLE_CONTAINER=BLOCK_ENTITIES.register("portable_container",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.tool.PortableContainerBlockEntity::new,GTToolBlocks.PORTABLE.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.MultiblockPortBlockEntity>> MULTIBLOCK_PORT=BLOCK_ENTITIES.register("multiblock_port",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.MultiblockPortBlockEntity::new,GTMultiblocks.parts().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.CokeOvenControllerBlockEntity>> COKE_OVEN=BLOCK_ENTITIES.register("coke_oven",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.CokeOvenControllerBlockEntity::new,GTMultiblocks.COKE_OVEN_MAIN.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.CryoDistillationControllerBlockEntity>> CRYO_DISTILLATION=BLOCK_ENTITIES.register("cryo_distillation",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.CryoDistillationControllerBlockEntity::new,GTMultiblocks.CRYO_DISTILLATION_MAIN.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.MultiblockTankControllerBlockEntity>> MULTIBLOCK_TANK=BLOCK_ENTITIES.register("multiblock_tank",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.MultiblockTankControllerBlockEntity::new,GTMultiblocks.tanks().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.OriginalLargeBoilerControllerBlockEntity>> ORIGINAL_LARGE_BOILER=BLOCK_ENTITIES.register("original_large_boiler",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.OriginalLargeBoilerControllerBlockEntity::new,GTMultiblocks.boilers().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.LargeTurbineControllerBlockEntity>> LARGE_TURBINE=BLOCK_ENTITIES.register("large_turbine",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.LargeTurbineControllerBlockEntity::new,com.gregtech.gregtech.content.multiblock.AxialGeneratorDefinitions.registeredBlocks(true)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.LargeDynamoControllerBlockEntity>> LARGE_DYNAMO=BLOCK_ENTITIES.register("large_dynamo",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.LargeDynamoControllerBlockEntity::new,com.gregtech.gregtech.content.multiblock.AxialGeneratorDefinitions.registeredBlocks(false)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.LargeGasTurbineControllerBlockEntity>> LARGE_GAS_TURBINE=BLOCK_ENTITIES.register("large_gas_turbine",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.LargeGasTurbineControllerBlockEntity::new,com.gregtech.gregtech.content.multiblock.GasTurbineDefinitions.registeredBlocks()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.LargeHeatExchangerControllerBlockEntity>> LARGE_HEAT_EXCHANGER=BLOCK_ENTITIES.register("large_heat_exchanger",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.LargeHeatExchangerControllerBlockEntity::new,GTMultiblocks.LARGE_HEAT_EXCHANGER_MAIN.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.LargeCrucibleControllerBlockEntity>> LARGE_CRUCIBLE=BLOCK_ENTITIES.register("large_crucible",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.LargeCrucibleControllerBlockEntity::new,GTMultiblocks.crucibles().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.LogisticsCoreControllerBlockEntity>> LOGISTICS_CORE=BLOCK_ENTITIES.register("logistics_core",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.LogisticsCoreControllerBlockEntity::new,GTMultiblocks.LOGISTICS_CORE.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.LargeBoilerControllerBlockEntity>> LARGE_BOILER=BLOCK_ENTITIES.register("large_boiler",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.LargeBoilerControllerBlockEntity::new,GTMultiblocks.LARGE_BOILER_MAIN.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.BedrockDrillControllerBlockEntity>> BEDROCK_DRILL=BLOCK_ENTITIES.register("bedrock_drill",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.BedrockDrillControllerBlockEntity::new,GTMultiblocks.BEDROCK_DRILL_MAIN.get(),GTMultiblocks.findPart(17999).get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.LightningRodControllerBlockEntity>> LIGHTNING_ROD=BLOCK_ENTITIES.register("lightning_rod",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.LightningRodControllerBlockEntity::new,GTMultiblocks.LIGHTNING_ROD_MAIN.get(),GTMultiblocks.findPart(17998).get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.platform.neoforge.smeltery.MoldEntity>> MOLD=com.gregtech.gregtech.platform.neoforge.smeltery.SmelteryRegistries.MOLD;
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.MoldBasinBlockEntity>> MOLD_BASIN=BLOCK_ENTITIES.register("mold_basin",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.MoldBasinBlockEntity::new,com.gregtech.gregtech.platform.neoforge.smeltery.SmelteryRegistries.basins().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.CrucibleFaucetBlockEntity>> CRUCIBLE_FAUCET=BLOCK_ENTITIES.register("crucible_faucet",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.CrucibleFaucetBlockEntity::new,com.gregtech.gregtech.platform.neoforge.smeltery.SmelteryRegistries.faucets().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.CrucibleCrossingBlockEntity>> CRUCIBLE_CROSSING=BLOCK_ENTITIES.register("crucible_crossing",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.CrucibleCrossingBlockEntity::new,com.gregtech.gregtech.platform.neoforge.smeltery.SmelteryRegistries.crossings().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.platform.neoforge.smeltery.SolidBurningBoxEntity>> SOLID_BURNING_BOX=com.gregtech.gregtech.platform.neoforge.smeltery.SmelteryRegistries.SOLID_BURNING_BOX;
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.BurningBoxBlockEntity>> BURNING_BOX=BLOCK_ENTITIES.register("burning_box",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.BurningBoxBlockEntity::new,com.gregtech.gregtech.platform.neoforge.smeltery.SmelteryRegistries.fuelBoxes().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.tool.BumbliaryBlockEntity>> BUMBLIARY=BLOCK_ENTITIES.register("bumbliary",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.tool.BumbliaryBlockEntity::new,GTBumbleBlocks.BUMBLIARY.get(),GTBumbleBlocks.ADVANCED_BUMBLIARY.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.misc.BumbleHiveBlockEntity>> BUMBLE_HIVE=BLOCK_ENTITIES.register("bumble_hive",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.misc.BumbleHiveBlockEntity::new,GTBumbleBlocks.allHives()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.BushBlockEntity>> BUSH=BLOCK_ENTITIES.register("bush",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.BushBlockEntity::new,GTBushes.BUSH.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.FluidSpringBlockEntity>> FLUID_SPRING=BLOCK_ENTITIES.register("fluid_spring",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.FluidSpringBlockEntity::new,GTFluidSprings.FLUID_SPRING.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.CFoamBlockEntity>> CFOAM=BLOCK_ENTITIES.register("cfoam",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.CFoamBlockEntity::new,GTConstructionBlocks.CFOAM_FRESH.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.misc.PileBlockEntity>> PILE=BLOCK_ENTITIES.register("pile",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.misc.PileBlockEntity::new,GTMaterialPiles.all().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.misc.CoinPileBlockEntity>> COIN_PILE=BLOCK_ENTITIES.register("coin_pile",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.misc.CoinPileBlockEntity::new,GTCoinPiles.COIN_PILE.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.inventory.BookShelfBlockEntity>> BOOKSHELF=BLOCK_ENTITIES.register("bookshelf",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.inventory.BookShelfBlockEntity::new,GTBookShelves.all().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.inventory.SafeBlockEntity>> SAFE=BLOCK_ENTITIES.register("safe",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.inventory.SafeBlockEntity::new,GTSafes.all().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.block.misc.AdvancedCraftingTableBlockEntity>> ADVANCED_CRAFTING_TABLE=BLOCK_ENTITIES.register("advanced_crafting_table",()->BlockEntityType.Builder.of(com.gregtech.gregtech.block.misc.AdvancedCraftingTableBlockEntity::new,GTCraftingTables.ADVANCED.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.block.misc.ChargingCraftingTableBlockEntity>> CHARGING_CRAFTING_TABLE=BLOCK_ENTITIES.register("charging_crafting_table",()->BlockEntityType.Builder.of(com.gregtech.gregtech.block.misc.ChargingCraftingTableBlockEntity::new,GTCraftingTables.CHARGING.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.inventory.DrawerQuadBlockEntity>> DRAWER_QUAD=BLOCK_ENTITIES.register("drawer_quad",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.inventory.DrawerQuadBlockEntity::new,GTStorageContainers.DRAWERS.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.inventory.BottleCrateBlockEntity>> BOTTLE_CRATE=BLOCK_ENTITIES.register("bottle_crate",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.inventory.BottleCrateBlockEntity::new,GTStorageContainers.BOTTLE_CRATES.stream().map(net.neoforged.neoforge.registries.DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.inventory.LockerBlockEntity>> LOCKER=BLOCK_ENTITIES.register("locker",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.inventory.LockerBlockEntity::new,GTStorageContainers.LOCKER.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.inventory.MetalChestBlockEntity>> METAL_CHEST=BLOCK_ENTITIES.register("metal_chest",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.inventory.MetalChestBlockEntity::new,GTMetalChests.all().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.inventory.EnderGarbageBlockEntity>> ENDER_GARBAGE=BLOCK_ENTITIES.register("ender_garbage",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.inventory.EnderGarbageBlockEntity::new,GTStorageContainers.ENDER_GARBAGE.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.inventory.EnderGarbageDumpBlockEntity>> ENDER_GARBAGE_DUMP=BLOCK_ENTITIES.register("ender_garbage_dump",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.inventory.EnderGarbageDumpBlockEntity::new,GTStorageContainers.ENDER_GARBAGE_DUMP.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.inventory.UsbSwitchBlockEntity>> USB_SWITCH=BLOCK_ENTITIES.register("usb_switch",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.inventory.UsbSwitchBlockEntity::new,GTStorageContainers.USB_SWITCH.get(),GTStorageContainers.HDD_SWITCH.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.block.misc.ExtenderBlockEntity>> EXTENDER=BLOCK_ENTITIES.register("extender",()->BlockEntityType.Builder.of(com.gregtech.gregtech.block.misc.ExtenderBlockEntity::new,GTRelaysFilters.EXTENDERS.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.block.misc.FilterBlockEntity>> FILTER=BLOCK_ENTITIES.register("filter",()->BlockEntityType.Builder.of(com.gregtech.gregtech.block.misc.FilterBlockEntity::new,GTRelaysFilters.FILTERS.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.block.misc.AutoIgniterBlockEntity>> AUTO_IGNITER=BLOCK_ENTITIES.register("auto_igniter",()->BlockEntityType.Builder.of(com.gregtech.gregtech.block.misc.AutoIgniterBlockEntity::new,GTRelaysFilters.IGNITERS.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.block.misc.AutoHammerBlockEntity>> AUTO_HAMMER=BLOCK_ENTITIES.register("auto_hammer",()->BlockEntityType.Builder.of(com.gregtech.gregtech.block.misc.AutoHammerBlockEntity::new,GTRelaysFilters.HAMMERS.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.tool.MaterialAnvilBlockEntity>> MATERIAL_ANVIL=BLOCK_ENTITIES.register("material_anvil",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.tool.MaterialAnvilBlockEntity::new,GTManualStations.ANVILS.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.tool.ManualToolBlockEntity>> MANUAL_TOOL=BLOCK_ENTITIES.register("manual_tool",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.tool.ManualToolBlockEntity::new,GTManualStations.MANUAL.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.tool.ProcessingToolBlockEntity>> PROCESSING_TOOL=BLOCK_ENTITIES.register("processing_tool",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.tool.ProcessingToolBlockEntity::new,GTManualStations.VESSELS.stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.tool.DustFunnelBlockEntity>> DUST_FUNNEL=BLOCK_ENTITIES.register("dust_funnel",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.tool.DustFunnelBlockEntity::new,GTManualStations.DUST_FUNNEL.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.SapBagBlockEntity>> SAP_BAG=BLOCK_ENTITIES.register("sap_bag",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.SapBagBlockEntity::new,GTManualStations.SAP_BAG.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.tool.AdvancedButtonBlockEntity>> ADVANCED_BUTTON=BLOCK_ENTITIES.register("advanced_button",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.tool.AdvancedButtonBlockEntity::new,GTManualStations.ADVANCED_BUTTON.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.tool.CoinMoldBlockEntity>> COIN_MOLD=BLOCK_ENTITIES.register("coin_mold",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.tool.CoinMoldBlockEntity::new,GTManualStations.COIN_MOLD.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.energy.ZpmModuleBlockEntity>> ZPM_MODULE=BLOCK_ENTITIES.register("zpm_module",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.energy.ZpmModuleBlockEntity::new,GTZpmArtifacts.ZPM.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.energy.ZpmDischargerBlockEntity>> ZPM_DISCHARGER=BLOCK_ENTITIES.register("zpm_discharger",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.energy.ZpmDischargerBlockEntity::new,GTZpmArtifacts.BASIC.get(),GTZpmArtifacts.ADVANCED.get(),GTZpmArtifacts.ELITE.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.block.misc.DungeonPortalBlockEntity>> DUNGEON_PORTAL=BLOCK_ENTITIES.register("dungeon_portal",()->BlockEntityType.Builder.of(com.gregtech.gregtech.block.misc.DungeonPortalBlockEntity::new,GTDungeonBlocks.PORTAL_NETHER.get(),GTDungeonBlocks.PORTAL_END.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.energy.LaserConverterBlockEntity>> LASER_CONVERTER=BLOCK_ENTITIES.register("laser_converter",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.energy.LaserConverterBlockEntity::new,GTLasers.all().stream().map(java.util.function.Supplier::get).filter(b->b instanceof com.gregtech.gregtech.block.energy.LaserConverterBlock).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.energy.LaserFiberBlockEntity>> LASER_FIBER=BLOCK_ENTITIES.register("laser_fiber",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.energy.LaserFiberBlockEntity::new,GTLasers.LASER_FIBER_WIRE.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.sensor.SensorBlockEntity>> SENSOR=BLOCK_ENTITIES.register("sensor",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.sensor.SensorBlockEntity::new,GTSensors.all().stream().map(java.util.function.Supplier::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.block.misc.LongDistEndpointBlockEntity>> LONG_DIST_ENDPOINT=BLOCK_ENTITIES.register("long_dist_endpoint",()->BlockEntityType.Builder.of(com.gregtech.gregtech.block.misc.LongDistEndpointBlockEntity::new,GTLongDistance.block("long_dist_endpoint_item"),GTLongDistance.block("long_dist_endpoint_fluid")).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.block.misc.LongDistanceTransformerBlockEntity>> LONG_DIST_TRANSFORMER=BLOCK_ENTITIES.register("long_dist_transformer",()->BlockEntityType.Builder.of(com.gregtech.gregtech.block.misc.LongDistanceTransformerBlockEntity::new,GTLongDistance.transformers()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.BoilerTankBlockEntity>> STEAM_BOILER=BLOCK_ENTITIES.register("steam_boiler",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.BoilerTankBlockEntity::new,GTBoilers.all().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.misc.SandwichBlockEntity>> SANDWICH_BLOCK=BLOCK_ENTITIES.register("sandwich_block",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.misc.SandwichBlockEntity::new,GTSandwich.SANDWICH_BLOCK.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.energy.PumpBlockEntity>> PUMP=BLOCK_ENTITIES.register("pump",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.energy.PumpBlockEntity::new,GTPumps.all().stream().map(DeferredHolder::get).toArray(net.minecraft.world.level.block.Block[]::new)).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.LogisticsTankBlockEntity>> LOGISTICS_TANK=BLOCK_ENTITIES.register("logistics_tank",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.LogisticsTankBlockEntity::new,GTLogisticsTank.BLOCK.get()).build(null));
    public static final DeferredHolder<BlockEntityType<?>,BlockEntityType<com.gregtech.gregtech.blockentity.machine.VonDaGraaggControllerBlockEntity>> VON_DA_GRAAGG=BLOCK_ENTITIES.register("von_da_graagg",()->BlockEntityType.Builder.of(com.gregtech.gregtech.blockentity.machine.VonDaGraaggControllerBlockEntity::new,com.gregtech.gregtech.content.multiblock.LargeMachineParts.block(17996)).build(null));
    private GTBlockEntities() {}
    public static void register(IEventBus bus) { BLOCK_ENTITIES.register(bus); }
}
