package com.gregtech.gregtech.registry;
import com.gregtech.gregtech.block.tool.*;import com.gregtech.gregtech.blockentity.tool.ManualToolBlockEntity.Kind;import net.minecraft.world.level.block.*;import net.minecraft.world.level.block.state.BlockBehaviour;import net.minecraft.world.level.material.MapColor;import net.neoforged.neoforge.registries.DeferredHolder;import java.util.*;
public final class GTManualStations {private GTManualStations(){}public static final List<DeferredHolder<Block,MaterialAnvilBlock>> ANVILS=new ArrayList<>();public static final List<DeferredHolder<Block,ManualToolBlock>> MANUAL=new ArrayList<>();public static final List<DeferredHolder<Block,ProcessingToolBlock>> VESSELS=new ArrayList<>();
 public static int tintOf(Kind kind){return switch(kind){case MORTAR->0xCDCDCD;case GRINDSTONE->0xB5B5B5;case SIFTING->com.gregtech.gregtech.content.material.Materials.Steel.getColor();};}
 public static final List<DeferredHolder<Block,ScaffoldBlock>> SCAFFOLDS=new ArrayList<>();public static final List<DeferredHolder<Block,RopeBlock>> ROPES=new ArrayList<>();public static final List<DeferredHolder<Block,ShapedToolBlock>> SHAPED=new ArrayList<>();
 public static DeferredHolder<Block,CoinMoldBlock> COIN_MOLD;
 public static DeferredHolder<Block,DustFunnelBlock> DUST_FUNNEL;public static DeferredHolder<Block,SapBagBlock> SAP_BAG;public static DeferredHolder<Block,AdvancedButtonBlock> ADVANCED_BUTTON;public static DeferredHolder<Block,CrankBlock> CRANK;public static DeferredHolder<Block,PlantPotBlock> PLANT_POT;
 private static void item(String id,java.util.function.Supplier<? extends Block> b,int count){GTBlocks.BLOCK_ITEMS.register(id,()->new net.minecraft.world.item.BlockItem(b.get(),new net.minecraft.world.item.Item.Properties().stacksTo(count)));}
 private static void item(String id,java.util.function.Supplier<? extends Block> b){GTBlocks.BLOCK_ITEMS.register(id,()->new net.minecraft.world.item.BlockItem(b.get(),new net.minecraft.world.item.Item.Properties().stacksTo(16)));}
 private static void manual(String id,Kind kind,String material,BlockBehaviour.Properties p){var b=GTBlocks.BLOCKS.register(id,()->new ManualToolBlock(kind,material,p));MANUAL.add(b);item(id,b);}
 public static void initialize(){
  COIN_MOLD=GTBlocks.BLOCKS.register("coin_mold",()->new CoinMoldBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(6f,6f).requiresCorrectToolForDrops().sound(SoundType.METAL)));SHAPED.add((DeferredHolder)COIN_MOLD);item("coin_mold",COIN_MOLD);
  for(var v:com.gregtech.gregtech.content.tool.UtilityToolRules.ROPES){var b=GTBlocks.BLOCKS.register(v.id(),()->new RopeBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WOOL).strength(.5f,.5f).sound(SoundType.WOOL).noOcclusion().noCollission(),com.gregtech.gregtech.api.material.GTMaterialRegistry.get(v.material()).getColor()));ROPES.add(b);item(v.id(),b,64);}
  for(var v:GTStorageMetals.ALL){String id=v.suffix().equals("steel")?"scaffold":"scaffold_"+v.suffix();var b=GTBlocks.BLOCKS.register(id,()->new ScaffoldBlock(v.material(),BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(5f,v.resistance()).sound(SoundType.METAL).noOcclusion()));SCAFFOLDS.add(b);item(id,b,64);}
  CRANK=GTBlocks.BLOCKS.register("crank",()->new CrankBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(1f,6f).sound(SoundType.METAL).noOcclusion()));item("crank",CRANK);
  DUST_FUNNEL=GTBlocks.BLOCKS.register("dust_funnel",()->new DustFunnelBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(1f,5f).requiresCorrectToolForDrops().noOcclusion()));item("dust_funnel",DUST_FUNNEL);
  PLANT_POT=GTBlocks.BLOCKS.register("plant_pot",()->new PlantPotBlock(BlockBehaviour.Properties.of().mapColor(MapColor.CLAY).strength(1f,5f).sound(SoundType.STONE)));SHAPED.add((DeferredHolder)PLANT_POT);item("plant_pot",PLANT_POT);
  SAP_BAG=GTBlocks.BLOCKS.register("sap_bag",()->new SapBagBlock("sap_bag",BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BROWN).strength(.5f,.5f).sound(SoundType.WOOL)));SHAPED.add((DeferredHolder)SAP_BAG);item("sap_bag",SAP_BAG);
  ADVANCED_BUTTON=GTBlocks.BLOCKS.register("advanced_button",()->new AdvancedButtonBlock(BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(6f,6f).sound(SoundType.METAL).noOcclusion()));item("advanced_button",ADVANCED_BUTTON,64);

  for(var v:com.gregtech.gregtech.content.tool.OpenVesselRules.ALL){var p=BlockBehaviour.Properties.of().strength(v.hardness(),v.resistance());if(v.wooden())p.mapColor(MapColor.WOOD).sound(SoundType.WOOD);else if(v.bowl())p.mapColor(MapColor.CLAY).sound(SoundType.STONE);else if(v.juicer())p.mapColor(MapColor.STONE).requiresCorrectToolForDrops();else p.mapColor(MapColor.METAL).requiresCorrectToolForDrops().sound(SoundType.METAL);var b=GTBlocks.BLOCKS.register(v.id(),()->new ProcessingToolBlock(v.id(),p));VESSELS.add(b);item(v.id(),b);}

  for(var v:com.gregtech.gregtech.content.tool.AnvilVariantCatalog.ALL){var b=GTBlocks.BLOCKS.register(v.id(),()->new MaterialAnvilBlock(()->com.gregtech.gregtech.api.material.GTMaterialRegistry.get(v.material()),v.durability(),BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(10f,1200f).requiresCorrectToolForDrops().sound(SoundType.ANVIL)));ANVILS.add(b);item(v.id(),b);}
  manual("mortar_block",Kind.MORTAR,"Steel",BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(1f,5f).requiresCorrectToolForDrops().noOcclusion());
  for(String m:List.of("Netherite","Sapphire","Diamond","Amethyst"))manual("mortar_"+m.toLowerCase(Locale.ROOT),Kind.MORTAR,m,BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(1f,5f).noOcclusion());
  manual("grindstone_block",Kind.GRINDSTONE,"Steel",BlockBehaviour.Properties.of().mapColor(MapColor.STONE).strength(1f,6f).requiresCorrectToolForDrops().noOcclusion());
  manual("sifting_table",Kind.SIFTING,"Steel",BlockBehaviour.Properties.of().mapColor(MapColor.METAL).strength(1f,6f).sound(SoundType.METAL).noOcclusion());
 }
}
