package com.gregtech.gregtech.registry;
/** Source-compatible name pointing at the native module's sole menu registration. */
public final class GTMenuTypes {
 private GTMenuTypes(){}
 public static final net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.inventory.MenuType<?>,net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.BasicMachineContainerMenu>> BASIC_MACHINE=com.gregtech.gregtech.platform.neoforge.machine.BasicMachineRegistries.MENU;
 public static final net.neoforged.neoforge.registries.DeferredRegister<net.minecraft.world.inventory.MenuType<?>> MENU_TYPES=net.neoforged.neoforge.registries.DeferredRegister.create(net.minecraft.core.registries.Registries.MENU,"gregtech");
 public static final net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.inventory.MenuType<?>,net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.BumbliaryContainerMenu>> BUMBLIARY=MENU_TYPES.register("bumbliary",()->net.neoforged.neoforge.common.extensions.IMenuTypeExtension.create((id,inventory,buffer)->new com.gregtech.gregtech.client.gui.BumbliaryContainerMenu(id,inventory,false)));
 public static final net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.inventory.MenuType<?>,net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.BumbliaryContainerMenu>> ADVANCED_BUMBLIARY=MENU_TYPES.register("advanced_bumbliary",()->net.neoforged.neoforge.common.extensions.IMenuTypeExtension.create((id,inventory,buffer)->new com.gregtech.gregtech.client.gui.BumbliaryContainerMenu(id,inventory,true)));
 public static final net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.inventory.MenuType<?>,net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.AdvancedCraftingMenu>> ADVANCED_CRAFTING=MENU_TYPES.register("advanced_crafting",()->net.neoforged.neoforge.common.extensions.IMenuTypeExtension.create((id,inventory,buffer)->new com.gregtech.gregtech.client.gui.AdvancedCraftingMenu(id,inventory)));
 public static final net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.inventory.MenuType<?>,net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.HopperContainerMenu>> GARBAGE_DUMP=MENU_TYPES.register("garbage_dump",()->net.neoforged.neoforge.common.extensions.IMenuTypeExtension.create((id,inventory,buffer)->new com.gregtech.gregtech.client.gui.GarbageDumpContainerMenu(id,inventory)));
 public static final net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.inventory.MenuType<?>,net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.DataSwitchMenu>> USB_SWITCH=MENU_TYPES.register("usb_switch",()->net.neoforged.neoforge.common.extensions.IMenuTypeExtension.create((id,inventory,buffer)->new com.gregtech.gregtech.client.gui.DataSwitchMenu(id,inventory,com.gregtech.gregtech.block.inventory.UsbSwitchBlock.Kind.USB)));
 public static final net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.inventory.MenuType<?>,net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.DataSwitchMenu>> HDD_SWITCH=MENU_TYPES.register("hdd_switch",()->net.neoforged.neoforge.common.extensions.IMenuTypeExtension.create((id,inventory,buffer)->new com.gregtech.gregtech.client.gui.DataSwitchMenu(id,inventory,com.gregtech.gregtech.block.inventory.UsbSwitchBlock.Kind.HDD)));
 public static final net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.inventory.MenuType<?>,net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.FilterMenu>> FILTER=MENU_TYPES.register("filter",()->net.neoforged.neoforge.common.extensions.IMenuTypeExtension.create((id,inventory,buffer)->new com.gregtech.gregtech.client.gui.FilterMenu(id,inventory,buffer.readBoolean())));
 private static final int[] HOPPER_SIZES=com.gregtech.gregtech.api.inventory.InventorySlotLayout.supportedSizes();
 private static final java.util.Map<Integer,net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.inventory.MenuType<?>,net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.HopperContainerMenu>>> BY_SIZE=new java.util.HashMap<>();
 static{for(int n:HOPPER_SIZES)BY_SIZE.put(n,MENU_TYPES.register("hopper_"+n,()->net.neoforged.neoforge.common.extensions.IMenuTypeExtension.create((id,inventory,buffer)->new com.gregtech.gregtech.client.gui.HopperContainerMenu(id,inventory,n))));}
 public static net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.HopperContainerMenu> forSlotCount(int n){var exact=BY_SIZE.get(n);if(exact!=null)return exact.get();for(int size:HOPPER_SIZES)if(size>=n)return BY_SIZE.get(size).get();return BY_SIZE.get(36).get();}
 public static Iterable<net.neoforged.neoforge.registries.DeferredHolder<net.minecraft.world.inventory.MenuType<?>,net.minecraft.world.inventory.MenuType<com.gregtech.gregtech.client.gui.HopperContainerMenu>>> allHopperTypes(){return BY_SIZE.values();}
 public static void register(net.neoforged.bus.api.IEventBus bus){MENU_TYPES.register(bus);}
}
