package com.gregtech.gregtech.registry;
import com.gregtech.gregtech.block.tool.DynamiteBlock;import com.gregtech.gregtech.content.material.Materials;import com.gregtech.gregtech.api.material.GTMaterial;
import net.minecraft.world.level.block.*;import net.minecraft.world.level.block.state.BlockBehaviour;import net.minecraft.world.level.material.MapColor;import net.minecraft.world.item.*;import net.neoforged.neoforge.registries.*;import net.neoforged.bus.api.IEventBus;
/** Original three mining charges; remaining tool-block families are separate pending ports. */
public final class GTToolBlocks {
 private GTToolBlocks(){}
 public static final java.util.List<DeferredBlock<com.gregtech.gregtech.block.tool.PortableContainerBlock>> PORTABLE=new java.util.ArrayList<>();
 public static final DeferredRegister.Blocks BLOCKS=DeferredRegister.createBlocks("gregtech");
 public static final DeferredRegister.Items ITEMS=DeferredRegister.createItems("gregtech");
 public static final DeferredBlock<DynamiteBlock> DYNAMITE=dynamite("dynamite",10,5,Materials.Red),BOOMSTICK=dynamite("boomstick",10,3,Materials.Orange),DYNAMITE_STRONG=dynamite("strong_dynamite",40,5,Materials.Purple);
 private static DeferredBlock<DynamiteBlock> dynamite(String id,float resistance,int fortune,GTMaterial material){var block=BLOCKS.register(id,()->new DynamiteBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_RED).strength(.2f,0).sound(SoundType.GRASS).noOcclusion().instabreak(),resistance,fortune,material.getColor()));ITEMS.register(id,()->new BlockItem(block.get(),new Item.Properties().stacksTo(64)));return block;}
 public static java.util.List<DeferredBlock<DynamiteBlock>> explosives(){return java.util.List.of(DYNAMITE,BOOMSTICK,DYNAMITE_STRONG);}
 private static BlockBehaviour.Properties attachmentProperties(String id){var p=BlockBehaviour.Properties.of().noOcclusion();if(java.util.Set.of("tap","nozzle","cap_nozzle").contains(id))return p.mapColor(net.minecraft.world.level.material.MapColor.METAL).strength(1.5f,6).sound(SoundType.METAL);if(id.equals("fluid_funnel"))return p.mapColor(net.minecraft.world.level.material.MapColor.METAL).strength(2,6).sound(SoundType.METAL).requiresCorrectToolForDrops();return p.strength(.5f,6);}
 public static void register(IEventBus bus){for(var spec:com.gregtech.gregtech.api.fluid.PortableFluidContainerSpec.values()){var block=BLOCKS.register("fluid_"+spec.id(),()->new com.gregtech.gregtech.block.tool.PortableContainerBlock(spec,BlockBehaviour.Properties.of().strength(1f).noOcclusion()));PORTABLE.add(block);ITEMS.register("fluid_"+spec.id(),()->new com.gregtech.gregtech.item.PortableFluidContainerItem(block.get(),spec,new Item.Properties().stacksTo(spec.shapeId().equals("cell")?64:16)));}var attachments=new java.util.ArrayList<>(com.gregtech.gregtech.content.tool.FluidAttachmentSpec.all());for(String id:java.util.List.of("tap","nozzle","fluid_funnel","cap_nozzle"))attachments.add(new com.gregtech.gregtech.content.tool.FluidAttachmentSpec(id,id,java.util.Set.of("cap_nozzle","nozzle").contains(id)?Materials.Steel:Materials.Ceramic,false));for(var spec:attachments){var block=BLOCKS.register(spec.id(),()->new com.gregtech.gregtech.block.tool.FluidAttachmentBlock(spec,attachmentProperties(spec.id())));ITEMS.register(spec.id(),()->new BlockItem(block.get(),new Item.Properties().stacksTo(64)));}GTFluidComponents.TYPES.register(bus);BLOCKS.register(bus);ITEMS.register(bus);}
}
