package com.gregtech.gregtech.worldgen;

/**
 * GT6's {@code WorldgenPit.SHAPE} — the 48x48 outline of a sand/clay pit, one string per Z row
 * with one character per X column ({@code T} = part of the pit). Generated from the original
 * source by {@code tools/generate_pit_shape.py} so the mask cannot drift.
 *
 * <p>The generator anchors the mask 16 blocks before the chunk it runs in, so one pit spans a
 * 3x3 chunk area; 2032 of the 2304 cells belong to the pit.
 */
public final class GTPitShape {
    private GTPitShape() {}

    public static final int SIZE = 48;

    /** Rows indexed by Z offset, characters by X offset (GT6 {@code SHAPE[x][z]}). */
    public static final String[] ROWS = {
        "FFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTFFFFFFFFFFFFFFFF",
        "FFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTFFFFFFFFFFFF",
        "FFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFFFFFFF",
        "FFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFFFFF",
        "FFFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFFF",
        "FFFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFFF",
        "FFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFF",
        "FFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFF",
        "FFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFF",
        "FFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFF",
        "FFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFF",
        "FFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFF",
        "FTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTF",
        "FTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTF",
        "FTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTF",
        "FTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTF",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "FTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTF",
        "FTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTF",
        "FTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTF",
        "FTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTF",
        "FFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFF",
        "FFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFF",
        "FFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFF",
        "FFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFF",
        "FFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFF",
        "FFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFF",
        "FFFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFFF",
        "FFFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFFF",
        "FFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFFFFF",
        "FFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTFFFFFFFF",
        "FFFFFFFFFFFFTTTTTTTTTTTTTTTTTTTTTTTTFFFFFFFFFFFF",
        "FFFFFFFFFFFFFFFFTTTTTTTTTTTTTTTTFFFFFFFFFFFFFFFF",
    };

    /** GT6's {@code SHAPE[x][z]}. */
    public static boolean at(int x, int z) {
        return x >= 0 && x < SIZE && z >= 0 && z < SIZE && ROWS[z].charAt(x) == 'T';
    }

    /** Number of cells the pit covers (GT6's mask). */
    public static int cells() {
        int count = 0;
        for (String row : ROWS) for (int i = 0; i < row.length(); i++) if (row.charAt(i) == 'T') count++;
        return count;
    }
}
