package com.gregtech.gregtech.worldgen;

import com.gregtech.gregtech.GregTech;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.levelgen.structure.Structure;
import net.minecraft.world.level.levelgen.structure.StructureSet;
import net.minecraft.world.level.levelgen.structure.StructureType;
import net.minecraft.world.level.levelgen.structure.pieces.StructurePieceType;
import net.minecraft.world.level.levelgen.structure.placement.StructurePlacementType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

/**
 * The registry entries behind GT6's dungeon as a <em>structure</em>, so vanilla systems can find it -
 * and nothing else: GT6's dungeon itself is generated by the {@link GTDungeonFeature} feature, cell by
 * cell, exactly as before this class existed. See {@link GTDungeonStructure} for the full explanation and
 * for the four data files that go with these entries.
 *
 * <p>Three of the five registries involved are loaded from JSON (the structure itself, its structure set
 * and the biome tag), so only their keys are declared here; the three code-side registries - the structure
 * type, the placement type and the piece type - are registered through {@link GTFeatures#register},
 * because a mod's registration order is fixed there. {@code Registries.STRUCTURE_PIECE} and
 * {@code Registries.STRUCTURE_PLACEMENT} are vanilla's own built-in registries; mods may add to them, and
 * Forge fires {@code RegisterEvent} for them like for any other registry.</p>
 *
 * <p>GT6's counterpart is its {@code Loader_Worldgen:652} registration of
 * {@code WorldgenDungeonGT} - a 1.7.10 world generator with no registry entry at all.</p>
 */
public final class GTStructures {

    /** {@code gregtech:gt_dungeon} as a structure type ({@code data/gregtech/worldgen/structure/gt_dungeon.json}). */
    public static final DeferredRegister<StructureType<?>> STRUCTURE_TYPES =
            DeferredRegister.create(Registries.STRUCTURE_TYPE, GregTech.NAMESPACE);

    /** {@code gregtech:gt_dungeon_lattice} as a placement type, registered like vanilla's {@code random_spread}. */
    public static final DeferredRegister<StructurePlacementType<?>> PLACEMENT_TYPES =
            DeferredRegister.create(Registries.STRUCTURE_PLACEMENT, GregTech.NAMESPACE);

    /** The anchor marker piece ({@link GTDungeonAnchorPiece}) needs a piece id to be saved with its chunk. */
    public static final DeferredRegister<StructurePieceType> PIECE_TYPES =
            DeferredRegister.create(Registries.STRUCTURE_PIECE, GregTech.NAMESPACE);

    /** The dungeon structure's type; its codec is {@link GTDungeonStructure#CODEC}. */
    public static final RegistryObject<StructureType<GTDungeonStructure>> DUNGEON_TYPE =
            STRUCTURE_TYPES.register("gt_dungeon", () -> () -> GTDungeonStructure.CODEC);

    /** GT6's lattice as a placement type; its codec is {@link GTDungeonPlacement#CODEC}. */
    public static final RegistryObject<StructurePlacementType<GTDungeonPlacement>> DUNGEON_LATTICE =
            PLACEMENT_TYPES.register("gt_dungeon_lattice", () -> () -> GTDungeonPlacement.CODEC);

    /** The no-op piece's id, read back from {@code structures.Starts} in the anchor chunks. */
    public static final RegistryObject<StructurePieceType> DUNGEON_PIECE =
            PIECE_TYPES.register("gt_dungeon_anchor",
                    () -> (StructurePieceType.ContextlessType) GTDungeonAnchorPiece::new);

    /** Key of the dungeon structure ({@code data/gregtech/worldgen/structure/gt_dungeon.json}). */
    public static final ResourceKey<Structure> DUNGEON = ResourceKey.create(Registries.STRUCTURE,
            ResourceLocation.fromNamespaceAndPath(GregTech.NAMESPACE, "gt_dungeon"));

    /** Key of the structure set that carries the dungeon ({@code data/gregtech/worldgen/structure_set/gt_dungeons.json}). */
    public static final ResourceKey<StructureSet> DUNGEON_SET = ResourceKey.create(Registries.STRUCTURE_SET,
            ResourceLocation.fromNamespaceAndPath(GregTech.NAMESPACE, "gt_dungeons"));

    /**
     * The dungeon in a tag of its own ({@code data/gregtech/tags/worldgen/structure/gt_dungeon.json}), so
     * {@code /locate structure #gregtech:gt_dungeon} and
     * {@code ServerLevel.findNearestMapStructure(TagKey, ...)} - the only public locate entry point
     * ({@code ServerLevel:1121-1134}) - can ask for it.
     */
    public static final TagKey<Structure> DUNGEON_TAG = TagKey.create(Registries.STRUCTURE,
            ResourceLocation.fromNamespaceAndPath(GregTech.NAMESPACE, "gt_dungeon"));

    private GTStructures() {}

    /** Registers the three code-side registries; called from {@link GTFeatures#register}. */
    public static void register(IEventBus modEventBus) {
        STRUCTURE_TYPES.register(modEventBus);
        PLACEMENT_TYPES.register(modEventBus);
        PIECE_TYPES.register(modEventBus);
    }
}
