package com.gregtech.gregtech.worldgen;

import com.gregtech.gregtech.block.wood.WoodSpecies;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.WorldGenLevel;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.chunk.ChunkGenerator;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.block.grower.AbstractTreeGrower;

/**
 * Sapling grower for the port's GT6 trees: replaces the vanilla oak grower the species saplings
 * used to carry (they grew oak logs and oak leaves) with {@link GTTreeShapes}' literal port of
 * GT6's {@code BlockBaseSapling.grow}.
 *
 * <p>{@code SaplingBlock} still owns the two-stage growth (its {@code stage} property is GT6's
 * "meta &lt; 8 → meta | 8" step), the bone meal path and the light level check; only the tree
 * generation itself is GT6's.
 */
public class GTTreeGrower extends AbstractTreeGrower {
    private final WoodSpecies species;

    public GTTreeGrower(WoodSpecies species) {
        this.species = species;
    }

    public WoodSpecies species() { return species; }

    /** The tree is generated by {@link GTTreeShapes}, so no configured feature is ever looked up. */
    @Override
    protected ResourceKey<ConfiguredFeature<?, ?>> getConfiguredFeature(RandomSource random, boolean hasFlowers) {
        return null;
    }

    @Override
    public boolean growTree(ServerLevel level, ChunkGenerator generator, BlockPos pos, BlockState state, RandomSource random) {
        return grow(level, pos, random);
    }

    /** Growth entry point shared by saplings ({@link ServerLevel}) and worldgen ({@link WorldGenLevel}). */
    public boolean grow(net.minecraft.world.level.LevelAccessor level, BlockPos pos, RandomSource random) {
        return GTTreeShapes.grow(level, pos, species, random);
    }
}
