package com.gregtech.gregtech.damage;

import com.gregtech.gregtech.GregTech;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.damagesource.DamageType;
import net.minecraft.world.level.Level;

import java.util.List;

/**
 * GT6's damage sources, ported to 1.20.1's data-driven damage types.
 *
 * <p>GT6 keeps one {@code DamageSource} subclass per hazard
 * ({@code gregapi/damage/DamageSource*.java}) whose whole content is a source name, a death message
 * and a few flags, and hands them out through {@code gregapi.damage.DamageSources}
 * ({@code getHeatDamage()}, {@code getSpikeDamage()}, {@code getBumbleDamage()} …). In 1.20.1 a
 * {@code DamageSource} is just a holder around a registered {@link DamageType}, so the port keeps the
 * same method names but reads the definition from {@code data/gregtech/damage_type/<id>.json} and the
 * flags from the vanilla damage-type tags - both generated by {@code tools/generate_damage_types.py}.
 *
 * <table>
 *   <caption>flag mapping</caption>
 *   <tr><th>GT6</th><th>1.20.1</th></tr>
 *   <tr><td>{@code setDamageBypassesArmor()}</td><td>{@code #minecraft:bypasses_armor}</td></tr>
 *   <tr><td>{@code setDamageIsAbsolute()}</td><td>{@code #minecraft:bypasses_armor} +
 *       {@code #minecraft:bypasses_resistance} + {@code #minecraft:bypasses_enchantments}</td></tr>
 *   <tr><td>{@code setDamageAllowedInCreativeMode()}</td>
 *       <td>{@code #minecraft:bypasses_invulnerability}</td></tr>
 * </table>
 *
 * <p>Two of GT6's helpers are absent on purpose: {@code getCombatDamage} carries a per-weapon death
 * message ("[VICTIM] got shot by [KILLER]"), and 1.20.1 needs one registered damage type per message;
 * that belongs to the weapon batch. {@code getElectricDamage}/{@code getRadioactiveDamage}/
 * {@code getNukeExplosionDamage} resolve to IC2's types in GT6 and fall back to <em>heat</em> without
 * IC2 - the port has no IC2, so it registers {@link #ELECTRIC} and {@link #RADIATION} instead of
 * reporting a shock as "was boiled alive".
 */
public final class GTDamageTypes {
    /** GT6 {@code DamageSourceHeat} — "was boiled alive". */
    public static final ResourceKey<DamageType> HEAT = key("heat");
    /** GT6 {@code DamageSourceFrost} — "got frozen". */
    public static final ResourceKey<DamageType> FROST = key("frost");
    /** GT6 {@code DamageSourceChem} — "had a chemical accident". */
    public static final ResourceKey<DamageType> CHEMICAL = key("chemical");
    /** GT6 {@code DamageSourceBumble} — "was allergic to Bumblebees" (bypasses armor). */
    public static final ResourceKey<DamageType> BUMBLE = key("bumble");
    /** GT6 {@code DamageSourceCrusher} — "was crushed to a pulp". */
    public static final ResourceKey<DamageType> CRUSHER = key("crusher");
    /** GT6 {@code DamageSourceShredder} — "was shred into flakes". */
    public static final ResourceKey<DamageType> SHREDDER = key("shredder");
    /** GT6 {@code DamageSourceSpike} — "was impaled by a Spike!". */
    public static final ResourceKey<DamageType> SPIKE = key("spike");
    /** GT6 {@code DamageSourceExploding} — "exploded" (absolute, allowed in creative). */
    public static final ResourceKey<DamageType> EXPLODED = key("exploded");
    /** GT6 {@code DamageSourceAlcohol} — "died from alcohol poisoning" (absolute). */
    public static final ResourceKey<DamageType> ALCOHOL = key("alcohol");
    /** GT6 {@code DamageSourceCaffeine} — "overdosed on caffeine" (absolute). */
    public static final ResourceKey<DamageType> CAFFEINE = key("caffeine");
    /** GT6 {@code DamageSourceDehydration} — "took more than the deadly dose of Salt" (absolute). */
    public static final ResourceKey<DamageType> DEHYDRATION = key("dehydration");
    /** GT6 {@code DamageSourceSugar} — "died of Diabetes" (absolute). */
    public static final ResourceKey<DamageType> SUGAR = key("sugar");
    /** GT6 {@code DamageSourceFat} — "got a Heart Attack" (absolute). */
    public static final ResourceKey<DamageType> FAT = key("fat");
    /** IC2's {@code DMG_ELECTRIC}, which {@code DamageSources.getElectricDamage} delegates to. */
    public static final ResourceKey<DamageType> ELECTRIC = key("electric");
    /** IC2's {@code DMG_RADIATION}, which {@code DamageSources.getRadioactiveDamage} delegates to. */
    public static final ResourceKey<DamageType> RADIATION = key("radiation");

    /** Every type this class registers, in GT6's {@code DamageSources} order of the hazard helpers. */
    public static final List<ResourceKey<DamageType>> ALL = List.of(
            HEAT, FROST, CHEMICAL, BUMBLE, CRUSHER, SHREDDER, SPIKE, EXPLODED,
            ALCOHOL, CAFFEINE, DEHYDRATION, SUGAR, FAT, ELECTRIC, RADIATION);

    private GTDamageTypes() {}

    private static ResourceKey<DamageType> key(String path) {
        return ResourceKey.create(Registries.DAMAGE_TYPE, GregTech.id(path));
    }

    /** The {@code ResourceLocation} of a type key, for building its {@code death.attack.<message_id>} key. */
    public static ResourceLocation id(ResourceKey<DamageType> type) {
        return type.location();
    }

    /** Builds a source for any of the keys above; every factory below is a one-liner over this. */
    public static DamageSource source(Level level, ResourceKey<DamageType> type) {
        return new DamageSource(level.registryAccess().registryOrThrow(Registries.DAMAGE_TYPE).getHolderOrThrow(type));
    }

    /** GT6 {@code DamageSources.getHeatDamage()}. */
    public static DamageSource heat(Level level) { return source(level, HEAT); }
    /** GT6 {@code DamageSources.getFrostDamage()}. */
    public static DamageSource frost(Level level) { return source(level, FROST); }
    /** GT6 {@code DamageSources.getChemDamage()}. */
    public static DamageSource chem(Level level) { return source(level, CHEMICAL); }
    /** GT6 {@code DamageSources.getBumbleDamage()}. */
    public static DamageSource bumble(Level level) { return source(level, BUMBLE); }
    /** GT6 {@code DamageSources.getCrusherDamage()}. */
    public static DamageSource crusher(Level level) { return source(level, CRUSHER); }
    /** GT6 {@code DamageSources.getShredderDamage()}. */
    public static DamageSource shredder(Level level) { return source(level, SHREDDER); }
    /** GT6 {@code DamageSources.getSpikeDamage()}. */
    public static DamageSource spike(Level level) { return source(level, SPIKE); }
    /** GT6 {@code DamageSources.getExplodingDamage()}. */
    public static DamageSource exploding(Level level) { return source(level, EXPLODED); }
    /** GT6 {@code DamageSources.getAlcoholDamage()}. */
    public static DamageSource alcohol(Level level) { return source(level, ALCOHOL); }
    /** GT6 {@code DamageSources.getCaffeineDamage()}. */
    public static DamageSource caffeine(Level level) { return source(level, CAFFEINE); }
    /** GT6 {@code DamageSources.getDehydrationDamage()}. */
    public static DamageSource dehydration(Level level) { return source(level, DEHYDRATION); }
    /** GT6 {@code DamageSources.getSugarDamage()}. */
    public static DamageSource sugar(Level level) { return source(level, SUGAR); }
    /** GT6 {@code DamageSources.getFatDamage()}. */
    public static DamageSource fat(Level level) { return source(level, FAT); }
    /** GT6 {@code DamageSources.getElectricDamage()} (IC2's type; see the class javadoc). */
    public static DamageSource electric(Level level) { return source(level, ELECTRIC); }
    /** GT6 {@code DamageSources.getRadioactiveDamage()} (IC2's type; see the class javadoc). */
    public static DamageSource radiation(Level level) { return source(level, RADIATION); }
}
